
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;




CREATE TABLE IF NOT EXISTS `country_currency` (
  `country_code` varchar(4) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `currency_code` varchar(5) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `country_currency` (`country_code`, `currency_code`) VALUES
('AD', 'EUR'),
('AE', 'AED'),
('AF', 'AFN'),
('AG', 'XCD'),
('AI', 'XCD'),
('AL', 'ALL'),
('AM', 'AMD'),
('AN', 'ANG'),
('AO', 'AOA'),
('AR', 'ARS'),
('AS', 'USD'),
('AT', 'EUR'),
('AU', 'AUD'),
('AW', 'AWG'),
('AZ', 'AZN'),
('BA', 'BAM'),
('BB', 'BBD'),
('BD', 'BDT'),
('BE', 'EUR'),
('BF', 'XOF'),
('BG', 'BGN'),
('BH', 'BHD'),
('BI', 'BIF'),
('BJ', 'XOF'),
('BM', 'BMD'),
('BN', 'BND'),
('BO', 'BOB'),
('BR', 'BRL'),
('BS', 'BSD'),
('BT', 'BTN'),
('BV', 'NOK'),
('BW', 'BWP'),
('BY', 'BYR'),
('BZ', 'BZD'),
('CA', 'CAD'),
('CC', 'AUD'),
('CD', 'CDF'),
('CF', 'XAF'),
('CG', 'XAF'),
('CH', 'CHF'),
('CI', 'XOF'),
('CK', 'NZD'),
('CL', 'CLP'),
('CM', 'XAF'),
('CN', 'CNY'),
('CO', 'COP'),
('CR', 'CRC'),
('CS', 'RSD'),
('CU', 'CUP'),
('CV', 'CVE'),
('CX', 'AUD'),
('CY', 'EUR'),
('CY', 'TRY'),
('CZ', 'CZK'),
('DE', 'EUR'),
('DJ', 'DJF'),
('DK', 'DKK'),
('DM', 'XCD'),
('DO', 'DOP'),
('DZ', 'DZD'),
('EC', 'USD'),
('EG', 'EGP'),
('EH', 'MAD'),
('ER', 'ERN'),
('ES', 'EUR'),
('ET', 'ETB'),
('FI', 'EUR'),
('FJ', 'FJD'),
('FK', 'FKP'),
('FM', 'USD'),
('FO', 'DKK'),
('FR', 'EUR'),
('GA', 'XAF'),
('GB', 'GBP'),
('GD', 'XCD'),
('GE', 'GEL'),
('GF', 'EUR'),
('GI', 'GIP'),
('GL', 'DKK'),
('GM', 'GMD'),
('GN', 'GNF'),
('GP', 'EUR'),
('GQ', 'XAF'),
('GR', 'EUR'),
('GS', 'GBP'),
('GT', 'GTQ'),
('GU', 'USD'),
('GW', 'XOF'),
('GY', 'GYD'),
('HK', 'HKD'),
('HM', 'AUD'),
('HN', 'HNL'),
('HR', 'HRK'),
('HT', 'HTG'),
('HU', 'HUF'),
('ID', 'IDR'),
('IE', 'EUR'),
('IL', 'ILS'),
('IN', 'INR'),
('IO', 'USD'),
('IQ', 'IQD'),
('IR', 'IRR'),
('IS', 'ISK'),
('IT', 'EUR'),
('JM', 'JMD'),
('JO', 'JOD'),
('JP', 'JPY'),
('KE', 'KES'),
('KG', 'KGS'),
('KH', 'KHR'),
('KI', 'AUD'),
('KM', 'KMF'),
('KN', 'XCD'),
('KP', 'KPW'),
('KR', 'KRW'),
('KW', 'KWD'),
('KY', 'KYD'),
('KZ', 'KZT'),
('LA', 'LAK'),
('LB', 'LBP'),
('LC', 'XCD'),
('LI', 'CHF'),
('LK', 'LKR'),
('LR', 'LRD'),
('LS', 'LSL'),
('LT', 'LTL'),
('LU', 'EUR'),
('LY', 'LYD'),
('MA', 'MAD'),
('MC', 'EUR'),
('MD', 'MDL'),
('MG', 'MGA'),
('MH', 'USD'),
('MK', 'MKD'),
('ML', 'XOF'),
('MM', 'MMK'),
('MN', 'MNT'),
('MO', 'MOP'),
('MP', 'USD'),
('MQ', 'EUR'),
('MR', 'MRO'),
('MS', 'XCD'),
('MU', 'MUR'),
('MV', 'MVR'),
('MW', 'MWK'),
('MX', 'MXN'),
('MY', 'MYR'),
('MZ', 'MZN'),
('NA', 'NAD'),
('NC', 'XPF'),
('NE', 'XOF'),
('NF', 'AUD'),
('NG', 'NGN'),
('NI', 'NIO'),
('NL', 'EUR'),
('NO', 'NOK'),
('NP', 'NPR'),
('NR', 'AUD'),
('NU', 'NZD'),
('NZ', 'NZD'),
('OM', 'OMR'),
('PA', 'PAB'),
('PE', 'PEN'),
('PF', 'XPF'),
('PG', 'PGK'),
('PH', 'PHP'),
('PK', 'PKR'),
('PL', 'PLN'),
('PM', 'EUR'),
('PN', 'NZD'),
('PR', 'USD'),
('PS', 'ILS'),
('PT', 'EUR'),
('PW', 'USD'),
('PY', 'PYG'),
('QA', 'QAR'),
('RE', 'EUR'),
('RO', 'RON'),
('RU', 'RUB'),
('RW', 'RWF'),
('SA', 'SAR'),
('SB', 'SBD'),
('SC', 'SCR'),
('SE', 'SEK'),
('SG', 'SGD'),
('SH', 'SHP'),
('SI', 'EUR'),
('SJ', 'NOK'),
('SL', 'SLL'),
('SM', 'EUR'),
('SN', 'XOF'),
('SO', 'SOS'),
('SR', 'SRD'),
('ST', 'STD'),
('SV', 'SVC'),
('SY', 'SYP'),
('SZ', 'SZL'),
('TC', 'USD'),
('TD', 'XAF'),
('TF', 'EUR'),
('TG', 'XOF'),
('TH', 'THB'),
('TJ', 'TJS'),
('TK', 'NZD'),
('TL', 'USD'),
('TN', 'TND'),
('TO', 'TOP'),
('TR', 'TRY'),
('TT', 'TTD'),
('TV', 'AUD'),
('TW', 'TWD'),
('TZ', 'TZS'),
('UA', 'UAH'),
('UG', 'UGX'),
('UM', 'USD'),
('US', 'USD'),
('UY', 'UYU'),
('UZ', 'UZS'),
('VA', 'EUR'),
('VC', 'XCD'),
('VE', 'VEF'),
('VG', 'USD'),
('VI', 'USD'),
('VN', 'VND'),
('VU', 'VUV'),
('WF', 'XPF'),
('WS', 'WST'),
('YE', 'YER'),
('YT', 'EUR'),
('ZA', 'ZAR');


ALTER TABLE `country_currency`
 ADD KEY `country_code` (`country_code`,`currency_code`), ADD KEY `currency_code` (`currency_code`);


ALTER TABLE `country_currency`
ADD CONSTRAINT `country_currency_ibfk_1` FOREIGN KEY (`country_code`) REFERENCES `country` (`code`) ON DELETE CASCADE ON UPDATE CASCADE,
ADD CONSTRAINT `country_currency_ibfk_2` FOREIGN KEY (`currency_code`) REFERENCES `currency` (`code`) ON DELETE CASCADE ON UPDATE CASCADE;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
