INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("BG1FAREPRU","BG","Blagoevgrad",NULL),
("BGXT02Z292","BG","Burgas",NULL),
("BG06B8WE4B","BG","Dobrich",NULL),
("BG4U9GADBC","BG","Gabrovo",NULL),
("BGTM37CV2A","BG","Grad",NULL),
("BGO3CO5LQ5","BG","Khaskovo",NULL),
("BGS1EPGJ0L","BG","Kŭrdzhali",NULL),
("BGE91OND0H","BG","Kyustendil",NULL),
("BGZ3OCYRMN","BG","Lovech",NULL),
("BGUZCZK25D","BG","Mikhaylovgrad",NULL),
("BG4J2K226G","BG","Montana",NULL),
("BGC75ZK5GK","BG","Oblast Sofiya-Grad",NULL),
("BG95W8WJWR","BG","Pazardzhit",NULL),
("BGI8Q3AWGF","BG","Pernik",NULL),
("BGGJ0IL6ZX","BG","Pleven",NULL),
("BGE4XYAEJK","BG","Plovdiv",NULL),
("BGJGSGZO7I","BG","Razgrad",NULL),
("BGWYL7U1NA","BG","Ruse",NULL),
("BGKNT6UT48","BG","Shumen",NULL),
("BGY179FRTZ","BG","Silistra",NULL),
("BG7LF7ANQ7","BG","Sliven",NULL),
("BGMBFHD2SX","BG","Smolyan",NULL),
("BGQL4LF8TE","BG","Sofiya",NULL),
("BGA0NQRGPZ","BG","Stara Zagora",NULL),
("BG257DSXLE","BG","Tŭrgovishte",NULL),
("BG80VL3NJU","BG","Varna",NULL),
("BG9NFPW836","BG","Veliko Tŭrnovo",NULL),
("BG9RW08M0B","BG","Vidin",NULL),
("BGR7OJ49YD","BG","Vratsa",NULL),
("BGAUZDII7S","BG","Yambol",NULL);