INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("BSDUZX440F","BS","Acklins",NULL),
("BSDJ0U5ES3","BS","Berry Islands",NULL),
("BS3GC5B3WR","BS","Bimini",NULL),
("BSGL4Y4K8H","BS","Black Point, Exuma",NULL),
("BSF8EJCFYQ","BS","Cat Island",NULL),
("BSYYL4DD7G","BS","Central Abaco",NULL),
("BSUKM5NJX4","BS","Central Andros",NULL),
("BS5129LBQ1","BS","Central Eleuthera",NULL),
("BSJ5KWKJMJ","BS","City of Freeport, Grand Bahama",NULL),
("BSI8NVLVCF","BS","Crooked Island",NULL),
("BSFYL3HI7M","BS","East Grand Bahama",NULL),
("BSK9W6LM74","BS","Exuma",NULL),
("BSRS1CBNVU","BS","Grand Cay, Abaco",NULL),
("BSWJPHE1XU","BS","Harbour Island, Eleuthera",NULL),
("BS0JXI255M","BS","Hope Town, Abaco",NULL),
("BSE1SZO04G","BS","Inagua",NULL),
("BSS5S4TOYQ","BS","Long Island",NULL),
("BS7O8MQ5GQ","BS","Mangrove Cay, Andros",NULL),
("BSPE9RJEDY","BS","Mayaguana",NULL),
("BSG6Y573LZ","BS","Mooreʼs Island, Abaco",NULL),
("BS9D4313T9","BS","North Abaco",NULL),
("BSR1VH7C8W","BS","North Andros",NULL),
("BSQHNAW19D","BS","North Eleuthera",NULL),
("BS87IFB3FK","BS","Ragged Island",NULL),
("BSHJNJMGSD","BS","Rum Cay",NULL),
("BSINVP03MR","BS","San Salvador",NULL),
("BSLA1HBAUK","BS","South Abaco",NULL),
("BSICZTGEEX","BS","South Andros",NULL),
("BSY1GLI8Z0","BS","South Eleuthera",NULL),
("BSWUQWYCNJ","BS","Spanish Wells, Eleuthera",NULL),
("BSMP1Y0VII","BS","West Grand Bahama",NULL);