INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("CAIA7DC8MJ","CA","Abbotsford","BC"),
("CAJUR3AYII","CA","Abbottsford","BC"),
("CALXV9ECH3","CA","Aberdeen","SK"),
("CALR6UNO85","CA","Abord a Plouffe","QC"),
("CAYGJBP6U9","CA","Acme","AB"),
("CA0LCBKVU6","CA","Acton","ON"),
("CASPG71XAN","CA","Acton Vale","QC"),
("CAOHHB5QH4","CA","Agassiz","BC"),
("CA71FW7A68","CA","Agincourt","ON"),
("CAVJJGEEM7","CA","Airdrie","AB"),
("CA32E50PSP","CA","Aiyansh","BC"),
("CA6A1C0IG7","CA","Ajax","ON"),
("CAKW4R6AZ2","CA","Aklavik","NT"),
("CATJI7Y5F1","CA","Albanel","QC"),
("CA8U78J0XQ","CA","Albany","NS"),
("CABY2BHJJ1","CA","Albert Canyon","BC"),
("CAGNTMYSPS","CA","Aldouane","NB"),
("CAC80AEFCM","CA","Alert Bay","BC"),
("CA9KVTLTJW","CA","Alexander","MB"),
("CASM7A5RCM","CA","Alexandria","ON"),
("CAF59DYY6B","CA","Alfred","ON"),
("CA76LLLY8U","CA","Algonquin Park","ON"),
("CAI4N3X7ZQ","CA","Alix","AB"),
("CAT70ZZDLE","CA","Allan","SK"),
("CAJUSHSYT0","CA","Allenford","ON"),
("CA4ELQDTLV","CA","Alliston","ON"),
("CAX9ZVGZL9","CA","Alma","QC"),
("CA7M960ULJ","CA","Almonte","ON"),
("CAOD1HCUHH","CA","Altona","MB"),
("CA937MWSIU","CA","Amber Valley","AB"),
("CA1HPIGBSO","CA","Amherst","NS"),
("CAY1UYVFHK","CA","Amherstburg","ON"),
("CATI26CJNM","CA","Amos","QC"),
("CAMU8JNQDP","CA","Amqui","QC"),
("CA837PEZDD","CA","Ancienne Lorette","QC"),
("CA17BWNSHH","CA","Angus","ON"),
("CABJNO2AAP","CA","Anjou","QC"),
("CA5I8T9MIH","CA","Annapolis","NS"),
("CAQQ65QJIR","CA","Annapolis Royal","NS"),
("CARTOFM5WX","CA","Anteuil","QC"),
("CAOKLRVVG0","CA","Antigonish","NS"),
("CAEPTNCC42","CA","Apex","NT"),
("CA2B7SUPKM","CA","Apsley","ON"),
("CAJ815DY22","CA","Arborfield","SK"),
("CAJOTEK9EY","CA","Arborg","MB"),
("CAZ8MBKQDN","CA","Arcola","SK"),
("CA1KGWA0IT","CA","Arctic Bay","NT"),
("CA8KYMJ1O2","CA","Ardrossan","AB"),
("CAPHG9RV8Q","CA","Arichat","NS"),
("CA3U1OLFBN","CA","Armstrong","BC"),
("CA0RJAS241","CA","Arnprior","ON"),
("CAM3O54C8U","CA","Arthabaska","QC"),
("CAUO4LJCCN","CA","Arthur","ON"),
("CA7EBSUMFU","CA","Arviat","NT"),
("CAEZ57198O","CA","Arvida","QC"),
("CACWUH92B3","CA","Asbestos","QC"),
("CAQFPAS2XZ","CA","Ashcroft","BC"),
("CAG8SBV75A","CA","Ashern","MB"),
("CA6BH8LQWY","CA","Asquith","SK"),
("CAMQFWSRZJ","CA","Assiniboia","SK"),
("CA7PTZRQZ8","CA","Aston Junction","QC"),
("CAZRJUZP56","CA","Athabasca","AB"),
("CA0NELDAJ0","CA","Atikokan","ON"),
("CA0ZWTQVCX","CA","Atlin","BC"),
("CAL5XCWWLV","CA","Attawapiskat","ON"),
("CAO5QOUVUU","CA","Aurora","ON"),
("CAJ9GWJZWK","CA","Austin","MB"),
("CAYSEPOQM9","CA","Auteuil","QC"),
("CAVJMRG8N4","CA","Authier","QC"),
("CADDT79N2S","CA","Avonlea","SK"),
("CAWJPGJL1H","CA","Ayers Cliff","QC"),
("CAEF725TC1","CA","Aylmer","QC"),
("CADYTT7GYK","CA","Ayr","ON"),
("CAURS4FVXC","CA","Ayton","ON"),
("CAEMTX7VFL","CA","Baden","ON"),
("CAAMOGG0IT","CA","Bagotville","QC"),
("CAZCN6SMRN","CA","Baie Verte","NL"),
("CAEJSTEP6T","CA","Baie-Comeau","QC"),
("CABZQJU555","CA","Baie-d'Urfe","QC"),
("CASTM8U42T","CA","Baie-Saint-Paul","QC"),
("CAGP09CRXQ","CA","Baker Lake","NT"),
("CABPJPFPIQ","CA","Bala","ON"),
("CAP9AJFGP7","CA","Balzac","AB"),
("CA9BG4GIYX","CA","Bamfield","BC"),
("CA8Y6KQ4B1","CA","Bancroft","ON"),
("CAUUR9KA09","CA","Banff","AB"),
("CAJATYQI60","CA","Barachois","QC"),
("CAUM5A537E","CA","Barraute","QC"),
("CA2EZSJAUD","CA","Barrhead","AB"),
("CA5LMPVNZF","CA","Barrie","ON"),
("CAXTDOCJP6","CA","Barriere","BC"),
("CA6UHCYPQ0","CA","Barrington","NS"),
("CA4QTN0O05","CA","Bashaw","AB"),
("CAANV5AVK8","CA","Bath","ON"),
("CAOYX1IM8P","CA","Bathurst","NB"),
("CAHP1FESGI","CA","Batiscan","QC"),
("CAIA6IY6O8","CA","Bauline","NL"),
("CATKE4GZC5","CA","Bay Bulls","NL"),
("CAX96GVE5D","CA","Bay De Verde","NL"),
("CA47SIZ91H","CA","Bay Roberts","NL"),
("CAJ70HEPQ8","CA","Bayfield","ON"),
("CAA4CQ3OV0","CA","Beachburg","ON"),
("CAX1HTGM7K","CA","Beaconsfield","QC"),
("CATZ3S84AS","CA","Beamsville","ON"),
("CACBAQ10YB","CA","Bear River","NS"),
("CA4B18ZX9X","CA","Bearskin Lake","ON"),
("CAYQRECYZ6","CA","Beauceville","QC"),
("CAY2Y779ZJ","CA","Beauharnois","QC"),
("CAL9AM99XE","CA","Beaumont","AB"),
("CAKZMKWVHV","CA","Beauport","QC"),
("CAL9AY7945","CA","Beaupre","QC"),
("CAB3CICC2Y","CA","Beausejour","MB"),
("CALCKVMI96","CA","Beaver","QC"),
("CAHWQER89D","CA","Beaver Harbour","NS"),
("CAHKBPTFU5","CA","Beaverton","ON"),
("CAI7NVJQT5","CA","Becancour","QC"),
("CA3E0PWAWE","CA","Bedford","NS"),
("CA6MTYV3BD","CA","Beebe","QC"),
("CANN2G2XML","CA","Beiseker","AB"),
("CA5AHP0BU3","CA","Bella Coola","BC"),
("CAPVSM6O1D","CA","Belle River","ON"),
("CABUB7YNKL","CA","Belleoram","NL"),
("CAAN2DLOZQ","CA","Belleville","ON"),
("CAYGGYSB2H","CA","Bellevue","AB"),
("CA6U4DJ6RU","CA","Belmont","ON"),
("CA021YQMK1","CA","Beloeil","QC"),
("CAAMEVBDM9","CA","Benalto","AB"),
("CAU28MDA4K","CA","Berthier","QC"),
("CA59XOFOJG","CA","Berthier-sur-Mer","QC"),
("CARKFI7ZJH","CA","Berthierville","QC"),
("CAMYDXCZ76","CA","Berwick","NS"),
("CA1FTEQYYV","CA","Bethany","ON"),
("CA8WJNL24D","CA","Betsiamites","QC"),
("CANJVVJFC6","CA","Big River","SK"),
("CADP4PPBWQ","CA","Biggar","SK"),
("CARQ5HO3CW","CA","Bilby","AB"),
("CA0WKMYOZL","CA","Birchy Bay","NL"),
("CA8UGSATZN","CA","Birsay","SK"),
("CAJ3C8F9Z7","CA","Bishops Falls","NL"),
("CAZ4PN81K9","CA","Black Diamond","AB"),
("CAY5VWUUI2","CA","Black Pines","BC"),
("CAPZVZTVMD","CA","Blackfalds","AB"),
("CAYZME8LL8","CA","Blackie","AB"),
("CAPBWYDG7B","CA","Blackville","NB"),
("CAM28GWQJM","CA","Blaine Lake","SK"),
("CAQFMKA9X9","CA","Blairmore","AB"),
("CA8JNH49QU","CA","Blenheim","ON"),
("CAKMSX3Z9P","CA","Blind River","ON"),
("CA2H5Z8OLZ","CA","Blucher Hall","BC"),
("CA47JEGGNP","CA","Bluesky","AB"),
("CA0B75KXZ5","CA","Bluffton","AB"),
("CAJS3NSCCU","CA","Bobcaygeon","ON"),
("CAUHU26G1A","CA","Bois-des-Filion","QC"),
("CAOLP52CU2","CA","Boischatel","QC"),
("CAN28808EK","CA","Bolton","ON"),
("CA0I7TVJOP","CA","Bon Accord","AB"),
("CA1IS8YUJM","CA","Bonaventure","QC"),
("CAF8RILMK8","CA","Bonavista","NL"),
("CAPTHP1W91","CA","Bonnyville","AB"),
("CAEHV90JY2","CA","Borden","ON"),
("CA2RA0LUN1","CA","Borden-Carleton","PE"),
("CA2FJN24WR","CA","Boswell","BC"),
("CAXEHYAR0O","CA","Botwood","NL"),
("CA8VY9FXBH","CA","Bow Island","AB"),
("CAOMI9G5BJ","CA","Bowmanville","ON"),
("CALU6NY3EW","CA","Bowness","AB"),
("CAHWUSNVGV","CA","Boyle","AB"),
("CAQE55BHN0","CA","Bracebridge","ON"),
("CA35AKAL3W","CA","Brackendale","BC"),
("CAFAJEDYAV","CA","Bradford","ON"),
("CAU5NI04ER","CA","Brampton","ON"),
("CAJJXV0KV3","CA","Brancepeth","SK"),
("CAP5O0QRW6","CA","Brandon","MB"),
("CA1GLFFWAA","CA","Brantford","ON"),
("CA1YS226UM","CA","Brechin","ON"),
("CAPSHPCCT2","CA","Brentwood Bay","BC"),
("CAHH289ZEB","CA","Breton","AB"),
("CAGZQVV15X","CA","Bridge Lake","BC"),
("CAZX023VOT","CA","Bridgetown","NS"),
("CAN6JZID20","CA","Bridgewater","NS"),
("CAV5944NFL","CA","Brighton","ON"),
("CAN5GJ7MH6","CA","Brigus","NL"),
("CAJH9NCYHZ","CA","Brimley","ON"),
("CA40ZND2O8","CA","Britt","ON"),
("CA7XDCLSX8","CA","Brochet","MB"),
("CAYER508CK","CA","Brockville","ON"),
("CAQM83KP3P","CA","Broderick","SK"),
("CAQ3D451DC","CA","Bromptonville","QC"),
("CAZQPKJMTH","CA","Brooks","AB"),
("CA1LN2U0MK","CA","Brossard","QC"),
("CAMUN7KQXA","CA","Broughton Island","NT"),
("CAUAFZCSCC","CA","Bruce Mines","ON"),
("CAI1W2OPJP","CA","Bruno","SK"),
("CAA7R47EPU","CA","Bryson","QC"),
("CA9D1T4Y4Y","CA","Buckhorn","ON"),
("CA9JXMC9YU","CA","Buckingham","QC"),
("CABVWZKGPV","CA","Buctouche","NB"),
("CAOH0WVPQ4","CA","Buffalo Narrows","SK"),
("CA2SY6R350","CA","Burgeo","NL"),
("CAN2NZCLUN","CA","Burin","NL"),
("CAGRM18CWW","CA","Burks Falls","ON"),
("CATXSONJTQ","CA","Burlington","ON"),
("CABSW2V23J","CA","Burnaby","BC"),
("CA4QIGCD4S","CA","Burns Lake","BC"),
("CA4RUC3R8W","CA","Burnside","NL"),
("CAO1LBKF1W","CA","Burnsville","NB"),
("CA7YY302N5","CA","Burnt Church","NB"),
("CAS6M4JQXO","CA","Busby","AB"),
("CAHR0LI9H6","CA","Cabano","QC"),
("CAB3IWIKSQ","CA","Cabri","SK"),
("CAIRUJTHOM","CA","Cacouna","QC"),
("CAOAQ71OVI","CA","Calabogie","ON"),
("CAFW3Y6L5H","CA","Caledon","ON"),
("CAPND876YQ","CA","Caledon East","ON"),
("CAXT9QBYCZ","CA","Caledonia","ON"),
("CA837AR3S7","CA","Calgary","AB"),
("CA0W56HAO6","CA","Callander","ON"),
("CAY1E68DW5","CA","Calmar","AB"),
("CA76VI48ID","CA","Cambridge","ON"),
("CABPN3TGAT","CA","Cambridge Bay","NT"),
("CACGZURN1P","CA","Campbell River","BC"),
("CAPGWXUT21","CA","Campbellford","ON"),
("CAZYK462II","CA","Campbellton","NB"),
("CAS6LLNVE0","CA","Camrose","AB"),
("CABEU32WTR","CA","Canal Flats","BC"),
("CADPP7IS9I","CA","Candiac","QC"),
("CARTNXW5FO","CA","Canfield","ON"),
("CAC1AZWOZ8","CA","Canmore","AB"),
("CA3UB5R4X4","CA","Cannington","ON"),
("CAUNCCFLV7","CA","Canoe Narrows","SK"),
("CAFI4BNK00","CA","Canora","SK"),
("CAMAZIZZR2","CA","Canterbury Station","NB"),
("CAU38L85Q2","CA","Cap-aux-Meules","QC"),
("CAS3F8OAF4","CA","Cap-Chat","QC"),
("CASKFG5GGR","CA","Cap-de-la-Madeleine","QC"),
("CAQGAQG1TA","CA","Cap-Rouge","QC"),
("CA51WE7NGZ","CA","Cape Dorset","NT"),
("CAQW8F7OJ0","CA","Cape Ray","NL"),
("CA8ZGDGX56","CA","Capreol","ON"),
("CAEFXUHQ5N","CA","Caraquet","NB"),
("CAR11YPIYG","CA","Carberry","MB"),
("CAE7VLVFL3","CA","Carbonear","NL"),
("CAF2HV0N2E","CA","Cardinal","ON"),
("CA2Z8KPD7H","CA","Cardston","AB"),
("CAF8G4RFL5","CA","Carleton","PE"),
("CAMGRIWDMC","CA","Carleton Place","ON"),
("CAG37GRAUU","CA","Carlyle","SK"),
("CA92EZGMHV","CA","Carmacks","YT"),
("CAVY0MDMR0","CA","Carman","MB"),
("CA2JIZX4BD","CA","Carnduff","SK"),
("CA8JTZTNT3","CA","Caroline","AB"),
("CAQ826UK2Q","CA","Caronport","SK"),
("CAI3CVP4WS","CA","Carp","ON"),
("CANESLI3YR","CA","Carrot River","SK"),
("CANRQGFKK5","CA","Carseland","AB"),
("CASNCN7FDP","CA","Carstairs","AB"),
("CAJQL9UI1I","CA","Casselman","ON"),
("CAWU3FX16L","CA","Castlegar","BC"),
("CATW28HME9","CA","Catalina","NL"),
("CA9RXG7A6Q","CA","Caughnawaga","QC"),
("CA0SZVA1D7","CA","Cecil Lake","BC"),
("CAVHMTISFC","CA","Centreville","NS"),
("CAPHL73ZGC","CA","Chalk River","ON"),
("CARETYP0PQ","CA","Chamberlain","SK"),
("CATOL4QZBM","CA","Chambly","QC"),
("CAGYGYRVBG","CA","Chambord","QC"),
("CACWOFW4SN","CA","Champion","AB"),
("CAJMM8MBYG","CA","Champlain","QC"),
("CA0KKRJVDZ","CA","Chandler","QC"),
("CATTYKP911","CA","Change Islands","NL"),
("CA5PH1U9PD","CA","Channel-Port Aux Basques","NL"),
("CAVBMIMKYN","CA","Chapais","QC"),
("CA5IEOERN8","CA","Chapel Arm","NL"),
("CALMTAVUB1","CA","Chapleau","ON"),
("CAKT3F2STY","CA","Chaplin","SK"),
("CA3FGQ0FD5","CA","Charlemagne","QC"),
("CAYRTCJHK4","CA","Charlesbourg","QC"),
("CA3DEZ8Q0T","CA","Charlottetown","PE"),
("CAJ38MW2L0","CA","Charny","QC"),
("CAH2QIH4NF","CA","Chase","BC"),
("CAVHSEZDJ3","CA","Chateauguay","QC"),
("CAQX2ZO3T8","CA","Chatham","NB"),
("CA72V34G3L","CA","Chatsworth","ON"),
("CAIU3ZYRFU","CA","Chelmsford","ON"),
("CA9788KRBB","CA","Chemainus","BC"),
("CAPDBEH4MO","CA","Cheminis","ON"),
("CA6ISAYWWG","CA","Cherhill","AB"),
("CAR0GPSWJ1","CA","Cherryville","BC"),
("CA4S9OKK0A","CA","Chesley","ON"),
("CAYCOFHB4O","CA","Chester","NS"),
("CATXZSTV8K","CA","Chesterfield Inlet","NT"),
("CAWPAOLUPP","CA","Chesterville","ON"),
("CANZE8KFII","CA","Chibougamau","QC"),
("CAR7Y9I3XC","CA","Chicoutimi","QC"),
("CA0W4USDFP","CA","Chicoutimi-Nord","QC"),
("CA2QDOK3E8","CA","Chief Lake","BC"),
("CA2SGM8Y5Z","CA","Chilliwack","BC"),
("CA549O7618","CA","Chip Lake","AB"),
("CA353VJIKM","CA","Chipman","AB"),
("CA9YAT2O25","CA","Chomedey","QC"),
("CAHISPHXPN","CA","Church Point","NS"),
("CA1YC95DH8","CA","Churchill","ON"),
("CAJK423OOC","CA","Chute-aux-Outardes","QC"),
("CANY6PN8U4","CA","Chute-Shipshaw","QC"),
("CARMU8KJWM","CA","Cinema","BC"),
("CAI8VNLDW4","CA","Clair","SK"),
("CAY062PVEC","CA","Clairmont","AB"),
("CATL2HUXMM","CA","Clarenville","NL"),
("CAJGV40RQI","CA","Claresholm","AB"),
("CAZM6KZ2PY","CA","Clarkson","ON"),
("CA3W0SRE5L","CA","Clearwater","BC"),
("CA072V4PHO","CA","Clericy","QC"),
("CA5CS63JP2","CA","Clermont","QC"),
("CA5VN5YD32","CA","Clinton","ON"),
("CA93U1IZMI","CA","Clive","AB"),
("CA6PDBFVZK","CA","Clo-oose","BC"),
("CA7SQACFDH","CA","Cloverdale","BC"),
("CAB1MAEQCO","CA","Clyde River","NT"),
("CAT7PB6CUD","CA","Coal Creek","BC"),
("CA28OH3O2A","CA","Coaldale","AB"),
("CAGSLS8ZAK","CA","Coaticook","QC"),
("CA0XVFN83G","CA","Cobalt","ON"),
("CAFTSL5NY8","CA","Cobble Hill","BC"),
("CAVNPZBRAS","CA","Cobden","ON"),
("CAKVKTVVEV","CA","Cobourg","ON"),
("CASAAFIEWX","CA","Cochrane","ON"),
("CA7PJDCIL7","CA","Coderre","SK"),
("CA5B6H3G9N","CA","Colborne","ON"),
("CACUH7PW3I","CA","Cold Lake","AB"),
("CA6EXOSUL0","CA","Coldwater","ON"),
("CAJ5EVN03S","CA","Colebrook","BC"),
("CAC99FQJ33","CA","Coleman","AB"),
("CADLB3HELN","CA","Colliers","NL"),
("CASJBLDXMX","CA","Collingwood","ON"),
("CA21SQ2WJE","CA","Colonsay","SK"),
("CA6STWCX0P","CA","Colville Lake","NT"),
("CAIBSZPDMI","CA","Comber","ON"),
("CAXY4AWR8Y","CA","Come By Chance","NL"),
("CAS1PVX893","CA","Comox","BC"),
("CA13ZD002I","CA","Contrecoeur","QC"),
("CABVI195K6","CA","Cookshire","QC"),
("CA3OHZFPY8","CA","Coquitlam","BC"),
("CAQN3NWDQX","CA","Coral Harbour","NT"),
("CAGQAHQD02","CA","Corner Brook","NL"),
("CA8I3HNNOR","CA","Cornwall","ON"),
("CAC5RSUQ0K","CA","Cornwallis","NS"),
("CAE47AIY7Y","CA","Coronation","AB"),
("CAOHFFVFH3","CA","Cortes Bay","BC"),
("CAYKLM79EJ","CA","Cote","SK"),
("CAE5B8WCTA","CA","Cote-Saint-Luc","QC"),
("CAH0KZYSYN","CA","Cottam","ON"),
("CAAE25UJ9S","CA","Courtenay","BC"),
("CA4UFB4TVI","CA","Courtright","ON"),
("CAY7RVKK52","CA","Cow Bay","NS"),
("CALQ1JIZ7T","CA","Cowansville","QC"),
("CAD9Y7T80X","CA","Cowichan Bay","BC"),
("CA2F9785P7","CA","Crabtree","QC"),
("CACH3X18ZM","CA","Cranberry Portage","MB"),
("CAY16H1DBF","CA","Cranbrook","BC"),
("CANANGINDL","CA","Creemore","ON"),
("CA3NSCSIK5","CA","Creighton","ON"),
("CAZN20V2NU","CA","Creston","BC"),
("CA3TC47NJU","CA","Crofton","BC"),
("CAY6BGUP2X","CA","Crooked River","SK"),
("CACU94CT9C","CA","Cross Lake","MB"),
("CAHCDCE07I","CA","Crossfield","AB"),
("CATKM186V6","CA","Crystal Beach","ON"),
("CAC7M6WO48","CA","Cumberland","ON"),
("CAJEDW7N8P","CA","Cumberland House","SK"),
("CAZL2EL9WF","CA","Cut Knife","SK"),
("CATJH1PC71","CA","Dalhousie","NB"),
("CAKU8GJDO2","CA","Dalmeny","SK"),
("CAR2YZP7OO","CA","Daniels Cove","NL"),
("CASQ3E0ZUU","CA","Danville","QC"),
("CAIBV7O398","CA","Dartmouth","NS"),
("CAYIPHVDKN","CA","Dauphin","MB"),
("CAFIM4PATI","CA","Dawson City","YT"),
("CA1WX1WRVE","CA","Dawson Creek","BC"),
("CA3RMSVW1T","CA","Daysland","AB"),
("CAFQBA3VYJ","CA","De Lery","QC"),
("CAEKO3VIMW","CA","Dease Lake","BC"),
("CAFJXBBSQE","CA","Debert","NS"),
("CAJD7E988O","CA","Deep River","ON"),
("CAYJZ2FXMT","CA","Deer","MB"),
("CAHAXDTJ98","CA","Deer Lake","ON"),
("CA36KEZATJ","CA","Delburne","AB"),
("CAN0YX96L7","CA","Delhi","ON"),
("CAQLA5IWY0","CA","Deline","NT"),
("CA7WD0FM9I","CA","Delson","QC"),
("CATTXS3QCR","CA","Delta","BC"),
("CARAO0G987","CA","Denare Beach","SK"),
("CAVIDDFCEM","CA","Denbigh","ON"),
("CA8RNNEW67","CA","Denfield","ON"),
("CAP40TVCKM","CA","Deroche","BC"),
("CAN8N4IWBD","CA","Derval","QC"),
("CAFORU05H9","CA","Desbarats","ON"),
("CAX4XB14JQ","CA","Desbiens","QC"),
("CA8KK3W4QK","CA","Deschambault","QC"),
("CADEOWAZAP","CA","Deseronto","ON"),
("CAO1KP71Y4","CA","Deux-Montagnes","QC"),
("CA6VG7ZZY7","CA","Devon","AB"),
("CAJIBGN100","CA","Didsbury","AB"),
("CAFPWQO6GD","CA","Dieppe","NB"),
("CA802F20K8","CA","Digby","NS"),
("CAW0GW0E4K","CA","Dildo","NL"),
("CAXF0KH1KX","CA","Dillon","SK"),
("CAQHNFO3SW","CA","Dingwall","NS"),
("CA4UC6VWFS","CA","Dinsmore","SK"),
("CAWVOWASG7","CA","Disraeli","QC"),
("CA8HRPJBMA","CA","Doaktown","NB"),
("CAT9PHDIDH","CA","Dodsland","SK"),
("CADQO8M31I","CA","Dolbeau","QC"),
("CAZPF9IWGQ","CA","Dollard-des-Ormeaux","QC"),
("CAD7FXJ27C","CA","Domremy","SK"),
("CACXUPF87S","CA","Don Mills","ON"),
("CAYW1KZ33Z","CA","Donnacona","QC"),
("CASJ8BFP1T","CA","Dorintosh","SK"),
("CAXHQGJYTW","CA","Dorion","QC"),
("CAVOMBWT4U","CA","Dorion-Vaudreuil","QC"),
("CAP6FP9JP2","CA","Dorset","ON"),
("CA2XDHNEBK","CA","Dorval","QC"),
("CAW20G0UCW","CA","Dot","BC"),
("CAIY7FSC9I","CA","Dowling","AB"),
("CAIP8R8XUA","CA","Downsview","ON"),
("CAU7SHM31I","CA","Doyles","NL"),
("CA62Z6XB2G","CA","Drayton Valley","AB"),
("CA9AV2M5K4","CA","Dresden","ON"),
("CAUSW3PQDK","CA","Drinkwater","ON"),
("CAY62KA33G","CA","Drumbo","ON"),
("CA62N4DPKN","CA","Drumheller","AB"),
("CA0FPMKARF","CA","Drummondville","QC"),
("CA2OIREWCC","CA","Dryden","ON"),
("CA3EXDH0UO","CA","Dubuisson","QC"),
("CA3HSG7D47","CA","Duchess","AB"),
("CASUUD4MT7","CA","Duck Lake","SK"),
("CAACYP9A1C","CA","Duffield","AB"),
("CAPZQ70LV3","CA","Dufresne","MB"),
("CA2OKA1OIU","CA","Duncan","BC"),
("CAJC8NY1U8","CA","Dundalk","ON"),
("CAETXN4ZZT","CA","Dundas","ON"),
("CAZQ0ZBW2E","CA","Dundurn","SK"),
("CAKMOMB6HU","CA","Dunfermline","SK"),
("CAIPHHRCQ5","CA","Dunnville","ON"),
("CA5NSANS3M","CA","Dunsford","ON"),
("CAI4LT0O7L","CA","Dunville","NL"),
("CAAW8L2PFL","CA","Durham","ON"),
("CAEX269TBF","CA","Durham Bridge","NB"),
("CAG4Q4WURF","CA","Duvernay","QC"),
("CAYD8Z1GLB","CA","Eaglesham","AB"),
("CACTXFID0X","CA","Earlton","ON"),
("CAB33LWF0D","CA","East Angus","QC"),
("CAJRHGL9VK","CA","East Chezzetcook","NS"),
("CAM4JNL4ZY","CA","Eastern Passage","NS"),
("CAXXDGADDL","CA","Eastmain","QC"),
("CAHH6DW7QG","CA","Eastman","QC"),
("CAY8WKIS44","CA","Echo Bay","ON"),
("CAXNSISRHP","CA","Economy","NS"),
("CAOU6Z8JKP","CA","Edam","SK"),
("CA0R3XYTDX","CA","Edgewood","BC"),
("CA2AHK3LP0","CA","Edmonton","AB"),
("CA9HJ190RX","CA","Edmundston","NB"),
("CAUXW3HHSI","CA","Edson","AB"),
("CA8VF7PT5S","CA","Eganville","ON"),
("CA4ND7837I","CA","Elbow","SK"),
("CAKRJTRBRM","CA","Elgin","ON"),
("CA8OPP5I8E","CA","Elk Lake","ON"),
("CAENM3HRWL","CA","Elk Point","AB"),
("CAEASND05X","CA","Elko","BC"),
("CARPRJ1I69","CA","Elliot Lake","ON"),
("CA6WZCE7RS","CA","Elmira","ON"),
("CAVDWC5SYK","CA","Elmsdale","NS"),
("CA2Q7GRDDJ","CA","Elmvale","ON"),
("CA3424N9EU","CA","Elora","ON"),
("CA5E7JMYCI","CA","Emerald","ON"),
("CAC9VI2T25","CA","Emo","ON"),
("CAKALBOYUS","CA","Enderby","BC"),
("CA3XWR6BLC","CA","Endiang","AB"),
("CAQSWCR8V3","CA","Englehart","ON"),
("CAHQLJJOO3","CA","Enterprise","ON"),
("CAY9FM89EC","CA","Entwistle","AB"),
("CA7B3ENOQD","CA","Eriksdale","MB"),
("CAHMQ9VLDD","CA","Erin","ON"),
("CACYWVNLZL","CA","Erindale","ON"),
("CAVE83ONGW","CA","Espanola","ON"),
("CAZJAN811Q","CA","Essex","ON"),
("CAORZJDCWP","CA","Esterhazy","SK"),
("CABTLYFLKA","CA","Estevan","SK"),
("CA0TEPHULG","CA","Eston","SK"),
("CADW3MX4CL","CA","Etang-du-Nord","QC"),
("CAWB5AO1ZZ","CA","Etobicoke","ON"),
("CAVLXA6IK7","CA","Exeter","ON"),
("CABYWSTH97","CA","Extension","BC"),
("CAECTBH6XE","CA","Fabreville","QC"),
("CAI2O64O5Z","CA","Fairmont Hot Springs","BC"),
("CA939GLTNW","CA","Fairview","AB"),
("CASJOM1XTF","CA","Falconbridge","ON"),
("CAANRSUP7C","CA","Farnham","QC"),
("CARVIVKNVT","CA","Faust","AB"),
("CAQ4ABYX8R","CA","Fenelon Falls","ON"),
("CAHXDIU7Y5","CA","Fergus","ON"),
("CAVQYPF526","CA","Ferme-Neuve","QC"),
("CA1K2L8XEY","CA","Fernie","BC"),
("CA2OA0MJR3","CA","Fielding","SK"),
("CAG5MBCLH8","CA","Finmoore","BC"),
("CABFXQKZXL","CA","Flatbush","AB"),
("CAK06SYLR0","CA","Flesherton","ON"),
("CAA21XLT12","CA","Flin Flon","MB"),
("CAYNDA9UIL","CA","Foam Lake","SK"),
("CAAGCUGAG0","CA","Fonthill","ON"),
("CAANS98KAJ","CA","Foremost","AB"),
("CAMBG74HA2","CA","Forest","ON"),
("CA5NDEIW0S","CA","Forestburg","AB"),
("CADCNTM4UX","CA","Forestville","QC"),
("CARN607GJT","CA","Fort Albany","ON"),
("CAS01WHBZM","CA","Fort Erie","ON"),
("CAZD1I91AN","CA","Fort Frances","ON"),
("CAEYG03BYU","CA","Fort Good Hope","NT"),
("CAY4V5LEZD","CA","Fort Hope","ON"),
("CAE0AWCAJB","CA","Fort Liard","NT"),
("CANKTXM4K0","CA","Fort Macleod","AB"),
("CA3116DZ1B","CA","Fort McMurray","AB"),
("CA4WHQBG4P","CA","Fort McPherson","NT"),
("CAHFMTP54D","CA","Fort Nelson","BC"),
("CAPYAC2VD5","CA","Fort Providence","NT"),
("CAXFCAEDMJ","CA","Fort Qu'Appelle","SK"),
("CA93AKKEA1","CA","Fort Resolution","NT"),
("CATWUJ1ZWR","CA","Fort Saint James","BC"),
("CAX7303G61","CA","Fort Saint John","BC"),
("CAVICAVYU4","CA","Fort Saskatchewan","AB"),
("CA25OMJZND","CA","Fort Severn","ON"),
("CAVIXWITNG","CA","Fort Simpson","NT"),
("CA1RG58N63","CA","Fort Smith","NT"),
("CA5IE0G95J","CA","Fort Vermilion","AB"),
("CAEU5YTTBO","CA","Fortune","NL"),
("CAC8KU28B4","CA","Fox Valley","SK"),
("CAZR97EFBK","CA","Foxtrap","NL"),
("CAYQKEZQXE","CA","Foymount","ON"),
("CAK3CDWO29","CA","Francois","NL"),
("CAXN40VF4V","CA","Frankford","ON"),
("CA7D3LTF6R","CA","Fraser Lake","BC"),
("CA5R65H4K1","CA","Frederickton","NB"),
("CA7WF4LHEI","CA","Fredericton","NB"),
("CA4IIZXMV4","CA","Fruitvale","BC"),
("CA0YQUDWLJ","CA","Gabriola","BC"),
("CANSP4W964","CA","Galt","ON"),
("CA6L9R2O96","CA","Gambo","NL"),
("CA6R63E18F","CA","Gananoque","ON"),
("CA0Y9EVUYI","CA","Gander","NL"),
("CANNNKWTO2","CA","Ganges","BC"),
("CAEYUHM3OS","CA","Garden River","ON"),
("CAVUWAW4PW","CA","Garibaldi","BC"),
("CA3YBYT9HG","CA","Garson","ON"),
("CAW40TYPWD","CA","Gaspe","QC"),
("CAOQUAUI3Q","CA","Gatineau","QC"),
("CAD0095P68","CA","Georgetown","ON"),
("CAOH7HROYN","CA","Geraldton","ON"),
("CASZHQOE4C","CA","Gibsons","BC"),
("CA4YNZHRPU","CA","Gillam","MB"),
("CARP4XFA63","CA","Gimli","MB"),
("CASDKJ1J7U","CA","Girouxville","AB"),
("CAIOL62PJ7","CA","Gjoa Haven","NT"),
("CAO765YVZQ","CA","Glace Bay","NS"),
("CAL4O0EU37","CA","Glacier","BC"),
("CA7OQ97X4P","CA","Glassville","NB"),
("CAMPWOFFV3","CA","Gleichen","AB"),
("CAN29MY9CJ","CA","Glenburnie","NL"),
("CAD0KRVOY2","CA","Glencoe","ON"),
("CACPCKMG98","CA","Glendon","AB"),
("CA66XLMTP9","CA","Glenwood","AB"),
("CAVYVU78DK","CA","Gloucester","ON"),
("CA9YC4MB7Y","CA","Glovertown","NL"),
("CA0JINZSW6","CA","Godbout","QC"),
("CAYTRLNGUI","CA","Goderich","ON"),
("CAFQDMYR67","CA","Gods Lake","MB"),
("CAPJCBUJAV","CA","Gogama","ON"),
("CA3TI3LF9K","CA","Gold Bridge","BC"),
("CA815VH0EW","CA","Golden","BC"),
("CAQRJPJQW8","CA","Golden Lake","ON"),
("CA99J4SUZW","CA","Goldpines","ON"),
("CANIZ9X8U6","CA","Gooderham","ON"),
("CA902R0HOR","CA","Goodfish Lake","AB"),
("CA97GSXD17","CA","Goose Bay","NL"),
("CAMLCFFBB3","CA","Gore Bay","ON"),
("CAUACSJ7ZS","CA","Govan","SK"),
("CA72K8K8ZT","CA","Granby","QC"),
("CAGGMETNLG","CA","Grand Bank","NL"),
("CA8XVN97Q4","CA","Grand Bay","NB"),
("CAH3X0AWTI","CA","Grand Bend","ON"),
("CAZDRJLRC1","CA","Grand Centre","AB"),
("CA7ZF1M1HV","CA","Grand Falls","NB"),
("CAZDJ9K9D1","CA","Grand Forks","BC"),
("CADA2O7V76","CA","Grand Narrows","NS"),
("CA9YPVP2WW","CA","Grand Valley","ON"),
("CA1CYOEFJD","CA","Grande Prairie","AB"),
("CAT2NDC0FQ","CA","Grande-Riviere","QC"),
("CABHEIDLPN","CA","Granville Ferry","NS"),
("CAKEI9GF6I","CA","Grates Cove","NL"),
("CAS566KQKE","CA","Gravelbourg","SK"),
("CAT7R586WJ","CA","Gravenhurst","ON"),
("CAOA22WRPH","CA","Greenfield Park","QC"),
("CA68QNNX5F","CA","Greenwood","NS"),
("CA2CMN371W","CA","Grenfell","SK"),
("CAET2N0Y7P","CA","Griffin","SK"),
("CA99R61HN7","CA","Grimsby","ON"),
("CAQEUDC0TE","CA","Grimshaw","AB"),
("CADG2GN4C2","CA","Griswold","MB"),
("CAXFPXDXMM","CA","Grosses-Roches","QC"),
("CA7ET8VGGL","CA","Guelph","ON"),
("CAUBZ6BTLO","CA","Guigues","QC"),
("CA9O5WSIZP","CA","Gull Lake","SK"),
("CAXOMAL9XT","CA","Gypsumville","MB"),
("CANQ1J7I52","CA","Hafford","SK"),
("CAT495YUT7","CA","Hagensborg","BC"),
("CAIZ4AH30E","CA","Hagersville","ON"),
("CASMPEVM7J","CA","Hague","SK"),
("CAD92KR7MK","CA","Haileybury","ON"),
("CACVPAQJH9","CA","Haley Station","ON"),
("CAIMJZPJEI","CA","Haliburton","ON"),
("CA63W2P4L3","CA","Halifax","NS"),
("CADNN4UAO7","CA","Halkirk","AB"),
("CA5EHWXZ5G","CA","Hall Beach","NT"),
("CALOGB8UUF","CA","Hamilton","ON"),
("CAXQHNV3R8","CA","Hamiota","MB"),
("CAQFCLP1SV","CA","Hampton","NB"),
("CAGARE9WUV","CA","Hanley","SK"),
("CALB7U5193","CA","Hanna","AB"),
("CASRRNUIVL","CA","Hanover","ON"),
("CAX87NA0IQ","CA","Hantsport","NS"),
("CAA94J6ZFS","CA","Happy Valley","NL"),
("CAAMMGNWKF","CA","Harbour Grace","NL"),
("CANC2IUY3S","CA","Hardisty","AB"),
("CA7BFHBY8L","CA","Harriston","ON"),
("CA8D5FCK7N","CA","Harrow","ON"),
("CA7T4UQOAE","CA","Hartley Bay","BC"),
("CA0DWVC0OJ","CA","Harvey","NB"),
("CAB40N298B","CA","Hastings","ON"),
("CAMEQZYXM6","CA","Havelock","ON"),
("CARR0HGBWH","CA","Hawk Junction","ON"),
("CAOSC0T1K5","CA","Hawkesbury","ON"),
("CA5KS8T0JG","CA","Hay River","NT"),
("CAEAFD72JZ","CA","Hazelton","BC"),
("CATKH9VDQK","CA","Hearst","ON"),
("CA63LZ454A","CA","Hebertville","QC"),
("CAQXIKX20C","CA","Hedley","BC"),
("CACFQKI9JB","CA","Heisler","AB"),
("CAU1LQECAL","CA","Helina","AB"),
("CAGWKK1PVR","CA","Hemmingford","QC"),
("CAMDBKGCXS","CA","Hensall","ON"),
("CASNDAXXMR","CA","Heron Bay","ON"),
("CAY8IDKSY0","CA","Herschel","SK"),
("CAOILQ8GHU","CA","Hespeler","ON"),
("CAUTFA5C3X","CA","High Level","AB"),
("CAZG8XDUOC","CA","High Prairie","AB"),
("CA27PNZNNO","CA","High River","AB"),
("CA69EFPW9J","CA","Hillsborough","NB"),
("CAPPUV1XT1","CA","Hindon","ON"),
("CAE1YSWN5Z","CA","Hinton","AB"),
("CAUUMUIAIP","CA","Hixon","BC"),
("CAJX49UETK","CA","Hobbema","AB"),
("CA3NF4L950","CA","Holland","ON"),
("CAB4S7RX6L","CA","Holman Island","NT"),
("CASTFB3Y0N","CA","Holyrood","NL"),
("CAW4WQJPAM","CA","Hope","ON"),
("CADQRYZXYA","CA","Hopewell","NS"),
("CA1RITPPEH","CA","Horburg","AB"),
("CAIUSMTT9Q","CA","Hornepayne","ON"),
("CAX5GGVR38","CA","Houston","BC"),
("CAHU6GS5RT","CA","Hubbards","NS"),
("CAX9MMZ14H","CA","Hudson","QC"),
("CAWW3PPCGN","CA","Hudson Bay","SK"),
("CAIW4DN7L4","CA","Hudson Heights","QC"),
("CA2SLUYDOV","CA","Hull","QC"),
("CANAHMCL48","CA","Humboldt","SK"),
("CAI8Y8KEV3","CA","Hunter River","PE"),
("CAB0GY823A","CA","Huntingdon","QC"),
("CAUP5T3TOQ","CA","Huntsville","ON"),
("CA45DGQHP9","CA","Iberville","QC"),
("CAPOHA2DEE","CA","Igloolik","NT"),
("CADUCLXGWS","CA","Ignace","ON"),
("CA61L9V90Z","CA","Ile-a-la-Crosse","SK"),
("CAFEG6W6FM","CA","Ile-Perrot","QC"),
("CAUWXX9BBN","CA","Indian Head","SK"),
("CA6O8345WB","CA","Ingersoll","ON"),
("CA7HL2RL26","CA","Ingleside","ON"),
("CA0JCWPRIK","CA","Inglewood","ON"),
("CAOFHXRSKX","CA","Innisfail","AB"),
("CAHT1MZXX6","CA","Inuvik","NT"),
("CAEI964CC4","CA","Invermere","BC"),
("CAVO1LFJ53","CA","Inverness","NS"),
("CAZN1QFMOX","CA","Inwood","MB"),
("CAGPJFNGM2","CA","Iqaluit","NT"),
("CAYV837K73","CA","Iroquois","ON"),
("CA88OOSTSS","CA","Iroquois Falls","ON"),
("CAGUJWH7UX","CA","Irricana","AB"),
("CAXDDKTZMS","CA","Irvine","AB"),
("CAVUV2E35N","CA","Isle Pierre","BC"),
("CACTC5N5X4","CA","Jacques-Cartier","QC"),
("CAZG1HOVEL","CA","Jarvie","AB"),
("CA8S62RSVM","CA","Jasper","AB"),
("CANRP2UUP7","CA","Jean Marie River","NT"),
("CAO2CC7AH7","CA","Joliette","QC"),
("CAQJOFF31O","CA","Jonquiere","QC"),
("CAV7QNZLAM","CA","Joussard","AB"),
("CACZO7UEEJ","CA","Judique","NS"),
("CAHRWP1DXS","CA","Kagawong","ON"),
("CAWL7CP80K","CA","Kakabeka Falls","ON"),
("CAFQ8FCI2P","CA","Kamloops","BC"),
("CAHRWC5BVN","CA","Kamsack","SK"),
("CA3SC459X2","CA","Kanata","ON"),
("CAV4EKDF5T","CA","Kapuskasing","ON"),
("CA5D8IVB7D","CA","Kaslo","YT"),
("CA24Q8GMVJ","CA","Kedgwick","NB"),
("CAE8OKHLND","CA","Keene","ON"),
("CAQ1X4G3XM","CA","Keewatin","ON"),
("CAG65CHCQK","CA","Kelligrews","NL"),
("CAHHSX3OHH","CA","Kelowna","BC"),
("CAW62ESPSJ","CA","Kelvington","SK"),
("CARQN7TLUA","CA","Kemnay","MB"),
("CASZNACDUU","CA","Kemptville","ON"),
("CAUNSYB9G8","CA","Kennedy","SK"),
("CAGIN87FSY","CA","Kennetcook","NS"),
("CA5F6Y119T","CA","Kenora","ON"),
("CA1W4EAY85","CA","Kensington","PE"),
("CAM03YAJ6Q","CA","Kent Junction","NB"),
("CA2TZA9R9E","CA","Kentville","NS"),
("CA6GD8HM2J","CA","Keoma","AB"),
("CAI6XT55YR","CA","Keremeos","BC"),
("CA51PFLW6O","CA","Kerrobert","SK"),
("CAP5YYW8D3","CA","Keswick","ON"),
("CAOQB6CDPV","CA","Killam","AB"),
("CAJNOPSNGY","CA","Killarney","MB"),
("CAO6EA2KZS","CA","Kimberley","BC"),
("CAPYQL64OU","CA","Kimberly","BC"),
("CAU017DQ3X","CA","Kimmirut","NT"),
("CAERN6E353","CA","Kincardine","ON"),
("CA9JEC3E4S","CA","Kincolith","BC"),
("CACVDIZ2DU","CA","Kindersley","SK"),
("CA3E1H54EJ","CA","King City","ON"),
("CAW2PB5UFF","CA","Kingsport","NS"),
("CADUSH8W9K","CA","Kingston","ON"),
("CARN3RQGLT","CA","Kingsville","ON"),
("CAUNAZSPIO","CA","Kinistino","SK"),
("CAR80X3GCH","CA","Kinuso","AB"),
("CAA4YJ183T","CA","Kirkland Lake","ON"),
("CAV7KLN6FH","CA","Kitchener","ON"),
("CAUPHME0B5","CA","Kitimat","BC"),
("CA9C3CSFU2","CA","Kitscoty","AB"),
("CAKTMM1QFX","CA","Kitwanga","BC"),
("CAX0JK7Y21","CA","Knowlton","QC"),
("CANJN2KZ8T","CA","Kugaaruk","NU"),
("CABB63R16C","CA","Kugluktuk","NT"),
("CAUSYWIEUF","CA","Kuujjuaq","QC"),
("CAED0LC2M0","CA","L'Assomption","QC"),
("CAMA269B0L","CA","L'Epiphanie","QC"),
("CAM6OD8VQ2","CA","L'Etete","NB"),
("CANOZ62TMH","CA","L'Original","ON"),
("CA7M2KPPKC","CA","La Baie","QC"),
("CA0MJAXJVK","CA","La Guadeloupe","QC"),
("CAQJYYEO12","CA","La Macaza","QC"),
("CAD19FVVW2","CA","La Malbaie","QC"),
("CAIZM8P7KP","CA","La Ronge","SK"),
("CAU4ZSOUCE","CA","La Salle","QC"),
("CAEADTZFVC","CA","La Sarre","QC"),
("CAG5SB0OEJ","CA","La Scie","NL"),
("CAO1SD8C32","CA","La Tuque","QC"),
("CAH2U5X6KB","CA","Labelle","QC"),
("CAHX5HD1TT","CA","Lac La Biche","AB"),
("CA6L47AJQZ","CA","Lac-Megantic","QC"),
("CAKICSVGVC","CA","Lachine","QC"),
("CAIPIGW2SE","CA","Lachute","QC"),
("CA0XVDYP64","CA","Lacolle","QC"),
("CAABBLU2KF","CA","Lacombe","AB"),
("CAKX8GD3SW","CA","Ladner","BC"),
("CATACQD45D","CA","Ladysmith","BC"),
("CA11QZQX41","CA","Lafontaine","QC"),
("CA8FM3H7J2","CA","Lake Cowichan","BC"),
("CA4RIHVBDP","CA","Lake Louise","AB"),
("CAMQFZULCW","CA","Lakefield","ON"),
("CAM3WC00D9","CA","Lamaline","NL"),
("CAG0DX7W0B","CA","Lamont","AB"),
("CAOITKU79G","CA","Lampman","SK"),
("CAXPFRASNX","CA","Lancaster","ON"),
("CAVJ9WKN50","CA","Lancaster Park","AB"),
("CANIYVFY73","CA","Lang","SK"),
("CAH0NB7XR5","CA","Langbank","SK"),
("CAM7XXZLUV","CA","Langham","SK"),
("CA54RPRXPF","CA","Langley","BC"),
("CAFOAUMIY4","CA","Langruth","MB"),
("CAIMFQJ7W6","CA","Lanigan","SK"),
("CAFT4FEYAJ","CA","Lanoraie","QC"),
("CA228UZYAE","CA","Lansdowne","ON"),
("CAML9938DL","CA","Laprairie","QC"),
("CAUTCE18LG","CA","Lashburn","SK"),
("CA1PVGN5ZQ","CA","Laurentides","QC"),
("CA78L76VMT","CA","Lauzon","QC"),
("CAGW2K4G6Z","CA","Laval","QC"),
("CA9IEARZQT","CA","Laval-des-Rapides","QC"),
("CAOL9BR92Z","CA","Laval-Ouest","QC"),
("CAHO6OJSI0","CA","Lavaltrie","QC"),
("CAOKLT0RSA","CA","Lawn","NL"),
("CAA6K16BVU","CA","Lawrencetown","NS"),
("CAW56OE8NW","CA","Lazare","MB"),
("CAXULHM3HB","CA","Leader","SK"),
("CAO34OUXY4","CA","Leamington","ON"),
("CA4J6AU14R","CA","Leaside","ON"),
("CA6AFLJ2HG","CA","Leduc","AB"),
("CAX3XJ6FVV","CA","Lefroy","ON"),
("CAIZJDXIH1","CA","Legal","AB"),
("CA2NBWOGNV","CA","Lennoxville","QC"),
("CAR2GB5YR2","CA","Leon","BC"),
("CA1PM85H3O","CA","Lery","QC"),
("CAHN1E6IG8","CA","Les Escoumins","QC"),
("CA6S4V8SQ0","CA","Lethbridge","AB"),
("CAV6B05236","CA","Levack","ON"),
("CASQFX8JMP","CA","Levis","QC"),
("CA7N4D6LMC","CA","Lewisporte","NL"),
("CADR7MJYME","CA","Lillooet","BC"),
("CA4XFA0JGT","CA","Lindsay","ON"),
("CA9WRIFD8M","CA","Liniere","QC"),
("CA0C07YMJB","CA","Lipton","SK"),
("CADRYXPKCU","CA","Listowel","ON"),
("CAIR4JBLCK","CA","Little Bay Island","NL"),
("CAI42XHBKI","CA","Little Current","ON"),
("CANLPM89YM","CA","Little Harbour","NL"),
("CA1WJQHVK0","CA","Livelong","SK"),
("CANPJYAWJS","CA","Lively","ON"),
("CA0MQIXB1L","CA","Liverpool","NS"),
("CAWR7505R1","CA","Lloydminster","AB"),
("CA2ASJ6CJU","CA","Logy Bay","NL"),
("CA23TC0C51","CA","London","ON"),
("CAZWJX7KI4","CA","Londonderry","NS"),
("CABQ9CW0EZ","CA","Long Point","NS"),
("CAB6IIJ2CL","CA","Long Sault","ON"),
("CA66Y6I47I","CA","Longlac","ON"),
("CA0RF7CYCN","CA","Longueuil","QC"),
("CAPL0MMELY","CA","Looma","AB"),
("CAL3G46TQD","CA","Loon Bay","NL"),
("CAZPKITR1T","CA","Loon Lake","SK"),
("CAJH1VFEJ5","CA","Loretteville","QC"),
("CAZJRMYCLK","CA","Louiseville","QC"),
("CAG1PNVF0V","CA","Lourdes","NL"),
("CA5KDYCFSV","CA","Lucan","ON"),
("CAWURB8AH8","CA","Luceville","QC"),
("CAU8UTLGD1","CA","Lucknow","ON"),
("CAI3PDJP8O","CA","Lumby","BC"),
("CAAMMN1FJX","CA","Lumsden","SK"),
("CA9A9HLRPG","CA","Lunenburg","NS"),
("CAZK9L0NMI","CA","Luskville","QC"),
("CAQCW915XC","CA","Lyster","QC"),
("CARKZTZIR9","CA","Lytton","BC"),
("CAT1QESGUS","CA","Mabou","NS"),
("CA04D1RZJI","CA","Macamic","QC"),
("CACFSEKPQC","CA","Macdiarmid","ON"),
("CAAQ6A9XJ2","CA","Macgregor","MB"),
("CAZAHRRBJS","CA","Mackay","AB"),
("CAGWT8WDQ8","CA","Mackenzie","BC"),
("CATIME8DQJ","CA","Macklin","SK"),
("CA3XTCVDFU","CA","Madoc","ON"),
("CAOWLF857O","CA","Magnetawan","ON"),
("CA10XYEN77","CA","Magog","QC"),
("CA6TLE6CXA","CA","Magpie","QC"),
("CA9RN452ZT","CA","Magrath","AB"),
("CAZL98QGXS","CA","Mahone Bay","NS"),
("CAHUQVHX3N","CA","Maidstone","SK"),
("CARO2Y108B","CA","Maitland","ON"),
("CARWGWZFPY","CA","Malartic","QC"),
("CA0Z7QF4IX","CA","Malonton","MB"),
("CAY9TG7W4Y","CA","Malton","ON"),
("CAL6WM65YY","CA","Manitou","MB"),
("CA1EU0TKZU","CA","Manitouwadge","ON"),
("CAJ6KZA3W9","CA","Manitowaning","ON"),
("CADQPKMUJ8","CA","Maniwaki","QC"),
("CA1GV8LT6N","CA","Mannville","AB"),
("CA71O1LNV5","CA","Manseau","QC"),
("CATF44J1DX","CA","Maple","ON"),
("CAR3HEY1NZ","CA","Maple Creek","SK"),
("CAHI72BEQJ","CA","Maple Grove","QC"),
("CAFEK01F6V","CA","Maple Ridge","BC"),
("CAVBZFCDC4","CA","Marathon","ON"),
("CAHUJGV6FC","CA","Marieville","QC"),
("CAPNF125KH","CA","Markdale","ON"),
("CAJ4IKKOFF","CA","Markham","ON"),
("CAZFUCT7HB","CA","Markstay","ON"),
("CA10RW778X","CA","Marmora","ON"),
("CAVOYXTIEC","CA","Marshy Hope","NS"),
("CANXX7LDNL","CA","Marwayne","AB"),
("CASHYMOFXQ","CA","Marystown","NL"),
("CAGOMNWVLR","CA","Marysville","BC"),
("CAJJOD13PP","CA","Masset","BC"),
("CA0MWMZJ8S","CA","Massey","ON"),
("CA16EQLCG2","CA","Masson","QC"),
("CA13QXYBOI","CA","Matagami","QC"),
("CAUDVWHLLI","CA","Matane","QC"),
("CA8I481C03","CA","Mattawa","ON"),
("CAJFU5RA7S","CA","Mauricie","QC"),
("CAEXPD8EV2","CA","Maxville","ON"),
("CASRY9CKRL","CA","Mayne","BC"),
("CA2WT49T7S","CA","Maynooth","ON"),
("CA91X0C4TQ","CA","McAdam","NB"),
("CA2J3AYZDQ","CA","McBride","BC"),
("CARB04WSPY","CA","McCreary","MB"),
("CAOI2YCAQL","CA","McGregor","ON"),
("CACOLPTEGV","CA","McKinnon Harbour","NS"),
("CAYK5WKJMB","CA","McLennan","AB"),
("CAVNFRF5P4","CA","McMasterville","QC"),
("CANS2Z3TLF","CA","McMurphy","BC"),
("CAH65BLL6K","CA","McMurray","AB"),
("CA6CGQV31Q","CA","McWatters","QC"),
("CAQHH6M7AA","CA","Meadow Lake","SK"),
("CA0D936VJO","CA","Meaford","ON"),
("CA1P0NA67H","CA","Medicine Hat","AB"),
("CAJO7FR95H","CA","Melfort","SK"),
("CAQNNDVYNV","CA","Melita","MB"),
("CABXZISJ7U","CA","Melocheville","QC"),
("CA87IJEP0X","CA","Melville","SK"),
("CAE7D5GJM7","CA","Memramcook","NB"),
("CA69K277YJ","CA","Merigomishe","NS"),
("CA5Y1XH8RP","CA","Merrickville","ON"),
("CAGA9U09SE","CA","Merritt","BC"),
("CAH5JYO55V","CA","Merville","BC"),
("CAFQYNYW63","CA","Metabetchouan","QC"),
("CAU81BHT1X","CA","Miami","MB"),
("CA3AS3KKH1","CA","Michel","SK"),
("CAQ00F65AL","CA","Michipicoten","ON"),
("CAW89V5GYZ","CA","Midale","SK"),
("CAO0B5TD3W","CA","Middle Arm","NL"),
("CAOV08GHA7","CA","Middleton","NS"),
("CAIAMOGXAC","CA","Midhurst","ON"),
("CA5J7BZ6BN","CA","Midland","ON"),
("CA6MT00XXO","CA","Midnapore","AB"),
("CATXX9E7HW","CA","Midway","BC"),
("CAH3LX0VA6","CA","Milden","SK"),
("CAEIHDOS1V","CA","Mildmay","ON"),
("CAFVVFTS4M","CA","Milk River","AB"),
("CAP1W48D1Q","CA","Millbrook","ON"),
("CAGMOHIYNW","CA","Millet","AB"),
("CAG4A5XC0C","CA","Millhaven","ON"),
("CA7VS0OXNE","CA","Millstream","QC"),
("CAYJI7WKYD","CA","Milton","ON"),
("CA7MUPKIM1","CA","Milverton","ON"),
("CAMW6K97WH","CA","Mimico","ON"),
("CA3PIRM55L","CA","Minden","ON"),
("CAOOTL8RZG","CA","Minitonas","MB"),
("CADU5YCSZZ","CA","Minnedosa","MB"),
("CAP6JYDGFG","CA","Mirabel","QC"),
("CA6X8S2EER","CA","Miramichi","NB"),
("CA27DBYCRC","CA","Mission","BC"),
("CA7XAJPAJE","CA","Mississauga","ON"),
("CAG2DUJSBP","CA","Mitchell","ON"),
("CAPKISYWJ0","CA","Moberly Lake","BC"),
("CA4WC294EG","CA","Monarch","AB"),
("CA1P0RZJ6G","CA","Moncton","NB"),
("CAMJB5CNV1","CA","Mont-Apica","QC"),
("CA7DT5AD6E","CA","Mont-Joli","QC"),
("CAAJHKNW0P","CA","Mont-Laurier","QC"),
("CAL1HLLN17","CA","Mont-Royal","QC"),
("CA7DDJ08L7","CA","Mont-Saint-Hilaire","QC"),
("CAMFDWSKB3","CA","Mont-Tremblant","QC"),
("CA3SNQOOGA","CA","Montague","PE"),
("CAQXVBLXJS","CA","Montebello","QC"),
("CAAWBA5XIS","CA","Montmagny","QC"),
("CACVP5F08J","CA","Montmartre","SK"),
("CATW9HKPSA","CA","Montreal","QC"),
("CANNL8K50U","CA","Montreal Lake","SK"),
("CA1C579NZM","CA","Montreal-Est","QC"),
("CAJORZPZII","CA","Montreal-Nord","QC"),
("CAVR0GHSR4","CA","Moores Mills","NB"),
("CAFDD0IDUJ","CA","Moose Factory","ON"),
("CAQ0R0NQM6","CA","Moose Jaw","SK"),
("CAFE54ENM9","CA","Moosomin","SK"),
("CAFMQXEH2U","CA","Morden","MB"),
("CAUFUCTPWK","CA","Morinville","AB"),
("CAPNLDE8KT","CA","Morris","MB"),
("CAMQX0DJAT","CA","Morrisburg","ON"),
("CA50RKITEC","CA","Mortlach","SK"),
("CA99P3ZLNP","CA","Mosherville","NS"),
("CA982NGNG3","CA","Mossbank","SK"),
("CADD3RXEL2","CA","Mount Forest","ON"),
("CAECNX629F","CA","Mount Pearl","NL"),
("CABZIBL60U","CA","Mount Pearl Park","NL"),
("CAF3IWQYZ3","CA","Mount Uniacke","NS"),
("CAC3V9HGCW","CA","Mount-Royal","QC"),
("CAS0TY23ED","CA","Mountain Grove","ON"),
("CA2XOO3PII","CA","Mud River","BC"),
("CAS0FIZEMC","CA","Munson","AB"),
("CAIHMZXZVQ","CA","Murdochville","QC"),
("CAZPP1T3FV","CA","Musquodoboit","NS"),
("CA03K4S2NL","CA","Musquodoboit Harbour","NS"),
("CA3243HQFZ","CA","Nadu","BC"),
("CA82Y61UX0","CA","Nahanni Butte","NT"),
("CAKM2DQH9R","CA","Naicam","SK"),
("CALTVDWJZZ","CA","Naisberry","SK"),
("CAL333UI22","CA","Nakina","ON"),
("CAL19MW6NG","CA","Nakusp","BC"),
("CASPUI63AR","CA","Nampa","AB"),
("CAX55TO4TA","CA","Nanaimo","BC"),
("CA8WD2FF50","CA","Nanoose Bay","BC"),
("CAGENDKATD","CA","Nanton","AB"),
("CA0NW6R6YO","CA","Napanee","ON"),
("CAC4I09CAH","CA","Napierville","QC"),
("CA8OJN3POK","CA","Natashquan","QC"),
("CA3BXOMR1M","CA","Nauwigewauk","NB"),
("CAFYT65RVH","CA","Neepawa","MB"),
("CAVEH4QSMY","CA","Neguac","NB"),
("CAH6MKVB5Y","CA","Neilburg","SK"),
("CAN3N9UPV9","CA","Nelson","BC"),
("CANOGSGB9C","CA","Nelson House","MB"),
("CAQRHGK3F1","CA","Nepean","ON"),
("CA91M5DS40","CA","Netherhill","SK"),
("CAVR9PG5Z4","CA","Neuville","QC"),
("CATFXAR7MI","CA","New Denver","BC"),
("CAY3YJ7DKG","CA","New Germany","NS"),
("CAF7MSZQSU","CA","New Glasgow","NS"),
("CAI2KZ7K31","CA","New Hamburg","ON"),
("CA00BS7YA6","CA","New Liskeard","ON"),
("CA18P8MAP1","CA","New Osgoode","SK"),
("CAIBUH2NCK","CA","New Richmond","QC"),
("CAPWJXGNYH","CA","New Waterford","NS"),
("CAOA9V8J2A","CA","New Westminster","BC"),
("CARSIE38FL","CA","Newburgh","ON"),
("CAKA2MXE7N","CA","Newcastle","ON"),
("CABRLSEJ92","CA","Newcastle Bridge","NB"),
("CAUIY310DT","CA","Newgate","BC"),
("CASW7W5NHP","CA","Newmarket","ON"),
("CAXKCVZJJA","CA","Niagara","ON"),
("CAA42OOCRI","CA","Niagara Falls","ON"),
("CAUPMWPZQI","CA","Niagara-on-the-Lake","ON"),
("CAWYF1LWRJ","CA","Nicolet","QC"),
("CAG3FFNYQX","CA","Nigadoo","NB"),
("CA2TMQ5D9Z","CA","Nipawin","SK"),
("CA2VWSVMBS","CA","Nipigon","ON"),
("CALQU7NLR4","CA","Nippers Harbour","NL"),
("CAO6KB5A98","CA","Nisku","AB"),
("CA3VZ8988C","CA","Nobleford","AB"),
("CA4550RGSD","CA","Noelville","ON"),
("CA7MKV8BZX","CA","Noranda","QC"),
("CAHJ8NTIVX","CA","Norman Wells","NT"),
("CAEU5N3EZ7","CA","Normandin","QC"),
("CAJ48BL0OT","CA","Norris Arm","NL"),
("CAN8OWKOT2","CA","North Battleford","SK"),
("CA82P1KKZY","CA","North Bay","ON"),
("CAF4MIJLQ3","CA","North Portal","SK"),
("CAQYECZ35N","CA","North Surrey","BC"),
("CACUJWICYQ","CA","North Vancouver","BC"),
("CAENSZ8RXN","CA","North Vermilion","AB"),
("CAWK5G6VJW","CA","Norway House","MB"),
("CAUY9T1EHD","CA","Norwich","ON"),
("CA90ASC8JR","CA","Norwood","ON"),
("CAWCQ44OS1","CA","Notre Dame","NB"),
("CA8XHET1BO","CA","Notre-Dame-de-Lourdes","MB"),
("CAZKI0ZZE8","CA","Notre-Dame-des-Monts","QC"),
("CAZO1CXL4T","CA","Notre-Dame-du-Lac","QC"),
("CAXUX2IP3Q","CA","Notre-Dame-du-Laus","QC"),
("CANL5HMG5M","CA","Notre-Dame-du-Nord","QC"),
("CA0NNZN18M","CA","Oakville","ON"),
("CAQAZNV3GT","CA","Obed","AB"),
("CAXEVG4Y7S","CA","Ocean Falls","BC"),
("CAJC96SFST","CA","Ochre River","MB"),
("CA3FTQH2C7","CA","Okanagan","BC"),
("CACCU8FB1D","CA","Okotoks","AB"),
("CAPWUUU1ME","CA","Old Crow","YT"),
("CAEWL7BD0E","CA","Olds","AB"),
("CATU4AWHH9","CA","Oliver","BC"),
("CATCH9NIND","CA","Omemee","ON"),
("CAEI79JUOY","CA","Omerville","QC"),
("CAQ951M6FG","CA","One Hundred Mile House","BC"),
("CA0KQW185V","CA","Onion Lake","SK"),
("CAKM585SMJ","CA","Onoway","AB"),
("CAAUTUOHTE","CA","Orangeville","ON"),
("CAQYGD4WU4","CA","Orillia","ON"),
("CAGK0IT6DE","CA","Orleans","ON"),
("CATJMYB9IM","CA","Ormstown","QC"),
("CA3BHRTA6K","CA","Oromocto","NB"),
("CA8NXDJSH0","CA","Oshawa","ON"),
("CACII5PWJI","CA","Osoyoos","BC"),
("CAF6GRFZEJ","CA","Ottawa","ON"),
("CAAVA46HOF","CA","Otter Lake","ON"),
("CA4MSNEAOR","CA","Otterburn Park","QC"),
("CAS7WI4G0J","CA","Otterburne","MB"),
("CANHB3GPMR","CA","Outlook","SK"),
("CALXVREJ7J","CA","Outremont","QC"),
("CA5Z6K9VB2","CA","Owen Sound","ON"),
("CA28K6PLQC","CA","Oxbow","SK"),
("CA21GJR2AD","CA","Oxford","NS"),
("CA055EPCXV","CA","Oxford House","MB"),
("CAB4FLZQN2","CA","Oxford Junction","NS"),
("CAY89NTZ0W","CA","Oyama","BC"),
("CA1GFSJP6J","CA","Pacific","BC"),
("CAVBYLNVGY","CA","Paisley","ON"),
("CA0VJ0M73L","CA","Pakenham","ON"),
("CAGC99BA6D","CA","Palmerston","ON"),
("CAQL5ABCT7","CA","Pangnirtung","NT"),
("CANRSAN89O","CA","Papineauville","QC"),
("CA4TOR0RCG","CA","Paradise","NL"),
("CA3MQFWWSN","CA","Paradise Valley","AB"),
("CAIYXUAR1X","CA","Parent","QC"),
("CAIT862HU7","CA","Paris","ON"),
("CAAJYBABSE","CA","Park Head","ON"),
("CAXITUFMHY","CA","Parkhill","ON"),
("CAKFSV6TTO","CA","Parksville","BC"),
("CAN1VPJPWT","CA","Parrsboro","NS"),
("CA9V5J6XY4","CA","Parry Sound","ON"),
("CAGSYVEGTZ","CA","Parsons Pond","NL"),
("CAVMU1FNQ3","CA","Pascal","SK"),
("CAPLS8BP2L","CA","Pass Lake","ON"),
("CAK74R43VK","CA","Patricia","AB"),
("CAVUGAAA96","CA","Paulatuk","NT"),
("CAW47CRYFG","CA","Peace River","AB"),
("CAK7PWXRHH","CA","Peachland","BC"),
("CAYM83P4OL","CA","Peers","AB"),
("CAZ4V9E4GB","CA","Pefferlaw","ON"),
("CA8ON0M2H7","CA","Pelly Bay","NT"),
("CAA637YKPW","CA","Pelly Crossing","YT"),
("CA7Y0W3OH2","CA","Pemberton","BC"),
("CASDC7HSJQ","CA","Pembroke","ON"),
("CAG6R398AK","CA","Penetanguishene","ON"),
("CAFDRDYHA5","CA","Penhold","AB"),
("CAFB2IZKKS","CA","Pennfield","NB"),
("CAXW0FPJ65","CA","Penticton","BC"),
("CAQX906JKM","CA","Perth","ON"),
("CAXC0VTA19","CA","Petawawa","ON"),
("CAL3SLNCDL","CA","Peterborough","ON"),
("CA9E0ZX75O","CA","Petit-Etang","NS"),
("CA4EOBX9XV","CA","Petrolia","ON"),
("CALXQE8ROU","CA","Petty Harbour","NL"),
("CAVGFJTT43","CA","Pickering","ON"),
("CA7525C7TH","CA","Picton","ON"),
("CALISJRPED","CA","Pictou","NS"),
("CAN5SVXGPS","CA","Pierrefonds","QC"),
("CAW4BPXGS5","CA","Pierreville","QC"),
("CALUAY24FO","CA","Pikangikum","ON"),
("CAN88FXNSK","CA","Pilot Butte","SK"),
("CASKGP05IW","CA","Pilot Mound","MB"),
("CAAUM8AEDW","CA","Pinawa","MB"),
("CA9OUBSA0F","CA","Pincher Creek","AB"),
("CAI8UFVN0N","CA","Pincourt","QC"),
("CA7GD7MW4W","CA","Pine Falls","MB"),
("CAQQ405HXE","CA","Pinewood","ON"),
("CA5RQY1QEJ","CA","Pitt Meadows","BC"),
("CAZ9ZUW0I3","CA","Placentia","NL"),
("CAHWB3SGZJ","CA","Plamondon","AB"),
("CA74KCMHRS","CA","Plaster Rock","NB"),
("CA9IQA94U8","CA","Plessisville","QC"),
("CADU3AUMDB","CA","Plunkett","SK"),
("CAIPEB5EVC","CA","Point Claire","QC"),
("CAIFP5XGX6","CA","Point Edward","ON"),
("CAYNH7SBG6","CA","Pointe-aux-Trembles","QC"),
("CA6JG06UCP","CA","Pointe-Calumet","QC"),
("CAJR0P5W2O","CA","Pointe-Claire","QC"),
("CABRT98RF7","CA","Pointe-du-Chene","NB"),
("CAFWF78VEE","CA","Pointe-Lebel","QC"),
("CAFUFLPRA9","CA","Pond Inlet","NT"),
("CAJBYO71DJ","CA","Ponoka","AB"),
("CAT7S1Y78D","CA","Pont-Rouge","QC"),
("CA4NLDJZSY","CA","Pontypool","ON"),
("CAU7JKZUTI","CA","Poplar Hill","ON"),
("CA5S7CTLVM","CA","Port Alberni","BC"),
("CATNOSVX6Z","CA","Port Albert","NL"),
("CALRC4R43M","CA","Port Alice","BC"),
("CACN6CH0UM","CA","Port Blandford","NL"),
("CAS2ZMOU8H","CA","Port Clements","BC"),
("CAIX9DUFCG","CA","Port Colborne","ON"),
("CA7PKZTOM6","CA","Port Coquitlam","BC"),
("CABSITSDFL","CA","Port Credit","ON"),
("CAGE749GMR","CA","Port Dover","ON"),
("CADV48BHOJ","CA","Port Edward","BC"),
("CA69I0Y469","CA","Port Elgin","ON"),
("CAXP2Q2ICJ","CA","Port Hardy","BC"),
("CAWJN6Z9XD","CA","Port Hastings","NS"),
("CA51MHJA1P","CA","Port Hawkesbury","NS"),
("CAKKQIPXSM","CA","Port Hope","ON"),
("CAMVDPDP8A","CA","Port Mann","BC"),
("CA8WG86DMC","CA","Port McNicoll","ON"),
("CAF8TYJVO3","CA","Port Mellon","BC"),
("CAFEM4BEQY","CA","Port Moody","BC"),
("CA94ONTXX2","CA","Port Mouton","NS"),
("CATDB0RXC6","CA","Port Neville","BC"),
("CA564P1TTG","CA","Port Perry","ON"),
("CA7FKJUBI4","CA","Port Saunders","NL"),
("CAF6R93OBX","CA","Port Stanley","ON"),
("CA2MXTKAZQ","CA","Port Weller","ON"),
("CAG4FIX8Y5","CA","Port Williams","NS"),
("CAOJPJV8NB","CA","Port-Cartier","QC"),
("CAEEKI3WF5","CA","Portage","PE"),
("CAJDY3NYU4","CA","Portage La Prairie","MB"),
("CA39M1IK66","CA","Portneuf","QC"),
("CA4WQZ4DBJ","CA","Portugal Cove","NL"),
("CASV1VSH1C","CA","Pouce Coupe","BC"),
("CAU0FIZ9M2","CA","Powassan","ON"),
("CAJ831TA8X","CA","Powell River","BC"),
("CA6YXBC8U4","CA","Preeceville","SK"),
("CA4V0XC297","CA","Prescott","ON"),
("CA3PP2ZB4I","CA","Preston","ON"),
("CAJ8KDITAP","CA","Price","QC"),
("CAS804HU9M","CA","Prince","SK"),
("CAQAJ3DTBG","CA","Prince Albert","SK"),
("CAI0IHCN0W","CA","Prince George","BC"),
("CAVK9EEJ46","CA","Prince Rupert","BC"),
("CAS4B9ZLVQ","CA","Prince William","NB"),
("CAWFT984PQ","CA","Princeton","BC"),
("CA588HV8DR","CA","Princeville","QC"),
("CATM676AEY","CA","Pritchard","BC"),
("CAEQ8EB448","CA","Providence","NT"),
("CAKYHS37J8","CA","Provost","AB"),
("CAFRQA032U","CA","Pubnico","NS"),
("CAQ82WIGVX","CA","Puvirnituq","QC"),
("CA74CI9GRT","CA","Qualicum Beach","BC"),
("CAF8LIF4RU","CA","Quathiaski Cove","BC"),
("CAWH5XL8RC","CA","Queen Charlotte","BC"),
("CAGT8Z94XH","CA","Queenston","ON"),
("CA99ZIQRB6","CA","Quesnel","BC"),
("CAZXPE2G9Y","CA","Quill Lake","SK"),
("CAYFVJNNV4","CA","Radisson","SK"),
("CAG44Q917J","CA","Radville","SK"),
("CAB712YD8X","CA","Radway","AB"),
("CABXCDEMCC","CA","Ralston","AB"),
("CA18WPVSUB","CA","Ramea","NL"),
("CAXY2709QC","CA","Rankin Inlet","NT"),
("CAGSEF6NCH","CA","Rawdon","QC"),
("CAKPVZB7BD","CA","Raymond","AB"),
("CAF83A1XMZ","CA","Red Deer","AB"),
("CAVO6WYX8E","CA","Red Lake","ON"),
("CAQMTX96EU","CA","Red Rock","ON"),
("CAW9U8H5MW","CA","Redcliff","AB"),
("CAEP7GMUFI","CA","Redvers","SK"),
("CAJLEHJMW9","CA","Redwater","ON"),
("CA9Q7IWLDT","CA","Regina","SK"),
("CAV71DDN9S","CA","Renfrew","ON"),
("CACH8ZBNHU","CA","Renous","NB"),
("CA9VCSH82Q","CA","Repentigny","QC"),
("CAY99VVNOR","CA","Repulse Bay","NT"),
("CAVQ49DE1Q","CA","Resolute","NU"),
("CAWAP8X737","CA","Resolution","NT"),
("CA2F0KN3BM","CA","Revelstoke","BC"),
("CADKH98603","CA","Revenue","SK"),
("CAW5CAKE1H","CA","Rexdale","ON"),
("CAORPMYSU1","CA","Rexton","NB"),
("CA7ULVXXHA","CA","Richan","ON"),
("CAIZJQ5KU2","CA","Richelieu","QC"),
("CAQ7DBMFSA","CA","Richer","MB"),
("CA6IX5AR7I","CA","Richibucto","NB"),
("CAMSDJQVU8","CA","Richmond","BC"),
("CAUEY0ZT3Q","CA","Richmond Hill","ON"),
("CA0H2MWUX3","CA","Ridgetown","ON"),
("CACU9NMG58","CA","Rigaud","QC"),
("CA9JSZEN79","CA","Rigolet","NL"),
("CA2692ZDSZ","CA","Rimbey","AB"),
("CAUULQPJU2","CA","Rimouski","QC"),
("CAE3P0JV9S","CA","Riondel","BC"),
("CAE2STQZ2S","CA","Ripon","QC"),
("CA5CU4PN4K","CA","River Charlo","NB"),
("CAHQB7959N","CA","River Valley","ON"),
("CA9ZOSVXL9","CA","Rivers","MB"),
("CA0D3QD6II","CA","Riviere-des-Prairies","QC"),
("CAJDN90RTI","CA","Riviere-du-Loup","QC"),
("CAH4PRAZEJ","CA","Riviere-Pigou","QC"),
("CAY2CT0Y30","CA","Roberts Creek","BC"),
("CAC7QPD98W","CA","Roberval","QC"),
("CAMW5NOZ56","CA","Roblin","ON"),
("CA4UXEUCYT","CA","Rockglen","SK"),
("CAEBNFAQGM","CA","Rockland","ON"),
("CAY6CBGL83","CA","Rocky Mountain House","AB"),
("CAHEQ5DVBI","CA","Rodney","ON"),
("CAQ9WKLVE0","CA","Rogersville","NB"),
("CA71FHRV4P","CA","Rosalind","AB"),
("CA2G1J1AMJ","CA","Rose Lake","BC"),
("CAOCO280KY","CA","Rosedale","AB"),
("CA9HJUDXUK","CA","Rosemary","AB"),
("CAYA2Q67G9","CA","Rosemere","QC"),
("CAOISQSE9H","CA","Rosenfeld","MB"),
("CARYJZY3Y8","CA","Rosetown","SK"),
("CALI3YFXJE","CA","Rossland","BC"),
("CA8L5ETMNH","CA","Rossport","ON"),
("CA4F7XUHEL","CA","Rothesay","NB"),
("CAFYLE2JMN","CA","Rouyn","QC"),
("CA1PLHN5WV","CA","Roxboro","QC"),
("CAR1AKOY1T","CA","Russell","ON"),
("CAE9Q8Q5U6","CA","Rustico","PE"),
("CA3FK6Y6TZ","CA","Rycroft","AB"),
("CAWFHJKDFC","CA","Sable River","NS"),
("CAFQW3OYW2","CA","Sachs Harbour","NT"),
("CA7NBYT54X","CA","Sackville","NB"),
("CAKO3IVXIS","CA","Sacre-Coeur","QC"),
("CAC0BXDR9T","CA","Saint Albert","AB"),
("CAH6X54U8C","CA","Saint Andrews","NB"),
("CAHJBAOG89","CA","Saint Anthony","NL"),
("CA4BR08ASL","CA","Saint Antoine","QC"),
("CAB4JOWTID","CA","Saint Brieux","SK"),
("CAZFJ49SHQ","CA","Saint Bruno","QC"),
("CABS108A9D","CA","Saint Catharines","ON"),
("CAL1EUC7GN","CA","Saint Catherines","ON"),
("CABZC7SULS","CA","Saint Clair Beach","ON"),
("CA95WIXD99","CA","Saint George","NL"),
("CA6B9ELJS7","CA","Saint Georges De Beauce","QC"),
("CAK61XDHKP","CA","Saint Gregor","SK"),
("CAHWX9RI10","CA","Saint Guillaume","QC"),
("CANYJLBSUH","CA","Saint Isidore","QC"),
("CA44WPNOW8","CA","Saint John","NB"),
("CAVY58FQXW","CA","Saint John's","NL"),
("CANV6ED8E1","CA","Saint Jones Within","NL"),
("CA6YMIQH0U","CA","Saint Lazare","MB"),
("CALWK9LGHG","CA","Saint Leonard","QC"),
("CAFNPUDNR0","CA","Saint Louis","SK"),
("CAIYFW6TXD","CA","Saint Louis De Kent","NB"),
("CASKVI2WDN","CA","Saint Margaret Bay","NB"),
("CATYWEFEVU","CA","Saint Marys","ON"),
("CA1LPF8GFQ","CA","Saint Paul","AB"),
("CAFUMMOKZG","CA","Saint Peters","NS"),
("CA4VZ7RDUL","CA","Saint Thomas","ON"),
("CABRZQ6VK7","CA","Saint Vincent","AB"),
("CAGANPR2G6","CA","Saint Walberg","SK"),
("CAX2SMNS3S","CA","Saint Walburg","SK"),
("CAN2ZFGU0S","CA","Saint-Agapit","QC"),
("CAL0ISW30D","CA","Saint-Ambroise","QC"),
("CADN24PIBN","CA","Saint-Anselme","QC"),
("CAL498WC1K","CA","Saint-Augustin","QC"),
("CAF0ZVU0NG","CA","Saint-Basile","QC"),
("CA169XA9BN","CA","Saint-Bruno-de-Montarville","QC"),
("CAWDSMW49H","CA","Saint-Cesaire","QC"),
("CA8IQ4VROA","CA","Saint-Charles","ON"),
("CASO6NPU4Q","CA","Saint-Denis","QC"),
("CA0DOAMZYI","CA","Saint-Eustache","QC"),
("CADR49VER3","CA","Saint-Fabien","QC"),
("CAXH7S9W32","CA","Saint-Felicien","QC"),
("CAK9PA4U04","CA","Saint-Felix-de-Valois","QC"),
("CA7PFUODC2","CA","Saint-Francois","QC"),
("CA5HB0W23T","CA","Saint-Gabriel","QC"),
("CAKBMT7PVS","CA","Saint-Gedeon","QC"),
("CAZL23F28N","CA","Saint-Georges","QC"),
("CASNHH1UJ6","CA","Saint-Germain-de-Grantham","QC"),
("CABU68XA1H","CA","Saint-Henri-de-Levis","QC"),
("CALNATD6LD","CA","Saint-Henri-de-Taillon","QC"),
("CASOH7RPVJ","CA","Saint-Hilaire","QC"),
("CADC0F6JLI","CA","Saint-Honore","QC"),
("CAESQB3SSP","CA","Saint-Hubert","QC"),
("CAG2IT9471","CA","Saint-Hyacinthe","QC"),
("CASO9JE42R","CA","Saint-Isidore-de-Bellevue","SK"),
("CAH26NMS60","CA","Saint-Jacques","QC"),
("CALWBOP4D5","CA","Saint-Jean","QC"),
("CA6WYG06IS","CA","Saint-Jean-Eudes","QC"),
("CAURC9WE1D","CA","Saint-Jerome","QC"),
("CAH714074L","CA","Saint-Joseph-de-Beauce","QC"),
("CA4G9TKNYR","CA","Saint-Joseph-de-Kamouraska","QC"),
("CAJX8J3QCY","CA","Saint-Jovite","QC"),
("CAHO7D38RL","CA","Saint-Lambert","QC"),
("CAGSPHZU24","CA","Saint-Lambert-Chambly","QC"),
("CABCXVZWNJ","CA","Saint-Laurent","QC"),
("CATV3XLFV3","CA","Saint-Lazare","QC"),
("CA43G8C8TS","CA","Saint-Leonard","QC"),
("CA0I90DC4O","CA","Saint-Malo","QC"),
("CAO1KOY78R","CA","Saint-Marc-des-Carrieres","QC"),
("CA2BOORKRV","CA","Saint-Michel-des-Saints","QC"),
("CAN84ZGXSG","CA","Saint-Nicolas","QC"),
("CAG2HTELI3","CA","Saint-Pascal","QC"),
("CAN2SL90DC","CA","Saint-Pie","QC"),
("CAC103MSZA","CA","Saint-Prosper","QC"),
("CA039G12XH","CA","Saint-Raphael","QC"),
("CA4EBJZTMN","CA","Saint-Raymond","QC"),
("CAWF85GMIS","CA","Saint-Remi","QC"),
("CAOJWABVKB","CA","Saint-Roch-de-Richelieu","QC"),
("CAYUS0WPH1","CA","Saint-Romuald","QC"),
("CA3TK3N7RJ","CA","Saint-Sauveur","QC"),
("CAN0P3M7WA","CA","Saint-Sauveur-des-Monts","QC"),
("CARSK2N5DM","CA","Saint-Stanislas-de-Kostka","QC"),
("CAZ6MWV4XZ","CA","Saint-Tite","QC"),
("CAXI2KQT4D","CA","Saint-Tite-des-Caps","QC"),
("CATTHF0DPR","CA","Saint-Vallier","QC"),
("CA5AUTF8FF","CA","Saint-Vincent-de-Paul","QC"),
("CAE2B96984","CA","Saint-Zotique","QC"),
("CARBPH5TVY","CA","Sainte-Adele","QC"),
("CAMCENP4FV","CA","Sainte-Agathe","QC"),
("CAF9OUI49W","CA","Sainte-Agathe-des-Monts","QC"),
("CA6L6DUFIM","CA","Sainte-Anne","MB"),
("CAQ74V0ZUN","CA","Sainte-Anne-de-Beaupre","QC"),
("CAC8B2DQXS","CA","Sainte-Anne-de-Bellevue","QC"),
("CA0MNJQXFX","CA","Sainte-Anne-des-Monts","QC"),
("CAIMAD1S0R","CA","Sainte-Catherine","QC"),
("CA04N04HOG","CA","Sainte-Cecile-de-Masham","QC"),
("CAQZI4QGWQ","CA","Sainte-Claire","QC"),
("CA2K9SHPP0","CA","Sainte-Dorothee","QC"),
("CAB0ECSE4S","CA","Sainte-Foy","QC"),
("CAJRTN8H3Z","CA","Sainte-Genevieve-de-Batiscan","QC"),
("CAHM372ZY4","CA","Sainte-Julienne","QC"),
("CAK7X2XN38","CA","Sainte-Marie","QC"),
("CANHLGWP8F","CA","Sainte-Martine","QC"),
("CAG22PK6O1","CA","Sainte-Rose","QC"),
("CATR9WR71B","CA","Sainte-Therese","QC"),
("CAFYDCLHK9","CA","Sainte-Therese-de-Blainville","QC"),
("CAY5PVVXAB","CA","Salaberry-de-Valleyfield","QC"),
("CA0D0LKOND","CA","Salisbury","NB"),
("CAGWA73BJI","CA","Salmon Arm","BC"),
("CAAXVWEF5C","CA","Salmon Valley","BC"),
("CALU8GSISS","CA","Sandy Lake","SK"),
("CAWTDGI0UY","CA","Sangudo","AB"),
("CAX551GOJQ","CA","Sanikiluaq","NT"),
("CALEM0URDG","CA","Sarnia","ON"),
("CAMLXE4P60","CA","Saskatoon","SK"),
("CAJKH1LCZJ","CA","Sault Sainte Marie","ON"),
("CAH5KYU4OG","CA","Savona","BC"),
("CAJBGD3TUP","CA","Sayabec","QC"),
("CAER3IHAJ0","CA","Sayward","BC"),
("CAV11GD1ZV","CA","Scandia","AB"),
("CA6KT1OIH7","CA","Scarborough","ON"),
("CATXKWRFM5","CA","Scarborough Junction","ON"),
("CA6POOZ8OU","CA","Scarborough Township","ON"),
("CA9QBNRBIY","CA","Schreiber","ON"),
("CAVBZJUHQN","CA","Schumacher","ON"),
("CAEBK6Q6CX","CA","Scotia","ON"),
("CAW0LW9ARI","CA","Scotsburn","NS"),
("CA025SEOQA","CA","Seaforth","ON"),
("CA0QTU7KIM","CA","Sechelt","BC"),
("CAW2SN94L5","CA","Selkirk","MB"),
("CA561EGSXH","CA","Senneterre","QC"),
("CAV39AR0KS","CA","Senneville","QC"),
("CAQEMYZ4KV","CA","Sept-Iles","QC"),
("CA7DJGH4LN","CA","Severn Bridge","ON"),
("CABN2SGZ9B","CA","Sexsmith","AB"),
("CA2JMUJ6MA","CA","Sharbot Lake","ON"),
("CAK88JDSFL","CA","Shaunavon","SK"),
("CA6Y1O3NBE","CA","Shawinigan","QC"),
("CAAD6RDG3F","CA","Shawinigan-Sud","QC"),
("CAZPAJVWTG","CA","Shawville","QC"),
("CA51ZJUE40","CA","Shediac","NB"),
("CAD5OGT0V3","CA","Shefford","QC"),
("CAE1VRIY7H","CA","Shelburne","ON"),
("CANH1IDUZJ","CA","Sheldrake","QC"),
("CAVY2PD6QR","CA","Shellbrook","SK"),
("CACE75F39T","CA","Sherbrook","QC"),
("CA54KN2R5Q","CA","Sherbrooke","QC"),
("CA969M086W","CA","Shere","BC"),
("CA78MKFCBR","CA","Sherwood Park","AB"),
("CARJW6N60S","CA","Shipshaw","QC"),
("CAAKFDCL3L","CA","Shoal Lake","MB"),
("CARC8SLFOS","CA","Shubenacadie","NS"),
("CANBD2NOUF","CA","Sicamous","BC"),
("CA8RMWXMO8","CA","Sidney","BC"),
("CA74MKPP6H","CA","Sillery","QC"),
("CA2E9OTYGH","CA","Silton","SK"),
("CA9TKXIFCR","CA","Silverdale","NL"),
("CA6ZN4LBDT","CA","Simcoe","ON"),
("CAFZD5OJMR","CA","Simmie","SK"),
("CAYVFSUWA3","CA","Sioux Lookout","ON"),
("CAPU07ADZG","CA","Skidegate","BC"),
("CACMLXYYRE","CA","Slave Lake","AB"),
("CAX4JMO5DM","CA","Slocan","BC"),
("CA1TEVPPZF","CA","Smith","AB"),
("CAJZNTCMAP","CA","Smithers","BC"),
("CA8VM7UELR","CA","Smiths Falls","ON"),
("CAI4D6ARSC","CA","Smithville","ON"),
("CAL78BW7QG","CA","Smoky Lake","AB"),
("CA6DAJ0L88","CA","Snare Lake","NT"),
("CAHVFB912S","CA","Sointula","BC"),
("CA6GYH8RTT","CA","Sombra","ON"),
("CAZ24W9VDG","CA","Sooke","BC"),
("CA9N0998IQ","CA","Sorel","QC"),
("CA4Y1EZ465","CA","Sorrento","BC"),
("CAK5NTWGMW","CA","Souris","PE"),
("CAJRTSN69W","CA","South Branch","NL"),
("CAU953INTN","CA","South Nelson","NB"),
("CALV1KZ7QK","CA","South Porcupine","ON"),
("CADDDAU06E","CA","South River","ON"),
("CASZ6F6GB0","CA","Southampton","ON"),
("CAPG374XVP","CA","Southern Bay","NL"),
("CASWAS41CH","CA","Southport","MB"),
("CAFQRAQYOI","CA","Spaniards Bay","NL"),
("CAXVX3B940","CA","Spanish","ON"),
("CAQ78U53KX","CA","Sparta","ON"),
("CA0VP4X2MC","CA","Spedden","AB"),
("CASDMJBB29","CA","Spirit River","AB"),
("CA60DH9HHZ","CA","Spiritwood","SK"),
("CAPQUUUESU","CA","Springdale","NL"),
("CAAHY7KKJD","CA","Springhill","NS"),
("CAY6WAHYJN","CA","Springwater","SK"),
("CAYX58FN74","CA","Spruce Grove","AB"),
("CAD2Y7HR1R","CA","Squamish","BC"),
("CA90ZTLI6K","CA","Stamford","ON"),
("CAP3U71EV0","CA","Standard","AB"),
("CAB08QNFV1","CA","Stanley","NB"),
("CAIU8ZLAQU","CA","Stanstead","QC"),
("CABPNX8UHY","CA","Stayner","ON"),
("CAXC5ZQ1Z2","CA","Steinbach","MB"),
("CA17TPNOQ5","CA","Stellarton","NS"),
("CAIZ44AVYL","CA","Stephen","BC"),
("CALMJUH0SE","CA","Stephenville","NL"),
("CADYD3ZD50","CA","Stettler","AB"),
("CAKZQ7NGD6","CA","Stewart","BC"),
("CAFIAPD9BZ","CA","Stirling","ON"),
("CAVVTCVMR8","CA","Stittsville","ON"),
("CAK5CKIIL3","CA","Stoneham","QC"),
("CAHBB5ROB7","CA","Stonewall","MB"),
("CA6MXKV9KR","CA","Stoney Creek","ON"),
("CA4E300V9L","CA","Stony Mountain","MB"),
("CA1L5J4RML","CA","Stony Plain","AB"),
("CA2YQUM21T","CA","Stouffville","ON"),
("CAOYEJ8ZAC","CA","Stranraer","SK"),
("CADECEAL0B","CA","Stratford","ON"),
("CA75UBXHXZ","CA","Strathroy","ON"),
("CAFOT2QVWE","CA","Streetsville","ON"),
("CAUAY298EN","CA","Sturdies Bay","BC"),
("CANQ1XC18J","CA","Sturgeon Falls","ON"),
("CA73V4LS40","CA","Sudbury","ON"),
("CAGX37SZLM","CA","Suffield","AB"),
("CAAJPKS37F","CA","Summerland","BC"),
("CAU9C6BLQI","CA","Summerside","PE"),
("CAOMN9FRAV","CA","Sundridge","ON"),
("CAPE2IDO5O","CA","Surrey","BC"),
("CA8U80YGGS","CA","Sussex","NB"),
("CAPTZ1EQK3","CA","Sutton","QC"),
("CAC7DRZNNP","CA","Swan River","MB"),
("CA2Q8FED4N","CA","Swansea","ON"),
("CA8CN6T4YJ","CA","Swift Current","SK"),
("CAXYKCO4G0","CA","Sydenham","ON"),
("CACTRBHE1J","CA","Sydney","NS"),
("CA49ZJN36V","CA","Sydney Mines","NS"),
("CAGU29Z1TX","CA","Sylvan Lake","AB"),
("CAZD9NHPNT","CA","Taber","AB"),
("CAJF50U7JZ","CA","Tadoussac","QC"),
("CAGJI4MP02","CA","Tahsis","BC"),
("CAJ2CI35F3","CA","Taloyoak","NT"),
("CAJPQ0FDUY","CA","Tappen","BC"),
("CAT0ZN7IMO","CA","Taschereau","QC"),
("CA14SOUTRD","CA","Tatamagouche","NS"),
("CAV4WZ9C2T","CA","Tavistock","ON"),
("CA2SUH6OG0","CA","Taylor","BC"),
("CAPFNXY9M0","CA","Tecumseh","ON"),
("CAEFO88GM3","CA","Teeswater","ON"),
("CAKI3UV6NX","CA","Telegraph Creek","BC"),
("CAZHF66V6W","CA","Temiscaming","QC"),
("CAATT93F9H","CA","Templeton","QC"),
("CAUXQ3EC7Y","CA","Tenecape","NS"),
("CAVASQGGOF","CA","Terrace","BC"),
("CAX4M4ZS0A","CA","Terrace Bay","ON"),
("CALUJOAT64","CA","Terrebonne","QC"),
("CARW758E34","CA","Teulon","MB"),
("CAPWV6DJMB","CA","The Pas","MB"),
("CAO8FN0GYL","CA","Thedford","ON"),
("CAAIAKBGP2","CA","Thessalon","ON"),
("CADX7LCBQ1","CA","Thetford Mines","QC"),
("CA8L8L5UWT","CA","Thicket Portage","MB"),
("CA2BH3RFP2","CA","Thompson","MB"),
("CAXZN9GCBT","CA","Thorhild","AB"),
("CA9JFMV5N3","CA","Thornbury","ON"),
("CAQWOWQKPT","CA","Thornhill","ON"),
("CAW6WOMLQJ","CA","Thorold","ON"),
("CALET2Q4V0","CA","Three Hills","AB"),
("CAOBMJGAM7","CA","Thunder Bay","ON"),
("CA6B4XWTQS","CA","Thurso","QC"),
("CA0NHM986U","CA","Tichborne","ON"),
("CAMZWC3SDS","CA","Tilbury","ON"),
("CA3ZBKAYSH","CA","Tillsonburg","ON"),
("CAAWE6P5ZQ","CA","Tilsonburg","ON"),
("CASGC1OIWA","CA","Timmins","ON"),
("CAHSNLL0DO","CA","Tiverton","ON"),
("CA0P9BO1SZ","CA","Tlell","BC"),
("CAX75NC4D5","CA","Tobermory","ON"),
("CALP7973KP","CA","Tofield","AB"),
("CAW8AH9O69","CA","Tofino","BC"),
("CAEFL3GE2D","CA","Topsail","NL"),
("CAL70YCE4Y","CA","Torbay","NL"),
("CA3B8BES0B","CA","Toronto","ON"),
("CA1BSA0YKE","CA","Tottenham","ON"),
("CAE5HUJJ85","CA","Tracadie","NS"),
("CAR944N82Q","CA","Tracy","QC"),
("CAJA2Y32A4","CA","Trail","BC"),
("CAE2EE1YSF","CA","Treherne","MB"),
("CA4AAOUITM","CA","Trenton","ON"),
("CARXQE5T4P","CA","Trochu","AB"),
("CA47O79YCO","CA","Trois-Pistoles","QC"),
("CA1Q22PVIT","CA","Trois-Rivieres","QC"),
("CA5SH0ABM1","CA","Trout Lake","NT"),
("CA8CGE6L4A","CA","Truro","NS"),
("CASSH2QTQR","CA","Tsawwassen","BC"),
("CAKSUAOC3T","CA","Tsiigehtchic","NT"),
("CA5LUFXGH5","CA","Tudhope","ON"),
("CATXKZIO9B","CA","Tuktoyaktuk","NT"),
("CAGRD7L3Z5","CA","Tulita","NT"),
("CAWUFK7JEC","CA","Turtleford","SK"),
("CA58S2OA8H","CA","Tweed","ON"),
("CA8SHQGR2X","CA","Twillingate","NL"),
("CAIF53I49E","CA","Two Hills","AB"),
("CAYPY58CIE","CA","Tyrone","ON"),
("CALAG9KPRS","CA","Ucluelet","BC"),
("CAH9JY0LWI","CA","Union Bay","BC"),
("CA01MJ6VX4","CA","Unity","SK"),
("CALWAU9S8U","CA","Upper Musquodoboit","NS"),
("CA3P4NEWGW","CA","Uxbridge","ON"),
("CA50U5MQOM","CA","Val-Barrette","QC"),
("CASB6Y733S","CA","Val-d'Or","QC"),
("CA0DM96V49","CA","Val-David","QC"),
("CAK8XY5EVA","CA","Valcourt","QC"),
("CAEPG0G5N9","CA","Valemount","BC"),
("CAGT7OXAGY","CA","Vallee-Jonction","QC"),
("CAO38VYC5J","CA","Valleyfield","QC"),
("CAL3IQHD1W","CA","Valleyview","AB"),
("CA3HXJNLS4","CA","Vancouver","BC"),
("CAF0SCB9BZ","CA","Vanderhoof","BC"),
("CACJVBW0UH","CA","Vankleek Hill","ON"),
("CA3D8LQ9IT","CA","Varennes","QC"),
("CARGDE15IG","CA","Vaudreuil","QC"),
("CA6BTHL4HY","CA","Vauxhall","AB"),
("CAOC9KD41H","CA","Vegreville","AB"),
("CAH928JL1A","CA","Vercheres","QC"),
("CA1FP2L7JR","CA","Verdun","QC"),
("CAJC84HP25","CA","Vermilion","AB"),
("CA2CQFHSWZ","CA","Verner","ON"),
("CA2Z7LL9VM","CA","Vernon","BC"),
("CAOKP9S81C","CA","Vernon River","PE"),
("CAL9H3ZJ82","CA","Verona","ON"),
("CAWZHDRECT","CA","Veteran","AB"),
("CAEKEZTALH","CA","Victoria","BC"),
("CAVBROJS05","CA","Victoria Harbour","ON"),
("CA2H811H4X","CA","Victoriaville","QC"),
("CAGLB80O1E","CA","Viking","AB"),
("CA8GE1R0JM","CA","Ville-Marie","QC"),
("CABBAV3B06","CA","Virden","MB"),
("CAS88TPCR6","CA","Vulcan","AB"),
("CAY2EYQGDY","CA","Wabana","NL"),
("CAWR0NRKA3","CA","Wabush","NL"),
("CAVLYZWY5P","CA","Wadena","SK"),
("CA7EIXQA3O","CA","Wainwright","AB"),
("CADIN3Y02V","CA","Wakefield","QC"),
("CAR3IJNTMJ","CA","Walkerton","ON"),
("CAELJBJO0R","CA","Wallace","ON"),
("CA3JOTTSH6","CA","Wallaceburg","ON"),
("CAA4A95D4W","CA","Warman","SK"),
("CAHNG5G3OV","CA","Warren","ON"),
("CAO768W7ZZ","CA","Warwick","QC"),
("CAQOTJHAQS","CA","Waswanipi","QC"),
("CAF11LE5IW","CA","Waterdown","ON"),
("CATY1A1P5P","CA","Waterford","ON"),
("CAXCXTJXTA","CA","Waterloo","ON"),
("CALMU2XKVD","CA","Waterville","QC"),
("CAMWY12GXV","CA","Watford","ON"),
("CAFY5HOB7L","CA","Watino","AB"),
("CAN5F728HO","CA","Watrous","SK"),
("CAVBRSWM5I","CA","Watson","SK"),
("CAI4JLLGG0","CA","Wawa","ON"),
("CAFMI3XPOL","CA","Wawanesa","MB"),
("CAU4SXCAL8","CA","Webbwood","ON"),
("CAMD0JZ61I","CA","Webster","AB"),
("CAAL4W2KWH","CA","Wedgeport","NS"),
("CA6EK449PY","CA","Weedon","QC"),
("CADIWQSHYF","CA","Welland","ON"),
("CAVZYV50DG","CA","Wellington","ON"),
("CALICN2949","CA","Welsford","NB"),
("CAOPDSY2RC","CA","Wembley","AB"),
("CAKN2D51T0","CA","West Lorne","ON"),
("CA0RV6R9MC","CA","Westlock","AB"),
("CARZ0U843W","CA","Westmount","QC"),
("CATHPSKG45","CA","Weston","ON"),
("CA47J99CAA","CA","Westport","ON"),
("CA35GVF377","CA","Westville","NS"),
("CA371BC586","CA","Wetaskiwin","AB"),
("CANYZ7E3CJ","CA","Weyburn","SK"),
("CABWTL83VB","CA","Weymouth","NS"),
("CA9C7PGFWJ","CA","Wha Ti","NT"),
("CAMXVZ346Q","CA","Whaletown","BC"),
("CA25YH9B0K","CA","Wheatley","ON"),
("CA7T6FX1R6","CA","Whitbourne","NL"),
("CAEYVVDRE0","CA","Whitby","ON"),
("CAPA0TE6KG","CA","Whitchurch-Stouffville","ON"),
("CABIXKTY50","CA","White River","ON"),
("CASBGPD8VS","CA","White Rock","BC"),
("CA7RNLJ2M8","CA","Whitecourt","AB"),
("CADM2RTM85","CA","Whitefish","ON"),
("CA46QX4VYX","CA","Whitehorse","YT"),
("CA7FMLOIEV","CA","Whitewood","SK"),
("CA92GS421H","CA","Whitney","ON"),
("CAP39IPHNT","CA","Wiarton","ON"),
("CANDRS9QPH","CA","Widewater","AB"),
("CA6B3UUHP3","CA","Wilberforce","ON"),
("CAJ6VO9X5Y","CA","Wildwood","AB"),
("CA0FHPW4JK","CA","Wilkie","SK"),
("CAIADR1397","CA","Williams Lake","BC"),
("CAEC29TSCC","CA","Willowbrook","SK"),
("CAY8185765","CA","Willowdale","ON"),
("CAMNVJSE4B","CA","Winchester","ON"),
("CAPH3RKCZZ","CA","Windermere","BC"),
("CAO18ITLVS","CA","Windsor","ON"),
("CATW0Y364P","CA","Winfield","BC"),
("CAUZ9NEDY4","CA","Wingham","ON"),
("CAU1VFDUF2","CA","Winkler","MB"),
("CAWNKP8FH2","CA","Winnipeg","MB"),
("CABI1FO55J","CA","Winnipegosis","MB"),
("CA5E6KS5ON","CA","Winterton","NL"),
("CA6K2KFHNB","CA","Witless Bay","NL"),
("CA571ENJGZ","CA","Wolfville","NS"),
("CA1HEQNJ9S","CA","Wolseley","SK"),
("CAYGDQM2DT","CA","Woodbridge","ON"),
("CAMGD1X0D3","CA","Woods Harbour","NS"),
("CA8EHVXXVZ","CA","Woodstock","NB"),
("CAF9P2TZVS","CA","Wrentham","AB"),
("CAF8I2BWVX","CA","Wright","BC"),
("CAC9Z9ADCI","CA","Wrigley","NT"),
("CARUEPR9O7","CA","Wyebridge","ON"),
("CAJE9DD55T","CA","Wymark","SK"),
("CAENVPJQMV","CA","Wynyard","SK"),
("CAZM59ZISR","CA","Wyoming","ON"),
("CAC6H4G6C0","CA","Yamachiche","QC"),
("CAKLDXRJQ5","CA","Yamaska","QC"),
("CA6LUQCHMB","CA","Yarker","ON"),
("CA3SL3BDUO","CA","Yarmouth","NS"),
("CAKCT1I512","CA","Yellowknife","NT"),
("CARFZIYQN5","CA","York","ON"),
("CABIWOZIZ3","CA","York Harbour","NL"),
("CABL6MY1AJ","CA","Yorkton","SK"),
("CAD4KV9MX0","CA","Youbou","BC"),
("CA1XI0N65Z","CA","Young","SK"),
("CAO1NOKNRV","CA","Zeballos","BC");