INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("CI4STOHGIJ","CI","Abidjan",NULL),
("CIRPXZ3QUL","CI","Aboisso",NULL),
("CICX3YVV91","CI","Adiake",NULL),
("CIP13LHB4L","CI","Agnéby",NULL),
("CI4YALFS56","CI","Alepe",NULL),
("CIH26LS075","CI","Antofagasta Region",NULL),
("CIYB4U6EVV","CI","Araucanía Region",NULL),
("CIGZGXBLIF","CI","Atacama Region",NULL),
("CIKT1ZL662","CI","Bafing",NULL),
("CI9CO1DV7B","CI","Bangolo",NULL),
("CI6B5DQ186","CI","Bas-Sassandra",NULL),
("CI0P3CAMRV","CI","Beoumi",NULL),
("CIFTV1Z148","CI","Biobío Region",NULL),
("CIESAROH3V","CI","Bocanda",NULL),
("CIT98JBHQC","CI","Bondoukou",NULL),
("CI7UOIHGDX","CI","Bongouanou",NULL),
("CI98Y8A2HO","CI","Bouafle",NULL),
("CIVRGK9JF3","CI","Bouake",NULL),
("CISOM46DGE","CI","Coquimbo Region",NULL),
("CI74WPK9MT","CI","Dabou",NULL),
("CIIK2SNJGI","CI","Daloa",NULL),
("CIBW3KGIN9","CI","Danane",NULL),
("CI7ADEOTSV","CI","Daoukro",NULL),
("CIXOKIY7CH","CI","Denguélé",NULL),
("CIRE9FYQY9","CI","Dimbokro",NULL),
("CIN1U3KHDS","CI","Divo",NULL),
("CISQ6GKZCI","CI","Dix-Huit Montagnes",NULL),
("CINX0M4D3W","CI","Duekoue",NULL),
("CIRDBQ3AZR","CI","Ferkessedougou",NULL),
("CIBUVVB8N4","CI","Fromager",NULL),
("CIYUKJTX1H","CI","Gagnoa",NULL),
("CIU13ZF7V6","CI","Grand-Bassam",NULL),
("CIK7XOHWGT","CI","Grand-Lahou",NULL),
("CIRBP2JC7I","CI","Guiglo",NULL),
("CI7S10P3HK","CI","Haut-Sassandra",NULL),
("CI5LJKTFRD","CI","Issia",NULL),
("CINO25LIYC","CI","Jacqueville",NULL),
("CIUNFE0MW7","CI","Katiola",NULL),
("CIEY831QO6","CI","Korhogo",NULL),
("CIB7R5NIIA","CI","Lacs",NULL),
("CI6LFR4D3Y","CI","Lagunes",NULL),
("CI1ID2499J","CI","Lakota",NULL),
("CI8IMA8AHK","CI","Man",NULL),
("CII8P5Q8FW","CI","Mankono",NULL),
("CIUVOZ9RYA","CI","Marahoué",NULL),
("CIABCELMXT","CI","Maule Region",NULL),
("CI4K4DVLYE","CI","Mbahiakro",NULL),
("CITOKKX0GR","CI","Moyen-Cavally",NULL),
("CIV4Q4WPF6","CI","Moyen-Comoé",NULL),
("CI0RKLEIEJ","CI","Nʼzi-Comoé",NULL),
("CI3IWZ4VDX","CI","Odienne",NULL),
("CIJXHGXY8T","CI","Oume",NULL),
("CI3ZXZOC5O","CI","Sakassou",NULL),
("CI4QAJ9P2D","CI","San Pedro",NULL),
("CI8ZCCUQAE","CI","Santiago Metropolitan Region",NULL),
("CINSVLQ4FT","CI","Sassandra",NULL),
("CI3CTSPYHU","CI","Savanes",NULL),
("CIPRDYGFCO","CI","Seguela",NULL),
("CIFO19EBO2","CI","Sinfra",NULL),
("CI3JOUN3OR","CI","Soubre",NULL),
("CIGIJ6H006","CI","Sud-Bandama",NULL),
("CIRE58UHX9","CI","Sud-Comoé",NULL),
("CI6YJK97ND","CI","Tabou",NULL),
("CIRB8FFX6V","CI","Tanda",NULL),
("CIFP2WQ22I","CI","Tiassale",NULL),
("CIH8QBPNLV","CI","Tiebissou",NULL),
("CIM4GWC4A3","CI","Tingrela",NULL),
("CIFIIVFPRU","CI","Touba",NULL),
("CIFTQ5WTOD","CI","Toulepleu",NULL),
("CI1EPR2ANP","CI","Toumodi",NULL),
("CIE4LQ8VUO","CI","Vallée du Bandama",NULL),
("CIEDJU2AOH","CI","Valparaíso Region",NULL),
("CI3FM09ADB","CI","Vavoua",NULL),
("CIP22SCQHR","CI","Worodougou",NULL),
("CIU3I2ZCRD","CI","Yamoussoukro",NULL),
("CIPA7RLW9P","CI","Zanzan",NULL),
("CICWPL62WW","CI","Zuenoula",NULL);