INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("CLARO94FNU","CL","Aisén del General Carlos Ibáñez del Campo",NULL),
("CLPVMBRV03","CL","Antofagasta",NULL),
("CLRPPYSMVX","CL","Araucanía",NULL),
("CLMKFCROY2","CL","Atacama",NULL),
("CLGMCK1ZFR","CL","Bío-Bío",NULL),
("CLV12MW2QO","CL","Coquimbo",NULL),
("CLRGMK2HHP","CL","Libertador General Bernardo OʼHiggins",NULL),
("CL1W2TL0V1","CL","Los Lagos",NULL),
("CLM8MO71F2","CL","Magallanes y Antártica Chilena",NULL),
("CL2HPZKGNC","CL","Maule",NULL),
("CLW9WZRDOT","CL","Región de Arica y Parinacota",NULL),
("CLARMVRIXE","CL","Región de Los Ríos",NULL),
("CLQJ2YLH1O","CL","Región Metropolitana",NULL),
("CLZQNJ7BV3","CL","Tarapaca",NULL),
("CLLR3C5S5F","CL","Valparaíso",NULL);