INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("DE9MCHNXYN","DE","Aach","BW"),
("DEA3XT19GW","DE","Aachen","NW"),
("DEVM62Z3XT","DE","Aalen","BW"),
("DEREN1UQP4","DE","Abenberg","BY"),
("DED1L0YKO9","DE","Abensberg","BY"),
("DENL2PUJLQ","DE","Achern","BW"),
("DE6SS6VQZN","DE","Achim","NI"),
("DE4MPZDE3R","DE","Adelsheim","BW"),
("DEGPRF9GOX","DE","Adenau","RP"),
("DE1RNWB8MH","DE","Adorf/Vogtl.","SN"),
("DE1FOX5NKA","DE","Ahaus","NW"),
("DEAA9NPDE5","DE","Ahlen","NW"),
("DE26LBM98O","DE","Ahrensburg","SH"),
("DE1VKC46U6","DE","Aichach","BY"),
("DELI3R6O1G","DE","Aichtal","BW"),
("DEYB3NOITQ","DE","Aken/Elbe","ST"),
("DEPE1BOAZP","DE","Albstadt","BW"),
("DE6K2BQWHC","DE","Alfeld/Leine","NI"),
("DEFK4L9617","DE","Allendorf/Lumda","HE"),
("DEH5V6OOWD","DE","Allstedt","ST"),
("DE3YPR9OHG","DE","Alpirsbach","BW"),
("DE8JRZF9CV","DE","Alsdorf","NW"),
("DEUGH3NIB4","DE","Alsfeld","HE"),
("DEO6ACV7PY","DE","Alsleben/Saale","ST"),
("DE5EQF37VC","DE","Altdorf bei Nürnberg","BY"),
("DEQNC6WP1R","DE","Altena","NW"),
("DE6IUT16YQ","DE","Altenberg","SN"),
("DED928GS7M","DE","Altenburg","TH"),
("DE7X1B4XOV","DE","Altenkirchen/Westerwald","RP"),
("DEL01IP39W","DE","Altensteig","BW"),
("DEM4POANEN","DE","Altentreptow","MV"),
("DEWHWD93ZH","DE","Altlandsberg","BB"),
("DE11T6ZH1K","DE","Altötting","BY"),
("DEH3277C4T","DE","Alzenau","BY"),
("DEGTHRHVFD","DE","Alzey","RP"),
("DECBRMEQ4G","DE","Amberg","BY"),
("DESXMREOCW","DE","Amöneburg","HE"),
("DERF4YR8S7","DE","Amorbach","BY"),
("DE29ZJ5EXI","DE","Andernach","RP"),
("DEPO54F9K7","DE","Angermünde","BB"),
("DE77ZMVCIN","DE","Anklam, Hansestadt","MV"),
("DERNLIVEQX","DE","Annaberg-Buchholz","SN"),
("DEOPHT3ECT","DE","Annaburg","ST"),
("DE2IXHRIPZ","DE","Annweiler am Trifels","RP"),
("DEPOLL038R","DE","Ansbach","BY"),
("DERUAM80KW","DE","Apolda","TH"),
("DEP1QTG3MI","DE","Arendsee/Altmark","ST"),
("DELK0D3PCT","DE","Arneburg","ST"),
("DEDXEE1M6S","DE","Arnis","SH"),
("DEHGFPG0M6","DE","Arnsberg","NW"),
("DE2D0IHM12","DE","Arnstadt","TH"),
("DE71FAQS34","DE","Arnstein","BY"),
("DEQIIR5PKM","DE","Arnstein","ST"),
("DE5ZCMZYS1","DE","Artern/Unstrut","TH"),
("DECSKTFLWN","DE","Arzberg","BY"),
("DEMCXD41HU","DE","Aschaffenburg","BY"),
("DEK0MPP6BU","DE","Aschersleben","ST"),
("DE6NH6M97Z","DE","Asperg","BW"),
("DE2SSIDO50","DE","Aßlar","HE"),
("DE13D54V0O","DE","Attendorn","NW"),
("DEVMELTPGZ","DE","Aub","BY"),
("DEDX506DZ9","DE","Aue","SN"),
("DE5RRJGWJH","DE","Auerbach in der Oberpfalz","BY"),
("DEZXN4SNTN","DE","Auerbach/Vogtl.","SN"),
("DEA783XO2B","DE","Augsburg","BY"),
("DEM8BSLA2R","DE","Augustusburg","SN"),
("DE2TAJQU0Q","DE","Aulendorf","BW"),
("DEROUJCO7M","DE","Auma-Weidatal","TH"),
("DEWGPT4S4R","DE","Aurich","NI"),
("DE0GKMQMDS","DE","Babenhausen","HE"),
("DEGNB6HCX8","DE","Bacharach","RP"),
("DE1RSDGZZC","DE","Backnang","BW"),
("DEFP6KHABI","DE","Bad Aibling","BY"),
("DEQV4HHHAX","DE","Bad Arolsen","HE"),
("DE5L4MY1VZ","DE","Bad Belzig","BB"),
("DETNC9NCM2","DE","Bad Bentheim","NI"),
("DE1SMJ3Y1U","DE","Bad Bergzabern","RP"),
("DET6BBOL9T","DE","Bad Berka","TH"),
("DE7DG5FC59","DE","Bad Berleburg","NW"),
("DEZIJNU5PV","DE","Bad Berneck im Fichtelgebirge","BY"),
("DEYCF1AHV3","DE","Bad Bevensen","NI"),
("DEN6FBRO4Z","DE","Bad Bibra","ST"),
("DE2L4HX9RX","DE","Bad Blankenburg","TH"),
("DESBKMG9IE","DE","Bad Bramstedt","SH"),
("DEMXGWEB02","DE","Bad Breisig","RP"),
("DEIFD94I86","DE","Bad Brückenau","BY"),
("DE3DO0NFYF","DE","Bad Buchau","BW"),
("DEQI27SKME","DE","Bad Camberg","HE"),
("DEI2BXECZW","DE","Bad Colberg-Heldburg","TH"),
("DESD6WVF3Z","DE","Bad Doberan","MV"),
("DESR0G6YWX","DE","Bad Driburg","NW"),
("DEHY59IRO1","DE","Bad Düben","SN"),
("DEUZY8CY45","DE","Bad Dürkheim","RP"),
("DEBA17P46I","DE","Bad Dürrenberg","ST"),
("DEW6Y25U0M","DE","Bad Dürrheim","BW"),
("DET5VCWKDR","DE","Bad Elster","SN"),
("DEKCZWA41L","DE","Bad Ems","RP"),
("DEE3S48ZN4","DE","Bad Fallingbostel","NI"),
("DE6M7BG7YA","DE","Bad Frankenhausen/Kyffhäuser","TH"),
("DEDUMAEZ1Y","DE","Bad Freienwalde/Oder","BB"),
("DEC0UM5W8J","DE","Bad Friedrichshall","BW"),
("DEZ0O8ZBC5","DE","Bad Gandersheim","NI"),
("DEXJHERFO4","DE","Bad Gottleuba-Berggießhübel","SN"),
("DE9BENBGMN","DE","Bad Griesbach im Rottal","BY"),
("DEHG9MDH6D","DE","Bad Harzburg","NI"),
("DEIULI6XO4","DE","Bad Herrenalb","BW"),
("DEH5J8L8DV","DE","Bad Hersfeld","HE"),
("DEJSJU85IP","DE","Bad Homburg vor der Höhe","HE"),
("DEMSCZAICS","DE","Bad Honnef","NW"),
("DEDYBKVZOD","DE","Bad Hönningen","RP"),
("DE57MRFZMZ","DE","Bad Iburg","NI"),
("DES5U0ACQX","DE","Bad Karlshafen","HE"),
("DE42WEL97Y","DE","Bad Kissingen","BY"),
("DE7IJ3I7GN","DE","Bad König","HE"),
("DEF2EV21UU","DE","Bad Königshofen im Grabfeld","BY"),
("DE6OVH0LE5","DE","Bad Köstritz","TH"),
("DEOBJALQ9T","DE","Bad Kötzting","BY"),
("DE8SWQZDEF","DE","Bad Kreuznach","RP"),
("DEFTAIU5C1","DE","Bad Krozingen","BW"),
("DET7IUTXZI","DE","Bad Laasphe","NW"),
("DE9JSU92NI","DE","Bad Langensalza","TH"),
("DEUK8UXN9D","DE","Bad Lauchstädt","ST"),
("DEGKVAP8BJ","DE","Bad Lausick","SN"),
("DEFUE9RES0","DE","Bad Lauterberg im Harz","NI"),
("DEXLV6NIOH","DE","Bad Liebenstein","TH"),
("DE3XC0KMD1","DE","Bad Liebenwerda","BB"),
("DE69BWHNGX","DE","Bad Liebenzell","BW"),
("DEHV699Z96","DE","Bad Lippspringe","NW"),
("DEK5D7O2PR","DE","Bad Lobenstein","TH"),
("DEZ2RKO5LV","DE","Bad Marienberg/Westerwald","RP"),
("DEEXSVL9T2","DE","Bad Mergentheim","BW"),
("DE40CDZMKJ","DE","Bad Münder am Deister","NI"),
("DERXRFZH6Z","DE","Bad Münstereifel","NW"),
("DEJXK8363H","DE","Bad Muskau","SN"),
("DE4WDP56S9","DE","Bad Nauheim","HE"),
("DE64M6Q6PH","DE","Bad Nenndorf","NI"),
("DE4HW4Y33I","DE","Bad Neuenahr-Ahrweiler","RP"),
("DE0OQ3UULY","DE","Bad Neustadt an der Saale","BY"),
("DEQYOV5G4C","DE","Bad Oeynhausen","NW"),
("DEKRIAY8R3","DE","Bad Oldesloe","SH"),
("DEPO7NRB5S","DE","Bad Orb","HE"),
("DEZWWUQITG","DE","Bad Pyrmont","NI"),
("DEHHBMXGZH","DE","Bad Rappenau","BW"),
("DE8HS7PKAF","DE","Bad Reichenhall","BY"),
("DE9H30T9TT","DE","Bad Rodach","BY"),
("DE5QNV8GBP","DE","Bad Sachsa","NI"),
("DEYNCV4BDD","DE","Bad Säckingen","BW"),
("DET6KJQVYZ","DE","Bad Salzdetfurth","NI"),
("DEC106BTZG","DE","Bad Salzuflen","NW"),
("DEKMCS3OI2","DE","Bad Salzungen","TH"),
("DECUXG6BUZ","DE","Bad Saulgau","BW"),
("DEHEI89H7M","DE","Bad Schandau","SN"),
("DEJ8TU2SBM","DE","Bad Schmiedeberg","ST"),
("DEFNEICXKO","DE","Bad Schussenried","BW"),
("DERI5YUZXC","DE","Bad Schwalbach","HE"),
("DEEGKOYSBH","DE","Bad Schwartau","SH"),
("DE04C3WNPC","DE","Bad Segeberg","SH"),
("DEB4VN1GBT","DE","Bad Sobernheim","RP"),
("DEZHRTGP6U","DE","Bad Soden am Taunus","HE"),
("DE5RJ4JULK","DE","Bad Soden-Salmünster","HE"),
("DEYYNVLD8X","DE","Bad Sooden-Allendorf","HE"),
("DEH3LJJXCI","DE","Bad Staffelstein","BY"),
("DEE4BUTIPZ","DE","Bad Sulza","TH"),
("DE983T3PD2","DE","Bad Sülze","MV"),
("DEN1Y9F67W","DE","Bad Teinach-Zavelstein","BW"),
("DE9SGSPTA3","DE","Bad Tennstedt","TH"),
("DEXMYR5ORE","DE","Bad Tölz","BY"),
("DEXV70KL37","DE","Bad Urach","BW"),
("DEN1H27OZH","DE","Bad Vilbel","HE"),
("DEGF969K96","DE","Bad Waldsee","BW"),
("DE78YCWPRT","DE","Bad Wildbad","BW"),
("DEKYU5KXD7","DE","Bad Wildungen","HE"),
("DEZUA7I9OZ","DE","Bad Wilsnack","BB"),
("DEPY5YIF5Q","DE","Bad Wimpfen","BW"),
("DEN32KTUEE","DE","Bad Windsheim","BY"),
("DES8JD6WK5","DE","Bad Wörishofen","BY"),
("DEQVC9518U","DE","Bad Wünnenberg","NW"),
("DEZETITZ8H","DE","Bad Wurzach","BW"),
("DE2B1W5FAY","DE","Baden-Baden","BW"),
("DEOTBVQW0G","DE","Baesweiler","NW"),
("DERDQWEZRE","DE","Baiersdorf","BY"),
("DEDKW6J4OM","DE","Balingen","BW"),
("DEFPJL5UJT","DE","Ballenstedt","ST"),
("DEOUOEQPVI","DE","Balve","NW"),
("DE3LEIK6WX","DE","Bamberg","BY"),
("DEQS4AXSXD","DE","Barby","ST"),
("DEIHYNBHHZ","DE","Bargteheide","SH"),
("DEC6D3V9LZ","DE","Barmstedt","SH"),
("DEUZHF6DCW","DE","Bärnau","BY"),
("DE6H73A5HS","DE","Barntrup","NW"),
("DENFGYXXY9","DE","Barsinghausen","NI"),
("DE4BCZLXZF","DE","Barth","MV"),
("DEXGU3U700","DE","Baruth/Mark","BB"),
("DEP840ELT1","DE","Bassum","NI"),
("DE19ZY7X8B","DE","Battenberg/Eder","HE"),
("DE9LBVJAAH","DE","Baumholder","RP"),
("DER5KLDLM3","DE","Baunach","BY"),
("DEUR39DWAE","DE","Baunatal","HE"),
("DE6ADE8LPI","DE","Bautzen","SN"),
("DE61DPCO63","DE","Bayreuth","BY"),
("DEURP8DBB8","DE","Bebra","HE"),
("DE2FHGBRUI","DE","Beckum","NW"),
("DE28WAUMS0","DE","Bedburg","NW"),
("DEN6Q0UX3O","DE","Beelitz","BB"),
("DEPSW348B7","DE","Beerfelden","HE"),
("DENSNZKIHM","DE","Beeskow","BB"),
("DEQEXK0QLO","DE","Beilngries","BY"),
("DEWCOQ9RFZ","DE","Beilstein","BW"),
("DEKC2OLEV8","DE","Belgern-Schildau","SN"),
("DE7J8R1PES","DE","Bendorf","RP"),
("DE3BC41YSY","DE","Bensheim","HE"),
("DEAGPK84JS","DE","Berching","BY"),
("DEHMH20DB7","DE","Berga/Elster","TH"),
("DEWJZY9DQD","DE","Bergen","NI"),
("DEP3HR2APC","DE","Bergen auf Rügen","MV"),
("DEQEXZJGR0","DE","Bergheim","NW"),
("DE3933MEBJ","DE","Bergisch Gladbach","NW"),
("DEXAH7N8KD","DE","Bergkamen","NW"),
("DEB24DCTQ2","DE","Bergneustadt","NW"),
("DE7N1Q4TR7","DE","Berka/Werra","TH"),
("DE3UBP8M96","DE","Berlin","BE"),
("DEWQDKYYYA","DE","Bernau bei Berlin","BB"),
("DE02OCVEF3","DE","Bernburg/Saale","ST"),
("DE1HU6BLDE","DE","Bernkastel-Kues","RP"),
("DEFP4OBDU8","DE","Bernsdorf","SN"),
("DE48T36RD6","DE","Bernstadt a. d. Eigen","SN"),
("DET1JPFYTH","DE","Bersenbrück","NI"),
("DEGNNR915O","DE","Besigheim","BW"),
("DEQAD2N7AS","DE","Betzdorf","RP"),
("DEG4VMV8TP","DE","Betzenstein","BY"),
("DEACFQB87R","DE","Beverungen","NW"),
("DEWVI5XOUN","DE","Bexbach","SL"),
("DEY7PME0EV","DE","Biberach an der Riß","BW"),
("DE49H0IBQS","DE","Biedenkopf","HE"),
("DEO5IZEQQA","DE","Bielefeld","NW"),
("DEM9FJY97W","DE","Biesenthal","BB"),
("DEHXJWYXR3","DE","Bietigheim-Bissingen","BW"),
("DE783PKTI8","DE","Billerbeck","NW"),
("DEZ17DRYOE","DE","Bingen am Rhein","RP"),
("DE84Y6E63V","DE","Birkenfeld","RP"),
("DE3MR1KI4R","DE","Bischofsheim an der Rhön","BY"),
("DER8HB2ZK1","DE","Bischofswerda","SN"),
("DE0SFSR46Z","DE","Bismark/Altmark","ST"),
("DE856NBAIF","DE","Bitburg","RP"),
("DEXAHHSL9K","DE","Bitterfeld-Wolfen","ST"),
("DEUQWXPGYP","DE","Blankenburg/Harz","ST"),
("DE8EH0JOZR","DE","Blankenhain","TH"),
("DEU6F5GXLD","DE","Blaubeuren","BW"),
("DE82V1O4LI","DE","Blaustein","BW"),
("DEUIFJZE98","DE","Bleckede","NI"),
("DETR8CG74A","DE","Bleicherode","TH"),
("DEEJGUH17Q","DE","Blieskastel","SL"),
("DE32RR7DA1","DE","Blomberg","NW"),
("DEVQLU4V2Y","DE","Blumberg","BW"),
("DEMAA3IFEW","DE","Bobingen","BY"),
("DEZVRGWZ60","DE","Böblingen","BW"),
("DE2YS9B3A6","DE","Bocholt","NW"),
("DETW1YR4WE","DE","Bochum","NW"),
("DEE7HXMWUL","DE","Bockenem","NI"),
("DERL2NL9ON","DE","Bodenwerder","NI"),
("DE7HWJK6PE","DE","Bogen","BY"),
("DE3RCUV88A","DE","Böhlen","SN"),
("DEGQ72M2OD","DE","Boizenburg/Elbe","MV"),
("DEOR190QW8","DE","Bonn","NW"),
("DE7SRSZH62","DE","Bonndorf im Schwarzwald","BW"),
("DE8JX4S6E8","DE","Bönnigheim","BW"),
("DEXLBJOZXC","DE","Bopfingen","BW"),
("DERZLRPI0X","DE","Boppard","RP"),
("DEASPAAWCI","DE","Borgentreich","NW"),
("DEFAM7G1FD","DE","Borgholzhausen","NW"),
("DEMQXBQVNH","DE","Borken","NW"),
("DEU99KR9H2","DE","Borken","HE"),
("DE26CC2PVH","DE","Borkum","NI"),
("DE0IPGJ4U6","DE","Borna","SN"),
("DEVSHLN53I","DE","Bornheim","NW"),
("DEFC26MJ9O","DE","Bottrop","NW"),
("DEQM1SBWAC","DE","Boxberg","BW"),
("DEE0SX4N4Z","DE","Brackenheim","BW"),
("DEFLL3QOL5","DE","Brake/Unterweser","NI"),
("DE0NCN6MBW","DE","Brakel","NW"),
("DE8DPK90WO","DE","Bramsche","NI"),
("DE0PM5CQ5S","DE","Brand-Erbisdorf","SN"),
("DEBQV2FG8F","DE","Brandenburg an der Havel","BB"),
("DE4L3A7F7G","DE","Brandis","SN"),
("DESX01YWPZ","DE","Braubach","RP"),
("DELC4Y29QE","DE","Braunfels","HE"),
("DE0MHF2PV6","DE","Braunlage","NI"),
("DEBYHJDPZ5","DE","Bräunlingen","BW"),
("DEN07LWXKI","DE","Braunsbedra","ST"),
("DE9OHCY7QY","DE","Braunschweig","NI"),
("DET7EWX939","DE","Breckerfeld","NW"),
("DE8LSLBSRY","DE","Bredstedt","SH"),
("DESZJPX476","DE","Breisach am Rhein","BW"),
("DETOJRW9QQ","DE","Bremen, Freie Hansestadt","HB"),
("DEH4NEEQOM","DE","Bremerhaven","HB"),
("DECH8N90M1","DE","Bremervörde","NI"),
("DEZ5QW9Y32","DE","Bretten","BW"),
("DENMUJWKAD","DE","Breuberg","HE"),
("DEPXS3OGP1","DE","Brilon","NW"),
("DEYYO7YA9X","DE","Brotterode-Trusetal","TH"),
("DEG0UQYYTM","DE","Bruchköbel","HE"),
("DELN6H8GVX","DE","Bruchsal","BW"),
("DEEO125Q33","DE","Brück","BB"),
("DEPSAN3JLJ","DE","Brüel","MV"),
("DEJFAIE35Z","DE","Brühl","NW"),
("DERBHZSCX6","DE","Brunsbüttel","SH"),
("DE0Y95PD8E","DE","Brüssow","BB"),
("DE5J192MTM","DE","Buchen/Odenwald","BW"),
("DE235H7BGY","DE","Buchholz in der Nordheide","NI"),
("DENYYFAWMB","DE","Buchloe","BY"),
("DEUWGK9PYF","DE","Bückeburg","NI"),
("DE80PBNIYQ","DE","Buckow/Märkische Schweiz","BB"),
("DEM37TFOS2","DE","Büdelsdorf","SH"),
("DEMQIXN48H","DE","Büdingen","HE"),
("DE1O1BE0RM","DE","Bühl","BW"),
("DE0GYOZWEL","DE","Bünde","NW"),
("DE0MEFA7HX","DE","Büren","NW"),
("DEYZUL4236","DE","Burg","ST"),
("DER4H659S6","DE","Burg Stargard","MV"),
("DEPRUON99N","DE","Burgau","BY"),
("DEVO26WK4U","DE","Burgbernheim","BY"),
("DEKYFP1IVT","DE","Burgdorf","NI"),
("DENDZTMSZC","DE","Bürgel","TH"),
("DEJT063ATZ","DE","Burghausen","BY"),
("DEZW5VH9Q2","DE","Burgkunstadt","BY"),
("DE86R9ON3C","DE","Burglengenfeld","BY"),
("DE125NU40D","DE","Burgstädt","SN"),
("DEY0J2BD1B","DE","Burgwedel","NI"),
("DEA76SHXUP","DE","Burladingen","BW"),
("DE3LZS924A","DE","Burscheid","NW"),
("DE5AYZFYDE","DE","Bürstadt","HE"),
("DEZWGBAHML","DE","Buttelstedt","TH"),
("DEPTD6R7VU","DE","Buttstädt","TH"),
("DETVM3YRE3","DE","Butzbach","HE"),
("DE2C2HBGWB","DE","Bützow","MV"),
("DEDDNNVA9K","DE","Buxtehude","NI"),
("DE4MQVUMQO","DE","Calau","BB"),
("DEHCRF45J6","DE","Calbe/Saale","ST"),
("DEIMOU2L6F","DE","Calw","BW"),
("DEYU3T4CD9","DE","Castrop-Rauxel","NW"),
("DEZ34TQUI7","DE","Celle","NI"),
("DE7ANCG7JY","DE","Cham","BY"),
("DET8TVT0BR","DE","Chemnitz","SN"),
("DEUELZQY8Q","DE","Clausthal-Zellerfeld","NI"),
("DE2DJS820G","DE","Clingen","TH"),
("DECNSSUBRO","DE","Cloppenburg","NI"),
("DEJLJCLV4G","DE","Coburg","BY"),
("DE9PF0OOQQ","DE","Cochem","RP"),
("DE1AJ9CJQO","DE","Coesfeld","NW"),
("DE7IH2T8QD","DE","Colditz","SN"),
("DETAQF5UVE","DE","Coswig","SN"),
("DEKAE8Z4Z0","DE","Coswig/Anhalt","ST"),
("DEFIAR10G8","DE","Cottbus","BB"),
("DEJXAD61Q0","DE","Crailsheim","BW"),
("DEBHFGCAUW","DE","Creglingen","BW"),
("DEL95KE4LT","DE","Creußen","BY"),
("DENWLOX1XG","DE","Creuzburg","TH"),
("DEZ8T69K6K","DE","Crimmitschau","SN"),
("DE1L1DWVAH","DE","Crivitz","MV"),
("DE5F2JKOD7","DE","Cuxhaven","NI"),
("DEKYWI0TZ0","DE","Dachau","BY"),
("DE2T6BDCWF","DE","Dahlen","SN"),
("DEYXTUT3CY","DE","Dahme/Mark","BB"),
("DEJEI33VBO","DE","Dahn","RP"),
("DEU76V15V3","DE","Damme","NI"),
("DEY2ECEBRC","DE","Dannenberg/Elbe","NI"),
("DE8K71OJ07","DE","Dargun","MV"),
("DEYIB1ENP9","DE","Darmstadt","HE"),
("DEUV4W10Z0","DE","Dassel","NI"),
("DE2ECHP4TY","DE","Dassow","MV"),
("DEP10DK0LI","DE","Datteln","NW"),
("DEIXJXK96F","DE","Daun","RP"),
("DE5BB6BB7E","DE","Deggendorf","BY"),
("DEPKVFOPED","DE","Deidesheim","RP"),
("DEQERAECTX","DE","Delbrück","NW"),
("DE9DUUM19R","DE","Delitzsch","SN"),
("DECLYOW62M","DE","Delmenhorst","NI"),
("DEQX1EMGSC","DE","Demmin, Hansestadt","MV"),
("DEUKN8XG57","DE","Dessau-Roßlau","ST"),
("DET01G1A8E","DE","Detmold","NW"),
("DEV62SC5E3","DE","Dettelbach","BY"),
("DE2GIPWA2Q","DE","Dieburg","HE"),
("DEVPYS64Z0","DE","Diemelstadt","HE"),
("DE40G6BPK7","DE","Diepholz","NI"),
("DEWNZ9SDCV","DE","Dierdorf","RP"),
("DETUKP4NFZ","DE","Dietenheim","BW"),
("DEDESJJRKO","DE","Dietfurt an der Altmühl","BY"),
("DER1U3QFAM","DE","Dietzenbach","HE"),
("DE29VUN7QG","DE","Diez","RP"),
("DE1B66YM6B","DE","Dillenburg","HE"),
("DE1YVKPF8H","DE","Dillingen an der Donau","BY"),
("DEG3K6IVSL","DE","Dillingen/Saar","SL"),
("DE4NGSV68X","DE","Dingelstädt","TH"),
("DEHF3F1AR3","DE","Dingolfing","BY"),
("DE8MNY1WGH","DE","Dinkelsbühl","BY"),
("DEZ0OIWG30","DE","Dinklage","NI"),
("DE4JS0P1X7","DE","Dinslaken","NW"),
("DEH0NJBEMJ","DE","Dippoldiswalde","SN"),
("DE0AI26YK6","DE","Dissen am Teutoburger Wald","NI"),
("DEZ8PVPSWU","DE","Ditzingen","BW"),
("DECPU2RS98","DE","Döbeln","SN"),
("DETWR4BEOB","DE","Doberlug-Kirchhain","BB"),
("DEO6DU5Y15","DE","Döbern","BB"),
("DE6Q1WJYQV","DE","Dohna","SN"),
("DEOLYFD8O6","DE","Dömitz","MV"),
("DE4GAFUZRI","DE","Dommitzsch","SN"),
("DE55DB3EHA","DE","Donaueschingen","BW"),
("DE5I6OHXK5","DE","Donauwörth","BY"),
("DEJJLWR93W","DE","Donzdorf","BW"),
("DEPECKD32J","DE","Dorfen","BY"),
("DE9FVCUCNZ","DE","Dormagen","NW"),
("DEVUODR9IB","DE","Dornburg-Camburg","TH"),
("DES38JDBG3","DE","Dornhan","BW"),
("DEQSN4VQO4","DE","Dornstetten","BW"),
("DE5JH0W50S","DE","Dorsten","NW"),
("DEZP5RYO2R","DE","Dortmund","NW"),
("DESAB5MR8D","DE","Dransfeld","NI"),
("DEJWHFM5JS","DE","Drebkau","BB"),
("DEP1SM6TE5","DE","Dreieich","HE"),
("DEIJXH7Z8Z","DE","Drensteinfurt","NW"),
("DE9K5WBE9U","DE","Dresden","SN"),
("DEAQ9XWTPM","DE","Drolshagen","NW"),
("DEVI81CM7U","DE","Duderstadt","NI"),
("DE64CE4LDE","DE","Duisburg","NW"),
("DE5JAGXJB8","DE","Dülmen","NW"),
("DEAL56FUTA","DE","Düren","NW"),
("DED1CPOKKU","DE","Düsseldorf","NW"),
("DEPW8THM7N","DE","Ebeleben","TH"),
("DE5H421FBB","DE","Eberbach","BW"),
("DE1GIHBBSO","DE","Ebermannstadt","BY"),
("DED4D1PXVE","DE","Ebern","BY"),
("DEU48CQFZV","DE","Ebersbach an der Fils","BW"),
("DEX3YZJ9AL","DE","Ebersbach-Neugersdorf","SN"),
("DEQT215UQI","DE","Ebersberg","BY"),
("DEZ4JP2F4W","DE","Eberswalde","BB"),
("DEJC89S85P","DE","Eckartsberga","ST"),
("DEC4PWEZH4","DE","Eckernförde","SH"),
("DETK6YFWGF","DE","Edenkoben","RP"),
("DE0042F8ZZ","DE","Egeln","ST"),
("DEL78DGE3S","DE","Eggenfelden","BY"),
("DEISOWS61L","DE","Eggesin","MV"),
("DEQ7J540K4","DE","Ehingen/Donau","BW"),
("DE0P6FY5EJ","DE","Ehrenfriedersdorf","SN"),
("DEDNXU21NL","DE","Eibelstadt","BY"),
("DEUBHMIJ88","DE","Eibenstock","SN"),
("DEQSEUSZZS","DE","Eichstätt","BY"),
("DEP68NCN7Q","DE","Eilenburg","SN"),
("DEB5KD67Y1","DE","Einbeck","NI"),
("DEJGO1ZWAQ","DE","Eisenach","TH"),
("DEOOLGOL9D","DE","Eisenberg","TH"),
("DERI1458UG","DE","Eisenberg/Pfalz","RP"),
("DEEFULMTM6","DE","Eisenhüttenstadt","BB"),
("DE9A797I0V","DE","Eisfeld","TH"),
("DE7MCV8M90","DE","Eisleben, Lutherstadt","ST"),
("DE4A4AJYRY","DE","Eislingen/Fils","BW"),
("DEELJ0F57O","DE","Ellingen","BY"),
("DEGFYNXZJ4","DE","Ellrich","TH"),
("DEMW0UIAVM","DE","Ellwangen/Jagst","BW"),
("DELZX5YO3C","DE","Elmshorn","SH"),
("DE9NDOSKD9","DE","Elsdorf","NW"),
("DE0CWXCG2Z","DE","Elsfleth","NI"),
("DEC3TUEPHZ","DE","Elsterberg","SN"),
("DEOE4M28ZC","DE","Elsterwerda","BB"),
("DEVC1OXFXX","DE","Elstra","SN"),
("DESUV4BX3N","DE","Elterlein","SN"),
("DE1XIFM0EA","DE","Eltmann","BY"),
("DEEJXHSWUN","DE","Eltville am Rhein","HE"),
("DE9VC7B943","DE","Elzach","BW"),
("DE4Z7FXB3Z","DE","Elze","NI"),
("DE8LEVLT60","DE","Emden","NI"),
("DED4I50CSA","DE","Emmelshausen","RP"),
("DE84HKEMNJ","DE","Emmendingen","BW"),
("DEMVZK63JF","DE","Emmerich am Rhein","NW"),
("DEOXAARHB4","DE","Emsdetten","NW"),
("DELT9M62WF","DE","Endingen am Kaiserstuhl","BW"),
("DE7EZM1N5N","DE","Engen","BW"),
("DEI57P8Q4X","DE","Enger","NW"),
("DEOF7FWJKH","DE","Ennepetal","NW"),
("DEDT3KVZZ2","DE","Ennigerloh","NW"),
("DEEZPFMU35","DE","Eppelheim","BW"),
("DE0AU81Y5Q","DE","Eppingen","BW"),
("DEDD69XQRA","DE","Eppstein","HE"),
("DEJUUFUUI8","DE","Erbach","BW"),
("DET7OG2RM2","DE","Erbach/Odenwald","HE"),
("DE2GB3FHUT","DE","Erbendorf","BY"),
("DEU03RRU2A","DE","Erding","BY"),
("DEOWQIR8RK","DE","Erftstadt","NW"),
("DEGF1I7NK9","DE","Erfurt","TH"),
("DE4WCJD7C7","DE","Erkelenz","NW"),
("DE7FZY929Y","DE","Erkner","BB"),
("DEZZGQ88BO","DE","Erkrath","NW"),
("DEOC7V0R44","DE","Erlangen","BY"),
("DENHN1OZ9W","DE","Erlenbach am Main","BY"),
("DEF8VOB5MA","DE","Erlensee","HE"),
("DE530DCC20","DE","Erwitte","NW"),
("DEO9VP10TP","DE","Eschborn","HE"),
("DEHHQ6HZ2W","DE","Eschenbach in der Oberpfalz","BY"),
("DE8YKJ37U8","DE","Eschershausen","NI"),
("DEBVMN7ONW","DE","Eschwege","HE"),
("DEXJLZJEO1","DE","Eschweiler","NW"),
("DEWE7DDA9M","DE","Esens","NI"),
("DE9T5C1ZLC","DE","Espelkamp","NW"),
("DEU7Z2VNYT","DE","Essen","NW"),
("DE6JSQYHRU","DE","Esslingen am Neckar","BW"),
("DEVZ79AGVJ","DE","Ettenheim","BW"),
("DEA1VC1GOW","DE","Ettlingen","BW"),
("DEONYJAWDH","DE","Euskirchen","NW"),
("DEG67ENY8J","DE","Eutin","SH"),
("DEYGS8XOS8","DE","Falkenberg/Elster","BB"),
("DEPOKR58NT","DE","Falkensee","BB"),
("DEWMD7IQOY","DE","Falkenstein/Harz","ST"),
("DEWVDKUM3T","DE","Falkenstein/Vogtl.","SN"),
("DE2W10KU8A","DE","Fehmarn","SH"),
("DEIS2N0PGX","DE","Fellbach","BW"),
("DEBT4UJSTG","DE","Felsberg","HE"),
("DEO61JS4CV","DE","Feuchtwangen","BY"),
("DE1EVL83WQ","DE","Filderstadt","BW"),
("DEWYDXOTU0","DE","Finsterwalde","BB"),
("DENYU7RNNF","DE","Fladungen","BY"),
("DEUPYMTBIU","DE","Flensburg","SH"),
("DEPDGXHDOE","DE","Flöha","SN"),
("DEC1B0V50J","DE","Flörsheim am Main","HE"),
("DE4VQVJEBD","DE","Florstadt","HE"),
("DE3AZXLISB","DE","Forchheim","BY"),
("DEW89EMXSY","DE","Forchtenberg","BW"),
("DEZ3YV9ZEE","DE","Forst/Lausitz","BB"),
("DEU49DILRM","DE","Frankenau","HE"),
("DEVRJH9BS5","DE","Frankenberg/Eder","HE"),
("DEK1J6ZB5Y","DE","Frankenberg/Sa.","SN"),
("DEF4UP383Y","DE","Frankenthal/Pfalz","RP"),
("DEDDCWY3IU","DE","Frankfurt am Main","HE"),
("DEU1B4D49X","DE","Frankfurt/Oder","BB"),
("DE6T36595K","DE","Franzburg","MV"),
("DEDZ9G8CFL","DE","Frauenstein","SN"),
("DEPRHOV0IQ","DE","Frechen","NW"),
("DE1UUEZ4C5","DE","Freiberg","SN"),
("DEXGB2PGN2","DE","Freiberg am Neckar","BW"),
("DEGWIO9Y9Z","DE","Freiburg im Breisgau","BW"),
("DEQRNLR5CT","DE","Freilassing","BY"),
("DE077ZBK59","DE","Freinsheim","RP"),
("DE0GBPXYRD","DE","Freising","BY"),
("DEVA258B4Y","DE","Freital","SN"),
("DE3RKVXWOY","DE","Freren","NI"),
("DE3WXFG2OG","DE","Freudenberg","BW"),
("DEJ05GZXUU","DE","Freudenberg","NW"),
("DE7WZG84FC","DE","Freudenstadt","BW"),
("DEWZ7UWVS0","DE","Freyburg/Unstrut","ST"),
("DERPF7S4OB","DE","Freystadt","BY"),
("DE4US3RNYZ","DE","Freyung","BY"),
("DEKYFS2U4Y","DE","Fridingen an der Donau","BW"),
("DEUBSQ7KRY","DE","Friedberg","BY"),
("DEA762BUEG","DE","Friedberg","HE"),
("DEP7JGUHGE","DE","Friedland","MV"),
("DEFV7IQCGK","DE","Friedland","BB"),
("DEN9BVT3T4","DE","Friedrichroda","TH"),
("DEA07MVM2K","DE","Friedrichsdorf","HE"),
("DETL1O3H3J","DE","Friedrichshafen","BW"),
("DEDA13MHOA","DE","Friedrichstadt","SH"),
("DERZ5L2ZPD","DE","Friedrichsthal","SL"),
("DEZXZUJ1FC","DE","Friesack","BB"),
("DENG1QY4AB","DE","Friesoythe","NI"),
("DEEBE1T3BK","DE","Fritzlar","HE"),
("DE3H56GUJF","DE","Frohburg","SN"),
("DERIABKPN8","DE","Fröndenberg/Ruhr","NW"),
("DE6OY4T9G7","DE","Fulda","HE"),
("DEKV8DYKY1","DE","Fürstenau","NI"),
("DE137HYRXQ","DE","Fürstenberg/Havel","BB"),
("DEA81UYP24","DE","Fürstenfeldbruck","BY"),
("DEE197APFV","DE","Fürstenwalde/Spree","BB"),
("DEKN8I76K9","DE","Fürth","BY"),
("DEASQ8JOYT","DE","Furth im Wald","BY"),
("DEW0NUPQZ4","DE","Furtwangen im Schwarzwald","BW"),
("DES8B2XQXI","DE","Füssen","BY"),
("DEE61MDLVN","DE","Gadebusch","MV"),
("DEDMWXAVQ7","DE","Gaggenau","BW"),
("DEVE1L40PW","DE","Gaildorf","BW"),
("DE81Z6SXP6","DE","Gammertingen","BW"),
("DE3QTGBO4P","DE","Garbsen","NI"),
("DEB0MLVCSQ","DE","Garching bei München","BY"),
("DERUBVU1S3","DE","Gardelegen","ST"),
("DE3RAVOZ2S","DE","Garding","SH"),
("DEPV81JCRV","DE","Gartz/Oder","BB"),
("DECDH8QAYH","DE","Garz/Rügen","MV"),
("DE4ADZC53F","DE","Gau-Algesheim","RP"),
("DEXDAMCCE2","DE","Gebesee","TH"),
("DE7N4R0VND","DE","Gedern","HE"),
("DE84LZEJGJ","DE","Geesthacht","SH"),
("DEUUI6ZLMX","DE","Geestland","NI"),
("DEYWKB9YEH","DE","Gefell","TH"),
("DEMI9MDWZM","DE","Gefrees","BY"),
("DE0KLF42YZ","DE","Gehrden","NI"),
("DEWG5W2RT1","DE","Gehren","TH"),
("DEODCYCRFY","DE","Geilenkirchen","NW"),
("DE9OLMLK8M","DE","Geisa","TH"),
("DE5U1AWZ9S","DE","Geiselhöring","BY"),
("DEGFOI7IJV","DE","Geisenfeld","BY"),
("DEWWU8N97W","DE","Geisenheim","HE"),
("DEYSJJCS5I","DE","Geisingen","BW"),
("DEM7SI62BN","DE","Geislingen","BW"),
("DEH05OIPKE","DE","Geislingen an der Steige","BW"),
("DELEM8OT5N","DE","Geithain","SN"),
("DEMP7YHCH4","DE","Geldern","NW"),
("DEKANRCZET","DE","Gelnhausen","HE"),
("DEZJIH93VU","DE","Gelsenkirchen","NW"),
("DEII37C9UY","DE","Gemünden am Main","BY"),
("DEY1XGEELY","DE","Gemünden/Wohra","HE"),
("DEP8P173V6","DE","Gengenbach","BW"),
("DENEOWHKR0","DE","Genthin","ST"),
("DE3U7F41E2","DE","Georgsmarienhütte","NI"),
("DE2CJHR4FG","DE","Gera","TH"),
("DEC4HK8DRV","DE","Gerabronn","BW"),
("DERFS90K93","DE","Gerbstedt","ST"),
("DEFGJJIXML","DE","Geretsried","BY"),
("DEA5219HIM","DE","Geringswalde","SN"),
("DEM06UDYQ5","DE","Gerlingen","BW"),
("DEDJED3NHI","DE","Germering","BY"),
("DE402NYO88","DE","Germersheim","RP"),
("DETAA2SSOE","DE","Gernsbach","BW"),
("DESV96T0B7","DE","Gernsheim","HE"),
("DEJPLND26I","DE","Gerolstein","RP"),
("DE2851WEAQ","DE","Gerolzhofen","BY"),
("DEPKSHDHW6","DE","Gersfeld/Rhön","HE"),
("DEC5C66ODP","DE","Gersthofen","BY"),
("DEEYCS1IA4","DE","Gescher","NW"),
("DERG5NUFDJ","DE","Geseke","NW"),
("DE061DOYK1","DE","Gevelsberg","NW"),
("DE3X7ALLZ0","DE","Geyer","SN"),
("DEJCSLV2PM","DE","Giengen an der Brenz","BW"),
("DEJUADAOXA","DE","Gießen","HE"),
("DEVZOJX8K1","DE","Gifhorn","NI"),
("DE6SBSDASX","DE","Ginsheim-Gustavsburg","HE"),
("DENKIIN756","DE","Gladbeck","NW"),
("DE2GKC4HM0","DE","Gladenbach","HE"),
("DEGBJEJ4FQ","DE","Glashütte","SN"),
("DEWQIA1B7O","DE","Glauchau","SN"),
("DEVQ6JXCP0","DE","Glinde","SH"),
("DESACXRZX8","DE","Glücksburg/Ostsee","SH"),
("DEAHNUL2KI","DE","Glückstadt","SH"),
("DES3STE0IA","DE","Gnoien","MV"),
("DEQPTO1JPT","DE","Goch","NW"),
("DET1RL1OUB","DE","Goldberg","MV"),
("DE5H5RJQAC","DE","Goldkronach","BY"),
("DET3683OIU","DE","Golßen","BB"),
("DEDBJFV89O","DE","Gommern","ST"),
("DE90AAO4MU","DE","Göppingen","BW"),
("DEMSM6IWIC","DE","Görlitz","SN"),
("DEZPL3D3YR","DE","Goslar","NI"),
("DEFH7APGZZ","DE","Gößnitz","TH"),
("DEG9A5EX00","DE","Gotha","TH"),
("DEPM68JPLJ","DE","Göttingen","NI"),
("DEE6MSAKKP","DE","Grabow","MV"),
("DE2R0S8ZRO","DE","Grafenau","BY"),
("DE92UNZUOP","DE","Gräfenberg","BY"),
("DEHVX1LJK0","DE","Gräfenhainichen","ST"),
("DEP7SZSDPU","DE","Gräfenthal","TH"),
("DE5PMDPE2Y","DE","Grafenwöhr","BY"),
("DEGWMGRB59","DE","Grafing bei München","BY"),
("DE63ARMURC","DE","Gransee","BB"),
("DE2KCUY1O3","DE","Grebenau","HE"),
("DEQBHFPJE6","DE","Grebenstein","HE"),
("DEG1N8CTHI","DE","Greding","BY"),
("DEWRAJM2VO","DE","Greifswald, Hansestadt","MV"),
("DEM8JK98O0","DE","Greiz","TH"),
("DEJ5G9PUG6","DE","Greußen","TH"),
("DEV3E7WVQT","DE","Greven","NW"),
("DEN1CA38YP","DE","Grevenbroich","NW"),
("DEGIAQQZQA","DE","Grevesmühlen","MV"),
("DE56JU101W","DE","Griesheim","HE"),
("DE3F40BVUY","DE","Grimma","SN"),
("DEW78ZF7PW","DE","Grimmen","MV"),
("DEP0MGZDQ5","DE","Gröditz","SN"),
("DEJ90K91HD","DE","Groitzsch","SN"),
("DEGMERI8QE","DE","Gronau/Leine","NI"),
("DEGZEW64SW","DE","Gronau/Westf.","NW"),
("DE4FC4T29C","DE","Gröningen","ST"),
("DEC9XMBF0R","DE","Groß-Bieberau","HE"),
("DE2FJKN9Y4","DE","Groß-Gerau","HE"),
("DE8D0FHSBM","DE","Groß-Umstadt","HE"),
("DE8OR1R0E4","DE","Großalmerode","HE"),
("DEACQLRRDU","DE","Großbottwar","BW"),
("DE6WEU6CYF","DE","Großbreitenbach","TH"),
("DEQYU7R6U0","DE","Großenehrich","TH"),
("DEUL1MMGQX","DE","Großenhain","SN"),
("DESHJK8WEF","DE","Großräschen","BB"),
("DETTA058FW","DE","Großröhrsdorf","SN"),
("DE794YFYYA","DE","Großschirma","SN"),
("DEK0W6HN3A","DE","Grünberg","HE"),
("DE5NUDK9TD","DE","Grünhain-Beierfeld","SN"),
("DE23E8CT5J","DE","Grünsfeld","BW"),
("DE29II7HSR","DE","Grünstadt","RP"),
("DEIPYZD29I","DE","Guben","BB"),
("DEP4W9EPNH","DE","Gudensberg","HE"),
("DET1Q5UVPX","DE","Güglingen","BW"),
("DE48FCP848","DE","Gummersbach","NW"),
("DEY38B5HUV","DE","Gundelfingen an der Donau","BY"),
("DEMQ51GTIA","DE","Gundelsheim","BW"),
("DEV9GP55NA","DE","Günzburg","BY"),
("DEE3M3BRCA","DE","Gunzenhausen","BY"),
("DEVKM12GWP","DE","Güsten","ST"),
("DE62QNV9XQ","DE","Güstrow","MV"),
("DEIDGOJ4YX","DE","Gütersloh","NW"),
("DE7L1JCDT8","DE","Gützkow","MV"),
("DEYF90W6P3","DE","Haan","NW"),
("DE8GQ4QOV9","DE","Hachenburg","RP"),
("DE1BXLGVIN","DE","Hadamar","HE"),
("DEGJ6TX01V","DE","Hagen","NW"),
("DEGAWCGMFP","DE","Hagenbach","RP"),
("DE26TSUO1W","DE","Hagenow","MV"),
("DE0YHGU04A","DE","Haiger","HE"),
("DEKB3HC4DS","DE","Haigerloch","BW"),
("DEF95VVLLY","DE","Hainichen","SN"),
("DEREQM3SJ4","DE","Haiterbach","BW"),
("DER1LL1PVL","DE","Halberstadt","ST"),
("DE1Z3D3G6J","DE","Haldensleben","ST"),
("DEPBFLW0JO","DE","Halle/Saale","ST"),
("DEF9BI2VNT","DE","Halle/Westf.","NW"),
("DEW8FYYBK0","DE","Hallenberg","NW"),
("DEANDE4JXT","DE","Hallstadt","BY"),
("DEVCFSCYHR","DE","Haltern am See","NW"),
("DE7SAAOY3L","DE","Halver","NW"),
("DE7IK5U464","DE","Hamburg, Freie und Hansestadt","HH"),
("DESJIX3FQZ","DE","Hameln","NI"),
("DES5R448WB","DE","Hamm","NW"),
("DE17LP5PBD","DE","Hammelburg","BY"),
("DE8VJ2ZP7S","DE","Hamminkeln","NW"),
("DE9PPD5GCX","DE","Hanau","HE"),
("DEM32QCZ2E","DE","Hann. Münden","NI"),
("DE7O4DEFQN","DE","Hannover","NI"),
("DEA9PAYW28","DE","Harburg/Schwaben","BY"),
("DEMSLS8XPV","DE","Hardegsen","NI"),
("DE1SLDSORZ","DE","Haren/Ems","NI"),
("DECVDQB3DL","DE","Harsewinkel","NW"),
("DED3VC0YKN","DE","Hartenstein","SN"),
("DEQ5FZ25V4","DE","Hartha","SN"),
("DEXHHQ59QI","DE","Harzgerode","ST"),
("DE539G6N2K","DE","Haselünne","NI"),
("DEQXWRWGEN","DE","Haslach im Kinzigtal","BW"),
("DELUMOZITX","DE","Haßfurt","BY"),
("DEZBN4KDMQ","DE","Hattersheim am Main","HE"),
("DEHV6NI889","DE","Hattingen","NW"),
("DE6412KGQ6","DE","Hatzfeld/Eder","HE"),
("DEACVAUO7U","DE","Hausach","BW"),
("DEZVYK8LAQ","DE","Hauzenberg","BY"),
("DEGHEZQM9X","DE","Havelberg","ST"),
("DEQB0ARQH2","DE","Havelsee","BB"),
("DE3CCY1JS1","DE","Hayingen","BW"),
("DEEQLNBWES","DE","Hechingen","BW"),
("DEDSS4E214","DE","Hecklingen","ST"),
("DEE1F5SW8V","DE","Heide","SH"),
("DE9KTB4LCJ","DE","Heideck","BY"),
("DECX7OTLH7","DE","Heidelberg","BW"),
("DEDACRCDWR","DE","Heidenau","SN"),
("DEFBW7852I","DE","Heidenheim an der Brenz","BW"),
("DEPWTUH5DU","DE","Heilbad Heiligenstadt","TH"),
("DE2LIW6Z4J","DE","Heilbronn","BW"),
("DEAGBNU7E9","DE","Heiligenhafen","SH"),
("DEJAHRGK95","DE","Heiligenhaus","NW"),
("DEG20Y8DSB","DE","Heilsbronn","BY"),
("DEYB75BBPL","DE","Heimbach","NW"),
("DES18M8MVS","DE","Heimsheim","BW"),
("DEXDJDXTJD","DE","Heinsberg","NW"),
("DEWJB5X4GW","DE","Heitersheim","BW"),
("DEFN1QZQBR","DE","Heldrungen","TH"),
("DERKD069T3","DE","Helmbrechts","BY"),
("DEMCGJ6ZX3","DE","Helmstedt","NI"),
("DEI98GDOCT","DE","Hemau","BY"),
("DECDKB4V3W","DE","Hemer","NW"),
("DEFHXMQQPD","DE","Hemmingen","NI"),
("DE36WA5UDO","DE","Hemmoor","NI"),
("DE3M4HBHAN","DE","Hemsbach","BW"),
("DEUUZZQ2W6","DE","Hennef/Sieg","NW"),
("DEJUSAKHNO","DE","Hennigsdorf","BB"),
("DEOKYTECII","DE","Heppenheim/Bergstraße","HE"),
("DEYNZA4AXZ","DE","Herbolzheim","BW"),
("DE5WZVZV2J","DE","Herborn","HE"),
("DEPUTACHY0","DE","Herbrechtingen","BW"),
("DE1XUG9DY8","DE","Herbstein","HE"),
("DE0YI59F5E","DE","Herdecke","NW"),
("DEC4ABZCUP","DE","Herdorf","RP"),
("DE7OZK5XL7","DE","Herford","NW"),
("DEUFN4TMDU","DE","Heringen/Helme","TH"),
("DEKVZTB48O","DE","Heringen/Werra","HE"),
("DE9IZ8VUY2","DE","Hermeskeil","RP"),
("DEJXNOV8VQ","DE","Hermsdorf","TH"),
("DEOJVH58CQ","DE","Herne","NW"),
("DE3BJFGR3P","DE","Herrenberg","BW"),
("DEA3Y5YW8H","DE","Herrieden","BY"),
("DEUV6Q32GS","DE","Herrnhut","SN"),
("DELC9RKLHO","DE","Hersbruck","BY"),
("DEX03ES742","DE","Herten","NW"),
("DEA3880GQU","DE","Herzberg am Harz","NI"),
("DEBWLFZ27K","DE","Herzberg/Elster","BB"),
("DEEHBY3SM1","DE","Herzogenaurach","BY"),
("DETQFMXKO8","DE","Herzogenrath","NW"),
("DENXHND7IO","DE","Hessisch Lichtenau","HE"),
("DE43435BOJ","DE","Hessisch Oldendorf","NI"),
("DES0IVT5WN","DE","Hettingen","BW"),
("DEVC9TWY1K","DE","Hettstedt","ST"),
("DEVI88QRXU","DE","Heubach","BW"),
("DEU1Y0CMK5","DE","Heusenstamm","HE"),
("DEN31G8Y34","DE","Hilchenbach","NW"),
("DEBDX8BYS6","DE","Hildburghausen","TH"),
("DEH1F7SC2N","DE","Hilden","NW"),
("DEE0NQN8WA","DE","Hildesheim","NI"),
("DEBXQKWUO7","DE","Hillesheim","RP"),
("DE7LFJK8P1","DE","Hilpoltstein","BY"),
("DE9591HBOW","DE","Hirschau","BY"),
("DEBCMYLJ8W","DE","Hirschberg","TH"),
("DEHZHDU5L2","DE","Hirschhorn/Neckar","HE"),
("DER0LB8BDI","DE","Hitzacker/Elbe","NI"),
("DEGMJYX8U8","DE","Hochheim am Main","HE"),
("DELH760G3I","DE","Höchstadt an der Aisch","BY"),
("DEGKWAPHDH","DE","Höchstädt an der Donau","BY"),
("DEHYSQ968Q","DE","Hockenheim","BW"),
("DESSOQ0JZL","DE","Hof","BY"),
("DE06S1NVJ3","DE","Hofgeismar","HE"),
("DEFFE5WRME","DE","Hofheim am Taunus","HE"),
("DEQF50LDQE","DE","Hofheim in Unterfranken","BY"),
("DE6F46Y3SY","DE","Hohen Neuendorf","BB"),
("DEAK0XGJ0V","DE","Hohenberg an der Eger","BY"),
("DEZF1W7OBX","DE","Hohenleuben","TH"),
("DE3GXPUO30","DE","Hohenmölsen","ST"),
("DE3871C00M","DE","Hohenstein-Ernstthal","SN"),
("DEL0J1KKXK","DE","Hohnstein","SN"),
("DE0YG7MS5Q","DE","Höhr-Grenzhausen","RP"),
("DE83G3RJ3U","DE","Hollfeld","BY"),
("DESBW4CWQX","DE","Holzgerlingen","BW"),
("DEXAZHUW1V","DE","Holzminden","NI"),
("DEUI2HA78J","DE","Homberg/Efze","HE"),
("DEBOM28QX0","DE","Homberg/Ohm","HE"),
("DE2T5EQVCN","DE","Homburg","SL"),
("DE5B5077V2","DE","Horb am Neckar","BW"),
("DEQYK16SLH","DE","Horn-Bad Meinberg","NW"),
("DEH7JPYGP1","DE","Hornbach","RP"),
("DEAVG1QSOW","DE","Hornberg","BW"),
("DE4UXC1TER","DE","Hörstel","NW"),
("DERZTXSEE9","DE","Horstmar","NW"),
("DEMYYLFOMQ","DE","Höxter","NW"),
("DEJ2RAVG6Z","DE","Hoya","NI"),
("DEA4BCXQ3O","DE","Hoyerswerda","SN"),
("DEPXMIB1RX","DE","Hückelhoven","NW"),
("DE0PIFE56X","DE","Hückeswagen","NW"),
("DE8X73DE3N","DE","Hüfingen","BW"),
("DEJFZG535V","DE","Hünfeld","HE"),
("DE1SDCT4AU","DE","Hungen","HE"),
("DEUTA8YG66","DE","Hürth","NW"),
("DEDEARSDFC","DE","Husum","SH"),
("DESFSYJYUK","DE","Ibbenbüren","NW"),
("DEQ7XKC7E7","DE","Ichenhausen","BY"),
("DE0OGZ4M5I","DE","Idar-Oberstein","RP"),
("DE0F9TTP5M","DE","Idstein","HE"),
("DE4YKNWE8N","DE","Illertissen","BY"),
("DEM57YDM6E","DE","Ilmenau","TH"),
("DEAMDF8JY9","DE","Ilsenburg/Harz","ST"),
("DEZ72SX8E1","DE","Ilshofen","BW"),
("DE6YP3DYQZ","DE","Immenhausen","HE"),
("DE4XYHJ4VU","DE","Immenstadt im Allgäu","BY"),
("DEQ89ZR78R","DE","Ingelfingen","BW"),
("DEFBJDJYFP","DE","Ingelheim am Rhein","RP"),
("DEX4SA3JA7","DE","Ingolstadt","BY"),
("DEG8O0DKU4","DE","Iphofen","BY"),
("DET43LCBCS","DE","Iserlohn","NW"),
("DENV56TKWQ","DE","Isny im Allgäu","BW"),
("DEPP1S8B0P","DE","Isselburg","NW"),
("DEJOPX9K12","DE","Itzehoe","SH"),
("DEO4N1GZT3","DE","Jarmen","MV"),
("DEVZ9PK6F9","DE","Jena","TH"),
("DEVH24S2TC","DE","Jerichow","ST"),
("DERI903A3R","DE","Jessen/Elster","ST"),
("DEFQTVQNZL","DE","Jever","NI"),
("DEM9A6FQGB","DE","Joachimsthal","BB"),
("DE7IF0L8CC","DE","Johanngeorgenstadt","SN"),
("DERMDUXHMC","DE","Jöhstadt","SN"),
("DE8G8Y37KQ","DE","Jülich","NW"),
("DEHVWXMD8U","DE","Jüterbog","BB"),
("DEWOUHW7UO","DE","Kaarst","NW"),
("DEU8JRP54X","DE","Kahla","TH"),
("DELCVPKGF2","DE","Kaisersesch","RP"),
("DEBCZYP7SL","DE","Kaiserslautern","RP"),
("DEWM3TUXHO","DE","Kalbe/Milde","ST"),
("DE50FV6KSS","DE","Kalkar","NW"),
("DEWOHH5XJG","DE","Kaltenkirchen","SH"),
("DE9JFZR7LN","DE","Kaltennordheim","TH"),
("DETPGOMXCS","DE","Kamen","NW"),
("DEYSO5CGX9","DE","Kamenz","SN"),
("DE5FRACBRM","DE","Kamp-Lintfort","NW"),
("DEU6MLD797","DE","Kandel","RP"),
("DEXPVKN8CL","DE","Kandern","BW"),
("DE11QEHOON","DE","Kappeln","SH"),
("DE3FXGRP2M","DE","Karben","HE"),
("DEWO79WHHT","DE","Karlsruhe","BW"),
("DE6DDTLQFN","DE","Karlstadt","BY"),
("DER619UPXX","DE","Kassel","HE"),
("DE5VEWKGIG","DE","Kastellaun","RP"),
("DE5QQ278WE","DE","Katzenelnbogen","RP"),
("DELA770NUS","DE","Kaub","RP"),
("DETW2NL0LR","DE","Kaufbeuren","BY"),
("DEVZNGG6XM","DE","Kehl","BW"),
("DEXOO5WKJH","DE","Kelbra/Kyffhäuser","ST"),
("DEUROVEJO7","DE","Kelheim","BY"),
("DEFRV1RHSM","DE","Kelkheim/Taunus","HE"),
("DEGG3XN0JK","DE","Kellinghusen","SH"),
("DEO8PLS92N","DE","Kelsterbach","HE"),
("DE0RJEA7MQ","DE","Kemberg","ST"),
("DEYIRQZKDG","DE","Kemnath","BY"),
("DE1GEOHX96","DE","Kempen","NW"),
("DE5ZRY8UM9","DE","Kempten/Allgäu","BY"),
("DEL5NWDAMC","DE","Kenzingen","BW"),
("DESE2SZF80","DE","Kerpen","NW"),
("DEWNPDKZKQ","DE","Ketzin/Havel","BB"),
("DEYBP75BGR","DE","Kevelaer","NW"),
("DEH4NVFA78","DE","Kiel","SH"),
("DEPA0OP9PM","DE","Kierspe","NW"),
("DEWF0HEK7D","DE","Kindelbrück","TH"),
("DEVXL192SQ","DE","Kirchberg","SN"),
("DE6FLLQTTF","DE","Kirchberg an der Jagst","BW"),
("DE3U3S3TF0","DE","Kirchberg/Hunsrück","RP"),
("DE8FHNZP1V","DE","Kirchen/Sieg","RP"),
("DEMMWVOOMV","DE","Kirchenlamitz","BY"),
("DE47GU1A94","DE","Kirchhain","HE"),
("DE4DX86C8F","DE","Kirchheim unter Teck","BW"),
("DERP2RF3M1","DE","Kirchheimbolanden","RP"),
("DEQIXF7JAB","DE","Kirn","RP"),
("DERR6S1GW6","DE","Kirtorf","HE"),
("DETTE06MFX","DE","Kitzingen","BY"),
("DECIPRMBTC","DE","Kitzscher","SN"),
("DETQR192C1","DE","Kleve","NW"),
("DETJTUZQ0S","DE","Klingenberg am Main","BY"),
("DEKFSQ28OF","DE","Klingenthal","SN"),
("DEQD6CO0OI","DE","Klötze","ST"),
("DEQGJ0IW1B","DE","Klütz","MV"),
("DEFV6EL775","DE","Knittlingen","BW"),
("DEMZWP7K4Y","DE","Koblenz","RP"),
("DEXBAMBY42","DE","Kohren-Sahlis","SN"),
("DEFO3YK59Z","DE","Kolbermoor","BY"),
("DE0GEMNLSA","DE","Kölleda","TH"),
("DELOZT83R6","DE","Köln","NW"),
("DEE1TQ0XTG","DE","Königs Wusterhausen","BB"),
("DEMWE61O52","DE","Königsberg in Bayern","BY"),
("DE4KPS5H2R","DE","Königsbrück","SN"),
("DE52KD5CKK","DE","Königsbrunn","BY"),
("DEDDBEB4VX","DE","Königsee-Rottenbach","TH"),
("DE1933X951","DE","Königslutter am Elm","NI"),
("DEUUTZBWRH","DE","Königstein im Taunus","HE"),
("DEYBV4NFP1","DE","Königstein/Sächsische Schweiz","SN"),
("DET0G45B26","DE","Königswinter","NW"),
("DEL69IGFKA","DE","Könnern","ST"),
("DEAEAMA138","DE","Konstanz","BW"),
("DECYD0D227","DE","Konz","RP"),
("DE3JB9VEGG","DE","Korbach","HE"),
("DEKQY05IAG","DE","Korntal-Münchingen","BW"),
("DEWK27L5GY","DE","Kornwestheim","BW"),
("DE4TZIW1P0","DE","Korschenbroich","NW"),
("DEL09GFQWZ","DE","Köthen/Anhalt","ST"),
("DEGVZMDA2A","DE","Kraichtal","BW"),
("DEU4IGAYEE","DE","Krakow am See","MV"),
("DESEWPFMP1","DE","Kranichfeld","TH"),
("DENZH2PE15","DE","Krautheim","BW"),
("DE91RNBTY6","DE","Krefeld","NW"),
("DEYGM8F1N7","DE","Kremmen","BB"),
("DEFKWV6LWT","DE","Krempe","SH"),
("DELEVASWF1","DE","Kreuztal","NW"),
("DEY7O90MFZ","DE","Kronach","BY"),
("DE327I4VPK","DE","Kronberg im Taunus","HE"),
("DEFLFL7CFS","DE","Kröpelin","MV"),
("DEQA3J7IK5","DE","Kroppenstedt","ST"),
("DEP9FQVVPY","DE","Krumbach/Schwaben","BY"),
("DEYXG2S6M8","DE","Kühlungsborn","MV"),
("DES2U0F9T6","DE","Kulmbach","BY"),
("DEKWPREAX4","DE","Külsheim","BW"),
("DEJDVF8LE6","DE","Künzelsau","BW"),
("DEIV9B1WKT","DE","Kupferberg","BY"),
("DEYEUDNNJ8","DE","Kuppenheim","BW"),
("DEJ9ZYJX22","DE","Kusel","RP"),
("DEAYHJJVP2","DE","Kyllburg","RP"),
("DEQZESVYMT","DE","Kyritz","BB"),
("DEDG713R9M","DE","Laage","MV"),
("DE09KJ6NMH","DE","Laatzen","NI"),
("DEM306ZQ9Q","DE","Ladenburg","BW"),
("DEQNILM5EZ","DE","Lage","NW"),
("DELM1ODABE","DE","Lahnstein","RP"),
("DEJWXQKK86","DE","Lahr/Schwarzwald","BW"),
("DEN9CNZLDP","DE","Laichingen","BW"),
("DE9WBW1QVM","DE","Lambrecht/Pfalz","RP"),
("DECWBQ7N4Q","DE","Lampertheim","HE"),
("DEK2H4MPBA","DE","Landau an der Isar","BY"),
("DEYOYYABOJ","DE","Landau in der Pfalz","RP"),
("DE8ZF9PBW2","DE","Landsberg","ST"),
("DE88SGWX6G","DE","Landsberg am Lech","BY"),
("DE0OLNDWYC","DE","Landshut","BY"),
("DEKWBV7ZEG","DE","Landstuhl","RP"),
("DEZUPO6MRF","DE","Langelsheim","NI"),
("DEVKVRH28I","DE","Langen","HE"),
("DEQT54P3HA","DE","Langenau","BW"),
("DEZS57RKNR","DE","Langenburg","BW"),
("DEFDFMZ71V","DE","Langenfeld/Rheinland","NW"),
("DERXM8ZURQ","DE","Langenhagen","NI"),
("DEOWVE0COZ","DE","Langenselbold","HE"),
("DE5U7XFUOU","DE","Langenzenn","BY"),
("DE73H7AI22","DE","Langewiesen","TH"),
("DEFPBFK258","DE","Lassan","MV"),
("DEY1MZDBZI","DE","Laubach","HE"),
("DE66FL13G9","DE","Laucha an der Unstrut","ST"),
("DE7XGIGJLW","DE","Lauchhammer","BB"),
("DE9WBTYH2X","DE","Lauchheim","BW"),
("DEIPWW0VF6","DE","Lauda-Königshofen","BW"),
("DE2VS3Z8C7","DE","Lauenburg/Elbe","SH"),
("DE6TQMDBJM","DE","Lauf an der Pegnitz","BY"),
("DE7UG5CI2V","DE","Laufen","BY"),
("DE7ZS8U7EW","DE","Laufenburg/Baden","BW"),
("DE3702GC9M","DE","Lauffen am Neckar","BW"),
("DE509IBS5I","DE","Lauingen/Donau","BY"),
("DENLO04QVB","DE","Laupheim","BW"),
("DEQNJKVYHY","DE","Lauscha","TH"),
("DE6H1MUB80","DE","Lauta","SN"),
("DEBIJMBO4Z","DE","Lauter-Bernsbach","SN"),
("DEATZEJUQ9","DE","Lauterbach","HE"),
("DEI9UD8CCE","DE","Lauterecken","RP"),
("DEUD0OO9PZ","DE","Lauterstein","BW"),
("DES8M4XR37","DE","Lebach","SL"),
("DEK2L4XBEF","DE","Lebus","BB"),
("DEL8TUL68F","DE","Leer/Ostfriesland","NI"),
("DEJ948JU8C","DE","Lehesten","TH"),
("DE2UGZLJ66","DE","Lehrte","NI"),
("DEMSAJ4OZQ","DE","Leichlingen/Rheinland","NW"),
("DEXTKIZTYI","DE","Leimen","BW"),
("DE33RMXZZ0","DE","Leinefelde-Worbis","TH"),
("DETFZFZ6LL","DE","Leinfelden-Echterdingen","BW"),
("DEZW43K3TH","DE","Leipheim","BY"),
("DEWD0W7ZFA","DE","Leipzig","SN"),
("DE26X05W0Z","DE","Leisnig","SN"),
("DEB0EB60W5","DE","Lemgo","NW"),
("DEW09H43Z1","DE","Lengenfeld","SN"),
("DEHZXOYDY1","DE","Lengerich","NW"),
("DEJV1OS2O4","DE","Lennestadt","NW"),
("DE23F84BE0","DE","Lenzen","BB"),
("DECOIHRHI8","DE","Leonberg","BW"),
("DEGGXFTWHD","DE","Leun","HE"),
("DESI2KKQON","DE","Leuna","ST"),
("DET4VXFAYS","DE","Leutenberg","TH"),
("DEYG9QYSZE","DE","Leutershausen","BY"),
("DE9WU3TBGL","DE","Leutkirch im Allgäu","BW"),
("DEUJ5F9U23","DE","Leverkusen","NW"),
("DEYY1E9078","DE","Lich","HE"),
("DEGGZE9YTJ","DE","Lichtenau","BW"),
("DEVONO049V","DE","Lichtenau","NW"),
("DENFBW9E08","DE","Lichtenberg","BY"),
("DEC1MM1UUI","DE","Lichtenfels","BY"),
("DEBTXKSR4N","DE","Lichtenfels","HE"),
("DEGRBGVLCI","DE","Lichtenstein/Sa.","SN"),
("DE0NFA1FIE","DE","Liebenau","HE"),
("DEH50JZV2A","DE","Liebenwalde","BB"),
("DEO0VHSZ48","DE","Lieberose","BB"),
("DEQGPM2142","DE","Liebstadt","SN"),
("DEPKDQ0V5I","DE","Limbach-Oberfrohna","SN"),
("DE051004AP","DE","Limburg an der Lahn","HE"),
("DE466X5B6W","DE","Lindau/Bodensee","BY"),
("DERVITXNWN","DE","Linden","HE"),
("DE79D85JQ6","DE","Lindenberg im Allgäu","BY"),
("DEOR6PWHF1","DE","Lindenfels","HE"),
("DENMYTX4PP","DE","Lindow/Mark","BB"),
("DE08JYWGL4","DE","Lingen/Ems","NI"),
("DEPZCVI217","DE","Linnich","NW"),
("DEU8WRPCSD","DE","Linz am Rhein","RP"),
("DEYR6WWWMW","DE","Lippstadt","NW"),
("DE45U1LG5B","DE","Löbau","SN"),
("DEFI7XL84G","DE","Löffingen","BW"),
("DEG176D0JC","DE","Lohmar","NW"),
("DERP8NLUKQ","DE","Löhne","NW"),
("DE0FSMVXYA","DE","Lohne/Oldenburg","NI"),
("DEG581EDHU","DE","Lohr am Main","BY"),
("DEEP0SPJ4H","DE","Loitz","MV"),
("DE9D4V8PL9","DE","Lollar","HE"),
("DE4DV0BUBR","DE","Lommatzsch","SN"),
("DEZJTDXB8B","DE","Löningen","NI"),
("DE093QT872","DE","Lorch","BW"),
("DELCXU1J36","DE","Lorch","HE"),
("DEXZ68TH0S","DE","Lörrach","BW"),
("DE1U6Y5FA6","DE","Lorsch","HE"),
("DEOEWHM3K8","DE","Lößnitz","SN"),
("DEFI3H16NZ","DE","Löwenstein","BW"),
("DE5T7ZB8SD","DE","Lübbecke","NW"),
("DE2YC8DMF2","DE","Lübben/Spreewald","BB"),
("DE0BKNF5VV","DE","Lübbenau/Spreewald","BB"),
("DENYDP50PB","DE","Lübeck, Hansestadt","SH"),
("DEUWA652J8","DE","Lübtheen","MV"),
("DE1VHFIWHJ","DE","Lübz","MV"),
("DE826N72JV","DE","Lüchow/Wendland","NI"),
("DE0WL6XAHR","DE","Lucka","TH"),
("DE7SXDUHLW","DE","Luckau","BB"),
("DEC3BVZTE7","DE","Luckenwalde","BB"),
("DEVKV3NFZN","DE","Lüdenscheid","NW"),
("DEBLU8WB03","DE","Lüdinghausen","NW"),
("DE3XHYE3UR","DE","Ludwigsburg","BW"),
("DE66M5Z1DV","DE","Ludwigsfelde","BB"),
("DEM9Z9OZXZ","DE","Ludwigshafen am Rhein","RP"),
("DEKR8G38K7","DE","Ludwigslust","MV"),
("DE616L50CB","DE","Ludwigsstadt","BY"),
("DE6ZH61V1N","DE","Lugau/Erzgeb.","SN"),
("DE41WS0TSK","DE","Lügde","NW"),
("DEL11OAMWG","DE","Lüneburg, Hansestadt","NI"),
("DEO21T3E5A","DE","Lünen","NW"),
("DEEMGFHI2M","DE","Lunzenau","SN"),
("DEJZEKS74E","DE","Lütjenburg","SH"),
("DE863JSZZG","DE","Lützen","ST"),
("DE11A4GFEU","DE","Lychen","BB"),
("DE2V9JDB6X","DE","Magdala","TH"),
("DEALH3SMI1","DE","Magdeburg","ST"),
("DESLKLKK2L","DE","Mahlberg","BW"),
("DELCQ1R5VT","DE","Mainbernheim","BY"),
("DE05DDGJBR","DE","Mainburg","BY"),
("DE5SVXEDZ7","DE","Maintal","HE"),
("DEYJSJ3U5P","DE","Mainz","RP"),
("DE7VRY1NS1","DE","Malchin","MV"),
("DES6F9QQ1V","DE","Malchow","MV"),
("DEJWTYAS59","DE","Manderscheid","RP"),
("DECYSGTY60","DE","Mannheim","BW"),
("DEUXZVKRWD","DE","Mansfeld","ST"),
("DEYBNO2OJL","DE","Marbach am Neckar","BW"),
("DELCKV5P5H","DE","Marburg","HE"),
("DEOXYHV4HP","DE","Marienberg","SN"),
("DE1HLM9HZ7","DE","Marienmünster","NW"),
("DETMVWBFHW","DE","Markdorf","BW"),
("DES1SXRXFF","DE","Markgröningen","BW"),
("DEUDXQHFGJ","DE","Märkisch Buchholz","BB"),
("DEW155J5CD","DE","Markkleeberg","SN"),
("DES893NR0F","DE","Markneukirchen","SN"),
("DETSDKPS0K","DE","Markranstädt","SN"),
("DE5YBNDR69","DE","Marktbreit","BY"),
("DETCFDIRQA","DE","Marktheidenfeld","BY"),
("DE0ZENQE3J","DE","Marktleuthen","BY"),
("DE6G4W85GE","DE","Marktoberdorf","BY"),
("DE3R2GJ8QD","DE","Marktredwitz","BY"),
("DEL5Q3XGDX","DE","Marktsteft","BY"),
("DEGSL66OQD","DE","Marl","NW"),
("DE4V9D0PR3","DE","Marlow","MV"),
("DEHTJ029DO","DE","Marne","SH"),
("DEF4RCL5A1","DE","Marsberg","NW"),
("DEXV84JZHN","DE","Maulbronn","BW"),
("DEUQ0UFSXW","DE","Maxhütte-Haidhof","BY"),
("DEMHXPRAD6","DE","Mayen","RP"),
("DEF5I0AS28","DE","Mechernich","NW"),
("DEOBC7BTV5","DE","Meckenheim","NW"),
("DEJW0ZOXVB","DE","Medebach","NW"),
("DEFS063DCJ","DE","Meerane","SN"),
("DEIVKTNM1B","DE","Meerbusch","NW"),
("DEYDJ97EEQ","DE","Meersburg","BW"),
("DEAFPZCLAS","DE","Meinerzhagen","NW"),
("DEEAYIOB17","DE","Meiningen","TH"),
("DE6L0U8166","DE","Meisenheim","RP"),
("DEFPFN4UDF","DE","Meißen","SN"),
("DE93FMPPF3","DE","Meldorf","SH"),
("DE0DLPONWV","DE","Melle","NI"),
("DE8WPGYWNE","DE","Mellrichstadt","BY"),
("DEL31QYF68","DE","Melsungen","HE"),
("DEJLU8A9CB","DE","Memmingen","BY"),
("DENY0CMX8U","DE","Menden/Sauerland","NW"),
("DEUXBSUZ7G","DE","Mendig","RP"),
("DE2960PC88","DE","Mengen","BW"),
("DEX3H8DUK1","DE","Meppen","NI"),
("DESLEEIM9C","DE","Merkendorf","BY"),
("DEKL5EKDUM","DE","Merseburg","ST"),
("DEM1NBEVKB","DE","Merzig","SL"),
("DEZ1KDV5EO","DE","Meschede","NW"),
("DEQS39ECMY","DE","Meßkirch","BW"),
("DEXSDH574S","DE","Meßstetten","BW"),
("DE9R4NNOZN","DE","Mettmann","NW"),
("DEQJ0MPEAG","DE","Metzingen","BW"),
("DE7DPLQCKO","DE","Meuselwitz","TH"),
("DE4X5A5A2E","DE","Meyenburg","BB"),
("DE271PW1DM","DE","Michelstadt","HE"),
("DEKD9ASJQZ","DE","Miesbach","BY"),
("DEXFKOS5CW","DE","Miltenberg","BY"),
("DE3I68T9NV","DE","Mindelheim","BY"),
("DEGPLCQYZB","DE","Minden","NW"),
("DEB8L3SB2Q","DE","Mirow","MV"),
("DERNEJSRFV","DE","Mittenwalde","BB"),
("DE9M42VSYC","DE","Mitterteich","BY"),
("DEHJO7HNJT","DE","Mittweida","SN"),
("DEV4WNGZE7","DE","Möckern","ST"),
("DENSRGJ7CT","DE","Möckmühl","BW"),
("DETHWP9U1Q","DE","Moers","NW"),
("DEDQYVEHOA","DE","Mölln","SH"),
("DEMLY2LCA8","DE","Mönchengladbach","NW"),
("DE41PO91H3","DE","Monheim","BY"),
("DEIETR8UIM","DE","Monheim am Rhein","NW"),
("DELGHZY59K","DE","Monschau","NW"),
("DEQ7NCJXKO","DE","Montabaur","RP"),
("DEZ9C9BUCT","DE","Moosburg an der Isar","BY"),
("DE85LH033L","DE","Mörfelden-Walldorf","HE"),
("DEKKLIQV3H","DE","Moringen","NI"),
("DE3RTMOEBO","DE","Mosbach","BW"),
("DEONXZIATR","DE","Mössingen","BW"),
("DEFF8GIC23","DE","Mücheln/Geiseltal","ST"),
("DEXNMNIP5L","DE","Mügeln","SN"),
("DEGZ85DJU2","DE","Mühlacker","BW"),
("DE7S2Q2VHI","DE","Mühlberg/Elbe","BB"),
("DEBPYU10XY","DE","Mühldorf am Inn","BY"),
("DENJM69RSQ","DE","Mühlhausen/Thüringen","TH"),
("DER1W5LQ7T","DE","Mühlheim am Main","HE"),
("DEJ9JL503G","DE","Mühlheim an der Donau","BW"),
("DEQ1AS18QP","DE","Mülheim an der Ruhr","NW"),
("DESDW25PSW","DE","Mülheim-Kärlich","RP"),
("DEQP1CG95Z","DE","Müllheim","BW"),
("DEIOKOPO5F","DE","Müllrose","BB"),
("DEQG7SOYHH","DE","Münchberg","BY"),
("DEBEJH3BDU","DE","Müncheberg","BB"),
("DE1F6HOCG7","DE","München","BY"),
("DE01VPQ15G","DE","Münchenbernsdorf","TH"),
("DEHC86BQNM","DE","Munderkingen","BW"),
("DE4648II2J","DE","Münnerstadt","BY"),
("DEX91MLITL","DE","Münsingen","BW"),
("DEKPBARGR8","DE","Munster","NI"),
("DETZE4Q2RU","DE","Münster","NW"),
("DE8W3QE5AC","DE","Münstermaifeld","RP"),
("DEEBY0TSMD","DE","Münzenberg","HE"),
("DEIXO9EFH8","DE","Murrhardt","BW"),
("DEFWD5Y507","DE","Mylau","SN"),
("DE13XF98RO","DE","Nabburg","BY"),
("DEJQODIAR0","DE","Nagold","BW"),
("DE8F9NVRVA","DE","Naila","BY"),
("DEO9GMEGTG","DE","Nassau","RP"),
("DEKRVTZNHJ","DE","Nastätten","RP"),
("DED6XWHOWP","DE","Nauen","BB"),
("DE46DZY9AM","DE","Naumburg","HE"),
("DEIQ9X72DR","DE","Naumburg/Saale","ST"),
("DEU8LTW3D9","DE","Naunhof","SN"),
("DE9A5QZ2G3","DE","Nebra/Unstrut","ST"),
("DE9T382DUK","DE","Neckarbischofsheim","BW"),
("DE33IA6V20","DE","Neckargemünd","BW"),
("DE4NU0Q7AZ","DE","Neckarsteinach","HE"),
("DEIFQHI7LS","DE","Neckarsulm","BW"),
("DE0O031UN5","DE","Neresheim","BW"),
("DEY6F41I55","DE","Netphen","NW"),
("DE5Z5V7FVP","DE","Nettetal","NW"),
("DEVM7ETS6T","DE","Netzschkau","SN"),
("DEG6WI1KN0","DE","Neu-Anspach","HE"),
("DEQ35RLAXQ","DE","Neu-Isenburg","HE"),
("DEA2MHIH6D","DE","Neu-Ulm","BY"),
("DE3ERW6YQN","DE","Neubrandenburg","MV"),
("DE5N578T7Y","DE","Neubukow","MV"),
("DEWCQINO8X","DE","Neubulach","BW"),
("DEQVE9DLNG","DE","Neuburg an der Donau","BY"),
("DEZFD6D4TI","DE","Neudenau","BW"),
("DERZPZSXYP","DE","Neuenbürg","BW"),
("DEAP7XDGV4","DE","Neuenburg am Rhein","BW"),
("DEBADOW05V","DE","Neuenhaus","NI"),
("DEFJ2TNVCF","DE","Neuenrade","NW"),
("DEU1FNZEC9","DE","Neuenstadt am Kocher","BW"),
("DE3J7H02LB","DE","Neuenstein","BW"),
("DEDZ09055G","DE","Neuerburg","RP"),
("DEO79C2LSX","DE","Neuffen","BW"),
("DEN7LMLXWP","DE","Neuhaus am Rennweg","TH"),
("DEH46H6SSK","DE","Neukalen","MV"),
("DERTTSYY8N","DE","Neukirchen","HE"),
("DE5H082S6Q","DE","Neukirchen-Vluyn","NW"),
("DE0RDMO9B5","DE","Neukloster","MV"),
("DEDINKBG42","DE","Neumark","TH"),
("DE9YU8W2W2","DE","Neumarkt in der Oberpfalz","BY"),
("DEKWANPGDQ","DE","Neumarkt-Sankt Veit","BY"),
("DE7QCW0O2D","DE","Neumünster","SH"),
("DE7PYI53LE","DE","Neunburg vorm Wald","BY"),
("DE1GNXJJZ3","DE","Neunkirchen","SL"),
("DEGAQ6Q4WY","DE","Neuötting","BY"),
("DEU9UUYX85","DE","Neuruppin","BB"),
("DEM7OSA97B","DE","Neusalza-Spremberg","SN"),
("DEPU88E8BU","DE","Neusäß","BY"),
("DEI2196X71","DE","Neuss","NW"),
("DE72W505BM","DE","Neustadt","HE"),
("DECZEM8LXX","DE","Neustadt am Kulm","BY"),
("DEG66UFIPX","DE","Neustadt am Rübenberge","NI"),
("DEKQ7ROFTV","DE","Neustadt an der Aisch","BY"),
("DEIP1IVC57","DE","Neustadt an der Donau","BY"),
("DECJUK5RIM","DE","Neustadt an der Orla","TH"),
("DEYOHD76BS","DE","Neustadt an der Waldnaab","BY"),
("DEWJJLYDHG","DE","Neustadt an der Weinstraße","RP"),
("DE3IZYV457","DE","Neustadt bei Coburg","BY"),
("DEO0RTRAGQ","DE","Neustadt in Holstein","SH"),
("DEZX463FY0","DE","Neustadt in Sachsen","SN"),
("DEYIMXV3EY","DE","Neustadt-Glewe","MV"),
("DELDXGH3N6","DE","Neustadt/Dosse","BB"),
("DE3F0VQGLP","DE","Neustrelitz","MV"),
("DEDPWH5VI4","DE","Neutraubling","BY"),
("DED4297G8T","DE","Neuwied","RP"),
("DEU59C8XIC","DE","Nidda","HE"),
("DEDI73YSTC","DE","Niddatal","HE"),
("DEIQUOLCSZ","DE","Nidderau","HE"),
("DEGV9OBHH5","DE","Nideggen","NW"),
("DENRIWP082","DE","Niebüll","SH"),
("DEIF6H80UQ","DE","Niedenstein","HE"),
("DEQOFB18BI","DE","Nieder-Olm","RP"),
("DE3K6E2OKP","DE","Niederkassel","NW"),
("DEF3L43U7M","DE","Niedernhall","BW"),
("DE9E3IEY84","DE","Niederstetten","BW"),
("DEMOGNWR6Z","DE","Niederstotzingen","BW"),
("DECCEE0Z3G","DE","Nieheim","NW"),
("DE2PL6JSST","DE","Niemegk","BB"),
("DE6WBKUKPH","DE","Nienburg/Saale","ST"),
("DE8555XB49","DE","Nienburg/Weser","NI"),
("DEOJNPIR5L","DE","Nierstein","RP"),
("DEHQR1JJUP","DE","Niesky","SN"),
("DEG5AAQZSY","DE","Nittenau","BY"),
("DE5X4398CX","DE","Norden","NI"),
("DES0MBSRW9","DE","Nordenham","NI"),
("DEIOA185QO","DE","Norderney","NI"),
("DEA1Z10R06","DE","Norderstedt","SH"),
("DEP49YDMV5","DE","Nordhausen","TH"),
("DEMIGF9COS","DE","Nordhorn","NI"),
("DE1ZT94KXF","DE","Nördlingen","BY"),
("DELWGMOGSD","DE","Northeim","NI"),
("DEL2BYO73B","DE","Nortorf","SH"),
("DEPJQZWERX","DE","Nossen","SN"),
("DEDK6I53XQ","DE","Nürnberg","BY"),
("DE0DDOU52F","DE","Nürtingen","BW"),
("DE8DEWKH79","DE","Ober-Ramstadt","HE"),
("DE0X8XC0UQ","DE","Oberasbach","BY"),
("DEK08Q46G5","DE","Oberharz am Brocken","ST"),
("DEJTUEZWU7","DE","Oberhausen","NW"),
("DE984UPB4Q","DE","Oberhof","TH"),
("DE9DNMDICY","DE","Oberkirch","BW"),
("DEILONR4SB","DE","Oberkochen","BW"),
("DEYMQYIK6S","DE","Oberlungwitz","SN"),
("DETAMJMRAW","DE","Obermoschel","RP"),
("DE4XIHFVFY","DE","Obernburg am Main","BY"),
("DEH3L98EK7","DE","Oberndorf am Neckar","BW"),
("DE0A6JVCBP","DE","Obernkirchen","NI"),
("DENY8AQI7U","DE","Oberriexingen","BW"),
("DEGQCWLRV3","DE","Obertshausen","HE"),
("DEVGC3VWBV","DE","Oberursel/Taunus","HE"),
("DE7HF3TRSH","DE","Oberviechtach","BY"),
("DEP1SGJZA0","DE","Oberweißbach/Thür. Wald","TH"),
("DEPMWBESE9","DE","Oberwesel","RP"),
("DE9QD4NOZU","DE","Oberwiesenthal","SN"),
("DE5EYZ5RGV","DE","Ochsenfurt","BY"),
("DES8BB7MCX","DE","Ochsenhausen","BW"),
("DE898M1MWA","DE","Ochtrup","NW"),
("DEC9EZXEU2","DE","Oderberg","BB"),
("DETT2YKIUC","DE","Oebisfelde-Weferlingen","ST"),
("DER6OZS1W1","DE","Oederan","SN"),
("DEA4OBRKM3","DE","Oelde","NW"),
("DEU03REYU7","DE","Oelsnitz/Erzgeb.","SN"),
("DESW6CF1P7","DE","Oelsnitz/Vogtl.","SN"),
("DE8E60F32P","DE","Oer-Erkenschwick","NW"),
("DE8R1ZCN36","DE","Oerlinghausen","NW"),
("DEN6Y25TAX","DE","Oestrich-Winkel","HE"),
("DEQHA5JZDR","DE","Oettingen in Bayern","BY"),
("DEDKRSNUHW","DE","Offenbach am Main","HE"),
("DELJVX6Y3U","DE","Offenburg","BW"),
("DE52XBV78L","DE","Ohrdruf","TH"),
("DEPIR8I4ZV","DE","Öhringen","BW"),
("DEOROCM697","DE","Olbernhau","SN"),
("DEP45W39Q9","DE","Olching","BY"),
("DEBNK6VTSL","DE","Oldenburg in Holstein","SH"),
("DECJTUNTQC","DE","Oldenburg/Oldb","NI"),
("DELEP7LYFA","DE","Olfen","NW"),
("DE2K66UXF5","DE","Olpe","NW"),
("DEL0CGT415","DE","Olsberg","NW"),
("DENV0BPQNB","DE","Oppenau","BW"),
("DE5CIQBY1E","DE","Oppenheim","RP"),
("DEJ8KD50JQ","DE","Oranienbaum-Wörlitz","ST"),
("DE0W7T19ZP","DE","Oranienburg","BB"),
("DE5Z0UPO5V","DE","Orlamünde","TH"),
("DE1OLCNMQ6","DE","Ornbau","BY"),
("DEUBK0B4QC","DE","Ortenberg","HE"),
("DE1X6365SC","DE","Ortrand","BB"),
("DE5T6VICQJ","DE","Oschatz","SN"),
("DE1BWOYNVT","DE","Oschersleben/Bode","ST"),
("DEZGTBLKNM","DE","Osnabrück","NI"),
("DEHTQOZI05","DE","Osterburg/Altmark","ST"),
("DEB70TKQDL","DE","Osterburken","BW"),
("DE2AA1X6UW","DE","Osterfeld","ST"),
("DEMN887VVP","DE","Osterhofen","BY"),
("DEPLEP3FUF","DE","Osterholz-Scharmbeck","NI"),
("DENV97MMSO","DE","Osterode am Harz","NI"),
("DEW3QU9KRW","DE","Osterwieck","ST"),
("DE8Z4GVZ5L","DE","Ostfildern","BW"),
("DEKKAN053N","DE","Ostheim vor der Rhön","BY"),
("DE0CUMZNBV","DE","Osthofen","RP"),
("DER1Q0MIWU","DE","Östringen","BW"),
("DEH0AD0GYK","DE","Ostritz","SN"),
("DE0880DBOE","DE","Otterberg","RP"),
("DEOJ1N7CJY","DE","Otterndorf","NI"),
("DEE9Z0RVV9","DE","Ottweiler","SL"),
("DEW5NWLLGM","DE","Overath","NW"),
("DEUPN80CMO","DE","Owen","BW"),
("DEVNC20V1F","DE","Paderborn","NW"),
("DE40GWVB6S","DE","Papenburg","NI"),
("DEHTO2F5P9","DE","Pappenheim","BY"),
("DEUDHVP4KK","DE","Parchim","MV"),
("DESWNTRO8W","DE","Parsberg","BY"),
("DEPPTL0ZDH","DE","Pasewalk","MV"),
("DET2K97AI2","DE","Passau","BY"),
("DEN0XC4HXX","DE","Pattensen","NI"),
("DEDKQ49Z0Z","DE","Pausa-Mühltroff","SN"),
("DEOTKOTX6N","DE","Pegau","SN"),
("DEZRW71F9O","DE","Pegnitz","BY"),
("DEF61KOYH1","DE","Peine","NI"),
("DEJ85T76SV","DE","Peitz","BB"),
("DE0DKUBRHB","DE","Penig","SN"),
("DEIDIKSS98","DE","Penkun","MV"),
("DEYBSMAAOT","DE","Penzberg","BY"),
("DEIUNQ1GM1","DE","Penzlin","MV"),
("DET6V4YDFH","DE","Perleberg","BB"),
("DERY1JQBSP","DE","Petershagen","NW"),
("DEMKCWV0QD","DE","Pfaffenhofen an der Ilm","BY"),
("DEVE4WUQXO","DE","Pfarrkirchen","BY"),
("DEXTTV69CX","DE","Pforzheim","BW"),
("DE7EHYQ9OC","DE","Pfreimd","BY"),
("DEU09Q1Z4W","DE","Pfullendorf","BW"),
("DEE8T8YQXV","DE","Pfullingen","BW"),
("DEKQQR03O8","DE","Pfungstadt","HE"),
("DEI668GULA","DE","Philippsburg","BW"),
("DEVU1XU5U8","DE","Pinneberg","SH"),
("DEDNHBEF6Y","DE","Pirmasens","RP"),
("DE6XP61EEJ","DE","Pirna","SN"),
("DEKLS0GDBB","DE","Plattling","BY"),
("DE8C83H2CU","DE","Plau am See","MV"),
("DEPU639D2F","DE","Plaue","TH"),
("DEARLB60VQ","DE","Plauen","SN"),
("DELNR112DA","DE","Plettenberg","NW"),
("DEFLDWOQRE","DE","Pleystein","BY"),
("DEKYITBK9L","DE","Plochingen","BW"),
("DECUXIVS9G","DE","Plön","SH"),
("DEG0II2VSH","DE","Pockau-Lengefeld","SN"),
("DEH6E5W6KH","DE","Pocking","BY"),
("DE42BFMK1Z","DE","Pohlheim","HE"),
("DEFZIARRR8","DE","Polch","RP"),
("DER9QT5JBM","DE","Porta Westfalica","NW"),
("DEPPSMWC30","DE","Pößneck","TH"),
("DEEEG1ZH1E","DE","Potsdam","BB"),
("DEGJP8AGH1","DE","Pottenstein","BY"),
("DEQ7VVQ6HG","DE","Preetz","SH"),
("DEWA3SM6T1","DE","Premnitz","BB"),
("DEL92LR4Z8","DE","Prenzlau","BB"),
("DENOGX5XZV","DE","Pressath","BY"),
("DE5VQW18CY","DE","Preußisch Oldendorf","NW"),
("DEJFR5MK68","DE","Prichsenstadt","BY"),
("DET9ULDTT1","DE","Pritzwalk","BB"),
("DEI9ZN7YJD","DE","Prüm","RP"),
("DET99VIMU1","DE","Puchheim","BY"),
("DE2L7P5EYZ","DE","Pulheim","NW"),
("DEOSK1MD34","DE","Pulsnitz","SN"),
("DEN2SV1B8V","DE","Putbus","MV"),
("DELIR45L57","DE","Putlitz","BB"),
("DE6DXCRVCF","DE","Püttlingen","SL"),
("DENWH9AKEY","DE","Quakenbrück","NI"),
("DEN6TOI2K3","DE","Quedlinburg","ST"),
("DELB7QWDY3","DE","Querfurt","ST"),
("DERVFIRRYF","DE","Quickborn","SH"),
("DEOFPZ03XO","DE","Rabenau","SN"),
("DEARDSUXWF","DE","Radeberg","SN"),
("DE8465H489","DE","Radebeul","SN"),
("DE0ORRGQ65","DE","Radeburg","SN"),
("DE6V47Y2V9","DE","Radevormwald","NW"),
("DEU82O5Y3E","DE","Radolfzell am Bodensee","BW"),
("DE39JLESUE","DE","Raguhn-Jeßnitz","ST"),
("DEGL5WCB2I","DE","Rahden","NW"),
("DE76P69KF3","DE","Rain","BY"),
("DETHRYGVDJ","DE","Ramstein-Miesenbach","RP"),
("DE5X4JPZX6","DE","Ranis","TH"),
("DEL33XF5FM","DE","Ransbach-Baumbach","RP"),
("DEC4SLP7OI","DE","Rastatt","BW"),
("DEPGH6BVQG","DE","Rastenberg","TH"),
("DESV0HUYOF","DE","Rathenow","BB"),
("DE1RDGWS28","DE","Ratingen","NW"),
("DEXUUN2I5S","DE","Ratzeburg","SH"),
("DEYNZAIQRA","DE","Rauenberg","BW"),
("DELRSGPHWR","DE","Raunheim","HE"),
("DE89752AD0","DE","Rauschenberg","HE"),
("DE58N8QT1P","DE","Ravensburg","BW"),
("DEG00ZRRAD","DE","Ravenstein","BW"),
("DEJ3T9KQ0S","DE","Recklinghausen","NW"),
("DE08X3JB3O","DE","Rees","NW"),
("DEKQXBKY01","DE","Regen","BY"),
("DEZ10QTB4C","DE","Regensburg","BY"),
("DEEXMYONRO","DE","Regis-Breitingen","SN"),
("DEWPRF1V4L","DE","Rehau","BY"),
("DEM1W60X70","DE","Rehburg-Loccum","NI"),
("DEY8RRJV4X","DE","Rehna","MV"),
("DETRWHEO6A","DE","Reichelsheim/Wetterau","HE"),
("DEDYQETU0G","DE","Reichenbach im Vogtland","SN"),
("DEWWMXUUYS","DE","Reichenbach/O.L.","SN"),
("DE3PKNKPLE","DE","Reinbek","SH"),
("DEGHWV526J","DE","Reinfeld/Holstein","SH"),
("DE1WYVRYBO","DE","Reinheim","HE"),
("DEVYMPTKIW","DE","Remagen","RP"),
("DE93JUS589","DE","Remda-Teichel","TH"),
("DEM55S7BB9","DE","Remscheid","NW"),
("DE8A4Z8GO4","DE","Remseck am Neckar","BW"),
("DEFAT8VC54","DE","Renchen","BW"),
("DEFPZ8U8HH","DE","Rendsburg","SH"),
("DEDM9LYLU6","DE","Rennerod","RP"),
("DEVZ54FU9V","DE","Renningen","BW"),
("DE5230F94U","DE","Rerik","MV"),
("DEZ43TCKBP","DE","Rethem/Aller","NI"),
("DE7LA564C2","DE","Reutlingen","BW"),
("DE4I7KCGFH","DE","Rheda-Wiedenbrück","NW"),
("DEJJHYTMTS","DE","Rhede","NW"),
("DEQWM2HXRP","DE","Rheinau","BW"),
("DEI2VP67SA","DE","Rheinbach","NW"),
("DEPZV1GAJ0","DE","Rheinberg","NW"),
("DET0YMMSFD","DE","Rheinböllen","RP"),
("DEP1F6Z7WI","DE","Rheine","NW"),
("DE9R7GY0RO","DE","Rheinfelden/Baden","BW"),
("DE0MQGW9GQ","DE","Rheinsberg","BB"),
("DEAFDX8TAX","DE","Rheinstetten","BW"),
("DEUQ4UX0C6","DE","Rhens","RP"),
("DERJMQKEEK","DE","Rhinow","BB"),
("DE040XEHNO","DE","Ribnitz-Damgarten","MV"),
("DEX1L5UW2P","DE","Richtenberg","MV"),
("DEM6JJ6VQY","DE","Riedenburg","BY"),
("DEFDOZR3JS","DE","Riedlingen","BW"),
("DE8KPM2DBZ","DE","Riedstadt","HE"),
("DEEX49T7YF","DE","Rieneck","BY"),
("DEDHZKDQIS","DE","Riesa","SN"),
("DE37SVBBNJ","DE","Rietberg","NW"),
("DEWC6YPIY4","DE","Rinteln","NI"),
("DEF3D8ABOO","DE","Röbel/Müritz","MV"),
("DETN87ERZH","DE","Rochlitz","SN"),
("DEZRDA30U0","DE","Rockenhausen","RP"),
("DED0Z2IX7Y","DE","Rodalben","RP"),
("DE0K6BWVZQ","DE","Rodenberg","NI"),
("DEJ7XXZXFY","DE","Rödental","BY"),
("DEOS9ST3T6","DE","Rödermark","HE"),
("DE4S9NQGLQ","DE","Rodewisch","SN"),
("DE1S2YN1O6","DE","Rodgau","HE"),
("DE9L38JI77","DE","Roding","BY"),
("DEBG04KTBO","DE","Römhild","TH"),
("DEMKBC1W32","DE","Romrod","HE"),
("DEP51C6PIF","DE","Ronneburg","TH"),
("DEBMOU5V2G","DE","Ronnenberg","NI"),
("DEC3LWWWKI","DE","Rosbach vor der Höhe","HE"),
("DEHWVITYLI","DE","Rosenfeld","BW"),
("DE3MU9CDPN","DE","Rosenheim","BY"),
("DE0DI59LLL","DE","Rosenthal","HE"),
("DEO7IL334K","DE","Rösrath","NW"),
("DEZZ3TXPB0","DE","Roßleben","TH"),
("DEB6AOKZCK","DE","Roßwein","SN"),
("DECUPLFB73","DE","Rostock, Hansestadt","MV"),
("DEIPPMST6R","DE","Rotenburg an der Fulda","HE"),
("DESALPZXQB","DE","Rotenburg/Wümme","NI"),
("DE40ZOZB9B","DE","Roth","BY"),
("DE6YXLA4PT","DE","Rötha","SN"),
("DEUEFM7LE0","DE","Röthenbach an der Pegnitz","BY"),
("DEWZPVWF60","DE","Rothenburg ob der Tauber","BY"),
("DEF6PFIYQO","DE","Rothenburg/O.L.","SN"),
("DEXO98TZ1N","DE","Rothenfels","BY"),
("DEEG9L2OMY","DE","Rottenburg a.d.Laaber","BY"),
("DEOBUKR1L7","DE","Rottenburg am Neckar","BW"),
("DE7BMPADD7","DE","Röttingen","BY"),
("DE1NGUNHI1","DE","Rottweil","BW"),
("DEYSN0G9Z4","DE","Rötz","BY"),
("DEKTPCUBK2","DE","Rüdesheim am Rhein","HE"),
("DEM6SXK65L","DE","Rudolstadt","TH"),
("DETLGG3ZI1","DE","Ruhla","TH"),
("DER527E1CZ","DE","Ruhland","BB"),
("DEV2BPDWS0","DE","Runkel","HE"),
("DE2KXMQ28K","DE","Rüsselsheim","HE"),
("DEOP1RPJSG","DE","Rutesheim","BW"),
("DEPUO3W12R","DE","Rüthen","NW"),
("DE3EHHA9HD","DE","Saalburg-Ebersdorf","TH"),
("DEUF0KI956","DE","Saalfeld/Saale","TH"),
("DEZ7YOQQ5G","DE","Saarbrücken","SL"),
("DELTJHVM8Y","DE","Saarburg","RP"),
("DE0QGBZXPT","DE","Saarlouis","SL"),
("DEDPEWYK3Y","DE","Sachsenhagen","NI"),
("DER1MISRYD","DE","Sachsenheim","BW"),
("DELHVH44F4","DE","Salzgitter","NI"),
("DEUWGTT5N7","DE","Salzkotten","NW"),
("DEU23TM6RD","DE","Salzwedel, Hansestadt","ST"),
("DE8EV06UER","DE","Sandau/Elbe","ST"),
("DEB98FDOK8","DE","Sandersdorf-Brehna","ST"),
("DEK12E6PM1","DE","Sangerhausen","ST"),
("DESQVEWMR4","DE","Sankt Augustin","NW"),
("DE1N57HJYT","DE","Sankt Goar","RP"),
("DES796WUFH","DE","Sankt Goarshausen","RP"),
("DEVHW27I3Z","DE","Sarstedt","NI"),
("DE9ZD5L5AM","DE","Sassenberg","NW"),
("DETFUBYS5R","DE","Sassnitz","MV"),
("DE0EYX9DF5","DE","Sayda","SN"),
("DEUB72UB13","DE","Schalkau","TH"),
("DEAF9WLKJF","DE","Schauenstein","BY"),
("DE0DQY6VQ7","DE","Scheer","BW"),
("DEAO5K1KPW","DE","Scheibenberg","SN"),
("DEWXYR80UJ","DE","Scheinfeld","BY"),
("DEF4G1O0GO","DE","Schelklingen","BW"),
("DEE6NL2ESD","DE","Schenefeld","SH"),
("DE2XX4IN1E","DE","Scheßlitz","BY"),
("DEK05T00DG","DE","Schieder-Schwalenberg","NW"),
("DE5UHTUXI9","DE","Schifferstadt","RP"),
("DE46U6KNKN","DE","Schillingsfürst","BY"),
("DEKIS35UHQ","DE","Schiltach","BW"),
("DEUNJUNXBS","DE","Schirgiswalde-Kirschau","SN"),
("DERSMLQ5VU","DE","Schkeuditz","SN"),
("DEBP1WCLKX","DE","Schkölen","TH"),
("DE3C096IZ1","DE","Schleiden","NW"),
("DE5JVTG6M7","DE","Schleiz","TH"),
("DEZ9TPEOKQ","DE","Schleswig","SH"),
("DEDLMQ77NB","DE","Schlettau","SN"),
("DEJNKQ6KRB","DE","Schleusingen","TH"),
("DE3N5JURQT","DE","Schlieben","BB"),
("DE1KJF835M","DE","Schlitz","HE"),
("DEOSCV0Z7J","DE","Schloß Holte-Stukenbrock","NW"),
("DENRATB25F","DE","Schlotheim","TH"),
("DEPAYJ2OD3","DE","Schlüchtern","HE"),
("DE8WJHZP3O","DE","Schlüsselfeld","BY"),
("DEIFJIER22","DE","Schmalkalden","TH"),
("DEJCVVE0A4","DE","Schmallenberg","NW"),
("DEB8OEX1I6","DE","Schmölln","TH"),
("DEX2NXRRL9","DE","Schnackenburg","NI"),
("DE65SLWUNF","DE","Schnaittenbach","BY"),
("DE7IAMJKQV","DE","Schneeberg","SN"),
("DETFAQGSXE","DE","Schneverdingen","NI"),
("DEVKBMBXWI","DE","Schömberg","BW"),
("DE2P3YJQER","DE","Schönau","BW"),
("DE9PDTA4O3","DE","Schönau im Schwarzwald","BW"),
("DEKZU0RREN","DE","Schönberg","MV"),
("DEBQ9NN65P","DE","Schönebeck/Elbe","ST"),
("DEV9OF0369","DE","Schöneck/Vogtl.","SN"),
("DESK22PR69","DE","Schönewalde","BB"),
("DEQ0AIRP52","DE","Schongau","BY"),
("DEFFQ3LWTH","DE","Schöningen","NI"),
("DE5IW6L2FE","DE","Schönsee","BY"),
("DENIGCANM1","DE","Schönwald","BY"),
("DENWKELQH1","DE","Schopfheim","BW"),
("DE574R4X8A","DE","Schöppenstedt","NI"),
("DEG4G17WFU","DE","Schorndorf","BW"),
("DEFW7QKTR7","DE","Schortens","NI"),
("DEPBLB22C7","DE","Schotten","HE"),
("DEAHZEF7PV","DE","Schramberg","BW"),
("DEC5XJ2CDH","DE","Schraplau","ST"),
("DE9K7TEZ13","DE","Schriesheim","BW"),
("DEBMFDPRL0","DE","Schrobenhausen","BY"),
("DE8KENR4J4","DE","Schrozberg","BW"),
("DE9GNBT1T2","DE","Schüttorf","NI"),
("DEM0W0ZX4B","DE","Schwaan","MV"),
("DEKJOAA9AJ","DE","Schwabach","BY"),
("DETP7LTQP3","DE","Schwäbisch Gmünd","BW"),
("DE6DEZE820","DE","Schwäbisch Hall","BW"),
("DE8Z08X5JI","DE","Schwabmünchen","BY"),
("DEO8SZH2IB","DE","Schwaigern","BW"),
("DERQWKGMNN","DE","Schwalbach am Taunus","HE"),
("DEZ2MDAPEJ","DE","Schwalmstadt","HE"),
("DEOFSMKC48","DE","Schwandorf","BY"),
("DEKW82YQDP","DE","Schwanebeck","ST"),
("DEHAAXWXLV","DE","Schwarzenbach am Wald","BY"),
("DE079BXOVL","DE","Schwarzenbach an der Saale","BY"),
("DE3N7N0BWK","DE","Schwarzenbek","SH"),
("DE84N6V0WC","DE","Schwarzenberg/Erzgeb.","SN"),
("DEA6A74V24","DE","Schwarzenborn","HE"),
("DE3CF01BM4","DE","Schwarzheide","BB"),
("DEYUSZ6PKE","DE","Schwedt/Oder","BB"),
("DEU7LP7H2I","DE","Schweich","RP"),
("DENDPR8SWC","DE","Schweinfurt","BY"),
("DE5CD6NZBM","DE","Schwelm","NW"),
("DEU3L0T5FN","DE","Schwentinental","SH"),
("DEC0CKHF24","DE","Schwerin","MV"),
("DESSW0KSDP","DE","Schwerte","NW"),
("DE4QWSQ7EK","DE","Schwetzingen","BW"),
("DEBZK44ZRH","DE","Sebnitz","SN"),
("DE031HI3MB","DE","Seehausen/Altmark","ST"),
("DEVIBGBP6G","DE","Seeland","ST"),
("DEF2859MPK","DE","Seelow","BB"),
("DEMAOQAG7A","DE","Seelze","NI"),
("DEK9S3CEE8","DE","Seesen","NI"),
("DEXQP9FVPU","DE","Sehnde","NI"),
("DEXY07KQS7","DE","Seifhennersdorf","SN"),
("DE1HYBX6MH","DE","Selb","BY"),
("DEFFKSUY0R","DE","Selbitz","BY"),
("DEOP03LQYJ","DE","Seligenstadt","HE"),
("DEOYQ9PJGQ","DE","Selm","NW"),
("DE0E2XKOF0","DE","Selters/Westerwald","RP"),
("DE4ZSYYSPN","DE","Senden","BY"),
("DEIQR4GPN5","DE","Sendenhorst","NW"),
("DEOEEEXV4X","DE","Senftenberg","BB"),
("DEA6VVVBVZ","DE","Seßlach","BY"),
("DEBNX9FNWY","DE","Siegburg","NW"),
("DEEO2VDQ02","DE","Siegen","NW"),
("DE4FG2ALZK","DE","Sigmaringen","BW"),
("DERVFN6BMH","DE","Simbach am Inn","BY"),
("DEYKRE8OCM","DE","Simmern/Hunsrück","RP"),
("DECFHQ6ISA","DE","Sindelfingen","BW"),
("DEX9C8UCTM","DE","Singen/Hohentwiel","BW"),
("DE899EKWWI","DE","Sinsheim","BW"),
("DEGNWPC9BO","DE","Sinzig","RP"),
("DEPTEVC76A","DE","Soest","NW"),
("DEHIICVBY3","DE","Solingen","NW"),
("DEL8I54FNL","DE","Solms","HE"),
("DE3KBFTM4I","DE","Soltau","NI"),
("DEGJESQK38","DE","Sömmerda","TH"),
("DE3LKYXJ2I","DE","Sondershausen","TH"),
("DESLOX0CI4","DE","Sonneberg","TH"),
("DEWUJQHN9X","DE","Sonnewalde","BB"),
("DE6NQX7T6B","DE","Sonthofen","BY"),
("DEFR9DACV2","DE","Sontra","HE"),
("DEXKZYWI2T","DE","Spaichingen","BW"),
("DECMJT9TRG","DE","Spalt","BY"),
("DEGIEOCLZR","DE","Spangenberg","HE"),
("DEC95ML0PJ","DE","Speicher/Eifel","RP"),
("DEKPHH7KAK","DE","Spenge","NW"),
("DE6UEGN5X3","DE","Speyer","RP"),
("DEOBS1WRS9","DE","Spremberg","BB"),
("DE1YVMYL6J","DE","Springe","NI"),
("DEAO1H8B2E","DE","Sprockhövel","NW"),
("DE5GUSMSWB","DE","St. Blasien","BW"),
("DE3OC0G59H","DE","St. Georgen im Schwarzwald","BW"),
("DE3541QBL0","DE","St. Ingbert","SL"),
("DEZMI7YLM3","DE","St. Wendel","SL"),
("DE1HWO9SZD","DE","Stade","NI"),
("DEHBEYGOFJ","DE","Stadt Wehlen","SN"),
("DETKLKV7LV","DE","Stadtallendorf","HE"),
("DET43SPQVR","DE","Stadtbergen","BY"),
("DE7SFHLEV2","DE","Stadthagen","NI"),
("DEQ916XGQR","DE","Stadtilm","TH"),
("DE1BCXJXSD","DE","Stadtlengsfeld","TH"),
("DE2V5RL1IT","DE","Stadtlohn","NW"),
("DETYBEC6H2","DE","Stadtoldendorf","NI"),
("DEGI9DZZ50","DE","Stadtprozelten","BY"),
("DEBIYUFQ7I","DE","Stadtroda","TH"),
("DEMD98ES27","DE","Stadtsteinach","BY"),
("DEQDL3K360","DE","Starnberg","BY"),
("DELGEKGKLR","DE","Staßfurt","ST"),
("DE2JMHAU0X","DE","Staufen im Breisgau","BW"),
("DE796L28TT","DE","Staufenberg","HE"),
("DEMEX6H363","DE","Stavenhagen","MV"),
("DEJLNZ59R7","DE","Stein","BY"),
("DESEP38P0G","DE","Steinach","TH"),
("DEZ721FVV2","DE","Steinau an der Straße","HE"),
("DEAS8SWFVG","DE","Steinbach-Hallenberg","TH"),
("DE1JG6S7DL","DE","Steinbach/Taunus","HE"),
("DEM2OUSPBR","DE","Steinfurt","NW"),
("DEWDTC9OEJ","DE","Steinheim","NW"),
("DEHNCD38U4","DE","Steinheim an der Murr","BW"),
("DERAAKIO54","DE","Stendal","ST"),
("DERUYJJABG","DE","Sternberg","MV"),
("DEO4TXT7HB","DE","Stockach","BW"),
("DEVUPZ2J3U","DE","Stolberg/Rheinland","NW"),
("DETEEB3KFU","DE","Stollberg/Erzgeb.","SN"),
("DEEEDYOPED","DE","Stolpen","SN"),
("DET7ANFSYB","DE","Storkow/Mark","BB"),
("DEMNAO6EI0","DE","Stößen","ST"),
("DESXCVHRQV","DE","Straelen","NW"),
("DE64TVT88M","DE","Stralsund, Hansestadt","MV"),
("DEGJ9WB87X","DE","Strasburg/Uckermark","MV"),
("DEVIM2W52P","DE","Straubing","BY"),
("DE2FLJ6BFD","DE","Strausberg","BB"),
("DEF989HGVY","DE","Strehla","SN"),
("DEZ5UBD289","DE","Stromberg","RP"),
("DELVCH0F72","DE","Stühlingen","BW"),
("DEUSM142EK","DE","Stutensee","BW"),
("DEBMTT3PR3","DE","Stuttgart","BW"),
("DEVME9PNIA","DE","Südliches Anhalt","ST"),
("DEIVSJAZM4","DE","Suhl","TH"),
("DES85XAJHL","DE","Sulingen","NI"),
("DE6BF906CV","DE","Sulz am Neckar","BW"),
("DETQ5IDNSW","DE","Sulzbach-Rosenberg","BY"),
("DEIKFTK1XC","DE","Sulzbach/Saar","SL"),
("DEA39KNR6T","DE","Sulzburg","BW"),
("DE2M23SFZM","DE","Sundern/Sauerland","NW"),
("DE544JSWGB","DE","Süßen","BW"),
("DEHV41X2D7","DE","Syke","NI"),
("DE5NSTEZMH","DE","Tambach-Dietharz","TH"),
("DELPKE4K0A","DE","Tangerhütte","ST"),
("DEO5UG1ARJ","DE","Tangermünde","ST"),
("DE6WK3YYB4","DE","Tann/Rhön","HE"),
("DEL4X04KIP","DE","Tanna","TH"),
("DE934EN5OB","DE","Tauberbischofsheim","BW"),
("DEAIRCTJVZ","DE","Taucha","SN"),
("DEFF3EEFIZ","DE","Taunusstein","HE"),
("DEJF0NZID9","DE","Tecklenburg","NW"),
("DELIN8NBKX","DE","Tegernsee","BY"),
("DEUC9NV4NB","DE","Telgte","NW"),
("DEKQPY57YP","DE","Teltow","BB"),
("DENZDNHRW3","DE","Templin","BB"),
("DE9JCWVXUP","DE","Tengen","BW"),
("DE93D480GS","DE","Tessin","MV"),
("DEQ5RWDPM0","DE","Teterow","MV"),
("DEOZN6QJA0","DE","Tettnang","BW"),
("DE3NWYKQNT","DE","Teublitz","BY"),
("DEU1Y21EVS","DE","Teuchern","ST"),
("DEKMPXCBX0","DE","Teupitz","BB"),
("DEBL624H28","DE","Teuschnitz","BY"),
("DE4Y6OPUHK","DE","Thale","ST"),
("DEVGMXUIPE","DE","Thalheim/Erzgeb.","SN"),
("DE4EBGQ9H1","DE","Thannhausen","BY"),
("DEUO3Z5679","DE","Tharandt","SN"),
("DE5EXU8FF4","DE","Themar","TH"),
("DEV11QJQ5O","DE","Thum","SN"),
("DE5H5VRMXL","DE","Tirschenreuth","BY"),
("DEB1KG7SQC","DE","Titisee-Neustadt","BW"),
("DE6O7E3MJZ","DE","Tittmoning","BY"),
("DEOKQ8BVWG","DE","Todtnau","BW"),
("DED2C4P9Q0","DE","Töging am Inn","BY"),
("DEAAHI37U9","DE","Tönisvorst","NW"),
("DEV2OZO7ZD","DE","Tönning","SH"),
("DESPL3LIKZ","DE","Torgau","SN"),
("DEKW3A6UAG","DE","Torgelow","MV"),
("DE4RY8ZTHU","DE","Tornesch","SH"),
("DEV6UKEUX6","DE","Traben-Trarbach","RP"),
("DEKJA52U5M","DE","Traunreut","BY"),
("DEQ9XW37D8","DE","Traunstein","BY"),
("DEZCGY5YT1","DE","Trebbin","BB"),
("DE4NLIHJP2","DE","Trebsen/Mulde","SN"),
("DE3Z75UDSK","DE","Treffurt","TH"),
("DEMPHQXVYW","DE","Trendelburg","HE"),
("DE7EUDDOEI","DE","Treuchtlingen","BY"),
("DEC01UKQWO","DE","Treuen","SN"),
("DEQ4TKHL54","DE","Treuenbrietzen","BB"),
("DEBNU8IS4Q","DE","Triberg im Schwarzwald","BW"),
("DE7Z4LNJ3Z","DE","Tribsees","MV"),
("DEJ4U4VQSL","DE","Trier","RP"),
("DEUM5B8AGJ","DE","Triptis","TH"),
("DEXARG3V7B","DE","Trochtelfingen","BW"),
("DEVBWJUZIE","DE","Troisdorf","NW"),
("DE4CJZ3CKX","DE","Trossingen","BW"),
("DEYQ960PPY","DE","Trostberg","BY"),
("DEZHF3CME8","DE","Tübingen","BW"),
("DEYBRTBA8F","DE","Tuttlingen","BW"),
("DENRFQ3ZN2","DE","Twistringen","NI"),
("DEQW8QMYPM","DE","Übach-Palenberg","NW"),
("DEF5PSS40Q","DE","Überlingen","BW"),
("DEFSKR2S6P","DE","Uebigau-Wahrenbrück","BB"),
("DEKMFOM3QC","DE","Ueckermünde","MV"),
("DEZZ2LXS7D","DE","Uelzen","NI"),
("DEXX5Q16GH","DE","Uetersen","SH"),
("DEY180TFQD","DE","Uffenheim","BY"),
("DE151N9S08","DE","Uhingen","BW"),
("DER2UPV22T","DE","Ulm","BW"),
("DEZ7J1E0JC","DE","Ulmen","RP"),
("DE2RDV7499","DE","Ulrichstein","HE"),
("DEABXJ4XRV","DE","Ummerstadt","TH"),
("DE0MKVPNPO","DE","Unkel","RP"),
("DEV9Q9A9MC","DE","Unna","NW"),
("DE10794HIE","DE","Unterschleißheim","BY"),
("DETFXXCPSD","DE","Usedom","MV"),
("DEBD900YPW","DE","Usingen","HE"),
("DE7G5IQSUR","DE","Uslar","NI"),
("DES10XJJBC","DE","Vacha","TH"),
("DEY99BY2OA","DE","Vaihingen an der Enz","BW"),
("DEGYBHW1D4","DE","Vallendar","RP"),
("DEHJM7BGZ4","DE","Varel","NI"),
("DEIZ12JDEH","DE","Vechta","NI"),
("DEMOTKRIV7","DE","Velbert","NW"),
("DEG6PD72IP","DE","Velburg","BY"),
("DEM4WXLW24","DE","Velden","BY"),
("DEW36FHLX3","DE","Velen","NW"),
("DE9RO09J8Q","DE","Vellberg","BW"),
("DEQX3Y0LNM","DE","Vellmar","HE"),
("DEQKKCGMGC","DE","Velten","BB"),
("DEQMS77PBH","DE","Verden/Aller","NI"),
("DEGZIQJQGA","DE","Veringenstadt","BW"),
("DEOK8O6WBX","DE","Verl","NW"),
("DEGV9XIQA8","DE","Versmold","NW"),
("DEC2GKRR28","DE","Vetschau/Spreewald","BB"),
("DEQKYABEKZ","DE","Viechtach","BY"),
("DEZSO5OZ25","DE","Viernheim","HE"),
("DEVC2D2DMF","DE","Viersen","NW"),
("DEF2Z7T2FJ","DE","Villingen-Schwenningen","BW"),
("DEMDTXSEXR","DE","Vilsbiburg","BY"),
("DE6MWVMZ0H","DE","Vilseck","BY"),
("DEB3UDHGSW","DE","Vilshofen an der Donau","BY"),
("DEIS4CUJWH","DE","Visselhövede","NI"),
("DEXQEP4CHA","DE","Vlotho","NW"),
("DEYE6KD62P","DE","Voerde/Niederrhein","NW"),
("DEAX2RDVOW","DE","Vogtsburg im Kaiserstuhl","BW"),
("DENS9IC5Z9","DE","Vohburg an der Donau","BY"),
("DEVEZZQG9P","DE","Vohenstrauß","BY"),
("DEUFA8MCXX","DE","Vöhrenbach","BW"),
("DE90PNVDKJ","DE","Vöhringen","BY"),
("DE5T1IY0RT","DE","Volkach","BY"),
("DEFQT572V1","DE","Völklingen","SL"),
("DEI6A5J72T","DE","Volkmarsen","HE"),
("DE7RH252LB","DE","Vreden","NW"),
("DEVNTUNKO2","DE","Wachenheim an der Weinstraße","RP"),
("DEBH8IK4K3","DE","Wächtersbach","HE"),
("DEAU8U2BN9","DE","Wadern","SL"),
("DE34C96YK2","DE","Waghäusel","BW"),
("DELEX8ZLBA","DE","Wahlstedt","SH"),
("DE3KTOODRZ","DE","Waiblingen","BW"),
("DE80UACHKG","DE","Waibstadt","BW"),
("DEMWPTUAWF","DE","Waischenfeld","BY"),
("DEOTONF0XI","DE","Waldbröl","NW"),
("DEKR695Y9D","DE","Waldeck","HE"),
("DEZ3OBL8R8","DE","Waldenbuch","BW"),
("DE4H1ZRXEF","DE","Waldenburg","SN"),
("DEQ32530OO","DE","Waldenburg","BW"),
("DERVYWU8AT","DE","Waldershof","BY"),
("DEBY4X7W5B","DE","Waldheim","SN"),
("DED6B44QKU","DE","Waldkappel","HE"),
("DETM0XNPMF","DE","Waldkirch","BW"),
("DELKBFSM84","DE","Waldkirchen","BY"),
("DELD1S964N","DE","Waldkraiburg","BY"),
("DEDFSH5CCY","DE","Waldmünchen","BY"),
("DEZDWM2I1N","DE","Waldsassen","BY"),
("DE2D3VZCZK","DE","Waldshut-Tiengen","BW"),
("DEP0CZ7GNK","DE","Walldorf","BW"),
("DEWF21RE0Q","DE","Walldürn","BW"),
("DERWCUFEIH","DE","Wallenfels","BY"),
("DERLDRXCCN","DE","Walsrode","NI"),
("DEDPNK6A52","DE","Waltershausen","TH"),
("DEQ73HM48E","DE","Waltrop","NW"),
("DE0L8GZQYR","DE","Wanfried","HE"),
("DECBJANVY0","DE","Wangen im Allgäu","BW"),
("DELLLRWQTN","DE","Wanzleben-Börde","ST"),
("DEYX4K1DY2","DE","Warburg","NW"),
("DEY7IYXGQA","DE","Waren/Müritz","MV"),
("DES9LF5JGQ","DE","Warendorf","NW"),
("DE52I2SBPR","DE","Warin","MV"),
("DE9UCA7AD6","DE","Warstein","NW"),
("DEHW4FDUQ5","DE","Wassenberg","NW"),
("DE4BLAU210","DE","Wasserburg am Inn","BY"),
("DE4J2XVRO5","DE","Wassertrüdingen","BY"),
("DEL0GSBTZT","DE","Wasungen","TH"),
("DEQ393YZ93","DE","Wedel","SH"),
("DEBUE6WF61","DE","Weener","NI"),
("DEZ8YVZN0L","DE","Wegberg","NW"),
("DEOGE0ADT0","DE","Wegeleben","ST"),
("DEH34F2DJE","DE","Wehr","BW"),
("DE7XK4CQ5C","DE","Weida","TH"),
("DEZ47YS8KG","DE","Weiden in der Oberpfalz","BY"),
("DEOYGZCA0T","DE","Weikersheim","BW"),
("DED49GHSUP","DE","Weil am Rhein","BW"),
("DEPEU25ZF4","DE","Weil der Stadt","BW"),
("DE4M3WUNCJ","DE","Weilburg","HE"),
("DEMTJZ3JTG","DE","Weilheim an der Teck","BW"),
("DEO2W5VRVL","DE","Weilheim in Oberbayern","BY"),
("DE6POBP3FT","DE","Weimar","TH"),
("DEPJQK734T","DE","Weingarten","BW"),
("DEWNT07MHV","DE","Weinheim","BW"),
("DEOE1K5W5B","DE","Weinsberg","BW"),
("DEMTNBW35M","DE","Weinstadt","BW"),
("DEMW7TZBNW","DE","Weismain","BY"),
("DEZGW62D2R","DE","Weißenberg","SN"),
("DER3BX0G8M","DE","Weißenburg in Bayern","BY"),
("DEAWY7Z4TL","DE","Weißenfels","ST"),
("DE01EZD1VC","DE","Weißenhorn","BY"),
("DEHSJK6MBX","DE","Weißensee","TH"),
("DEPMVQ33DD","DE","Weißenstadt","BY"),
("DEZBKZFEKG","DE","Weißenthurm","RP"),
("DEFYGS0B5I","DE","Weißwasser/O.L.","SN"),
("DE4P2ABE81","DE","Weiterstadt","HE"),
("DE03R374H6","DE","Welzheim","BW"),
("DEG26WHQCW","DE","Welzow","BB"),
("DEPSPQ4V88","DE","Wemding","BY"),
("DEKBJWPRXP","DE","Wendlingen am Neckar","BW"),
("DEUOT1TB89","DE","Werben/Elbe","ST"),
("DEEE5V4ISU","DE","Werdau","SN"),
("DEBHKFDSOX","DE","Werder/Havel","BB"),
("DE47TTZRJT","DE","Werdohl","NW"),
("DEFCV9O3I2","DE","Werl","NW"),
("DEIOXN6PHH","DE","Wermelskirchen","NW"),
("DE71XKUMIY","DE","Wernau/Neckar","BW"),
("DEUCST3BNJ","DE","Werne","NW"),
("DEOISCMBE4","DE","Werneuchen","BB"),
("DEZCS629O9","DE","Wernigerode","ST"),
("DEBMU68C52","DE","Wertheim","BW"),
("DEPXWS8JCW","DE","Werther/Westf.","NW"),
("DE249OGOTF","DE","Wertingen","BY"),
("DE0LM3UBC6","DE","Wesel","NW"),
("DEX6C5JI89","DE","Wesenberg","MV"),
("DEF41OOELQ","DE","Wesselburen","SH"),
("DEJUFZI8FJ","DE","Wesseling","NW"),
("DET1MOCZVA","DE","Westerburg","RP"),
("DE67GQPPZ5","DE","Westerstede","NI"),
("DEU1TIFE9Y","DE","Wetter","HE"),
("DE9OYSWDCQ","DE","Wetter/Ruhr","NW"),
("DEEZERY925","DE","Wettin-Löbejün","ST"),
("DEHIV77VD1","DE","Wetzlar","HE"),
("DEW6KCLTBU","DE","Widdern","BW"),
("DEH9NEMZ41","DE","Wiehe","TH"),
("DEYJTWTV2B","DE","Wiehl","NW"),
("DEEYIMTVOQ","DE","Wiesbaden","HE"),
("DE283O2EJJ","DE","Wiesensteig","BW"),
("DEO6YB52C3","DE","Wiesloch","BW"),
("DEL60F22QH","DE","Wiesmoor","NI"),
("DE083U4SL7","DE","Wildau","BB"),
("DE1OV33FNS","DE","Wildberg","BW"),
("DELL3QNGU9","DE","Wildenfels","SN"),
("DEMUOPXF6X","DE","Wildeshausen","NI"),
("DEOASS2D03","DE","Wilhelmshaven","NI"),
("DE2W75BUXW","DE","Wilkau-Haßlau","SN"),
("DEG1N3HHD4","DE","Willebadessen","NW"),
("DEC2T9HZ75","DE","Willich","NW"),
("DEA0YDDZHG","DE","Wilsdruff","SN"),
("DEVOM6JK3Z","DE","Wilster","SH"),
("DELR329G6M","DE","Wilthen","SN"),
("DEJ0V1037A","DE","Windischeschenbach","BY"),
("DE36OH55X0","DE","Windsbach","BY"),
("DETJ7D4BCP","DE","Winnenden","BW"),
("DE3FSCWZYG","DE","Winsen/Luhe","NI"),
("DEZUHZXOA1","DE","Winterberg","NW"),
("DEUYI03G0X","DE","Wipperfürth","NW"),
("DE08A4JNUM","DE","Wirges","RP"),
("DE3MZZLYGL","DE","Wismar, Hansestadt","MV"),
("DESXLQMVSH","DE","Wissen","RP"),
("DEUBHYRIWS","DE","Witten","NW"),
("DER7XAURXX","DE","Wittenberg","ST"),
("DEDXXZVDKO","DE","Wittenberge","BB"),
("DEB5FX17FW","DE","Wittenburg","MV"),
("DEIXUAGQ27","DE","Wittichenau","SN"),
("DEYZHSRFQ4","DE","Wittingen","NI"),
("DECN481OWC","DE","Wittlich","RP"),
("DEUBAWJPS1","DE","Wittmund","NI"),
("DENNC3EFAC","DE","Wittstock/Dosse","BB"),
("DEFS467VBK","DE","Witzenhausen","HE"),
("DEIFTK4PWY","DE","Woldegk","MV"),
("DE16VKWNMJ","DE","Wolfach","BW"),
("DEBYMPDX1S","DE","Wolfenbüttel","NI"),
("DEP6ZX1AHK","DE","Wolfhagen","HE"),
("DEPA4U00S2","DE","Wolframs-Eschenbach","BY"),
("DE7OM4B9NM","DE","Wolfratshausen","BY"),
("DE8ACL7DEX","DE","Wolfsburg","NI"),
("DEJEULOB5E","DE","Wolfstein","RP"),
("DEM98NA1PI","DE","Wolgast","MV"),
("DEPCM1MAOU","DE","Wolkenstein","SN"),
("DEL0GTDVQX","DE","Wolmirstedt","ST"),
("DE9KIXWOCJ","DE","Worms","RP"),
("DEYK69MWRB","DE","Wörrstadt","RP"),
("DE9ECVP1PA","DE","Wörth am Main","BY"),
("DE163F1UDA","DE","Wörth am Rhein","RP"),
("DEEV8BKKUI","DE","Wörth an der Donau","BY"),
("DE51RRYJ37","DE","Wriezen","BB"),
("DEXG3NHTXJ","DE","Wülfrath","NW"),
("DEZ1Y0VBBA","DE","Wunsiedel","BY"),
("DE7JLR4GA9","DE","Wunstorf","NI"),
("DEI21GL4OJ","DE","Wuppertal","NW"),
("DELS62L4LL","DE","Würselen","NW"),
("DE5KM1VXB3","DE","Wurzbach","TH"),
("DEHXVLE5UW","DE","Würzburg","BY"),
("DE7VDT02DL","DE","Wurzen","SN"),
("DEUJOGN91T","DE","Wustrow/Wendland","NI"),
("DEUOUQL6T2","DE","Wyk auf Föhr","SH"),
("DE4ONIUIF2","DE","Xanten","NW"),
("DEETVEV80P","DE","Zahna-Elster","ST"),
("DESO6GY79S","DE","Zarrentin am Schaalsee","MV"),
("DEW4IHACKE","DE","Zehdenick","BB"),
("DE18XVRCY5","DE","Zeil am Main","BY"),
("DE5TK12KRV","DE","Zeitz","ST"),
("DE9XC75L01","DE","Zell am Harmersbach","BW"),
("DEQIJ0U4FV","DE","Zell im Wiesental","BW"),
("DECCR4PP9V","DE","Zell/Mosel","RP"),
("DEJUWMFNIO","DE","Zella-Mehlis","TH"),
("DELUWQGWR6","DE","Zerbst/Anhalt","ST"),
("DEFB7AFM6S","DE","Zeulenroda-Triebes","TH"),
("DEZXWPN5L6","DE","Zeven","NI"),
("DE0HTF5B3R","DE","Ziegenrück","TH"),
("DE50HLW9RB","DE","Zierenberg","HE"),
("DEKYM0LSSL","DE","Ziesar","BB"),
("DEPOBCUWJU","DE","Zirndorf","BY"),
("DEECAKNEBT","DE","Zittau","SN"),
("DEESEB26NM","DE","Zörbig","ST"),
("DE59MR1FCQ","DE","Zossen","BB"),
("DE3O3YKMTY","DE","Zschopau","SN"),
("DEZ3JNHUGV","DE","Zülpich","NW"),
("DENU6P1TC6","DE","Zweibrücken","RP"),
("DE2YX4EAUH","DE","Zwenkau","SN"),
("DEYYGIL9HK","DE","Zwickau","SN"),
("DEC07TVOPI","DE","Zwiesel","BY"),
("DEJW7KQJQT","DE","Zwingenberg","HE"),
("DEIOXWYREW","DE","Zwönitz","SN");