INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("DOKJ4MRXLE","DO","Azua",NULL),
("DOVIBJMCYG","DO","Baoruco",NULL),
("DOP95A90AN","DO","Barahona",NULL),
("DOH36MHI61","DO","Dajabón",NULL),
("DO1AOT8A83","DO","Distrito Nacional",NULL),
("DOSKMFWLVL","DO","Duarte",NULL),
("DOU0V306RI","DO","El Seíbo",NULL),
("DOAX4RGBTI","DO","Elías Piña",NULL),
("DOLIBUSKXL","DO","Espaillat",NULL),
("DO4J004WMZ","DO","Hato Mayor",NULL),
("DOXI2YPUGZ","DO","Independencia",NULL),
("DOSLR8WKQI","DO","La Altagracia",NULL),
("DO32CVNAHS","DO","La Romana",NULL),
("DOTITYEFYC","DO","La Vega",NULL),
("DOX0ANVRMN","DO","María Trinidad Sánchez",NULL),
("DODDWAYNT1","DO","Monseñor Nouel",NULL),
("DOQ6XDGF5A","DO","Monte Cristi",NULL),
("DOXY9CE7OC","DO","Monte Plata",NULL),
("DO8YZ3PLQ3","DO","Pedernales",NULL),
("DOZMDX96ZZ","DO","Peravia",NULL),
("DOCWDSCJ29","DO","Puerto Plata",NULL),
("DOHBLWJ98R","DO","Salcedo",NULL),
("DO88UYTL1S","DO","Samaná",NULL),
("DO7EQHKPHW","DO","San Cristóbal",NULL),
("DOMVPYES7W","DO","San José de Ocoa",NULL),
("DO4TSN21EB","DO","San Juan",NULL),
("DO9993UAW2","DO","San Pedro de Macorís",NULL),
("DOOMJ9B16Y","DO","Sánchez Ramírez",NULL),
("DOWVWBO47S","DO","Santiago",NULL),
("DOX0G02VBB","DO","Santiago Rodríguez",NULL),
("DO4KFYUB0J","DO","Santo Domingo",NULL),
("DOYKS9LY7I","DO","Valverde",NULL);