INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("EENZCH3YP5","EE","Harjumaa",NULL),
("EEPJQV0BMW","EE","Hiiumaa",NULL),
("EEAPZYYPJJ","EE","Ida-Virumaa",NULL),
("EEKXCXNA1B","EE","Järvamaa",NULL),
("EE9ETDDIJ3","EE","Jõgevamaa",NULL),
("EE19Y2KKYV","EE","Lääne-Virumaa",NULL),
("EEAXT8NDS8","EE","Läänemaa",NULL),
("EEA56YF7AO","EE","Pärnumaa",NULL),
("EEM32ZMM2O","EE","Põlvamaa",NULL),
("EEV1QGMOBW","EE","Raplamaa",NULL),
("EEM559JXIT","EE","Saaremaa",NULL),
("EE2OSHV26H","EE","Tartumaa",NULL),
("EE59HSVJGR","EE","Valgamaa",NULL),
("EEL777VJ4I","EE","Viljandimaa",NULL),
("EEP9S87A1A","EE","Võrumaa",NULL);