INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("IQ1R000IMW","IQ","Al Başrah",NULL),
("IQK66ZLV73","IQ","Al Muthanná",NULL),
("IQPNTBXKSP","IQ","Al Qādisīyah",NULL),
("IQMTH4WZ3Y","IQ","An Najaf",NULL),
("IQR4ZSNMO7","IQ","Anbar",NULL),
("IQSV7EQEHG","IQ","Arbīl",NULL),
("IQ2AR0VJQI","IQ","As Sulaymānīyah",NULL),
("IQD7NA7Q9Z","IQ","At Taʼmīm",NULL),
("IQV8RIUGQN","IQ","Bābil",NULL),
("IQBX12CJIE","IQ","Baghdād",NULL),
("IQU9FPT586","IQ","Dahūk",NULL),
("IQCVHKMQJH","IQ","Dhi Qar",NULL),
("IQYA0TQQH2","IQ","Diyala",NULL),
("IQOI412MGW","IQ","Karbalāʼ",NULL),
("IQWVMQ0UXD","IQ","Maysan",NULL),
("IQQEXC5HU3","IQ","Nīnawá",NULL),
("IQRVXILFLA","IQ","Şalāḩ ad Dīn",NULL),
("IQYPC0CSW9","IQ","Wāsiţ",NULL);