INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("IRNIZOCX13","IR","Ardabīl",NULL),
("IRBYFGGAK8","IR","Āz̄ārbāyjān-e Gharbī",NULL),
("IR5IQRXC2V","IR","Āz̄ārbāyjān-e Sharqī",NULL),
("IR1EVE6SNU","IR","Bushehr Province",NULL),
("IRANINKKQW","IR","Chahār Maḩāll va Bakhtīārī",NULL),
("IRJ6CZHX7N","IR","Eşfahān",NULL),
("IRFYFDAH8B","IR","Fārs Province",NULL),
("IRW4Q2WDX7","IR","Gīlān",NULL),
("IR0GVL0MHJ","IR","Golestān",NULL),
("IRSUIARPX7","IR","Hamadān",NULL),
("IRNCLYTU9P","IR","Hormozgān Province",NULL),
("IRYZSVDQ3E","IR","Īlām",NULL),
("IR7YZ7KHRD","IR","Kerman",NULL),
("IRBAN30LBO","IR","Kermānshāh",NULL),
("IRXWMRRVHQ","IR","Khorāsān-e Jonūbī",NULL),
("IRVAL90PN7","IR","Khorāsān-e Shomālī",NULL),
("IRONF946MG","IR","Khūzestān",NULL),
("IRGAJGVV4T","IR","Kohgīlūyeh va Būyer Aḩmad",NULL),
("IRSRKJN19I","IR","Kordestān",NULL),
("IRBVSCKGK9","IR","Lorestān",NULL),
("IR3ZI865OM","IR","Markazi",NULL),
("IRF83B484W","IR","Markazi Province",NULL),
("IRZPGMRP53","IR","Mazandaran",NULL),
("IRLYF6E0FH","IR","Māzandarān Province",NULL),
("IRZYQ53FSJ","IR","Ostan-e Khorasan-e Razavi",NULL),
("IROWUS4ZP4","IR","Qazvīn",NULL),
("IRP5RGVXKH","IR","Qom",NULL),
("IRV0N903RZ","IR","Razavi Khorasan Province",NULL),
("IR1H54WXNK","IR","Semnān Province",NULL),
("IRUIDYI337","IR","Sīstān va Balūchestān",NULL),
("IR8UO4S8LN","IR","Tehrān",NULL),
("IR89W9CN8E","IR","Yazd",NULL),
("IR4EI1B6M5","IR","Zanjan",NULL),
("IRP04738FB","IR","Zanjan Province",NULL);