INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("JM0M6NVFVL","JM","Clarendon",NULL),
("JMKKYOIQAE","JM","Hanover Parish",NULL),
("JMGRO7RIPD","JM","Kingston",NULL),
("JM9GZAGWRG","JM","Manchester",NULL),
("JMIY3EEZZZ","JM","Portland",NULL),
("JMKYN2PXH5","JM","Saint Andrew",NULL),
("JMP6DHP3VY","JM","Saint Ann",NULL),
("JMKU80R0GA","JM","Saint Catherine",NULL),
("JMZKPEJPD3","JM","Saint James",NULL),
("JMN06CYOIO","JM","Saint Mary",NULL),
("JMVV6LY1KJ","JM","Saint Thomas",NULL),
("JMWTJNU0YT","JM","St. Elizabeth",NULL),
("JMKN74DL80","JM","Trelawny",NULL),
("JMLFDK4V80","JM","Westmoreland",NULL);