INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("LS6T89DBFA","LS","Balzers Commune",NULL),
("LSPQLA3RSQ","LS","Berea District",NULL),
("LS5TOWECC5","LS","Butha-Buthe District",NULL),
("LS53G947FA","LS","Eschen Commune",NULL),
("LS1NKEY0OO","LS","Gamprin Commune",NULL),
("LSQAZU1RK6","LS","Leribe District",NULL),
("LSL83ZLF5Q","LS","Mafeteng",NULL),
("LSIMZNTEYU","LS","Maseru",NULL),
("LS2J91JYPA","LS","Mauren Commune",NULL),
("LS8O49GPG1","LS","Mohaleʼs Hoek",NULL),
("LSXJ1JY79H","LS","Mokhotlong",NULL),
("LST84NN2IP","LS","Planken Commune",NULL),
("LSLRQ5QFGY","LS","Qachaʼs Nek",NULL),
("LS4K8KAOM8","LS","Quthing District",NULL),
("LS7NR6V0OO","LS","Ruggell Commune",NULL),
("LS9SCWVUMH","LS","Thaba-Tseka District",NULL);