INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("LVMI5MXSJT","LV","Aizkraukles Rajons",NULL),
("LV9AIW41E5","LV","Alūksnes Rajons",NULL),
("LVC95VL6PV","LV","Balvu Rajons",NULL),
("LV4ZWSJWI5","LV","Bauskas Rajons",NULL),
("LVENRBFB5P","LV","Cēsu Rajons",NULL),
("LVLOMQP0W2","LV","Daugavpils",NULL),
("LVA1YV7ORB","LV","Daugavpils Rajons",NULL),
("LVNN46JMBY","LV","Dobeles Rajons",NULL),
("LVA3APEFF0","LV","Gulbenes Rajons",NULL),
("LV41RU2NWC","LV","Jēkabpils Rajons",NULL),
("LVOV7WJZ86","LV","Jelgava",NULL),
("LVMCD6ZP59","LV","Jelgavas Rajons",NULL),
("LVTFZ8VE9Z","LV","Jūrmala",NULL),
("LVF0THNQUC","LV","Krāslavas Rajons",NULL),
("LVL1951HCO","LV","Kuldīgas Rajons",NULL),
("LVUPUTFZ38","LV","Liepāja",NULL),
("LVF2HAHQAW","LV","Liepājas Rajons",NULL),
("LVQ3EEU8RG","LV","Limbažu Rajons",NULL),
("LVA0LBIXZC","LV","Ludzas Rajons",NULL),
("LVNU63U9B9","LV","Madonas Rajons",NULL),
("LVCTKTJUQA","LV","Ogres Rajons",NULL),
("LVY5OSEG8O","LV","Preiļu Rajons",NULL),
("LVHT0ZR0BF","LV","Rēzekne",NULL),
("LVVIIPSUZ4","LV","Rēzeknes Rajons",NULL),
("LVNJY7EOHC","LV","Rīga",NULL),
("LVU648MDW3","LV","Rīgas Rajons",NULL),
("LV7X3YYFET","LV","Saldus Rajons",NULL),
("LVXWJPQJTD","LV","Talsu Rajons",NULL),
("LV3SLHG2UA","LV","Tukuma Rajons",NULL),
("LV8ZIVCFZJ","LV","Valkas Rajons",NULL),
("LVD3IBIW5F","LV","Valmieras Rajons",NULL),
("LVTP5J8ZXB","LV","Ventspils",NULL),
("LVRIS7LMIU","LV","Ventspils Rajons",NULL);