INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("MA48K96L5A","MA","Agadir",NULL),
("MAJ8HU4G7B","MA","Al Hoceïma",NULL),
("MA29QCO4IL","MA","Azizal",NULL),
("MAPPES2KK6","MA","Ben Slimane",NULL),
("MAS4FZQL99","MA","Beni Mellal",NULL),
("MAUR4Y7BAA","MA","Boulemane",NULL),
("MAK0M955UV","MA","Casablanca",NULL),
("MAV9OXT83L","MA","Chaouen",NULL),
("MADJL34UDY","MA","Chaouia-Ouardigha",NULL),
("MAMHXUT74E","MA","Doukkala-Abda",NULL),
("MA8RNDWI9R","MA","El Jadida",NULL),
("MASXOL6S7J","MA","El Kelaa des Srarhna",NULL),
("MABSNGN1F9","MA","Er Rachidia",NULL),
("MAJC3CJ7RR","MA","Essaouira",NULL),
("MAZE4VXENP","MA","Fes",NULL),
("MABCBH4J1G","MA","Fès-Boulemane",NULL),
("MABPXZRC8A","MA","Figuig",NULL),
("MAOCN7KEZJ","MA","Gharb-Chrarda-Beni Hssen",NULL),
("MAT4FQI2GT","MA","Grand Casablanca",NULL),
("MAFSBJBC0M","MA","Guelmim",NULL),
("MA2XMT9U4Y","MA","Guelmim-Es Smara",NULL),
("MA7R5R64AZ","MA","Ifrane",NULL),
("MA8QQQS7K7","MA","Kenitra",NULL),
("MAZVRA8SXB","MA","Khemisset",NULL),
("MAPJ4ZE8XL","MA","Khenifra",NULL),
("MA03C68N6H","MA","Khouribga",NULL),
("MAEW863SE3","MA","Laayoune",NULL),
("MAO6DWYA7O","MA","Laâyoune-Boujdour-Sakia El Hamra",NULL),
("MATCO7LLTL","MA","Larache",NULL),
("MAP5SXTYE7","MA","Marrakech",NULL),
("MAVMEZFT23","MA","Marrakech-Tensift-Al Haouz",NULL),
("MA0F0YQ7NJ","MA","Meknes",NULL),
("MAJBR4XKQN","MA","Meknès-Tafilalet",NULL),
("MAQJLKHZSD","MA","Nador",NULL),
("MAM7C20F50","MA","Oriental",NULL),
("MAV5ZLDN5X","MA","Ouarzazate",NULL),
("MAZX2XISK9","MA","Oujda",NULL),
("MAC5TU5M7S","MA","Rabat-Sale",NULL),
("MATKUT00UV","MA","Rabat-Salé-Zemmour-Zaër",NULL),
("MA6UGKHMHG","MA","Safi",NULL),
("MAJJE1CYAO","MA","Settat",NULL),
("MA44J9QQ2J","MA","Sidi Kacem",NULL),
("MABXDBY864","MA","Souss-Massa-Drâa",NULL),
("MA2NPK961T","MA","Tadla-Azilal",NULL),
("MAQFV2E6RI","MA","Tan-Tan",NULL),
("MAAAS11ULD","MA","Tanger",NULL),
("MARZOQ7VUA","MA","Tanger-Tétouan",NULL),
("MAIJVSQWMG","MA","Taounate",NULL),
("MACHJQNB8Y","MA","Taroudannt",NULL),
("MAM0ZNVK0M","MA","Tata",NULL),
("MAJPCRK723","MA","Taza",NULL),
("MARXWITIY6","MA","Taza-Al Hoceima-Taounate",NULL),
("MA0IWOT4MG","MA","Tetouan",NULL),
("MA5L4065MQ","MA","Tiznit",NULL);