INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("MVU47J4TNF","MV","Alifu",NULL),
("MV7U11NVLJ","MV","Alifu Atholhu",NULL),
("MVTMWWQ6IW","MV","Baa",NULL),
("MVJRZBY7ZS","MV","Baa Atholhu",NULL),
("MVB7CF00V8","MV","Dhaalu",NULL),
("MVUW9ISU1M","MV","Dhaalu Atholhu",NULL),
("MVHYI7404O","MV","Faafu",NULL),
("MVR3ZQBZIN","MV","Faafu Atholhu",NULL),
("MV6V37VYFQ","MV","Gaafu Alifu",NULL),
("MVUP8NJA91","MV","Gaafu Alifu Atholhu",NULL),
("MV8R8DRD2J","MV","Gaafu Dhaalu",NULL),
("MVG19R1SE7","MV","Gaafu Dhaalu Atholhu",NULL),
("MVOHEKGUAB","MV","Gnaviyani",NULL),
("MVJJY3T742","MV","Gnyaviyani Atoll",NULL),
("MVZDGRQIA6","MV","Haa Alifu",NULL),
("MVKKYLDDT1","MV","Haa Alifu Atholhu",NULL),
("MVV8LB2WMM","MV","Haa Dhaalu",NULL),
("MVFLP9STBS","MV","Haa Dhaalu Atholhu",NULL),
("MV6SJXAU3U","MV","Kaafu",NULL),
("MVF2GSF9UA","MV","Kaafu Atholhu",NULL),
("MVHFLJC86R","MV","Laamu",NULL),
("MVTV0MPCEV","MV","Lhaviyani",NULL),
("MV4YTFSWA7","MV","Lhaviyani Atholhu",NULL),
("MVYQ0E0UOH","MV","Maale",NULL),
("MVAA1MJ7DC","MV","Meemu",NULL),
("MV3EZSREOW","MV","Meemu Atholhu",NULL),
("MVCHC5EMDC","MV","Noonu",NULL),
("MVDDRE7GVI","MV","Noonu Atholhu",NULL),
("MVQX4A5IM8","MV","Raa",NULL),
("MVXM0O0OLD","MV","Raa Atholhu",NULL),
("MV6XIKKWXY","MV","Seenu",NULL),
("MV9OCH480V","MV","Shaviyani",NULL),
("MV645BMSJK","MV","Shaviyani Atholhu",NULL),
("MVEK9E9USF","MV","Thaa",NULL),
("MVSBZC7XBH","MV","Thaa Atholhu",NULL),
("MVLNZPVZL2","MV","Vaavu",NULL),
("MV3QDQIXBX","MV","Vaavu Atholhu",NULL);