INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("NISONJCK0M","NI","Atlántico Norte",NULL),
("NIZ4IFTB3X","NI","Atlántico Sur",NULL),
("NIEB77K13J","NI","Boaco",NULL),
("NI3BJB10RT","NI","Carazo",NULL),
("NIPED1YDNY","NI","Chinandega",NULL),
("NIH6DBIG9W","NI","Chontales",NULL),
("NISH3CJ6VM","NI","Estelí",NULL),
("NIIFYJFPD4","NI","Granada",NULL),
("NI4Q634U1M","NI","Jinotega",NULL),
("NI0FYIW8FO","NI","León",NULL),
("NIPI08PWV7","NI","Madriz",NULL),
("NIBURQJ5VO","NI","Managua",NULL),
("NIV1S0VTMW","NI","Masaya",NULL),
("NI9LE5TTTJ","NI","Matagalpa",NULL),
("NICUS2QNA2","NI","Nueva Segovia",NULL),
("NII2S27OQ2","NI","Ogun State",NULL),
("NIPI2LCPIL","NI","Río San Juan",NULL),
("NIAWR3QKM3","NI","Rivas",NULL);