INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("NRII9QQY4D","NR","Aiwo",NULL),
("NRIFT0FNF9","NR","Anabar",NULL),
("NRIKVV4DNC","NR","Anetan",NULL),
("NRSPDJFV7X","NR","Anibare",NULL),
("NRDHO4GTHY","NR","Baiti",NULL),
("NR8BZOYFYH","NR","Boe",NULL),
("NRZUD371F0","NR","Buada",NULL),
("NRRTJ6OQ42","NR","Denigomodu",NULL),
("NR7S6NMOMV","NR","Ewa",NULL),
("NR0LKZ1JH0","NR","Ijuw",NULL),
("NRDV4LWJLN","NR","Meneng",NULL),
("NRC4U1UY32","NR","Nibok",NULL),
("NRRAQDZD90","NR","Uaboe",NULL),
("NRYUZ0DH0Q","NR","Yaren",NULL);