INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("PG5EJZDWTB","PG","Bougainville",NULL),
("PGAWIN8ICH","PG","Central",NULL),
("PGAXE9HRYX","PG","Chimbu",NULL),
("PGL4576PKC","PG","East New Britain",NULL),
("PG44BI05TB","PG","East Sepik",NULL),
("PG2BZAUBS4","PG","Eastern Highlands",NULL),
("PG96DRXCOJ","PG","Enga",NULL),
("PGGURNKCZO","PG","Gulf",NULL),
("PGGB6HH0TJ","PG","Madang",NULL),
("PGCST64LAE","PG","Manus",NULL),
("PGSN5PZU9G","PG","Milne Bay",NULL),
("PGP049C4YT","PG","Morobe",NULL),
("PGF4BX55GH","PG","National Capital",NULL),
("PGXAN1WYFO","PG","New Ireland",NULL),
("PGLLELGN25","PG","Northern",NULL),
("PGO6E0ADUQ","PG","Sandaun",NULL),
("PGH6NNB448","PG","Southern Highlands",NULL),
("PGESAAQQYB","PG","West New Britain",NULL),
("PGBDXS00XO","PG","Western",NULL),
("PG6CPHPK87","PG","Western Highlands",NULL);