INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("PLC6LIK29I","PL","Biala Podlaska",NULL),
("PLXXJ3MRFO","PL","Bialystok",NULL),
("PLXFKF3KXO","PL","Bielsko",NULL),
("PLRHVEUPX6","PL","Bydgoszcz",NULL),
("PLWIPGLYZJ","PL","Chelm",NULL),
("PLVJMHB158","PL","Ciechanow",NULL),
("PLHQOLBLA2","PL","Czestochowa",NULL),
("PL25HXVE4R","PL","Elblag",NULL),
("PLWT8IS71N","PL","Gdansk",NULL),
("PLQN52OBA6","PL","Gorzow",NULL),
("PL2YRDK1GM","PL","Greater Poland Voivodeship",NULL),
("PL7XK3COV9","PL","Jelenia Gora",NULL),
("PLI3RBASY1","PL","Kalisz",NULL),
("PLF434FEBI","PL","Katowice",NULL),
("PLD2VX4BKC","PL","Kielce",NULL),
("PL95GLUBUD","PL","Konin",NULL),
("PLELOPENRT","PL","Koszalin",NULL),
("PLRVY7A9PN","PL","Krakow",NULL),
("PLCLLHX6T7","PL","Krosno",NULL),
("PLCAS6LNJZ","PL","Kujawsko-Pomorskie Voivodship",NULL),
("PL97PNUGHM","PL","Legnica",NULL),
("PLCFTMOJA0","PL","Lesser Poland Voivodeship",NULL),
("PL4WH22B9E","PL","Leszno",NULL),
("PLL2L6Q46Z","PL","Lodz",NULL),
("PLCWN6D4SP","PL","Lomza",NULL),
("PLJMB85L8A","PL","Lower Silesian Voivodeship",NULL),
("PLIQCL1M0N","PL","Lublin",NULL),
("PLOLUEP1E1","PL","Lublin Voivodeship",NULL),
("PLX18A61ZP","PL","Lubusz Voivodship",NULL),
("PLNBYSX63F","PL","Łódź Voivodeship",NULL),
("PLXG0Z20MR","PL","Masovian Voivodeship",NULL),
("PLLH6BIKDG","PL","Nowy Sacz",NULL),
("PLMMQSNQIA","PL","Olsztyn",NULL),
("PL1G3YN6DK","PL","Opole",NULL),
("PLMEJPE6G0","PL","Opole Voivodeship",NULL),
("PLOMC66PMS","PL","Ostroleka",NULL),
("PLBDLZ3394","PL","Piotrkow",NULL),
("PLJC36JHR6","PL","Pita",NULL),
("PLVBVAIBB6","PL","Plock",NULL),
("PLXND4DZXP","PL","Podlasie Voivodship",NULL),
("PLCJOGMYK6","PL","Pomeranian Voivodeship",NULL),
("PLBODU5401","PL","Poznan",NULL),
("PLGVBY7N55","PL","Przemysl",NULL),
("PLAIAOH7DU","PL","Radom",NULL),
("PLR2AD0VJB","PL","Rzeszow",NULL),
("PLJW6P16QH","PL","Siedlce",NULL),
("PL22G9PLEZ","PL","Sieradz",NULL),
("PL3OOLW1FN","PL","Silesian Voivodeship",NULL),
("PL4Q15LKH5","PL","Skierniewice",NULL),
("PLHNUIUL0W","PL","Slupsk",NULL),
("PLNG6C1KC5","PL","Subcarpathian Voivodeship",NULL),
("PL90Q626U6","PL","Suwalki",NULL),
("PLWVCIGTOX","PL","Świętokrzyskie Voivodship",NULL),
("PLGJGA4G7R","PL","Szczecin",NULL),
("PLXD4ZYG48","PL","Tarnobrzeg",NULL),
("PLGVFJ19PX","PL","Tarnow",NULL),
("PL41GKV4HB","PL","Torufi",NULL),
("PLNYMSEUKC","PL","Walbrzych",NULL),
("PL8OB75GFL","PL","Warmian-Masurian Voivodeship",NULL),
("PLBU5C3UA8","PL","Warszawa",NULL),
("PLWRSSVA4J","PL","West Pomeranian Voivodeship",NULL),
("PL9QCOLW0T","PL","Wloclawek",NULL),
("PLKC0PSGB4","PL","Wroclaw",NULL),
("PLBGHFBSN8","PL","Zamosc",NULL),
("PLJG0FR4Z0","PL","Zielona Gora",NULL);