INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("PTX0OOUOR4","PT","Aveiro",NULL),
("PT49QDFK51","PT","Azores",NULL),
("PTFEEELT94","PT","Beja",NULL),
("PTWLUP7DJ4","PT","Braga",NULL),
("PTE8T8WKD1","PT","Bragança",NULL),
("PTU3E9NKA2","PT","Castelo Branco",NULL),
("PTYPHKJROF","PT","Coimbra",NULL),
("PTCJ5KXPPB","PT","Évora",NULL),
("PTYIKV3XWY","PT","Faro",NULL),
("PT0B7OWIRV","PT","Guarda",NULL),
("PT78GQ046C","PT","Leiria",NULL),
("PTOCXL1MXZ","PT","Lisbon",NULL),
("PT4HV8ER6F","PT","Madeira",NULL),
("PT3D40WVV3","PT","Portalegre",NULL),
("PT4BU4G1H5","PT","Porto",NULL),
("PTDEQF0NE5","PT","Santarém",NULL),
("PT59DK1J05","PT","Setúbal",NULL),
("PTX45TZ1X4","PT","Viana do Castelo",NULL),
("PTDS8UTPZ7","PT","Vila Real",NULL),
("PT4QM4E19J","PT","Viseu",NULL);