INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("SCT5YK91RY","SC","Anse aux Pins",NULL),
("SCVV1RH9YD","SC","Anse Boileau",NULL),
("SCFB2WDVVO","SC","Anse Etoile",NULL),
("SCIPMZPMOJ","SC","Anse Louis",NULL),
("SCRN41OV0K","SC","Anse Royale",NULL),
("SCR1C9AAMQ","SC","Au Cap",NULL),
("SCLPMZLIN3","SC","Baie Lazare",NULL),
("SC792XWRHO","SC","Baie Sainte Anne",NULL),
("SCELQ3GQN7","SC","Beau Vallon",NULL),
("SCRZG293SV","SC","Bel Air",NULL),
("SCSFUDXIH5","SC","Bel Ombre",NULL),
("SCSK2OBKDP","SC","Cascade",NULL),
("SC53SMTGUL","SC","English River",NULL),
("SCGANQEGL7","SC","Glacis",NULL),
("SCVGLSY2XQ","SC","Grand Anse Mahe",NULL),
("SCM0FYKSNQ","SC","Grand Anse Praslin",NULL),
("SCWGCQW6BD","SC","Inner Islands",NULL),
("SCHZ3VGO2B","SC","La Riviere Anglaise",NULL),
("SC5N43Q1UD","SC","Les Mamelles",NULL),
("SC2ABM2YDZ","SC","Mont Buxton",NULL),
("SCFPPCV1PC","SC","Mont Fleuri",NULL),
("SC1S8HHASM","SC","Plaisance",NULL),
("SCYXQPYK21","SC","Pointe Larue",NULL),
("SCVDOYC1XR","SC","Port Glaud",NULL),
("SCQN3MPSZQ","SC","Roche Caiman",NULL),
("SCL772I0PH","SC","Saint Louis",NULL),
("SCXF6W08YV","SC","Saint Thomas Middle Island Parish",NULL),
("SCMMTYNRPE","SC","Takamaka",NULL),
("SCES14L1U6","SC","Trinity Palmetto Point Parish",NULL);