INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("UZGKZ3CE64","UZ","Andijon",NULL),
("UZHL3VWT8R","UZ","Buxoro",NULL),
("UZJSOD9W6Z","UZ","Farg ona",NULL),
("UZKK4BMOQ3","UZ","Jizzax",NULL),
("UZ9P7L3EQL","UZ","Karakalpakstan",NULL),
("UZZTGWNPO7","UZ","Namangan",NULL),
("UZHCKQ8QQT","UZ","Navoiy",NULL),
("UZBU5YJV2S","UZ","Qashqadaryo",NULL),
("UZL9EPN4AN","UZ","Samarqand",NULL),
("UZYRJMG7TX","UZ","Sirdaryo",NULL),
("UZJEOS4ELG","UZ","Surxondaryo",NULL),
("UZ9QETMGM8","UZ","Toshkent",NULL),
("UZQ0YD5904","UZ","Toshkent Shahri",NULL),
("UZ0KQGRJEA","UZ","Xorazm",NULL);