INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("VEWYKODOEV","VE","Amazonas",NULL),
("VEV7VSIN3Q","VE","Anzoátegui",NULL),
("VE0HCK61C4","VE","Apure",NULL),
("VE7IKW7JM3","VE","Aragua",NULL),
("VEH6SVV7QR","VE","Barinas",NULL),
("VEELJX8MN9","VE","Bolívar",NULL),
("VE40TB16F9","VE","Carabobo",NULL),
("VEPZ5WJS01","VE","Cojedes",NULL),
("VEYTWU1MLG","VE","Delta Amacuro",NULL),
("VE84DHR1QW","VE","Dependencias Federales",NULL),
("VE1K72QMBG","VE","Distrito Capital",NULL),
("VEMHC59D67","VE","Distrito Federal",NULL),
("VE6317QNOY","VE","Falcón",NULL),
("VER1GJ26F4","VE","Guárico",NULL),
("VEQM6H8IXV","VE","Isla Margarita",NULL),
("VEZA08N7GU","VE","Lara",NULL),
("VEAI205QZX","VE","Mérida",NULL),
("VERFGUMVYD","VE","Miranda",NULL),
("VEH5UQNSLM","VE","Monagas",NULL),
("VE2LVPTBJ3","VE","Portuguesa",NULL),
("VEUL4ZC3W3","VE","Sucre",NULL),
("VEJCY57WIP","VE","Táchira",NULL),
("VE1DFP50C7","VE","Trujillo",NULL),
("VEL7XFJHID","VE","Vargas",NULL),
("VE3NCFR9JA","VE","Yaracuy",NULL),
("VELHGTDZIF","VE","Zulia",NULL);