INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("VN5YNW777T","VN","An Giang",NULL),
("VNOON2N5I0","VN","Bà Rịa-Vũng Tàu",NULL),
("VN3NI247MS","VN","Bắc Giang",NULL),
("VNVL003M89","VN","Bắc Kạn",NULL),
("VNKW6S3DLS","VN","Bạc Liêu",NULL),
("VN28UPECPI","VN","Bắc Ninh",NULL),
("VNZ7K3F6WB","VN","Bắc Thái Tỉnh",NULL),
("VNSXBWJK53","VN","Bến Tre",NULL),
("VNGBWKPHCR","VN","Bình Dương",NULL),
("VNQ7H5K7OK","VN","Bình Ðịnh",NULL),
("VNF8OVFK68","VN","Bình Phước",NULL),
("VNHI41395K","VN","Binh Thuan",NULL),
("VNL14AJH29","VN","Cà Mau",NULL),
("VNOKF9R3T7","VN","Cần Thơ",NULL),
("VNCH2S190J","VN","Cao Bang",NULL),
("VNS4LVEQF0","VN","Ðà Nẵng",NULL),
("VNRKAB1DLQ","VN","Ðắc Lắk",NULL),
("VNX0ZP4SWG","VN","Ðồng Nai",NULL),
("VN9Z8B88V0","VN","Ðồng Tháp",NULL),
("VNDGWS6BSY","VN","Gia Lai",NULL),
("VNV39XHUNE","VN","Hà Bắc Tỉnh",NULL),
("VNVM4ZF1FO","VN","Hà Giang",NULL),
("VN0O09XV9B","VN","Hà Nam",NULL),
("VNB63HHWGD","VN","Ha Nội",NULL),
("VNZQAHKXVG","VN","Ha Tay",NULL),
("VNK0FZ1UO1","VN","Hà Tĩnh",NULL),
("VNJOAGJKRU","VN","Hải Dương",NULL),
("VNRVC8RTMR","VN","Hải Hưng Tỉnh",NULL),
("VNJW83U4JE","VN","Hải Phòng",NULL),
("VN4ZD6U18D","VN","Hồ Chí Minh",NULL),
("VNQIT93L4U","VN","Hoa Binh",NULL),
("VNGH37APZT","VN","Hưng Yên",NULL),
("VNM8XGCHUH","VN","Khánh Hòa",NULL),
("VNG8NBAWO0","VN","Kiến Giang",NULL),
("VNFIAI3FDK","VN","Kon Tum",NULL),
("VNWHS67R0T","VN","Lai Châu",NULL),
("VNZX9CF4TW","VN","Lâm Ðồng",NULL),
("VNDH7NDVOS","VN","Lạng Sơn",NULL),
("VNEZBIEP2A","VN","Lào Cai",NULL),
("VN6UHDLH6L","VN","Long An",NULL),
("VNFGXUKRQX","VN","Minh Hải Tỉnh",NULL),
("VN8YLMTAF8","VN","Nam Ðịnh",NULL),
("VN9QQOFSYM","VN","Nam Hà Tỉnh",NULL),
("VNMG08Y6TD","VN","Nghệ An",NULL),
("VNNR87IZ5R","VN","Nin Thuan",NULL),
("VNXRDR1SZB","VN","Ninh Bình",NULL),
("VNJPZZIYL4","VN","Ninh Thuận",NULL),
("VNELDDS6QF","VN","Phú Thọ",NULL),
("VNYZNGZT8W","VN","Phú Yên",NULL),
("VNKLOMENXY","VN","Quảng Bình",NULL),
("VNDXXVVJ0A","VN","Quang Nam",NULL),
("VN4DNXKDDI","VN","Quảng Nam-Ðà Nẵng Tỉnh",NULL),
("VND1ZCU79F","VN","Quảng Ngãi",NULL),
("VNTX17LZ5Z","VN","Quảng Ninh",NULL),
("VNW3VRMV1R","VN","Quảng Trị",NULL),
("VN8OOT22BG","VN","Sóc Trăng",NULL),
("VN3ATYH2DB","VN","Sơn La",NULL),
("VN0FIMFOMB","VN","Sông Bé Tỉnh",NULL),
("VNSH3EC55L","VN","Tây Ninh",NULL),
("VNUUEXXQE0","VN","Ten Bai",NULL),
("VN07YIACTB","VN","Thái Bình",NULL),
("VNSCX71JJT","VN","Thái Nguyên",NULL),
("VN1N8DTEZO","VN","Thanh Hóa",NULL),
("VN9EL64064","VN","Thua Thien-Hue",NULL),
("VN75NIIHTA","VN","Tiền Giang",NULL),
("VNTRHVB1PC","VN","Trà Vinh",NULL),
("VNOXQHBP5L","VN","Tuyên Quang",NULL),
("VN4RR8RYDZ","VN","Vĩnh Long",NULL),
("VN40HMHBWB","VN","Vinh Phú Tỉnh",NULL),
("VN2E6EFVQ3","VN","Vĩnh Phúc",NULL),
("VNTHL57RQB","VN","Yên Bái",NULL);