INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("AF72U7ZQLY","AF","Badakhshan",NULL),
("AF3AHEFECU","AF","Badghis Province",NULL),
("AFCRFTC7HR","AF","Baghlān",NULL),
("AFFEC12GX9","AF","Balkh",NULL),
("AFJSHIJ2HM","AF","Bāmīān",NULL),
("AFDY1SCDMP","AF","Dāykondī",NULL),
("AF52II9Z9O","AF","Farah",NULL),
("AFEMQH2OQL","AF","Faryab Province",NULL),
("AFG74ZALMN","AF","Ghaznī",NULL),
("AFKNGX13M6","AF","Ghowr",NULL),
("AF54OE4Y3J","AF","Helmand Province",NULL),
("AFKT0NHR9Y","AF","Herat Province",NULL),
("AFZDYAZLXJ","AF","Jowzjān",NULL),
("AF8DGAH2GM","AF","Kabul",NULL),
("AF751C34WO","AF","Kandahār",NULL),
("AFYWBGOKFN","AF","Kāpīsā",NULL),
("AFYDYXYVH7","AF","Khowst",NULL),
("AF9XHQ0YD8","AF","Konar",NULL),
("AF3EK6JGUH","AF","Kunduz Province",NULL),
("AFD6Y1RDPP","AF","Laghmān",NULL),
("AFRNNPJ4XT","AF","Lowgar",NULL),
("AF2FJ2DXAH","AF","Nangarhār",NULL),
("AFBVOVBIDO","AF","Nīmrūz",NULL),
("AFPBQGOG6G","AF","Nūrestān",NULL),
("AF4U6NZ3G1","AF","Orūzgān",NULL),
("AFI03WXED9","AF","Paktia Province",NULL),
("AF914LKHAA","AF","Paktīkā",NULL),
("AFT0QHHXYL","AF","Panjshīr",NULL),
("AFS48R7PSQ","AF","Parvān",NULL),
("AFPVNNA0WJ","AF","Samangān",NULL),
("AF214MJEWC","AF","Sar-e Pol",NULL),
("AFFNUWLSHD","AF","Takhār",NULL),
("AFWQ44FWU5","AF","Vardak",NULL),
("AFSHT2IQMK","AF","Zabul Province",NULL);