INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("AOC32UMFSS","AO","Bengo",NULL),
("AOUBYIDO2C","AO","Benguela",NULL),
("AO9O7LF6TL","AO","Bié",NULL),
("AOH7IZSOF5","AO","Cabinda",NULL),
("AORHZEWR6R","AO","Cuando Cubango",NULL),
("AO34AGTCS3","AO","Cuanza Norte",NULL),
("AO0ZPG5J1N","AO","Cuanza Sul",NULL),
("AOQKNI82NZ","AO","Cunene",NULL),
("AOKNDHEK8H","AO","Huambo",NULL),
("AOPIYJUQMV","AO","Huíla",NULL),
("AOQBCVUEJK","AO","Luanda",NULL),
("AOY6368Q6S","AO","Lunda Norte",NULL),
("AODK9S4IAU","AO","Lunda Sul",NULL),
("AO08DVZZRP","AO","Malanje",NULL),
("AOB3K5H4QG","AO","Moxico",NULL),
("AOATNJJUCX","AO","Namibe",NULL),
("AOEMQJ40D4","AO","Uíge",NULL),
("AO9QZ8QQX1","AO","Zaire",NULL);