INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("ARUI6CMWSX","AR","Buenos Aires",NULL),
("ARQGG9AS7O","AR","Catamarca",NULL),
("AREX8IYLN8","AR","Chaco",NULL),
("ARCNG2EE38","AR","Chubut",NULL),
("ARXAKK7DHX","AR","Córdoba",NULL),
("ARTX73QES4","AR","Corrientes",NULL),
("ARC0NBMBJZ","AR","Distrito Federal",NULL),
("ARY01CF5LC","AR","Entre Ríos",NULL),
("ARG6WNKDLD","AR","Formosa",NULL),
("ARBSH17A6K","AR","Jujuy",NULL),
("ARBUVX5FX4","AR","La Pampa",NULL),
("ARFZHU427L","AR","La Rioja",NULL),
("AR938THU7S","AR","Mendoza",NULL),
("ARMPTUZ0EA","AR","Misiones",NULL),
("ARUA8ZQ535","AR","Neuquén",NULL),
("AR4K09N7UW","AR","Río Negro",NULL),
("ARB3QSYXLK","AR","Salta",NULL),
("ARNFFMFUX9","AR","San Juan",NULL),
("AR468UCC0H","AR","San Luis",NULL),
("ARX1RK9LHK","AR","Santa Cruz",NULL),
("ARP7DN5Z8S","AR","Santa Fe",NULL),
("AREOFTIC2N","AR","Santiago del Estero",NULL),
("ARJBIVOIDL","AR","Tierra del Fuego, Antártida e Islas del Atlán",NULL),
("ARK45TQNEF","AR","Tucumán",NULL);