INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("AT08ZIL264","AT","Allentsteig","Niederösterreich"),
("ATDO027DNR","AT","Altheim","Oberösterreich"),
("ATHTK7GZNA","AT","Althofen","Kärnten"),
("ATRQAI33O4","AT","Amstetten","Niederösterreich"),
("ATBNNXPT13","AT","Ansfelden","Oberösterreich"),
("ATH15OFTFW","AT","Attnang-Puchheim","Oberösterreich"),
("ATM032ZRDQ","AT","Bad Aussee","Steiermark"),
("ATIO9LSYP4","AT","Bad Hall","Oberösterreich"),
("ATLC1B53FN","AT","Bad Ischl","Oberösterreich"),
("AT4LCKERG1","AT","Bad Leonfelden","Oberösterreich"),
("ATSK4SBHJT","AT","Bad Radkersburg","Steiermark"),
("AT6SFYQ52C","AT","Bad St. Leonhard im Lavanttal","Kärnten"),
("ATH3ON63BB","AT","Bad Vöslau","Niederösterreich"),
("ATONV3FC57","AT","Baden","Niederösterreich"),
("ATW9Z8QI2W","AT","Bärnbach","Steiermark"),
("ATBIU2NXE5","AT","Berndorf","Niederösterreich"),
("AT12S763JV","AT","Bischofshofen","Salzburg"),
("ATRFY6R4DO","AT","Bleiburg","Kärnten"),
("ATDDX3WZ07","AT","Bludenz","Vorarlberg"),
("ATHV95SOAT","AT","Braunau am Inn","Oberösterreich"),
("ATR31X7LSY","AT","Bregenz","Vorarlberg"),
("AT0R4RVIG8","AT","Bruck an der Leitha","Niederösterreich"),
("ATVDCRDDZV","AT","Bruck an der Mur","Steiermark"),
("AT8901XAVO","AT","Deutsch-Wagram","Niederösterreich"),
("ATEXMLIEJI","AT","Deutschlandsberg","Steiermark"),
("AT6NA15RA1","AT","Dornbirn","Vorarlberg"),
("AT4NSH0RD9","AT","Drosendorf-Zissersdorf1","Niederösterreich"),
("AT1DAYO6N2","AT","Dürnstein","Niederösterreich"),
("AT39NMO75U","AT","Ebenfurth","Niederösterreich"),
("ATUFW0661B","AT","Ebreichsdorf","Niederösterreich"),
("ATTUTUM63N","AT","Eferding","Oberösterreich"),
("ATKEL9K9CO","AT","Eggenburg","Niederösterreich"),
("ATI0B67G12","AT","Eisenerz","Steiermark"),
("ATWX2333EX","AT","Eisenstadt","Burgenland"),
("ATX8RJEV6Z","AT","Enns","Oberösterreich"),
("AT9S8U1KIK","AT","Fehring","Steiermark"),
("ATLTRSASU6","AT","Feldbach","Steiermark"),
("ATPX9T0NRY","AT","Feldkirch","Vorarlberg"),
("ATVIIADP9N","AT","Feldkirchen in Kärnten","Kärnten"),
("ATHIHJ303O","AT","Ferlach","Kärnten"),
("ATUUH4NBAC","AT","Fischamend","Niederösterreich"),
("AT9J697X83","AT","Frauenkirchen","Burgenland"),
("ATFQETFOGX","AT","Freistadt","Oberösterreich"),
("AT6XGAYKZS","AT","Friedberg","Steiermark"),
("ATEGW2S6E1","AT","Friesach","Kärnten"),
("ATQLBYIJ2Y","AT","Frohnleiten","Steiermark"),
("ATAGRP48NB","AT","Fürstenfeld","Steiermark"),
("AT63L4NKW2","AT","Gallneukirchen","Oberösterreich"),
("AT1T4T0JVR","AT","Gänserndorf","Niederösterreich"),
("AT46PMQSL0","AT","Geras","Niederösterreich"),
("AT8CQDLDOS","AT","Gerasdorf bei Wien","Niederösterreich"),
("ATGAX4VU7W","AT","Gföhl","Niederösterreich"),
("ATNBQOVLFZ","AT","Gleisdorf","Steiermark"),
("ATS5MIX7J6","AT","Gloggnitz","Niederösterreich"),
("ATK9J5M8Y3","AT","Gmünd","Niederösterreich"),
("ATIV8EPFBD","AT","Gmünd in Kärnten","Kärnten"),
("ATR21MOGLG","AT","Gmunden","Oberösterreich"),
("ATL8ZJFIPZ","AT","Graz","Steiermark"),
("ATS85FG4JZ","AT","Grein","Oberösterreich"),
("ATZREP7P3Y","AT","Grieskirchen","Oberösterreich"),
("ATR4KFL6W7","AT","Groß Gerungs","Niederösterreich"),
("ATFVQUEGU6","AT","Groß-Enzersdorf","Niederösterreich"),
("ATO0L54554","AT","Groß-Siegharts","Niederösterreich"),
("ATWJU39X20","AT","Güssing","Burgenland"),
("AT2NGNUCV9","AT","Haag","Niederösterreich"),
("AT8L3M2YTR","AT","Hainburg an der Donau","Niederösterreich"),
("ATYFX3K28H","AT","Hainfeld","Niederösterreich"),
("ATM2LV0NW2","AT","Hall in Tirol","Tirol"),
("ATBCQ5PLEX","AT","Hallein","Salzburg"),
("AT7IK9HE0F","AT","Hardegg","Niederösterreich"),
("ATTXJE0SVM","AT","Hartberg","Steiermark"),
("ATUGHV4DXF","AT","Heidenreichstein","Niederösterreich"),
("ATQOKF9ZDG","AT","Hermagor-Pressegger See","Kärnten"),
("ATHYQYCQE6","AT","Herzogenburg","Niederösterreich"),
("ATOYKOQGAL","AT","Hohenems","Vorarlberg"),
("ATXSG16EHW","AT","Hollabrunn","Niederösterreich"),
("AT22CB1PSJ","AT","Horn","Niederösterreich"),
("ATNII08X6X","AT","Imst","Tirol"),
("ATWQLM7W84","AT","Innsbruck","Tirol"),
("ATOO6U3NR5","AT","Jennersdorf","Burgenland"),
("ATQ3HSS9CG","AT","Judenburg","Steiermark"),
("ATRUG0SMXO","AT","Kapfenberg","Steiermark"),
("ATDJBLFJP3","AT","Kindberg","Steiermark"),
("AT8VYBJPGA","AT","Kirchdorf an der Krems","Oberösterreich"),
("ATSX2L7E2Z","AT","Kirchschlag in der Buckligen Welt","Niederösterreich"),
("AT9JZ25XQJ","AT","Kitzbühel","Tirol"),
("ATH24WLU0U","AT","Klagenfurt am Wörthersee","Kärnten"),
("ATQY59OMJH","AT","Klosterneuburg","Niederösterreich"),
("ATJM2R15QA","AT","Knittelfeld","Steiermark"),
("ATOQDUO3E5","AT","Köflach","Steiermark"),
("AT6I2RD2L3","AT","Korneuburg","Niederösterreich"),
("AT1RDPDW6X","AT","Krems an der Donau","Niederösterreich"),
("ATJ9OKFFV3","AT","Kufstein","Tirol"),
("AT58XTCBZI","AT","Laa an der Thaya","Niederösterreich"),
("ATU1A73WA5","AT","Laakirchen","Oberösterreich"),
("ATNNV1K2Y4","AT","Landeck","Tirol"),
("ATCNOR2KU7","AT","Langenlois","Niederösterreich"),
("ATTS1530OY","AT","Leibnitz","Steiermark"),
("AT1Y55VGBJ","AT","Leoben","Steiermark"),
("AT46KP8ITK","AT","Leonding","Oberösterreich"),
("AT6IB836GW","AT","Lienz","Tirol"),
("ATYI22IQ0K","AT","Liezen","Steiermark"),
("ATP6QKN13S","AT","Lilienfeld","Niederösterreich"),
("AT8OHG6B1D","AT","Linz","Oberösterreich"),
("ATUDLYK2VI","AT","Litschau","Niederösterreich"),
("ATKXL3OLND","AT","Maissau","Niederösterreich"),
("ATSEYFG28O","AT","Mank","Niederösterreich"),
("ATQQ5X27AX","AT","Mannersdorf am Leithagebirge","Niederösterreich"),
("ATKWV4YQNJ","AT","Marchegg","Niederösterreich"),
("ATO9MCUAPN","AT","Marchtrenk","Oberösterreich"),
("ATOO34QBTG","AT","Mariazell","Steiermark"),
("AT1YD45N1Q","AT","Mattersburg","Burgenland"),
("ATJWVINJ1B","AT","Mattighofen","Oberösterreich"),
("ATSONNYDAN","AT","Mautern an der Donau","Niederösterreich"),
("AT1ESSPL8R","AT","Melk","Niederösterreich"),
("ATKLVP9XGT","AT","Mistelbach","Niederösterreich"),
("ATUCCHVETO","AT","Mittersill","Salzburg"),
("AT2HB1VMOW","AT","Mödling","Niederösterreich"),
("AT0GOQ1XIL","AT","Murau","Steiermark"),
("ATJEBSBSM6","AT","Mureck","Steiermark"),
("AT4YN0CHOE","AT","Mürzzuschlag","Steiermark"),
("ATY0FTM4QN","AT","Neufeld an der Leitha","Burgenland"),
("ATKFEMCX8W","AT","Neulengbach","Niederösterreich"),
("ATBJONCBTG","AT","Neumarkt am Wallersee","Salzburg"),
("AT9HGLY50X","AT","Neunkirchen","Niederösterreich"),
("AT5GRSKHF5","AT","Neusiedl am See","Burgenland"),
("ATXURARZ62","AT","Oberndorf bei Salzburg","Salzburg"),
("ATJVQV6KCF","AT","Oberpullendorf","Burgenland"),
("AT1T10Y2Y4","AT","Oberwart","Burgenland"),
("ATIPW27C74","AT","Oberwölz","Steiermark"),
("AT6ZEXZL0I","AT","Perg","Oberösterreich"),
("ATGRENBQ2D","AT","Peuerbach","Oberösterreich"),
("ATK4EI6CNO","AT","Pinkafeld","Burgenland"),
("AT1JR8VZD1","AT","Pöchlarn","Niederösterreich"),
("ATZSZYDZGU","AT","Poysdorf","Niederösterreich"),
("ATQVH2LKF6","AT","Pregarten","Oberösterreich"),
("ATOTPV5CJ7","AT","Pressbaum","Niederösterreich"),
("ATVBGRBUSA","AT","Pulkau","Niederösterreich"),
("ATMS80RPUI","AT","Purbach am Neusiedler See","Burgenland"),
("ATKCL6W0CL","AT","Purkersdorf","Niederösterreich"),
("ATU1G0D079","AT","Raabs an der Thaya","Niederösterreich"),
("ATCO0NITX5","AT","Radenthein","Kärnten"),
("ATL65DV0WG","AT","Radstadt","Salzburg"),
("ATDHMAIYVC","AT","Rattenberg","Tirol"),
("AT0CCDDKMQ","AT","Retz","Niederösterreich"),
("AT8MDRGBW1","AT","Ried im Innkreis","Oberösterreich"),
("ATI2ED3BTG","AT","Rohrbach in Oberösterreich","Oberösterreich"),
("ATSGQAEMME","AT","Rottenmann","Steiermark"),
("ATZZSCJF2S","AT","Rust","Burgenland"),
("AT1GJISGJA","AT","Saalfelden am Steinernen Meer","Salzburg"),
("ATJYOM9H32","AT","Salzburg","Salzburg"),
("ATYTCCGZRF","AT","Sankt Andrä","Kärnten"),
("ATYKRIZUA1","AT","Sankt Veit an der Glan","Kärnten"),
("ATBUJ3B2DU","AT","Schärding","Oberösterreich"),
("AT11HAJLDH","AT","Scheibbs","Niederösterreich"),
("ATEPUVPLAO","AT","Schladming","Steiermark"),
("AT5264XH68","AT","Schrattenthal","Niederösterreich"),
("ATCPBNROIT","AT","Schrems","Niederösterreich"),
("ATQ049LHR0","AT","Schwanenstadt","Oberösterreich"),
("AT7LVW76KD","AT","Schwaz","Tirol"),
("AT8RI58ODL","AT","Schwechat","Niederösterreich"),
("ATDP95ESY4","AT","Seekirchen am Wallersee","Salzburg"),
("ATS2EEJ5FQ","AT","Spielberg","Steiermark"),
("ATQANYH7BP","AT","Spittal an der Drau","Kärnten"),
("ATYTV7H9SU","AT","St. Johann im Pongau","Salzburg"),
("ATY1ZCTYHM","AT","St. Pölten","Niederösterreich"),
("AT0V0K0GBR","AT","St. Valentin","Niederösterreich"),
("ATQYQ761X5","AT","Stadtschlaining","Burgenland"),
("ATUSCC2570","AT","Steyr","Oberösterreich"),
("AT77D15UN6","AT","Steyregg","Oberösterreich"),
("ATPORQ42IV","AT","Stockerau","Niederösterreich"),
("AT1837A1C4","AT","Straßburg","Kärnten"),
("ATUPHWVOX2","AT","Ternitz","Niederösterreich"),
("ATVA315R7V","AT","Traiskirchen","Niederösterreich"),
("ATGYLL14G3","AT","Traismauer","Niederösterreich"),
("ATCKAMLNRF","AT","Traun","Oberösterreich"),
("ATD9B8X8BT","AT","Trieben","Steiermark"),
("ATJFUO72JN","AT","Trofaiach","Steiermark"),
("AT15839P6M","AT","Tulln an der Donau","Niederösterreich"),
("AT9G9U41AI","AT","Villach","Kärnten"),
("ATALR8U21D","AT","Vils","Tirol"),
("ATIW2PZLD0","AT","Vöcklabruck","Oberösterreich"),
("ATRL30B9NL","AT","Voitsberg","Steiermark"),
("ATQWGUYQC8","AT","Völkermarkt","Kärnten"),
("ATC3H66IKO","AT","Waidhofen an der Thaya","Niederösterreich"),
("ATFNEE9RE0","AT","Waidhofen an der Ybbs","Niederösterreich"),
("ATDI1ORO9I","AT","Weitra","Niederösterreich"),
("ATLPCJGPSS","AT","Weiz","Steiermark"),
("ATT9Z0SJP7","AT","Wels","Oberösterreich"),
("AT73LGV0G8","AT","Wien","Wien"),
("ATIHXA67SS","AT","Wiener Neustadt","Niederösterreich"),
("ATX5BDV35P","AT","Wieselburg","Niederösterreich"),
("ATD5Q5OFCW","AT","Wilhelmsburg","Niederösterreich"),
("ATJYCEZSNI","AT","Wolfsberg","Kärnten"),
("ATALSHSL9Q","AT","Wolkersdorf im Weinviertel","Niederösterreich"),
("ATRL3NP9C2","AT","Wörgl","Tirol"),
("ATE273IKZ1","AT","Ybbs an der Donau","Niederösterreich"),
("ATICGH440F","AT","Zell am See","Salzburg"),
("ATPSXIE686","AT","Zeltweg","Steiermark"),
("ATSCTHM6J1","AT","Zistersdorf","Niederösterreich"),
("AT9Q4RA4TT","AT","Zwettl-Niederösterreich","Niederösterreich");