INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("CH36GIE4IX","CH","Aargau",NULL),
("CH72WP14I3","CH","Appenzell Ausserrhoden",NULL),
("CH2ZZE3374","CH","Appenzell Innerrhoden",NULL),
("CH7AIIAYBD","CH","Basel-Landschaft",NULL),
("CH4RVIVEG2","CH","Bern",NULL),
("CHHCRJHANJ","CH","Fribourg",NULL),
("CH9MXCP4GX","CH","Genève",NULL),
("CHEZFPYQ32","CH","Glarus",NULL),
("CHHZLDE2GV","CH","Graubünden",NULL),
("CHF8FWI2FR","CH","Jura",NULL),
("CHPD4FHLCW","CH","Kanton Basel-Stadt",NULL),
("CHLSMJIPM0","CH","Kanton St. Gallen",NULL),
("CHP8E3AVZP","CH","Luzern",NULL),
("CH3ELMH1E7","CH","Neuchâtel",NULL),
("CHEJMW4ZSQ","CH","Nidwalden",NULL),
("CHRE9A4WAT","CH","Obwalden",NULL),
("CH4PWFKV4O","CH","Schaffhausen",NULL),
("CHAQBSRPZ6","CH","Schwyz",NULL),
("CH9M2ELU4D","CH","Solothurn",NULL),
("CH9ENDAX7F","CH","Thurgau",NULL),
("CHN3U7ZYVA","CH","Ticino",NULL),
("CHP62GW1N6","CH","Uri",NULL),
("CHOPK9KONT","CH","Valais",NULL),
("CH2A7D8ESV","CH","Vaud",NULL),
("CHIM2HLYRB","CH","Zug",NULL),
("CH5TS2VF8J","CH","Zürich",NULL);