INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("CO02PMU1HH","CO","Amazonas",NULL),
("COW3GM8X08","CO","Antioquia",NULL),
("COW2V9NZG8","CO","Arauca",NULL),
("COAB2JQLKR","CO","Archipiélago de San Andrés, Providencia y San",NULL),
("COO9DJBV08","CO","Atlántico",NULL),
("COZHV8EVGB","CO","Bogota D.C.",NULL),
("COYCKMB0UL","CO","Bolívar",NULL),
("COBX42IPT7","CO","Boyacá",NULL),
("COZ7QB2RJ1","CO","Caldas",NULL),
("CO8E9NAQY8","CO","Caquetá",NULL),
("CO2IUEJPZV","CO","Casanare",NULL),
("COM4X5URCT","CO","Cauca",NULL),
("COY351UO23","CO","Cesar",NULL),
("CO3CQD3PM5","CO","Chocó",NULL),
("CO7GKR6KMS","CO","Córdoba",NULL),
("COOKXJB9DA","CO","Cundinamarca",NULL),
("COCIB76EA9","CO","Guainía",NULL),
("COR0NUP9ZX","CO","Guaviare",NULL),
("COQKOW4BPS","CO","Huila",NULL),
("COVMC6WPG9","CO","La Guajira",NULL),
("CO7SGE6RNX","CO","Magdalena",NULL),
("COSASIKSFA","CO","Meta",NULL),
("COC47GFW9B","CO","Nariño",NULL),
("COILHFAYPH","CO","Norte de Santander",NULL),
("COR5VYXJWP","CO","Putumayo",NULL),
("COUO7EGNPS","CO","Quindío",NULL),
("CORW87THIC","CO","Risaralda",NULL),
("CO20RDZGUQ","CO","Santander",NULL),
("COMQPJAL94","CO","Sucre",NULL),
("CO9GJQ39IV","CO","Tolima",NULL),
("CO6R2Z8LBB","CO","Valle del Cauca",NULL),
("COM2OLJJC6","CO","Vaupés",NULL),
("COA1PKNYPW","CO","Vichada",NULL);