INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("CUV6L9POPC","CU","Camagüey",NULL),
("CU2RO4L0UW","CU","Ciego de Ávila",NULL),
("CUVXO19CPG","CU","Cienfuegos",NULL),
("CUGGODXTLT","CU","Ciudad de La Habana",NULL),
("CU072PVS2Y","CU","Granma",NULL),
("CUJR24RX1N","CU","Guantánamo",NULL),
("CUUPO32EKJ","CU","Holguín",NULL),
("CUU8WS2HL3","CU","Isla de la Juventud",NULL),
("CUPNTKGVJ0","CU","La Habana",NULL),
("CUMM4DJ61E","CU","Las Tunas",NULL),
("CUWPIY32IY","CU","Matanzas",NULL),
("CUBEQEWBIL","CU","Pinar del Río",NULL),
("CUZB6F6QFT","CU","Sancti Spíritus",NULL),
("CUCK7WQ8AM","CU","Santiago de Cuba",NULL),
("CUYTL1W308","CU","Villa Clara",NULL);