INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("CZ3RKU1Z6Q","CZ","Hlavní Mesto Praha",NULL),
("CZ54O07QBN","CZ","Hradec Kralove",NULL),
("CZQP0RY6TT","CZ","Jablonec nad Nisou",NULL),
("CZ5S290W53","CZ","Jiein",NULL),
("CZOQXPQ4GV","CZ","Jihlava",NULL),
("CZ94VHU74L","CZ","Jihočeský Kraj",NULL),
("CZX4CWA6PG","CZ","Karlovarský Kraj",NULL),
("CZZRPZOV2C","CZ","Kolin",NULL),
("CZL02C4I7D","CZ","Královéhradecký Kraj",NULL),
("CZN3UIBY38","CZ","Liberec",NULL),
("CZ3G4EMUUL","CZ","Liberecký Kraj",NULL),
("CZMKKAFNN1","CZ","Melnik",NULL),
("CZOPES8M6V","CZ","Mlada Boleslav",NULL),
("CZP1E00H93","CZ","Moravskoslezský Kraj",NULL),
("CZYDHK8C5U","CZ","Nachod",NULL),
("CZWQ5CESE2","CZ","Nymburk",NULL),
("CZISVQE2M4","CZ","Olomoucký Kraj",NULL),
("CZ3053IE7G","CZ","Pardubice",NULL),
("CZSP1017VY","CZ","Pardubický Kraj",NULL),
("CZX0ACSPFA","CZ","Plzeňský Kraj",NULL),
("CZIB1WDO1H","CZ","Semily",NULL),
("CZP6L7LSOD","CZ","South Moravian Region",NULL),
("CZHPEJW9HU","CZ","Středočeský Kraj",NULL),
("CZ9S72IMD0","CZ","Trutnov",NULL),
("CZYEXC2YTR","CZ","Ústecký Kraj",NULL),
("CZ5FZQ7N4P","CZ","Vysočina",NULL),
("CZCI99RR31","CZ","Zlínský Kraj",NULL);