INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("DERPPFXIJS","DE","Aach","BW"),
("DE477L47PG","DE","Aachen","NW"),
("DEKNHPAQKC","DE","Aalen","BW"),
("DEIC4ASXPJ","DE","Abenberg","BY"),
("DEMEZKXJC1","DE","Abensberg","BY"),
("DEQJMURCBC","DE","Achern","BW"),
("DEZS1AIMN1","DE","Achim","NI"),
("DEZRBRO1AA","DE","Adelsheim","BW"),
("DEF9UDS7EJ","DE","Adenau","RP"),
("DEQ1EIEPUE","DE","Adorf/Vogtl.","SN"),
("DEIWP0IC2H","DE","Ahaus","NW"),
("DE4D8SEJ3U","DE","Ahlen","NW"),
("DESY8L6N4W","DE","Ahrensburg","SH"),
("DEOJE389HQ","DE","Aichach","BY"),
("DE57ROJT6N","DE","Aichtal","BW"),
("DE7EGMXKHQ","DE","Aken/Elbe","ST"),
("DEJPCPCGM0","DE","Albstadt","BW"),
("DEZ148AMYG","DE","Alfeld/Leine","NI"),
("DETQ4DKA1R","DE","Allendorf/Lumda","HE"),
("DEPIEN2VDM","DE","Allstedt","ST"),
("DEKPBW6XX6","DE","Alpirsbach","BW"),
("DEY1F9OEPH","DE","Alsdorf","NW"),
("DE4TVO4WGT","DE","Alsfeld","HE"),
("DEEUGHPU39","DE","Alsleben/Saale","ST"),
("DEKF6RC3XB","DE","Altdorf bei Nürnberg","BY"),
("DE5DKTR9BV","DE","Altena","NW"),
("DE26K6300I","DE","Altenberg","SN"),
("DEVGZLB3VV","DE","Altenburg","TH"),
("DEI1MV5K6A","DE","Altenkirchen/Westerwald","RP"),
("DEXQ4OZFK2","DE","Altensteig","BW"),
("DEM49P5971","DE","Altentreptow","MV"),
("DEQ7M1AHXT","DE","Altlandsberg","BB"),
("DEJJOO4UY1","DE","Altötting","BY"),
("DEK2PKHAN4","DE","Alzenau","BY"),
("DEEWTK61LX","DE","Alzey","RP"),
("DE88YJPWC8","DE","Amberg","BY"),
("DEF0XJVVLG","DE","Amöneburg","HE"),
("DEYB0GLOK0","DE","Amorbach","BY"),
("DEKDKQE6NN","DE","Andernach","RP"),
("DEEM64IJDY","DE","Angermünde","BB"),
("DEKAIF63V4","DE","Anklam, Hansestadt","MV"),
("DEEWK0K405","DE","Annaberg-Buchholz","SN"),
("DEILWXRKK6","DE","Annaburg","ST"),
("DE7RBPAPOU","DE","Annweiler am Trifels","RP"),
("DE0796B5AQ","DE","Ansbach","BY"),
("DE2VQN0QTI","DE","Apolda","TH"),
("DEBPG3A0AH","DE","Arendsee/Altmark","ST"),
("DERL72AVWA","DE","Arneburg","ST"),
("DE36HECS4F","DE","Arnis","SH"),
("DENV3OLW6X","DE","Arnsberg","NW"),
("DEMN1WNBDF","DE","Arnstadt","TH"),
("DEXKH7GEIJ","DE","Arnstein","BY"),
("DEK0XWS2CG","DE","Arnstein","ST"),
("DEXF4IBBGY","DE","Artern/Unstrut","TH"),
("DEYHULT71Q","DE","Arzberg","BY"),
("DESJY8XHRH","DE","Aschaffenburg","BY"),
("DEHPE9RQPO","DE","Aschersleben","ST"),
("DE6U7I5NG3","DE","Asperg","BW"),
("DE5BPZIQPB","DE","Aßlar","HE"),
("DEAOJ75BOM","DE","Attendorn","NW"),
("DE03WRUMG0","DE","Aub","BY"),
("DEGNJLBZPG","DE","Aue","SN"),
("DEBEGU555F","DE","Auerbach in der Oberpfalz","BY"),
("DETOMZ0BM0","DE","Auerbach/Vogtl.","SN"),
("DEFIS958AL","DE","Augsburg","BY"),
("DEVU76UWN5","DE","Augustusburg","SN"),
("DEA3ZG94W3","DE","Aulendorf","BW"),
("DETJ2TUOUA","DE","Auma-Weidatal","TH"),
("DE7MKCVUXQ","DE","Aurich","NI"),
("DEP4XJ0KOB","DE","Babenhausen","HE"),
("DEONSXSO0M","DE","Bacharach","RP"),
("DE73G2RACY","DE","Backnang","BW"),
("DEXWASR8JG","DE","Bad Aibling","BY"),
("DEDGZD1OPQ","DE","Bad Arolsen","HE"),
("DECHN56ORD","DE","Bad Belzig","BB"),
("DES7FJISIG","DE","Bad Bentheim","NI"),
("DEOT8G1SXE","DE","Bad Bergzabern","RP"),
("DE9XSALI1Y","DE","Bad Berka","TH"),
("DEZP35DUJ5","DE","Bad Berleburg","NW"),
("DE2ZPLR71G","DE","Bad Berneck im Fichtelgebirge","BY"),
("DE1AX22UHB","DE","Bad Bevensen","NI"),
("DER9MCRNBR","DE","Bad Bibra","ST"),
("DECEXQ9GWC","DE","Bad Blankenburg","TH"),
("DEGMX7UZOV","DE","Bad Bramstedt","SH"),
("DE9LYCFFO6","DE","Bad Breisig","RP"),
("DEPBJHZU8C","DE","Bad Brückenau","BY"),
("DE963INZU3","DE","Bad Buchau","BW"),
("DEMSBGRZB0","DE","Bad Camberg","HE"),
("DELAD0P27E","DE","Bad Colberg-Heldburg","TH"),
("DEDRVCL4OU","DE","Bad Doberan","MV"),
("DEBRDYR82D","DE","Bad Driburg","NW"),
("DE0DURD6SY","DE","Bad Düben","SN"),
("DEG6Z686KL","DE","Bad Dürkheim","RP"),
("DEXGXJLMEW","DE","Bad Dürrenberg","ST"),
("DEERV6ZXJ0","DE","Bad Dürrheim","BW"),
("DEBERPKKN1","DE","Bad Elster","SN"),
("DEQM7YTSKQ","DE","Bad Ems","RP"),
("DE8I9U4NRJ","DE","Bad Fallingbostel","NI"),
("DEFMPFK9FW","DE","Bad Frankenhausen/Kyffhäuser","TH"),
("DEN7L8S99I","DE","Bad Freienwalde/Oder","BB"),
("DEWHHP91GI","DE","Bad Friedrichshall","BW"),
("DEJQCNE47T","DE","Bad Gandersheim","NI"),
("DERW9B5P8T","DE","Bad Gottleuba-Berggießhübel","SN"),
("DEWU1O4B70","DE","Bad Griesbach im Rottal","BY"),
("DETOQ2P6K9","DE","Bad Harzburg","NI"),
("DEXXXB245T","DE","Bad Herrenalb","BW"),
("DE0E464DZ1","DE","Bad Hersfeld","HE"),
("DE71PBDXC6","DE","Bad Homburg vor der Höhe","HE"),
("DEM28B9TL6","DE","Bad Honnef","NW"),
("DERIITMNMN","DE","Bad Hönningen","RP"),
("DE2RT65T7C","DE","Bad Iburg","NI"),
("DEUXO7U1DG","DE","Bad Karlshafen","HE"),
("DE3MSDFEK7","DE","Bad Kissingen","BY"),
("DEW20JQN6S","DE","Bad König","HE"),
("DEF0YKT6XN","DE","Bad Königshofen im Grabfeld","BY"),
("DE3LUYN8FQ","DE","Bad Köstritz","TH"),
("DEU849MOHJ","DE","Bad Kötzting","BY"),
("DERH2H58AK","DE","Bad Kreuznach","RP"),
("DE8941F2PJ","DE","Bad Krozingen","BW"),
("DEOJIBSY2M","DE","Bad Laasphe","NW"),
("DE66WTVDCN","DE","Bad Langensalza","TH"),
("DEVE40MFLV","DE","Bad Lauchstädt","ST"),
("DEOQX3SMNG","DE","Bad Lausick","SN"),
("DE65RY3TKA","DE","Bad Lauterberg im Harz","NI"),
("DE0H3WUFJP","DE","Bad Liebenstein","TH"),
("DEUOQH3BCR","DE","Bad Liebenwerda","BB"),
("DE19VUWIA2","DE","Bad Liebenzell","BW"),
("DEO21SWM2X","DE","Bad Lippspringe","NW"),
("DE35TXLCNF","DE","Bad Lobenstein","TH"),
("DE0EW3P9VR","DE","Bad Marienberg/Westerwald","RP"),
("DEJQLF8WIX","DE","Bad Mergentheim","BW"),
("DEZJPV6RT9","DE","Bad Münder am Deister","NI"),
("DEXM7JYUYZ","DE","Bad Münstereifel","NW"),
("DE8V3Y5YPO","DE","Bad Muskau","SN"),
("DEOB4X8NU7","DE","Bad Nauheim","HE"),
("DE7J3DBWM9","DE","Bad Nenndorf","NI"),
("DEITSHORHW","DE","Bad Neuenahr-Ahrweiler","RP"),
("DEMKVRJLG7","DE","Bad Neustadt an der Saale","BY"),
("DEWK558ZCF","DE","Bad Oeynhausen","NW"),
("DEJGSVDE4W","DE","Bad Oldesloe","SH"),
("DE7WDVNVS9","DE","Bad Orb","HE"),
("DEFN1Y9I65","DE","Bad Pyrmont","NI"),
("DE2BBABNQV","DE","Bad Rappenau","BW"),
("DE4IQHWUD4","DE","Bad Reichenhall","BY"),
("DEQR0EMTO2","DE","Bad Rodach","BY"),
("DEGP1P88VA","DE","Bad Sachsa","NI"),
("DEK6LVUBQZ","DE","Bad Säckingen","BW"),
("DEUHGQBUV2","DE","Bad Salzdetfurth","NI"),
("DEMVG9O4B5","DE","Bad Salzuflen","NW"),
("DEUDV2MRD6","DE","Bad Salzungen","TH"),
("DEXZ2SBTS5","DE","Bad Saulgau","BW"),
("DEA9WM3ROP","DE","Bad Schandau","SN"),
("DEM5YB9AG4","DE","Bad Schmiedeberg","ST"),
("DEOC7A3KH1","DE","Bad Schussenried","BW"),
("DEKJTVCM1N","DE","Bad Schwalbach","HE"),
("DEVY9YPXOC","DE","Bad Schwartau","SH"),
("DE3NNDX4HM","DE","Bad Segeberg","SH"),
("DEGOWJ9ELU","DE","Bad Sobernheim","RP"),
("DEXFQA1RXW","DE","Bad Soden am Taunus","HE"),
("DEP7UF5JR8","DE","Bad Soden-Salmünster","HE"),
("DE6FL4K3Q1","DE","Bad Sooden-Allendorf","HE"),
("DESNL116WZ","DE","Bad Staffelstein","BY"),
("DELM9ME7I4","DE","Bad Sulza","TH"),
("DEEDJJWBS2","DE","Bad Sülze","MV"),
("DEQD6BGXC9","DE","Bad Teinach-Zavelstein","BW"),
("DEKXAM37LO","DE","Bad Tennstedt","TH"),
("DETVA73TBH","DE","Bad Tölz","BY"),
("DE6U126U5W","DE","Bad Urach","BW"),
("DE7C8O9KXU","DE","Bad Vilbel","HE"),
("DEH8GLF2A9","DE","Bad Waldsee","BW"),
("DEYLG1ESJL","DE","Bad Wildbad","BW"),
("DEMLNSFTPN","DE","Bad Wildungen","HE"),
("DE5XCFI990","DE","Bad Wilsnack","BB"),
("DEIQLYTV7R","DE","Bad Wimpfen","BW"),
("DEHNSVFCG2","DE","Bad Windsheim","BY"),
("DEX4VCXL03","DE","Bad Wörishofen","BY"),
("DEJCI1MS14","DE","Bad Wünnenberg","NW"),
("DEIN3CJA30","DE","Bad Wurzach","BW"),
("DEYWVE8CH6","DE","Baden-Baden","BW"),
("DEGDJEYJIH","DE","Baesweiler","NW"),
("DEV0JHSLMB","DE","Baiersdorf","BY"),
("DE8PNR0RRY","DE","Balingen","BW"),
("DENNDWZU2G","DE","Ballenstedt","ST"),
("DE8LV64DO0","DE","Balve","NW"),
("DED8H6T4I1","DE","Bamberg","BY"),
("DET6TUXKTK","DE","Barby","ST"),
("DE76H71JO9","DE","Bargteheide","SH"),
("DE5JG9W5AA","DE","Barmstedt","SH"),
("DEDRH6WZ8Q","DE","Bärnau","BY"),
("DE51K2LDNT","DE","Barntrup","NW"),
("DEK41LOPVT","DE","Barsinghausen","NI"),
("DE8C35HDGU","DE","Barth","MV"),
("DE5X11X9R3","DE","Baruth/Mark","BB"),
("DEBB6WPUQ9","DE","Bassum","NI"),
("DEZRUNHQHQ","DE","Battenberg/Eder","HE"),
("DE2KWJXCE3","DE","Baumholder","RP"),
("DEAF48PVC0","DE","Baunach","BY"),
("DE7IXWDO5C","DE","Baunatal","HE"),
("DEG0ZXRHNT","DE","Bautzen","SN"),
("DE1KDZXR27","DE","Bayreuth","BY"),
("DE77GX2SX9","DE","Bebra","HE"),
("DEBV6OJC0Z","DE","Beckum","NW"),
("DEC0W3HKXJ","DE","Bedburg","NW"),
("DE5AJ22LAA","DE","Beelitz","BB"),
("DESQ7VJ45U","DE","Beerfelden","HE"),
("DE0BIJNJI0","DE","Beeskow","BB"),
("DEJF4101K5","DE","Beilngries","BY"),
("DEC47EPHOI","DE","Beilstein","BW"),
("DE8WER1JL1","DE","Belgern-Schildau","SN"),
("DEV4KJN3J7","DE","Bendorf","RP"),
("DEIO9IPUO1","DE","Bensheim","HE"),
("DEYVGOD56L","DE","Berching","BY"),
("DE2KD34Y4Z","DE","Berga/Elster","TH"),
("DE3PJRS3YA","DE","Bergen","NI"),
("DER8TG2II0","DE","Bergen auf Rügen","MV"),
("DEDZOR5VC7","DE","Bergheim","NW"),
("DEFPAKOFKS","DE","Bergisch Gladbach","NW"),
("DE43JW6I7X","DE","Bergkamen","NW"),
("DEQ1ESJXTX","DE","Bergneustadt","NW"),
("DEWHO1C18S","DE","Berka/Werra","TH"),
("DERJCGYX82","DE","Berlin","BE, Bundeshauptstadt"),
("DE0SZ7B641","DE","Bernau bei Berlin","BB"),
("DE8JURGNPC","DE","Bernburg/Saale","ST"),
("DE5DEIFNA6","DE","Bernkastel-Kues","RP"),
("DE6NM5KV7L","DE","Bernsdorf","SN"),
("DEO7SZEX1M","DE","Bernstadt a. d. Eigen","SN"),
("DEGVEWJ39P","DE","Bersenbrück","NI"),
("DEHN7WBH3H","DE","Besigheim","BW"),
("DE5QNQLUC9","DE","Betzdorf","RP"),
("DE249G2A3J","DE","Betzenstein","BY"),
("DE6HGQLPF2","DE","Beverungen","NW"),
("DEDMZO426A","DE","Bexbach","SL"),
("DEST0EOCOQ","DE","Biberach an der Riß","BW"),
("DEHX7K7A3D","DE","Biedenkopf","HE"),
("DERJ3D9JGN","DE","Bielefeld","NW"),
("DE5FCAIJKB","DE","Biesenthal","BB"),
("DECLQ1XESF","DE","Bietigheim-Bissingen","BW"),
("DEBZZJA3W2","DE","Billerbeck","NW"),
("DEM0FWKVKQ","DE","Bingen am Rhein","RP"),
("DEBW0UFL6S","DE","Birkenfeld","RP"),
("DE6WT4BMKN","DE","Bischofsheim an der Rhön","BY"),
("DEMJ6WN3YA","DE","Bischofswerda","SN"),
("DE4E6OAQEM","DE","Bismark/Altmark","ST"),
("DEMFG20NU7","DE","Bitburg","RP"),
("DEKOCVAWIW","DE","Bitterfeld-Wolfen","ST"),
("DEGPT3SRDX","DE","Blankenburg/Harz","ST"),
("DE6KLGBZ2Y","DE","Blankenhain","TH"),
("DEFJ0F6VNQ","DE","Blaubeuren","BW"),
("DEJ0MTW5QD","DE","Blaustein","BW"),
("DEUJHNBVKH","DE","Bleckede","NI"),
("DEG6XR60QL","DE","Bleicherode","TH"),
("DEJQ1PLOG5","DE","Blieskastel","SL"),
("DEO3ZL8PZ3","DE","Blomberg","NW"),
("DE9HRLCB2T","DE","Blumberg","BW"),
("DEH0KN1A9K","DE","Bobingen","BY"),
("DE1AANYRSN","DE","Böblingen","BW"),
("DEUR83H87Q","DE","Bocholt","NW"),
("DEPYB1AEUR","DE","Bochum","NW"),
("DEFFFGQO0S","DE","Bockenem","NI"),
("DEZBFX28KX","DE","Bodenwerder","NI"),
("DE0T0H178Q","DE","Bogen","BY"),
("DE5KSFYN7D","DE","Böhlen","SN"),
("DE3NUTCUMB","DE","Boizenburg/Elbe","MV"),
("DE6198AU5A","DE","Bonn","NW, Bundesstadt"),
("DEN6RPDZGJ","DE","Bonndorf im Schwarzwald","BW"),
("DEJ8ZIW7WZ","DE","Bönnigheim","BW"),
("DEUQS7LFJR","DE","Bopfingen","BW"),
("DEGS0QN51B","DE","Boppard","RP"),
("DECS0PSG9C","DE","Borgentreich","NW"),
("DEP8ULFQKA","DE","Borgholzhausen","NW"),
("DEHDI3S1U9","DE","Borken","NW"),
("DEUV0H01SD","DE","Borken","HE"),
("DEUT3MACYZ","DE","Borkum","NI"),
("DELTL1K6B2","DE","Borna","SN"),
("DEKU5DVZMQ","DE","Bornheim","NW"),
("DEUN7VP09J","DE","Bottrop","NW"),
("DETC63O539","DE","Boxberg","BW"),
("DEYPAJVMLF","DE","Brackenheim","BW"),
("DEHQSCQF2L","DE","Brake/Unterweser","NI"),
("DE3AHSAQB4","DE","Brakel","NW"),
("DE2I8RNC1M","DE","Bramsche","NI"),
("DE1C6WZRCG","DE","Brand-Erbisdorf","SN"),
("DEI5S9LVVO","DE","Brandenburg an der Havel","BB"),
("DE6CGH3SM6","DE","Brandis","SN"),
("DEAUXY6YL8","DE","Braubach","RP"),
("DEBR5AJHQ2","DE","Braunfels","HE"),
("DENJB8F6WL","DE","Braunlage","NI"),
("DEJD3M5PTG","DE","Bräunlingen","BW"),
("DEKQERP0Z0","DE","Braunsbedra","ST"),
("DER4AAM1C9","DE","Braunschweig","NI"),
("DEKOHZUELE","DE","Breckerfeld","NW"),
("DERO1XEUDY","DE","Bredstedt","SH"),
("DELSQBSPCJ","DE","Breisach am Rhein","BW"),
("DEUMUGO7Q8","DE","Bremen, Freie Hansestadt","HB"),
("DEV88QMT5E","DE","Bremerhaven","HB"),
("DEI6BX1OWM","DE","Bremervörde","NI"),
("DEGMY9CAT6","DE","Bretten","BW"),
("DEXONLVDUR","DE","Breuberg","HE"),
("DEL2I8WOME","DE","Brilon","NW"),
("DEUXBWM8J3","DE","Brotterode-Trusetal","TH"),
("DEUHC6R6DO","DE","Bruchköbel","HE"),
("DEU0APE4HZ","DE","Bruchsal","BW"),
("DE6082OUHJ","DE","Brück","BB"),
("DESTFF1YIW","DE","Brüel","MV"),
("DEFV271FWV","DE","Brühl","NW"),
("DEG6LUA2UH","DE","Brunsbüttel","SH"),
("DE32KRX2AQ","DE","Brüssow","BB"),
("DEVQ5XONT4","DE","Buchen/Odenwald","BW"),
("DEIVCKB8FR","DE","Buchholz in der Nordheide","NI"),
("DEF0MQ3G76","DE","Buchloe","BY"),
("DEJSXHU87P","DE","Bückeburg","NI"),
("DEYDMM1FRK","DE","Buckow/Märkische Schweiz","BB"),
("DEB34NCJFR","DE","Büdelsdorf","SH"),
("DEJ1HMIPT1","DE","Büdingen","HE"),
("DEHQJBZQ1X","DE","Bühl","BW"),
("DE4OK54BPG","DE","Bünde","NW"),
("DEFT3RDIJW","DE","Büren","NW"),
("DEK0J3QD47","DE","Burg","ST"),
("DE3OJ2FL0J","DE","Burg Stargard","MV"),
("DEAKOEWDUC","DE","Burgau","BY"),
("DE7Y4KHNH1","DE","Burgbernheim","BY"),
("DEO14EE9MI","DE","Burgdorf","NI"),
("DEY6LDSLW2","DE","Bürgel","TH"),
("DE6KH3YCF6","DE","Burghausen","BY"),
("DEBKQS88UW","DE","Burgkunstadt","BY"),
("DE9ZBO9Y67","DE","Burglengenfeld","BY"),
("DE5SKYDG0K","DE","Burgstädt","SN"),
("DE0INZV356","DE","Burgwedel","NI"),
("DENWYV4SSE","DE","Burladingen","BW"),
("DES3212987","DE","Burscheid","NW"),
("DE1S5F86Z9","DE","Bürstadt","HE"),
("DEPN9KQEQD","DE","Buttelstedt","TH"),
("DEAP9FH1T9","DE","Buttstädt","TH"),
("DE5WB75JF7","DE","Butzbach","HE"),
("DEBLMKSMUH","DE","Bützow","MV"),
("DE942ZISDT","DE","Buxtehude","NI"),
("DEHM9ZO29T","DE","Calau","BB"),
("DEZK154HCG","DE","Calbe/Saale","ST"),
("DE3Z1VLVDV","DE","Calw","BW"),
("DEZGVI88CQ","DE","Castrop-Rauxel","NW"),
("DEVLQKO0EO","DE","Celle","NI"),
("DEKFTPW550","DE","Cham","BY"),
("DE56WR29M2","DE","Chemnitz","SN"),
("DEPHKYQXPM","DE","Clausthal-Zellerfeld","NI"),
("DEJF67FKV0","DE","Clingen","TH"),
("DE0PPXVUX0","DE","Cloppenburg","NI"),
("DE1TR33E6T","DE","Coburg","BY"),
("DEVRRMOH87","DE","Cochem","RP"),
("DEWFFCZBCZ","DE","Coesfeld","NW"),
("DE02XVXUWY","DE","Colditz","SN"),
("DENO2R28KY","DE","Coswig","SN"),
("DEZCKOTTVP","DE","Coswig/Anhalt","ST"),
("DE8B18ME8N","DE","Cottbus","BB"),
("DEG5IDZFBN","DE","Crailsheim","BW"),
("DE3EE5MY3M","DE","Creglingen","BW"),
("DEBOA4H6TP","DE","Creußen","BY"),
("DEHVX496RP","DE","Creuzburg","TH"),
("DEBA2BPEYT","DE","Crimmitschau","SN"),
("DETDYGC22N","DE","Crivitz","MV"),
("DEQDR8JLY1","DE","Cuxhaven","NI"),
("DEGW5P2XFD","DE","Dachau","BY"),
("DE8IOXXNQQ","DE","Dahlen","SN"),
("DE0P6DS80J","DE","Dahme/Mark","BB"),
("DEMRR5DP7T","DE","Dahn","RP"),
("DEMDJOAY2I","DE","Damme","NI"),
("DEGQGDE74E","DE","Dannenberg/Elbe","NI"),
("DEXASPJS85","DE","Dargun","MV"),
("DEK0BXQIRC","DE","Darmstadt","HE"),
("DEVA1683OP","DE","Dassel","NI"),
("DEU538C7N9","DE","Dassow","MV"),
("DEHFZ1776S","DE","Datteln","NW"),
("DE8HQYZHAV","DE","Daun","RP"),
("DERB1ZFQP9","DE","Deggendorf","BY"),
("DEVSH804HI","DE","Deidesheim","RP"),
("DEKGJSOPKW","DE","Delbrück","NW"),
("DE6AU6S51J","DE","Delitzsch","SN"),
("DEH3JWT85P","DE","Delmenhorst","NI"),
("DE1NX1SFJC","DE","Demmin, Hansestadt","MV"),
("DEW24KRPHY","DE","Dessau-Roßlau","ST"),
("DEZC5RH7BZ","DE","Detmold","NW"),
("DEAUW432T4","DE","Dettelbach","BY"),
("DEPQ6I5PU2","DE","Dieburg","HE"),
("DESYMKN3JN","DE","Diemelstadt","HE"),
("DEFOFXVQX5","DE","Diepholz","NI"),
("DELU9OW3TM","DE","Dierdorf","RP"),
("DETZ4ZPY1H","DE","Dietenheim","BW"),
("DEXO2KSL88","DE","Dietfurt an der Altmühl","BY"),
("DE9N65E3AZ","DE","Dietzenbach","HE"),
("DEXKOUNHGH","DE","Diez","RP"),
("DEGKH5JJNG","DE","Dillenburg","HE"),
("DE7P10B98L","DE","Dillingen an der Donau","BY"),
("DEXEQCH1CF","DE","Dillingen/Saar","SL"),
("DEM09AHPSX","DE","Dingelstädt","TH"),
("DEA93TSRA0","DE","Dingolfing","BY"),
("DEHB0SL9DJ","DE","Dinkelsbühl","BY"),
("DEN4V557KS","DE","Dinklage","NI"),
("DE8U2PJUNU","DE","Dinslaken","NW"),
("DE4ROXIYXZ","DE","Dippoldiswalde","SN"),
("DEAYSV76FV","DE","Dissen am Teutoburger Wald","NI"),
("DEAA0GIK8Q","DE","Ditzingen","BW"),
("DEFBGZ53TA","DE","Döbeln","SN"),
("DEUH7DG5CQ","DE","Doberlug-Kirchhain","BB"),
("DE44MCA17L","DE","Döbern","BB"),
("DEC71VSAM7","DE","Dohna","SN"),
("DEL26R6010","DE","Dömitz","MV"),
("DEI8DZEQQI","DE","Dommitzsch","SN"),
("DEVCU5E1RR","DE","Donaueschingen","BW"),
("DE9SN1299O","DE","Donauwörth","BY"),
("DEBGFHGHIZ","DE","Donzdorf","BW"),
("DEQWY4MONI","DE","Dorfen","BY"),
("DE1HNGJE7S","DE","Dormagen","NW"),
("DE7UUA43YG","DE","Dornburg-Camburg","TH"),
("DEKEY1WG0M","DE","Dornhan","BW"),
("DEDZR0NEIO","DE","Dornstetten","BW"),
("DEV65ELC7S","DE","Dorsten","NW"),
("DE713C51SP","DE","Dortmund","NW"),
("DEGQQC7RZK","DE","Dransfeld","NI"),
("DEQQLE4330","DE","Drebkau","BB"),
("DE98FVKMNS","DE","Dreieich","HE"),
("DENR4SSXH9","DE","Drensteinfurt","NW"),
("DEN8MVZLGQ","DE","Dresden","SN"),
("DEB14G57GF","DE","Drolshagen","NW"),
("DEFWA0IYT5","DE","Duderstadt","NI"),
("DEPYYIVGRI","DE","Duisburg","NW"),
("DEODEOZUFB","DE","Dülmen","NW"),
("DEVKR1R8G7","DE","Düren","NW"),
("DE4Q8MP1SE","DE","Düsseldorf","NW"),
("DEZQXU7ODW","DE","Ebeleben","TH"),
("DE2RL2M0DI","DE","Eberbach","BW"),
("DEK4JCDZJH","DE","Ebermannstadt","BY"),
("DEPS4FUXTT","DE","Ebern","BY"),
("DEOQOVF2RI","DE","Ebersbach an der Fils","BW"),
("DEUDKGDXYY","DE","Ebersbach-Neugersdorf","SN"),
("DE2HAFGUX6","DE","Ebersberg","BY"),
("DEM1MGZFAN","DE","Eberswalde","BB"),
("DE6ZJL2B4W","DE","Eckartsberga","ST"),
("DEOOD1MB0O","DE","Eckernförde","SH"),
("DETA3A50HS","DE","Edenkoben","RP"),
("DE2391JKPP","DE","Egeln","ST"),
("DEJ8BLJFI7","DE","Eggenfelden","BY"),
("DE4V9Q79E0","DE","Eggesin","MV"),
("DEJIAPISHL","DE","Ehingen/Donau","BW"),
("DEVQMEAC4U","DE","Ehrenfriedersdorf","SN"),
("DEKFF3VXAZ","DE","Eibelstadt","BY"),
("DETJP0S40C","DE","Eibenstock","SN"),
("DENB163JRZ","DE","Eichstätt","BY"),
("DE9EEJQIEA","DE","Eilenburg","SN"),
("DEXTETRPSK","DE","Einbeck","NI"),
("DE9IL2NLEA","DE","Eisenach","TH"),
("DEXGG1Z709","DE","Eisenberg","TH"),
("DEMETCW7NU","DE","Eisenberg/Pfalz","RP"),
("DE01OSRGD0","DE","Eisenhüttenstadt","BB"),
("DEZY2MKGXH","DE","Eisfeld","TH"),
("DEXDIXLJ68","DE","Eisleben, Lutherstadt","ST"),
("DEXZKU68P7","DE","Eislingen/Fils","BW"),
("DEADZ1UD1T","DE","Ellingen","BY"),
("DEC3GWKEEI","DE","Ellrich","TH"),
("DERWFDGLLD","DE","Ellwangen/Jagst","BW"),
("DEK68REYYP","DE","Elmshorn","SH"),
("DECYQ6CR0O","DE","Elsdorf","NW"),
("DEVHKGVZYN","DE","Elsfleth","NI"),
("DEWD0CZMQJ","DE","Elsterberg","SN"),
("DETYB7X9X9","DE","Elsterwerda","BB"),
("DE8NFKFG8A","DE","Elstra","SN"),
("DEXTRSSPFO","DE","Elterlein","SN"),
("DE2F112RLV","DE","Eltmann","BY"),
("DEQW3N60XE","DE","Eltville am Rhein","HE"),
("DEOCZ3S8EP","DE","Elzach","BW"),
("DE25HVVXKX","DE","Elze","NI"),
("DEDLZFCKB3","DE","Emden","NI"),
("DEHEQNFN23","DE","Emmelshausen","RP"),
("DE027TBMJD","DE","Emmendingen","BW"),
("DES18NYSLB","DE","Emmerich am Rhein","NW"),
("DEDKQQ52TN","DE","Emsdetten","NW"),
("DEGKBW7E08","DE","Endingen am Kaiserstuhl","BW"),
("DEG71RUK4N","DE","Engen","BW"),
("DELDBK5WVJ","DE","Enger","NW"),
("DEHM9MO295","DE","Ennepetal","NW"),
("DEMK1UY13F","DE","Ennigerloh","NW"),
("DE9574PCRB","DE","Eppelheim","BW"),
("DEP3VVZREG","DE","Eppingen","BW"),
("DEDO32QD7D","DE","Eppstein","HE"),
("DEY98XBBDL","DE","Erbach","BW"),
("DEGKP6WHIL","DE","Erbach/Odenwald","HE"),
("DEKEHK5V1J","DE","Erbendorf","BY"),
("DEJ5LAISOH","DE","Erding","BY"),
("DE1XFD9SYQ","DE","Erftstadt","NW"),
("DECNW85FUQ","DE","Erfurt","TH"),
("DEUCAZ7CIR","DE","Erkelenz","NW"),
("DEH320WQHY","DE","Erkner","BB"),
("DENWBXO9N1","DE","Erkrath","NW"),
("DEXKA3Z5TT","DE","Erlangen","BY"),
("DEH4TPGCGY","DE","Erlenbach am Main","BY"),
("DEGIYC9FBX","DE","Erlensee","HE"),
("DECMU0WH2U","DE","Erwitte","NW"),
("DE1CY1HSVY","DE","Eschborn","HE"),
("DEWOND04BG","DE","Eschenbach in der Oberpfalz","BY"),
("DEN9TWP5T1","DE","Eschershausen","NI"),
("DERO2O54J7","DE","Eschwege","HE"),
("DEGH9Y94W6","DE","Eschweiler","NW"),
("DETKKUOWBB","DE","Esens","NI"),
("DE648V92W1","DE","Espelkamp","NW"),
("DEQZQW3A4J","DE","Essen","NW"),
("DERDH1IE8B","DE","Esslingen am Neckar","BW"),
("DEZS5NPGZV","DE","Ettenheim","BW"),
("DEL7QVANW0","DE","Ettlingen","BW"),
("DEMNXPX19P","DE","Euskirchen","NW"),
("DEFRRX6095","DE","Eutin","SH"),
("DETETIVSDG","DE","Falkenberg/Elster","BB"),
("DE04BAR8BD","DE","Falkensee","BB"),
("DEW93TBDJQ","DE","Falkenstein/Harz","ST"),
("DE5BOBBXG4","DE","Falkenstein/Vogtl.","SN"),
("DEC9M720N2","DE","Fehmarn","SH"),
("DE4YDV7O93","DE","Fellbach","BW"),
("DEYDX9QHZW","DE","Felsberg","HE"),
("DESO74LO8Y","DE","Feuchtwangen","BY"),
("DEYV50WS30","DE","Filderstadt","BW"),
("DERGWY5623","DE","Finsterwalde","BB"),
("DEJZCAGC69","DE","Fladungen","BY"),
("DE0EDM2MK0","DE","Flensburg","SH"),
("DEHQ1DI4EA","DE","Flöha","SN"),
("DELA9RHBV0","DE","Flörsheim am Main","HE"),
("DEB8BSLI1L","DE","Florstadt","HE"),
("DEWF8Z1T0J","DE","Forchheim","BY"),
("DEJ1W26BCR","DE","Forchtenberg","BW"),
("DELMJ2YE39","DE","Forst/Lausitz","BB"),
("DEMF27X3TU","DE","Frankenau","HE"),
("DEJ2UKVU3F","DE","Frankenberg/Eder","HE"),
("DEV0H1BUTX","DE","Frankenberg/Sa.","SN"),
("DEHCZFR3OD","DE","Frankenthal/Pfalz","RP"),
("DEIRLGVFBE","DE","Frankfurt am Main","HE"),
("DEH5YDZ2TV","DE","Frankfurt/Oder","BB"),
("DE2BXE5QBM","DE","Franzburg","MV"),
("DE3B2UER8X","DE","Frauenstein","SN"),
("DEITDD9ORR","DE","Frechen","NW"),
("DETQ5TSYOV","DE","Freiberg","SN"),
("DE9L9FBK2F","DE","Freiberg am Neckar","BW"),
("DEW49AVH7D","DE","Freiburg im Breisgau","BW"),
("DEBLQKAIC4","DE","Freilassing","BY"),
("DE9HX2FLXP","DE","Freinsheim","RP"),
("DE774JS6YO","DE","Freising","BY"),
("DEA7Z5P7I0","DE","Freital","SN"),
("DES9L3SX71","DE","Freren","NI"),
("DEF43UQ1JX","DE","Freudenberg","BW"),
("DE8NG1UFP4","DE","Freudenberg","NW"),
("DEMO9BVSCO","DE","Freudenstadt","BW"),
("DE2YRUVZVB","DE","Freyburg/Unstrut","ST"),
("DE4Z5U0PS8","DE","Freystadt","BY"),
("DED997OZCB","DE","Freyung","BY"),
("DEOMMJFZ8H","DE","Fridingen an der Donau","BW"),
("DEX0CTZ743","DE","Friedberg","BY"),
("DE6AY60QFD","DE","Friedberg","HE"),
("DE0PLOOXZC","DE","Friedland","MV"),
("DEKMWZL5GJ","DE","Friedland","BB"),
("DE5SC50H87","DE","Friedrichroda","TH"),
("DER7ERYU5Y","DE","Friedrichsdorf","HE"),
("DEJRN7OMK8","DE","Friedrichshafen","BW"),
("DE9G8VLOER","DE","Friedrichstadt","SH"),
("DEHRWI85P0","DE","Friedrichsthal","SL"),
("DED4SBYY9H","DE","Friesack","BB"),
("DEPWPEJANS","DE","Friesoythe","NI"),
("DEQVOCJ241","DE","Fritzlar","HE"),
("DET1J2793K","DE","Frohburg","SN"),
("DEDVVCT5UI","DE","Fröndenberg/Ruhr","NW"),
("DE1KWLUJEL","DE","Fulda","HE"),
("DEE2YY420Y","DE","Fürstenau","NI"),
("DE3J1AS4V6","DE","Fürstenberg/Havel","BB"),
("DEZQITVDBX","DE","Fürstenfeldbruck","BY"),
("DEX8IRSWC7","DE","Fürstenwalde/Spree","BB"),
("DEYA63D62H","DE","Fürth","BY"),
("DEP3SI7NO7","DE","Furth im Wald","BY"),
("DED709KC6H","DE","Furtwangen im Schwarzwald","BW"),
("DELP9DLMLK","DE","Füssen","BY"),
("DEWRNAXQRN","DE","Gadebusch","MV"),
("DETJ517U9L","DE","Gaggenau","BW"),
("DE19UMM147","DE","Gaildorf","BW"),
("DEQDLBZ6WW","DE","Gammertingen","BW"),
("DEYK6VAYJ3","DE","Garbsen","NI"),
("DEIP5PJEAL","DE","Garching bei München","BY"),
("DEO58B6CIW","DE","Gardelegen","ST"),
("DEQ48PA4M9","DE","Garding","SH"),
("DEOT4YRO2A","DE","Gartz/Oder","BB"),
("DED7ZXMAIA","DE","Garz/Rügen","MV"),
("DEFQLL34HT","DE","Gau-Algesheim","RP"),
("DE9PJKU5TI","DE","Gebesee","TH"),
("DEZXHQMJ0Z","DE","Gedern","HE"),
("DEQ0WDAFOP","DE","Geesthacht","SH"),
("DE69A9ES2N","DE","Geestland","NI"),
("DEIM7CS0VR","DE","Gefell","TH"),
("DEYCILVIKM","DE","Gefrees","BY"),
("DEJHZTWNJ2","DE","Gehrden","NI"),
("DEXUCCMF05","DE","Gehren","TH"),
("DE18HT8DK7","DE","Geilenkirchen","NW"),
("DEP2SKLD74","DE","Geisa","TH"),
("DEU7YRVIUT","DE","Geiselhöring","BY"),
("DEC65ZL54N","DE","Geisenfeld","BY"),
("DEEMGNZ1UP","DE","Geisenheim","HE"),
("DE3NAP1HUW","DE","Geisingen","BW"),
("DEPSNKAIDN","DE","Geislingen","BW"),
("DEPJMBPRY3","DE","Geislingen an der Steige","BW"),
("DEDEQDFK2J","DE","Geithain","SN"),
("DE8C89U26J","DE","Geldern","NW"),
("DEVU36CHT1","DE","Gelnhausen","HE"),
("DE0GCP7ASL","DE","Gelsenkirchen","NW"),
("DEPIZ531OB","DE","Gemünden am Main","BY"),
("DEEXL8ZRSU","DE","Gemünden/Wohra","HE"),
("DEMV1YCU0C","DE","Gengenbach","BW"),
("DEBC2INU4D","DE","Genthin","ST"),
("DEC3IF57RK","DE","Georgsmarienhütte","NI"),
("DE4DT35LYR","DE","Gera","TH"),
("DEGZQTUQ65","DE","Gerabronn","BW"),
("DE38OQ3T3G","DE","Gerbstedt","ST"),
("DEXMV2TNMX","DE","Geretsried","BY"),
("DE1F171ZYI","DE","Geringswalde","SN"),
("DEZOBTFIZI","DE","Gerlingen","BW"),
("DERN8VGCBD","DE","Germering","BY"),
("DEZ7GSV3QW","DE","Germersheim","RP"),
("DEJR3KR22Q","DE","Gernsbach","BW"),
("DEREK6XJOP","DE","Gernsheim","HE"),
("DE6XKNAV09","DE","Gerolstein","RP"),
("DE2H1XKRU3","DE","Gerolzhofen","BY"),
("DEJXOA0Q0R","DE","Gersfeld/Rhön","HE"),
("DE5KX23MRA","DE","Gersthofen","BY"),
("DEJCXT7Y2A","DE","Gescher","NW"),
("DEG480W24F","DE","Geseke","NW"),
("DE0SQ0JQSP","DE","Gevelsberg","NW"),
("DEBPRFBJQV","DE","Geyer","SN"),
("DEVNP3MRD2","DE","Giengen an der Brenz","BW"),
("DEWL3SO78O","DE","Gießen","HE"),
("DE0YPKPH91","DE","Gifhorn","NI"),
("DE71HIL7EG","DE","Ginsheim-Gustavsburg","HE"),
("DEV3KHVXKR","DE","Gladbeck","NW"),
("DEJNK7VTWW","DE","Gladenbach","HE"),
("DERLHH3RIA","DE","Glashütte","SN"),
("DESZTE77U2","DE","Glauchau","SN"),
("DEBFK6C4XW","DE","Glinde","SH"),
("DESI4NB0K3","DE","Glücksburg/Ostsee","SH"),
("DEM1LPS4ZL","DE","Glückstadt","SH"),
("DE4TZB0UDC","DE","Gnoien","MV"),
("DE9XIM1GJT","DE","Goch","NW"),
("DEYNHAN1EA","DE","Goldberg","MV"),
("DE3Z0V3ZH7","DE","Goldkronach","BY"),
("DETHJUCW6L","DE","Golßen","BB"),
("DEUO8W4RQ3","DE","Gommern","ST"),
("DEE7E29SCC","DE","Göppingen","BW"),
("DESC8VCP36","DE","Görlitz","SN"),
("DE7N0JJ65E","DE","Goslar","NI"),
("DEUDAZ503J","DE","Gößnitz","TH"),
("DE8HMH9ZU1","DE","Gotha","TH"),
("DEC2XPS1VZ","DE","Göttingen","NI"),
("DEOVJ82OMX","DE","Grabow","MV"),
("DE1WW7XZR5","DE","Grafenau","BY"),
("DEHDNQDHSP","DE","Gräfenberg","BY"),
("DEJQECRACG","DE","Gräfenhainichen","ST"),
("DE6VO8JB5L","DE","Gräfenthal","TH"),
("DE82S52JBJ","DE","Grafenwöhr","BY"),
("DEXYAAF30Z","DE","Grafing bei München","BY"),
("DETECLPO1V","DE","Gransee","BB"),
("DEJQ3319OA","DE","Grebenau","HE"),
("DEBHFD1RWY","DE","Grebenstein","HE"),
("DEP785A853","DE","Greding","BY"),
("DENHPD6Q8P","DE","Greifswald, Hansestadt","MV"),
("DEHBTJKHTW","DE","Greiz","TH"),
("DEZ99006YQ","DE","Greußen","TH"),
("DED7VOG1R4","DE","Greven","NW"),
("DEIHHP7PEO","DE","Grevenbroich","NW"),
("DE188MQ1IP","DE","Grevesmühlen","MV"),
("DEASPAZO0C","DE","Griesheim","HE"),
("DEVW1CXTGG","DE","Grimma","SN"),
("DEAX5HNK6O","DE","Grimmen","MV"),
("DETEBJGT8Q","DE","Gröditz","SN"),
("DEMY1LM1YI","DE","Groitzsch","SN"),
("DEYZVWSBD2","DE","Gronau/Leine","NI"),
("DE9JKW3RLW","DE","Gronau/Westf.","NW"),
("DE6XGMROCD","DE","Gröningen","ST"),
("DENDYAFXTE","DE","Groß-Bieberau","HE"),
("DEWOAP0ORA","DE","Groß-Gerau","HE"),
("DE7C7B3S89","DE","Groß-Umstadt","HE"),
("DEPOVGD8U0","DE","Großalmerode","HE"),
("DELTA1Q4FN","DE","Großbottwar","BW"),
("DESQCSE43L","DE","Großbreitenbach","TH"),
("DEGAWJ34TS","DE","Großenehrich","TH"),
("DETO96W46I","DE","Großenhain","SN"),
("DEXHKOL0BD","DE","Großräschen","BB"),
("DERN65RAR8","DE","Großröhrsdorf","SN"),
("DEKORNTKGM","DE","Großschirma","SN"),
("DE9QS6UZPS","DE","Grünberg","HE"),
("DEGAG2ARF1","DE","Grünhain-Beierfeld","SN"),
("DEFM77WZFH","DE","Grünsfeld","BW"),
("DEN74HSK32","DE","Grünstadt","RP"),
("DEAW84VYXC","DE","Guben","BB"),
("DE8DEJ5UKK","DE","Gudensberg","HE"),
("DEHSSDR8VF","DE","Güglingen","BW"),
("DEFZW7J0AU","DE","Gummersbach","NW"),
("DEWIZSHW4P","DE","Gundelfingen an der Donau","BY"),
("DE9I9ECUZT","DE","Gundelsheim","BW"),
("DEMS7E02TG","DE","Günzburg","BY"),
("DE2QOLQYFN","DE","Gunzenhausen","BY"),
("DEHEFYAKOK","DE","Güsten","ST"),
("DE2XZFRZ9D","DE","Güstrow","MV"),
("DERHSSJL8L","DE","Gütersloh","NW"),
("DECW73UNQB","DE","Gützkow","MV"),
("DE269DRYXT","DE","Haan","NW"),
("DEVX9NWI1O","DE","Hachenburg","RP"),
("DEZTGJFO5R","DE","Hadamar","HE"),
("DEKDUF1LQ3","DE","Hagen","NW"),
("DES0GJYEDU","DE","Hagenbach","RP"),
("DECMH85IX5","DE","Hagenow","MV"),
("DEBDPQ1VHM","DE","Haiger","HE"),
("DE8C19XSDP","DE","Haigerloch","BW"),
("DEST8Q8MKK","DE","Hainichen","SN"),
("DE82TDKQJV","DE","Haiterbach","BW"),
("DE48L633SC","DE","Halberstadt","ST"),
("DEGUMDMZ3F","DE","Haldensleben","ST"),
("DETC61YQM7","DE","Halle/Saale","ST"),
("DETGLD748B","DE","Halle/Westf.","NW"),
("DEDUIHYATE","DE","Hallenberg","NW"),
("DE5FSSEW78","DE","Hallstadt","BY"),
("DE9D984WFX","DE","Haltern am See","NW"),
("DED0AK5JWJ","DE","Halver","NW"),
("DEEE0DPURU","DE","Hamburg, Freie und Hansestadt","HH"),
("DE9KNOHUWQ","DE","Hameln","NI"),
("DE86YC3DAG","DE","Hamm","NW"),
("DEEL1K5X3J","DE","Hammelburg","BY"),
("DEC3W1YOW7","DE","Hamminkeln","NW"),
("DE9JWQETGM","DE","Hanau","HE"),
("DE0EZ4SAL7","DE","Hann. Münden","NI"),
("DEVMS0KVKW","DE","Hannover","NI"),
("DEZHYX5U5E","DE","Harburg/Schwaben","BY"),
("DEE24TWLGW","DE","Hardegsen","NI"),
("DE0F1SQM0L","DE","Haren/Ems","NI"),
("DE9SMTO7QN","DE","Harsewinkel","NW"),
("DEOPLTKQ8Y","DE","Hartenstein","SN"),
("DESDRPY8MY","DE","Hartha","SN"),
("DENNRE9R0J","DE","Harzgerode","ST"),
("DEKMD8U3VI","DE","Haselünne","NI"),
("DESGBC7KB0","DE","Haslach im Kinzigtal","BW"),
("DEX3PVBBUZ","DE","Haßfurt","BY"),
("DEYLD8CDRX","DE","Hattersheim am Main","HE"),
("DE045U80C1","DE","Hattingen","NW"),
("DEHOEO8QO6","DE","Hatzfeld/Eder","HE"),
("DETD25OW5N","DE","Hausach","BW"),
("DEHIWUWNRX","DE","Hauzenberg","BY"),
("DESWS1X52E","DE","Havelberg","ST"),
("DETH327S91","DE","Havelsee","BB"),
("DE5B6U7CIO","DE","Hayingen","BW"),
("DEUEJR2APV","DE","Hechingen","BW"),
("DE7HW4MZJF","DE","Hecklingen","ST"),
("DEGNIOFRPL","DE","Heide","SH"),
("DE3WGA8YZ3","DE","Heideck","BY"),
("DEDIVFSKAZ","DE","Heidelberg","BW"),
("DE174O7N4O","DE","Heidenau","SN"),
("DEAMCQE2BH","DE","Heidenheim an der Brenz","BW"),
("DEZRS8QRC3","DE","Heilbad Heiligenstadt","TH"),
("DE97J1SU1U","DE","Heilbronn","BW"),
("DE15I8SMW3","DE","Heiligenhafen","SH"),
("DE99UNB55B","DE","Heiligenhaus","NW"),
("DEXXJOOWSX","DE","Heilsbronn","BY"),
("DE3BZW60Q7","DE","Heimbach","NW"),
("DE59GYVD24","DE","Heimsheim","BW"),
("DEMWSY2YAZ","DE","Heinsberg","NW"),
("DEWUOKQGIU","DE","Heitersheim","BW"),
("DESIQYIH5O","DE","Heldrungen","TH"),
("DEQMNM0QRN","DE","Helmbrechts","BY"),
("DENJMPIWPE","DE","Helmstedt","NI"),
("DEQDZGTHBL","DE","Hemau","BY"),
("DE01KJJP79","DE","Hemer","NW"),
("DECVVCMMZ9","DE","Hemmingen","NI"),
("DE6LYOIO38","DE","Hemmoor","NI"),
("DE12PVK0HK","DE","Hemsbach","BW"),
("DE213LRBU4","DE","Hennef/Sieg","NW"),
("DE7QGTDG2K","DE","Hennigsdorf","BB"),
("DE119JPCSR","DE","Heppenheim/Bergstraße","HE"),
("DEEHNYI5JK","DE","Herbolzheim","BW"),
("DE7M5YY035","DE","Herborn","HE"),
("DERJY401P1","DE","Herbrechtingen","BW"),
("DE2YLSAEJP","DE","Herbstein","HE"),
("DEW7OEC7ZJ","DE","Herdecke","NW"),
("DEU5IT5LYX","DE","Herdorf","RP"),
("DE5X25ZR71","DE","Herford","NW"),
("DEPTU07EQ3","DE","Heringen/Helme","TH"),
("DELEIYMHIH","DE","Heringen/Werra","HE"),
("DEM0BSM9PR","DE","Hermeskeil","RP"),
("DE7SX6J489","DE","Hermsdorf","TH"),
("DEX3A5H093","DE","Herne","NW"),
("DEFR129JJV","DE","Herrenberg","BW"),
("DEKUO64EYC","DE","Herrieden","BY"),
("DE6VIQ0RZY","DE","Herrnhut","SN"),
("DEU93CACFP","DE","Hersbruck","BY"),
("DE4HRD1B9M","DE","Herten","NW"),
("DE6XTACRMI","DE","Herzberg am Harz","NI"),
("DEN59NX8MS","DE","Herzberg/Elster","BB"),
("DEIQ4S3KI7","DE","Herzogenaurach","BY"),
("DE29K4KUQR","DE","Herzogenrath","NW"),
("DERJ14BONY","DE","Hessisch Lichtenau","HE"),
("DEUWMS48KN","DE","Hessisch Oldendorf","NI"),
("DEZPG2AY9D","DE","Hettingen","BW"),
("DE7UHSO8JG","DE","Hettstedt","ST"),
("DESLK3A714","DE","Heubach","BW"),
("DE4OW8XHWW","DE","Heusenstamm","HE"),
("DE6CYHA7UI","DE","Hilchenbach","NW"),
("DE2CBQKV7C","DE","Hildburghausen","TH"),
("DEGRGQZIV3","DE","Hilden","NW"),
("DE6SC3980G","DE","Hildesheim","NI"),
("DELYXV6SE8","DE","Hillesheim","RP"),
("DE4PZPK620","DE","Hilpoltstein","BY"),
("DEYIRY0N27","DE","Hirschau","BY"),
("DEFEBPNB59","DE","Hirschberg","TH"),
("DE934GVIO0","DE","Hirschhorn/Neckar","HE"),
("DE8OPSVRTU","DE","Hitzacker/Elbe","NI"),
("DEALSB8UIN","DE","Hochheim am Main","HE"),
("DE9UCX5I6F","DE","Höchstadt an der Aisch","BY"),
("DELBVGUKG2","DE","Höchstädt an der Donau","BY"),
("DE96U4YOY9","DE","Hockenheim","BW"),
("DE9QKIL35V","DE","Hof","BY"),
("DEXIS31ZIM","DE","Hofgeismar","HE"),
("DEBE35YK88","DE","Hofheim am Taunus","HE"),
("DEQ3CPRBY1","DE","Hofheim in Unterfranken","BY"),
("DE2IJNMOJK","DE","Hohen Neuendorf","BB"),
("DE7BN9B6VM","DE","Hohenberg an der Eger","BY"),
("DEKYSJJ0R9","DE","Hohenleuben","TH"),
("DE34YUFXVH","DE","Hohenmölsen","ST"),
("DEFE523OMB","DE","Hohenstein-Ernstthal","SN"),
("DE0AKBGGY1","DE","Hohnstein","SN"),
("DEFQKYQC7U","DE","Höhr-Grenzhausen","RP"),
("DEH6OW3KEJ","DE","Hollfeld","BY"),
("DEZJM388E8","DE","Holzgerlingen","BW"),
("DEJZKZFI0U","DE","Holzminden","NI"),
("DE8LSZY0TF","DE","Homberg/Efze","HE"),
("DE7IBA3QU2","DE","Homberg/Ohm","HE"),
("DEAH5IPKQ8","DE","Homburg","SL"),
("DEJB8YT9S2","DE","Horb am Neckar","BW"),
("DEUL2SLV8S","DE","Horn-Bad Meinberg","NW"),
("DEEK3HAYJK","DE","Hornbach","RP"),
("DEFP359UES","DE","Hornberg","BW"),
("DE5MRYVK1Q","DE","Hörstel","NW"),
("DE53JRZRKE","DE","Horstmar","NW"),
("DEBOVMMF72","DE","Höxter","NW"),
("DE5A7E4L79","DE","Hoya","NI"),
("DE8Z84J9VP","DE","Hoyerswerda","SN"),
("DEDEHC61QI","DE","Hückelhoven","NW"),
("DEPM5C2CE7","DE","Hückeswagen","NW"),
("DEMLLR7T0G","DE","Hüfingen","BW"),
("DES8KCIG2V","DE","Hünfeld","HE"),
("DEUJ81KZKA","DE","Hungen","HE"),
("DEMPMO10VO","DE","Hürth","NW"),
("DEMHFTBFA3","DE","Husum","SH"),
("DEOUG7AI25","DE","Ibbenbüren","NW"),
("DE2B7NBRXX","DE","Ichenhausen","BY"),
("DEHKLJKH77","DE","Idar-Oberstein","RP"),
("DEYN192BDR","DE","Idstein","HE"),
("DE6UYHD1MF","DE","Illertissen","BY"),
("DEDU2OMZL3","DE","Ilmenau","TH"),
("DEK7M4OUCN","DE","Ilsenburg/Harz","ST"),
("DEHDXKOBCV","DE","Ilshofen","BW"),
("DE5ACICZXP","DE","Immenhausen","HE"),
("DET0EG0ZJK","DE","Immenstadt im Allgäu","BY"),
("DE76OV01JI","DE","Ingelfingen","BW"),
("DEEG23REZX","DE","Ingelheim am Rhein","RP"),
("DEPBF2ADS4","DE","Ingolstadt","BY"),
("DED6KD63XD","DE","Iphofen","BY"),
("DEAM9BOST2","DE","Iserlohn","NW"),
("DE8W60B5X1","DE","Isny im Allgäu","BW"),
("DEHD3RQVV4","DE","Isselburg","NW"),
("DE1GI7KGLU","DE","Itzehoe","SH"),
("DE2U6RMZUV","DE","Jarmen","MV"),
("DEW0V76S8O","DE","Jena","TH"),
("DE5CFW7B19","DE","Jerichow","ST"),
("DESJGCZ162","DE","Jessen/Elster","ST"),
("DEWCTICND9","DE","Jever","NI"),
("DEO8HV1PJ7","DE","Joachimsthal","BB"),
("DE2Z49B5I3","DE","Johanngeorgenstadt","SN"),
("DEOZFO1MQX","DE","Jöhstadt","SN"),
("DEYKGB7UKW","DE","Jülich","NW"),
("DE21R4RACU","DE","Jüterbog","BB"),
("DE9G3KMMNB","DE","Kaarst","NW"),
("DEM3ZOPQMO","DE","Kahla","TH"),
("DEB20IWLEZ","DE","Kaisersesch","RP"),
("DEN64FGH9Q","DE","Kaiserslautern","RP"),
("DEYCBKZZVM","DE","Kalbe/Milde","ST"),
("DE2VASMXGX","DE","Kalkar","NW"),
("DEZGGW1VWO","DE","Kaltenkirchen","SH"),
("DE113HID8G","DE","Kaltennordheim","TH"),
("DEPJ1PIXBL","DE","Kamen","NW"),
("DESMDFJUCJ","DE","Kamenz","SN"),
("DEASGCND1P","DE","Kamp-Lintfort","NW"),
("DEE57XIFE8","DE","Kandel","RP"),
("DEZFXID935","DE","Kandern","BW"),
("DEVHLEBXYM","DE","Kappeln","SH"),
("DEQEYERZ36","DE","Karben","HE"),
("DE4A4NPIVP","DE","Karlsruhe","BW"),
("DEYS7B2BHX","DE","Karlstadt","BY"),
("DES2C30APR","DE","Kassel","HE"),
("DEPO5HO8OT","DE","Kastellaun","RP"),
("DEJSG9BBY9","DE","Katzenelnbogen","RP"),
("DE45L6H249","DE","Kaub","RP"),
("DE5GD5R3WH","DE","Kaufbeuren","BY"),
("DER2YFBN8U","DE","Kehl","BW"),
("DEFO4Q0204","DE","Kelbra/Kyffhäuser","ST"),
("DE8LAPOFZT","DE","Kelheim","BY"),
("DEVCZNFW57","DE","Kelkheim/Taunus","HE"),
("DEZ4MARV56","DE","Kellinghusen","SH"),
("DEJ9XJCYOL","DE","Kelsterbach","HE"),
("DEJZB8EA2A","DE","Kemberg","ST"),
("DEN1X3Y3AX","DE","Kemnath","BY"),
("DE7W8YSD5B","DE","Kempen","NW"),
("DEM3VZ1JKK","DE","Kempten/Allgäu","BY"),
("DEJVTX6V7T","DE","Kenzingen","BW"),
("DEX5WV87TG","DE","Kerpen","NW"),
("DE41EWEK71","DE","Ketzin/Havel","BB"),
("DEN30ONL96","DE","Kevelaer","NW"),
("DEG23NXBGV","DE","Kiel","SH"),
("DEHDQPKK5O","DE","Kierspe","NW"),
("DEMKL04T2R","DE","Kindelbrück","TH"),
("DEW3GJPPQ5","DE","Kirchberg","SN"),
("DESUTQ5ALM","DE","Kirchberg an der Jagst","BW"),
("DENCC8WIXI","DE","Kirchberg/Hunsrück","RP"),
("DE2IJ7BMZ8","DE","Kirchen/Sieg","RP"),
("DEQFSF4ILX","DE","Kirchenlamitz","BY"),
("DECENIO85C","DE","Kirchhain","HE"),
("DELHKIZH12","DE","Kirchheim unter Teck","BW"),
("DE0K9B78KX","DE","Kirchheimbolanden","RP"),
("DENCDSUYP7","DE","Kirn","RP"),
("DECDQ1MVD7","DE","Kirtorf","HE"),
("DECYPCFQEG","DE","Kitzingen","BY"),
("DEBOSIXCGL","DE","Kitzscher","SN"),
("DEOTDJS3Q4","DE","Kleve","NW"),
("DEHG63BJAO","DE","Klingenberg am Main","BY"),
("DEHZ0XQFD1","DE","Klingenthal","SN"),
("DE35K0I0L6","DE","Klötze","ST"),
("DEUZPM3FRK","DE","Klütz","MV"),
("DEWXN8HYWZ","DE","Knittlingen","BW"),
("DEXXXNCAPG","DE","Koblenz","RP"),
("DEG9HYA255","DE","Kohren-Sahlis","SN"),
("DE2UR6AJQ6","DE","Kolbermoor","BY"),
("DEHEEYCBY9","DE","Kölleda","TH"),
("DE8VXL6N1M","DE","Köln","NW"),
("DEWIL7LRCO","DE","Königs Wusterhausen","BB"),
("DEL4UVNK24","DE","Königsberg in Bayern","BY"),
("DEYH3AT1K1","DE","Königsbrück","SN"),
("DEWIM25OP2","DE","Königsbrunn","BY"),
("DE6B9S2MGO","DE","Königsee-Rottenbach","TH"),
("DEQAKEVNJU","DE","Königslutter am Elm","NI"),
("DE4M5XOPZL","DE","Königstein im Taunus","HE"),
("DE8MODAEGH","DE","Königstein/Sächsische Schweiz","SN"),
("DEQQ9TCQH3","DE","Königswinter","NW"),
("DE12HWP0QT","DE","Könnern","ST"),
("DENVRBLQWT","DE","Konstanz","BW"),
("DECL7NZO4P","DE","Konz","RP"),
("DEEEIQ40U5","DE","Korbach","HE"),
("DE2B2RCSLZ","DE","Korntal-Münchingen","BW"),
("DEOCBA374G","DE","Kornwestheim","BW"),
("DETB3SZ8IE","DE","Korschenbroich","NW"),
("DEN14R1YX4","DE","Köthen/Anhalt","ST"),
("DEAZVMSHLH","DE","Kraichtal","BW"),
("DETWRX4VDY","DE","Krakow am See","MV"),
("DE7HR6Q9LD","DE","Kranichfeld","TH"),
("DEAQ5CP2HZ","DE","Krautheim","BW"),
("DE2CMUU8BO","DE","Krefeld","NW"),
("DE43L9YZ85","DE","Kremmen","BB"),
("DEHZC78XLJ","DE","Krempe","SH"),
("DENQWCTDCV","DE","Kreuztal","NW"),
("DEQYPK618B","DE","Kronach","BY"),
("DE4UL2TT8A","DE","Kronberg im Taunus","HE"),
("DESLI1I3K6","DE","Kröpelin","MV"),
("DEUGJNTVIJ","DE","Kroppenstedt","ST"),
("DET8409CBE","DE","Krumbach/Schwaben","BY"),
("DE7WG0PPBI","DE","Kühlungsborn","MV"),
("DEAUJTY30S","DE","Kulmbach","BY"),
("DEKJGEEYY8","DE","Külsheim","BW"),
("DE628GFJUM","DE","Künzelsau","BW"),
("DEGBM51YNB","DE","Kupferberg","BY"),
("DES75QA5JV","DE","Kuppenheim","BW"),
("DEOZ93Y7C5","DE","Kusel","RP"),
("DE9KLO4GBK","DE","Kyllburg","RP"),
("DERYQSWE4P","DE","Kyritz","BB"),
("DEL9GVF0Q4","DE","Laage","MV"),
("DEZ08X7K3G","DE","Laatzen","NI"),
("DE4O584HSW","DE","Ladenburg","BW"),
("DEFIOCWT1I","DE","Lage","NW"),
("DE3IEII4NI","DE","Lahnstein","RP"),
("DE5VFCFITJ","DE","Lahr/Schwarzwald","BW"),
("DE7YRCGK8V","DE","Laichingen","BW"),
("DE3X70Q9IT","DE","Lambrecht/Pfalz","RP"),
("DESWCA1ZS6","DE","Lampertheim","HE"),
("DEU8I9RBSY","DE","Landau an der Isar","BY"),
("DEAKBQ5JM8","DE","Landau in der Pfalz","RP"),
("DEGU973R0V","DE","Landsberg","ST"),
("DENC6PBYV5","DE","Landsberg am Lech","BY"),
("DE7EFYQ7X0","DE","Landshut","BY"),
("DES8RYSD79","DE","Landstuhl","RP"),
("DE7GGB7G7V","DE","Langelsheim","NI"),
("DETEL5CGBK","DE","Langen","HE"),
("DEVQILYGMR","DE","Langenau","BW"),
("DEODPHRWQZ","DE","Langenburg","BW"),
("DEC6BKNJFG","DE","Langenfeld/Rheinland","NW"),
("DEX1LAHWUC","DE","Langenhagen","NI"),
("DENCYLTKCI","DE","Langenselbold","HE"),
("DEY1ZPXPPA","DE","Langenzenn","BY"),
("DEV0UIJAZG","DE","Langewiesen","TH"),
("DEBKQTHK64","DE","Lassan","MV"),
("DEX4QQO28N","DE","Laubach","HE"),
("DE47C2X1CT","DE","Laucha an der Unstrut","ST"),
("DE27CLHB2T","DE","Lauchhammer","BB"),
("DEWSMDDSIB","DE","Lauchheim","BW"),
("DEX81MBA9G","DE","Lauda-Königshofen","BW"),
("DEILIGNV9Q","DE","Lauenburg/Elbe","SH"),
("DE2LBKXDDT","DE","Lauf an der Pegnitz","BY"),
("DE607KSPVP","DE","Laufen","BY"),
("DEYXCA7LQQ","DE","Laufenburg/Baden","BW"),
("DE796U4FK7","DE","Lauffen am Neckar","BW"),
("DE1WRYA5RH","DE","Lauingen/Donau","BY"),
("DE5Y1YOXOM","DE","Laupheim","BW"),
("DEU0W1LNSS","DE","Lauscha","TH"),
("DEWYN1E89F","DE","Lauta","SN"),
("DE40DF64WC","DE","Lauter-Bernsbach","SN"),
("DE3YARVYEP","DE","Lauterbach","HE"),
("DEYBRKYJDV","DE","Lauterecken","RP"),
("DEI0XW86BD","DE","Lauterstein","BW"),
("DE7OSDTPPW","DE","Lebach","SL"),
("DENZOIY28X","DE","Lebus","BB"),
("DEDZHCJU71","DE","Leer/Ostfriesland","NI"),
("DEV4X3A8HH","DE","Lehesten","TH"),
("DEXAVQZKNM","DE","Lehrte","NI"),
("DEKB5JDDGR","DE","Leichlingen/Rheinland","NW"),
("DEDY3WTBXO","DE","Leimen","BW"),
("DEFUSQ3980","DE","Leinefelde-Worbis","TH"),
("DEJ4RJOE69","DE","Leinfelden-Echterdingen","BW"),
("DEQBS3P9V2","DE","Leipheim","BY"),
("DE7YZ09WOP","DE","Leipzig","SN"),
("DERHGUQOVA","DE","Leisnig","SN"),
("DESMTH10RR","DE","Lemgo","NW"),
("DECKV1TQ41","DE","Lengenfeld","SN"),
("DEP42Z0ROS","DE","Lengerich","NW"),
("DE85MYUI9N","DE","Lennestadt","NW"),
("DE53463WXG","DE","Lenzen","BB"),
("DEHTIAJNC9","DE","Leonberg","BW"),
("DERE8R5WJD","DE","Leun","HE"),
("DE26CWPMJU","DE","Leuna","ST"),
("DEQO0TKYA1","DE","Leutenberg","TH"),
("DERSCAFPJ6","DE","Leutershausen","BY"),
("DE4SY9PHNR","DE","Leutkirch im Allgäu","BW"),
("DEO0NDN67D","DE","Leverkusen","NW"),
("DEU77F6HHX","DE","Lich","HE"),
("DE9U8OJRVN","DE","Lichtenau","BW"),
("DEJTX8BL0Z","DE","Lichtenau","NW"),
("DELND9UKMP","DE","Lichtenberg","BY"),
("DEST4YAMVK","DE","Lichtenfels","BY"),
("DEG380V4OF","DE","Lichtenfels","HE"),
("DEXLO87O8T","DE","Lichtenstein/Sa.","SN"),
("DECL266OVY","DE","Liebenau","HE"),
("DEH0XSNTC4","DE","Liebenwalde","BB"),
("DEXL4TPT8M","DE","Lieberose","BB"),
("DEEXVMM3FY","DE","Liebstadt","SN"),
("DEOH5U51TN","DE","Limbach-Oberfrohna","SN"),
("DE2QFPKSTH","DE","Limburg an der Lahn","HE"),
("DEDYA3RJQ6","DE","Lindau/Bodensee","BY"),
("DEHLS3O72D","DE","Linden","HE"),
("DEP87U91IB","DE","Lindenberg im Allgäu","BY"),
("DESX1CQUU3","DE","Lindenfels","HE"),
("DET56KOXR6","DE","Lindow/Mark","BB"),
("DEIKA7SDKH","DE","Lingen/Ems","NI"),
("DELSBUTU6M","DE","Linnich","NW"),
("DER7YI2SLV","DE","Linz am Rhein","RP"),
("DEXSGMP7T8","DE","Lippstadt","NW"),
("DES3FKG011","DE","Löbau","SN"),
("DETDWM729Z","DE","Löffingen","BW"),
("DEA7HC037Y","DE","Lohmar","NW"),
("DEVNKLVDUN","DE","Löhne","NW"),
("DEH97XA9Z3","DE","Lohne/Oldenburg","NI"),
("DEMWQTYZS8","DE","Lohr am Main","BY"),
("DE7AL7DS59","DE","Loitz","MV"),
("DEGQUB4PZL","DE","Lollar","HE"),
("DEZ7J9GJC2","DE","Lommatzsch","SN"),
("DEF3WE2PM9","DE","Löningen","NI"),
("DEZ8HC0MLG","DE","Lorch","BW"),
("DEDGSH5S34","DE","Lorch","HE"),
("DEZNEF6QIL","DE","Lörrach","BW"),
("DEUE0W3N62","DE","Lorsch","HE"),
("DEVNFVA0CO","DE","Lößnitz","SN"),
("DEG56MXARW","DE","Löwenstein","BW"),
("DEX5C4WUQQ","DE","Lübbecke","NW"),
("DE9QNDDTG8","DE","Lübben/Spreewald","BB"),
("DEHV3SVGGC","DE","Lübbenau/Spreewald","BB"),
("DELMZIWQEU","DE","Lübeck, Hansestadt","SH"),
("DEVQYSLOIU","DE","Lübtheen","MV"),
("DEE57RZNZG","DE","Lübz","MV"),
("DEJ38EJPR4","DE","Lüchow/Wendland","NI"),
("DEBRN8H12D","DE","Lucka","TH"),
("DES05EOO83","DE","Luckau","BB"),
("DETGUT4U9N","DE","Luckenwalde","BB"),
("DEYI2I7UMJ","DE","Lüdenscheid","NW"),
("DELAR3CTG5","DE","Lüdinghausen","NW"),
("DEUMJJBSM5","DE","Ludwigsburg","BW"),
("DE8HYDB80A","DE","Ludwigsfelde","BB"),
("DEQ3SYXFHI","DE","Ludwigshafen am Rhein","RP"),
("DEP8L1226W","DE","Ludwigslust","MV"),
("DEPQF0I15R","DE","Ludwigsstadt","BY"),
("DEJ34VB552","DE","Lugau/Erzgeb.","SN"),
("DE8X05CHO2","DE","Lügde","NW"),
("DEQA3SDAP2","DE","Lüneburg, Hansestadt","NI"),
("DE053J78AQ","DE","Lünen","NW"),
("DECFLOKQQS","DE","Lunzenau","SN"),
("DEORY08N3Z","DE","Lütjenburg","SH"),
("DEX6SAHIDI","DE","Lützen","ST"),
("DENG1UOCK1","DE","Lychen","BB"),
("DER5PCWG5K","DE","Magdala","TH"),
("DE73LGROGO","DE","Magdeburg","ST"),
("DEV8ZDQCVD","DE","Mahlberg","BW"),
("DESX8HASI1","DE","Mainbernheim","BY"),
("DEY8EUOJFW","DE","Mainburg","BY"),
("DEN0DEPT2K","DE","Maintal","HE"),
("DE12XSET66","DE","Mainz","RP"),
("DEREO17635","DE","Malchin","MV"),
("DEFH040G0N","DE","Malchow","MV"),
("DEHD1664R8","DE","Manderscheid","RP"),
("DE6O1KI7R9","DE","Mannheim","BW"),
("DELFATMDY2","DE","Mansfeld","ST"),
("DEUZ6UF6IW","DE","Marbach am Neckar","BW"),
("DEKJ3QOUZU","DE","Marburg","HE"),
("DEJ0F177AT","DE","Marienberg","SN"),
("DEMKM9YLBS","DE","Marienmünster","NW"),
("DEKHN0O6X8","DE","Markdorf","BW"),
("DEP0ZEVY8E","DE","Markgröningen","BW"),
("DEZNF6VQ0H","DE","Märkisch Buchholz","BB"),
("DEANR9832T","DE","Markkleeberg","SN"),
("DELQU9WSHM","DE","Markneukirchen","SN"),
("DETH0OF83F","DE","Markranstädt","SN"),
("DEWIMR8M9J","DE","Marktbreit","BY"),
("DE91SI4VCQ","DE","Marktheidenfeld","BY"),
("DEL7ZHZH3S","DE","Marktleuthen","BY"),
("DEY3GECJT9","DE","Marktoberdorf","BY"),
("DE2F1B2BVC","DE","Marktredwitz","BY"),
("DEDOVIJ784","DE","Marktsteft","BY"),
("DEF8LEPP6O","DE","Marl","NW"),
("DETN357XFA","DE","Marlow","MV"),
("DEDHLGTGS6","DE","Marne","SH"),
("DE4OOOWXSB","DE","Marsberg","NW"),
("DE5EPU3WJW","DE","Maulbronn","BW"),
("DEJN2QLH0Y","DE","Maxhütte-Haidhof","BY"),
("DEZMES37Y8","DE","Mayen","RP"),
("DEVNWRKO3P","DE","Mechernich","NW"),
("DE2SK6O428","DE","Meckenheim","NW"),
("DER4ZCM0BM","DE","Medebach","NW"),
("DEMQEPXDXT","DE","Meerane","SN"),
("DE0TLLIOAL","DE","Meerbusch","NW"),
("DEHVR5ZUER","DE","Meersburg","BW"),
("DEZD4LDF80","DE","Meinerzhagen","NW"),
("DE5MP30NX1","DE","Meiningen","TH"),
("DEHIM07XLO","DE","Meisenheim","RP"),
("DESDUS78J6","DE","Meißen","SN"),
("DEMNSZ30Z9","DE","Meldorf","SH"),
("DENPCND9OU","DE","Melle","NI"),
("DESBUZ8GO1","DE","Mellrichstadt","BY"),
("DETJT0SD6E","DE","Melsungen","HE"),
("DE1YE4ZDDM","DE","Memmingen","BY"),
("DE3Q9GZYBS","DE","Menden/Sauerland","NW"),
("DE95RIMGJF","DE","Mendig","RP"),
("DEZDGRQN6S","DE","Mengen","BW"),
("DELKWLYA71","DE","Meppen","NI"),
("DE0HH0FTSP","DE","Merkendorf","BY"),
("DEZK7L0R10","DE","Merseburg","ST"),
("DE4HSV4YNQ","DE","Merzig","SL"),
("DEIKBGUIHV","DE","Meschede","NW"),
("DE0ZWGSP5S","DE","Meßkirch","BW"),
("DE9DDA4EB9","DE","Meßstetten","BW"),
("DEV3401SQJ","DE","Mettmann","NW"),
("DEC206KH2L","DE","Metzingen","BW"),
("DEHY1AO62X","DE","Meuselwitz","TH"),
("DEKG8PUJYQ","DE","Meyenburg","BB"),
("DEN3QOVH88","DE","Michelstadt","HE"),
("DEJ8E4QHP8","DE","Miesbach","BY"),
("DEGQI4XL2H","DE","Miltenberg","BY"),
("DE1A7WU6NH","DE","Mindelheim","BY"),
("DE9D65VFDE","DE","Minden","NW"),
("DENSJDA8MQ","DE","Mirow","MV"),
("DEZ5UWQWES","DE","Mittenwalde","BB"),
("DE7LP1RCJ1","DE","Mitterteich","BY"),
("DEQQ7L5K0T","DE","Mittweida","SN"),
("DEDJ7NRTEQ","DE","Möckern","ST"),
("DEY8NP51HC","DE","Möckmühl","BW"),
("DEM7EDJYF9","DE","Moers","NW"),
("DEOMVU7VNK","DE","Mölln","SH"),
("DEEU86NMWM","DE","Mönchengladbach","NW"),
("DEVJB0LTC7","DE","Monheim","BY"),
("DE0QLJP0TE","DE","Monheim am Rhein","NW"),
("DENO8UKWFY","DE","Monschau","NW"),
("DEQN5EA115","DE","Montabaur","RP"),
("DELC576IE6","DE","Moosburg an der Isar","BY"),
("DE80QY1KCO","DE","Mörfelden-Walldorf","HE"),
("DE9KITGYS7","DE","Moringen","NI"),
("DELXMVZO1L","DE","Mosbach","BW"),
("DE06S7O7DX","DE","Mössingen","BW"),
("DE74V9O7XY","DE","Mücheln/Geiseltal","ST"),
("DESGR9EJH0","DE","Mügeln","SN"),
("DEH4WGSX1T","DE","Mühlacker","BW"),
("DE4T0T0EQ8","DE","Mühlberg/Elbe","BB"),
("DEIMH7UF5N","DE","Mühldorf am Inn","BY"),
("DEVXWAGEBX","DE","Mühlhausen/Thüringen","TH"),
("DEI7EB5F49","DE","Mühlheim am Main","HE"),
("DE942AITI1","DE","Mühlheim an der Donau","BW"),
("DEF08AFEXB","DE","Mülheim an der Ruhr","NW"),
("DEBUMR8XPR","DE","Mülheim-Kärlich","RP"),
("DE533AJ7KS","DE","Müllheim","BW"),
("DECN2UGLVW","DE","Müllrose","BB"),
("DEL461I4DT","DE","Münchberg","BY"),
("DEYZL7XBZ2","DE","Müncheberg","BB"),
("DEE2CYAXQM","DE","München","BY"),
("DEKTG0FCX1","DE","Münchenbernsdorf","TH"),
("DEG42Z8GS6","DE","Munderkingen","BW"),
("DEFEECPEF3","DE","Münnerstadt","BY"),
("DEGR2QPTC9","DE","Münsingen","BW"),
("DEMTA2573M","DE","Munster","NI"),
("DEB6MJMEQ2","DE","Münster","NW"),
("DES5FIJULZ","DE","Münstermaifeld","RP"),
("DELOQAH3K4","DE","Münzenberg","HE"),
("DEWU621APD","DE","Murrhardt","BW"),
("DEGBX3PN5I","DE","Mylau","SN"),
("DESK0CEMB0","DE","Nabburg","BY"),
("DEB2BS5VW1","DE","Nagold","BW"),
("DEQ33SDT5T","DE","Naila","BY"),
("DE42XUQ2DJ","DE","Nassau","RP"),
("DENDV1072B","DE","Nastätten","RP"),
("DE9E4EA0G0","DE","Nauen","BB"),
("DE4KSHDYBH","DE","Naumburg","HE"),
("DE18BRAOAY","DE","Naumburg/Saale","ST"),
("DE2503C2FM","DE","Naunhof","SN"),
("DEHJ1RKHSO","DE","Nebra/Unstrut","ST"),
("DE1L6FJHWK","DE","Neckarbischofsheim","BW"),
("DEP8C0XMYZ","DE","Neckargemünd","BW"),
("DESY351IRI","DE","Neckarsteinach","HE"),
("DE2S9NA2CC","DE","Neckarsulm","BW"),
("DENIR7ZOSP","DE","Neresheim","BW"),
("DEW4PTQOTJ","DE","Netphen","NW"),
("DEMXOOGG6I","DE","Nettetal","NW"),
("DE9G6JIIW6","DE","Netzschkau","SN"),
("DE0ND0B5P7","DE","Neu-Anspach","HE"),
("DE9F103VKQ","DE","Neu-Isenburg","HE"),
("DES9E8PLRZ","DE","Neu-Ulm","BY"),
("DE2XILGERG","DE","Neubrandenburg","MV"),
("DE25HDA6LK","DE","Neubukow","MV"),
("DELNLPI5GB","DE","Neubulach","BW"),
("DEEVK4HC3J","DE","Neuburg an der Donau","BY"),
("DE9M5Q1X63","DE","Neudenau","BW"),
("DE2NHDU2YG","DE","Neuenbürg","BW"),
("DEQJ69PMK3","DE","Neuenburg am Rhein","BW"),
("DEH47ZHBIR","DE","Neuenhaus","NI"),
("DEXNHYKO2N","DE","Neuenrade","NW"),
("DEBJ06MYMC","DE","Neuenstadt am Kocher","BW"),
("DEITL7F5BX","DE","Neuenstein","BW"),
("DEAJWSUFJR","DE","Neuerburg","RP"),
("DE30QOOSB0","DE","Neuffen","BW"),
("DEBC6XBT9T","DE","Neuhaus am Rennweg","TH"),
("DEMV121C0B","DE","Neukalen","MV"),
("DEVX3PCNHF","DE","Neukirchen","HE"),
("DEN74BZFBA","DE","Neukirchen-Vluyn","NW"),
("DESI83BIXY","DE","Neukloster","MV"),
("DEDZ1EC1Q7","DE","Neumark","TH"),
("DEYUXBHFQ4","DE","Neumarkt in der Oberpfalz","BY"),
("DEMUGMARX2","DE","Neumarkt-Sankt Veit","BY"),
("DEA56LN4K0","DE","Neumünster","SH"),
("DE4MFGN5NM","DE","Neunburg vorm Wald","BY"),
("DEZLXH0OLN","DE","Neunkirchen","SL"),
("DEJ19TT6W3","DE","Neuötting","BY"),
("DEC3P08A0C","DE","Neuruppin","BB"),
("DEWGSJLG6L","DE","Neusalza-Spremberg","SN"),
("DE1322SOPB","DE","Neusäß","BY"),
("DEPY5J52MH","DE","Neuss","NW"),
("DE6CHEMIQI","DE","Neustadt","HE"),
("DEZJ2KZ961","DE","Neustadt am Kulm","BY"),
("DED835WTGM","DE","Neustadt am Rübenberge","NI"),
("DERM5XOSFU","DE","Neustadt an der Aisch","BY"),
("DE5X9SF0AE","DE","Neustadt an der Donau","BY"),
("DEJDZJN5K0","DE","Neustadt an der Orla","TH"),
("DEEO5BHMY9","DE","Neustadt an der Waldnaab","BY"),
("DE946XWMS2","DE","Neustadt an der Weinstraße","RP"),
("DEJ1UZ25DL","DE","Neustadt bei Coburg","BY"),
("DEJD56JP6Y","DE","Neustadt in Holstein","SH"),
("DEEC9WZ758","DE","Neustadt in Sachsen","SN"),
("DEBC68YZAH","DE","Neustadt-Glewe","MV"),
("DE14G3AUPT","DE","Neustadt/Dosse","BB"),
("DE8UZRK6PY","DE","Neustrelitz","MV"),
("DEJZUI60RI","DE","Neutraubling","BY"),
("DECYQBX1TY","DE","Neuwied","RP"),
("DE6A1G4QAC","DE","Nidda","HE"),
("DEK945GU3Z","DE","Niddatal","HE"),
("DETYI0Y9IB","DE","Nidderau","HE"),
("DE79M5BF3H","DE","Nideggen","NW"),
("DEP5YUV87G","DE","Niebüll","SH"),
("DEICLZ6PY0","DE","Niedenstein","HE"),
("DENH0MRIXZ","DE","Nieder-Olm","RP"),
("DESK4308LQ","DE","Niederkassel","NW"),
("DEDKL9TSPB","DE","Niedernhall","BW"),
("DE5BBB19BP","DE","Niederstetten","BW"),
("DERBBIU9HN","DE","Niederstotzingen","BW"),
("DEUMQUUCK7","DE","Nieheim","NW"),
("DEW6GPY613","DE","Niemegk","BB"),
("DEHCFJMQ8E","DE","Nienburg/Saale","ST"),
("DE2JWXTEKN","DE","Nienburg/Weser","NI"),
("DE0BIUN32K","DE","Nierstein","RP"),
("DE9IA8OBB6","DE","Niesky","SN"),
("DEORPBIXPK","DE","Nittenau","BY"),
("DEHMIB03Y1","DE","Norden","NI"),
("DEEHW2KYMT","DE","Nordenham","NI"),
("DEHW168DCX","DE","Norderney","NI"),
("DE428M0Y7H","DE","Norderstedt","SH"),
("DEKQTLTRN7","DE","Nordhausen","TH"),
("DE8J9THVMY","DE","Nordhorn","NI"),
("DESO402HX6","DE","Nördlingen","BY"),
("DEK6TK412P","DE","Northeim","NI"),
("DERVBKNYRW","DE","Nortorf","SH"),
("DEH1PZXCYP","DE","Nossen","SN"),
("DE13Q3KN95","DE","Nürnberg","BY"),
("DEU3PZ4RPV","DE","Nürtingen","BW"),
("DEN0GAY77G","DE","Ober-Ramstadt","HE"),
("DE9WG69EVA","DE","Oberasbach","BY"),
("DEHME29N74","DE","Oberharz am Brocken","ST"),
("DERX3VPSRC","DE","Oberhausen","NW"),
("DET7NSFU9O","DE","Oberhof","TH"),
("DERPV03RBL","DE","Oberkirch","BW"),
("DEDPONDWR4","DE","Oberkochen","BW"),
("DETV0IOSUH","DE","Oberlungwitz","SN"),
("DEZHAFCJ43","DE","Obermoschel","RP"),
("DE8Z3CRFX4","DE","Obernburg am Main","BY"),
("DE4MSIIJMB","DE","Oberndorf am Neckar","BW"),
("DEFNU3FOLF","DE","Obernkirchen","NI"),
("DE6VVIF0MN","DE","Oberriexingen","BW"),
("DE0PZR5XW9","DE","Obertshausen","HE"),
("DEJOS18FDN","DE","Oberursel/Taunus","HE"),
("DE27RIWDY2","DE","Oberviechtach","BY"),
("DE8ULNU7BU","DE","Oberweißbach/Thür. Wald","TH"),
("DEXBL28HCS","DE","Oberwesel","RP"),
("DE65TEK61N","DE","Oberwiesenthal","SN"),
("DEET5A64DF","DE","Ochsenfurt","BY"),
("DEYY3S6EN4","DE","Ochsenhausen","BW"),
("DEP87YQKQW","DE","Ochtrup","NW"),
("DEPKA9RCW5","DE","Oderberg","BB"),
("DE62FC6SR5","DE","Oebisfelde-Weferlingen","ST"),
("DERUXY9L2Z","DE","Oederan","SN"),
("DET9XKTOHI","DE","Oelde","NW"),
("DE9SS04O6A","DE","Oelsnitz/Erzgeb.","SN"),
("DEQLNXEE26","DE","Oelsnitz/Vogtl.","SN"),
("DE904IL6HF","DE","Oer-Erkenschwick","NW"),
("DEGFZ94GSD","DE","Oerlinghausen","NW"),
("DE8KDD9JOZ","DE","Oestrich-Winkel","HE"),
("DE5BXKQZQZ","DE","Oettingen in Bayern","BY"),
("DEZVIK2ZZI","DE","Offenbach am Main","HE"),
("DEFYSJFLXO","DE","Offenburg","BW"),
("DE6A1FUPF0","DE","Ohrdruf","TH"),
("DE0CKRBBQB","DE","Öhringen","BW"),
("DE78V98URN","DE","Olbernhau","SN"),
("DETK7954XB","DE","Olching","BY"),
("DEFZRAO6AP","DE","Oldenburg in Holstein","SH"),
("DEIVGU675D","DE","Oldenburg/Oldb","NI"),
("DEF0NNVEBP","DE","Olfen","NW"),
("DEZJZ4OWG3","DE","Olpe","NW"),
("DEV7EKEOAW","DE","Olsberg","NW"),
("DEJQRQXX4D","DE","Oppenau","BW"),
("DEYR1T6DJ5","DE","Oppenheim","RP"),
("DEXJALGRPB","DE","Oranienbaum-Wörlitz","ST"),
("DEY3WDS6AB","DE","Oranienburg","BB"),
("DEX12VY68W","DE","Orlamünde","TH"),
("DEX9Q4NA9K","DE","Ornbau","BY"),
("DETK59BVLA","DE","Ortenberg","HE"),
("DEYHNQOX2L","DE","Ortrand","BB"),
("DEZ4HXBPU9","DE","Oschatz","SN"),
("DEZKDMUN6O","DE","Oschersleben/Bode","ST"),
("DE7CYJ7JT6","DE","Osnabrück","NI"),
("DE1HXPE0BD","DE","Osterburg/Altmark","ST"),
("DE5SBGI5QH","DE","Osterburken","BW"),
("DEQ44LRB9Z","DE","Osterfeld","ST"),
("DEO7IWRC2S","DE","Osterhofen","BY"),
("DEU0I80UM5","DE","Osterholz-Scharmbeck","NI"),
("DENXM53CNT","DE","Osterode am Harz","NI"),
("DEGSE84N8S","DE","Osterwieck","ST"),
("DEVROM3RFX","DE","Ostfildern","BW"),
("DERX6SSTXF","DE","Ostheim vor der Rhön","BY"),
("DEQKLUX9ND","DE","Osthofen","RP"),
("DE11M5PUYL","DE","Östringen","BW"),
("DELM8PENN5","DE","Ostritz","SN"),
("DELTYDMWTD","DE","Otterberg","RP"),
("DEGF7DOVRP","DE","Otterndorf","NI"),
("DEWEVM8T8U","DE","Ottweiler","SL"),
("DEGGJU360P","DE","Overath","NW"),
("DE0Y3NUW0B","DE","Owen","BW"),
("DEB8P03GQ0","DE","Paderborn","NW"),
("DEULN3FVXW","DE","Papenburg","NI"),
("DEBHQFOR4O","DE","Pappenheim","BY"),
("DEQ7BK4CWG","DE","Parchim","MV"),
("DELLGO16PW","DE","Parsberg","BY"),
("DESC088X4J","DE","Pasewalk","MV"),
("DEFUY3M3RC","DE","Passau","BY"),
("DEB3WFFTV0","DE","Pattensen","NI"),
("DEECPGJECB","DE","Pausa-Mühltroff","SN"),
("DERCJZANJP","DE","Pegau","SN"),
("DEIIS4LKGW","DE","Pegnitz","BY"),
("DENDC3674L","DE","Peine","NI"),
("DEKT138EE0","DE","Peitz","BB"),
("DERYZ1LIR4","DE","Penig","SN"),
("DE0K8M4PIS","DE","Penkun","MV"),
("DE2UV920UM","DE","Penzberg","BY"),
("DETVQ29420","DE","Penzlin","MV"),
("DE322OKTSL","DE","Perleberg","BB"),
("DEE17IQQAT","DE","Petershagen","NW"),
("DEL62O6XB0","DE","Pfaffenhofen an der Ilm","BY"),
("DES1226539","DE","Pfarrkirchen","BY"),
("DE76YS0RDE","DE","Pforzheim","BW"),
("DESLWJC7CY","DE","Pfreimd","BY"),
("DEEFMLCXL5","DE","Pfullendorf","BW"),
("DEZO85TBE1","DE","Pfullingen","BW"),
("DEHDTH47VW","DE","Pfungstadt","HE"),
("DESSG50T3E","DE","Philippsburg","BW"),
("DE8Q0LNLRN","DE","Pinneberg","SH"),
("DEAZS4A75S","DE","Pirmasens","RP"),
("DEKYAP65LZ","DE","Pirna","SN"),
("DEY24ZV8E4","DE","Plattling","BY"),
("DEYEQM0H9A","DE","Plau am See","MV"),
("DEG2ERAJKV","DE","Plaue","TH"),
("DEIUKO06NZ","DE","Plauen","SN"),
("DE8SY30C8Y","DE","Plettenberg","NW"),
("DEQYKQGU1X","DE","Pleystein","BY"),
("DEWFO7Z92H","DE","Plochingen","BW"),
("DE4M64SU41","DE","Plön","SH"),
("DEM25MFDL6","DE","Pockau-Lengefeld","SN"),
("DEC5WS0YPX","DE","Pocking","BY"),
("DEDE4DN7US","DE","Pohlheim","HE"),
("DET1WMV1OH","DE","Polch","RP"),
("DE4T4J7PPJ","DE","Porta Westfalica","NW"),
("DEVMBVK1SY","DE","Pößneck","TH"),
("DEFXB346VY","DE","Potsdam","BB"),
("DE7SL3T9LX","DE","Pottenstein","BY"),
("DE3PHAE7T9","DE","Preetz","SH"),
("DET55E7YCM","DE","Premnitz","BB"),
("DEVOQ0ULZ2","DE","Prenzlau","BB"),
("DEEK57UQ5X","DE","Pressath","BY"),
("DEGN8UU24N","DE","Preußisch Oldendorf","NW"),
("DE792E7F13","DE","Prichsenstadt","BY"),
("DE3R4YD31R","DE","Pritzwalk","BB"),
("DEO7ZIY4GE","DE","Prüm","RP"),
("DERO9MRD9Y","DE","Puchheim","BY"),
("DENCDVRFZV","DE","Pulheim","NW"),
("DE63TK7VBV","DE","Pulsnitz","SN"),
("DE2AE0FVE7","DE","Putbus","MV"),
("DEKOTB129P","DE","Putlitz","BB"),
("DEFNK62J19","DE","Püttlingen","SL"),
("DEMVTUQ5PT","DE","Quakenbrück","NI"),
("DEF4TUZ81J","DE","Quedlinburg","ST"),
("DEWVUYX4ND","DE","Querfurt","ST"),
("DER7JUQL4D","DE","Quickborn","SH"),
("DEHY883X1J","DE","Rabenau","SN"),
("DE1UE03GKZ","DE","Radeberg","SN"),
("DEBEX9ILMA","DE","Radebeul","SN"),
("DES65JRAX9","DE","Radeburg","SN"),
("DE85HC3IV5","DE","Radevormwald","NW"),
("DEDA6GQQG2","DE","Radolfzell am Bodensee","BW"),
("DE4EBNZYYS","DE","Raguhn-Jeßnitz","ST"),
("DE43CWE95M","DE","Rahden","NW"),
("DEFMZI5VNJ","DE","Rain","BY"),
("DE5T0WKGYP","DE","Ramstein-Miesenbach","RP"),
("DEVACV8BNC","DE","Ranis","TH"),
("DEFZ8T9EFO","DE","Ransbach-Baumbach","RP"),
("DE1F77AUQF","DE","Rastatt","BW"),
("DEOQC97AY3","DE","Rastenberg","TH"),
("DEKBYTMM61","DE","Rathenow","BB"),
("DELEUUTAJU","DE","Ratingen","NW"),
("DEQQ10LSFA","DE","Ratzeburg","SH"),
("DEJSJR2HUN","DE","Rauenberg","BW"),
("DESTHFFNG0","DE","Raunheim","HE"),
("DE2BVVMFQC","DE","Rauschenberg","HE"),
("DE5SDRKT14","DE","Ravensburg","BW"),
("DELLVN2PBV","DE","Ravenstein","BW"),
("DEISAYGRZI","DE","Recklinghausen","NW"),
("DE3UDQA43G","DE","Rees","NW"),
("DEWG7G99LV","DE","Regen","BY"),
("DEUGJX6UTP","DE","Regensburg","BY"),
("DEN4N3WML0","DE","Regis-Breitingen","SN"),
("DEHZRR3U7Z","DE","Rehau","BY"),
("DEBFGLO2GJ","DE","Rehburg-Loccum","NI"),
("DEIZHPUAEI","DE","Rehna","MV"),
("DEF2LBO7C6","DE","Reichelsheim/Wetterau","HE"),
("DE73XBX5B9","DE","Reichenbach im Vogtland","SN"),
("DELSVAUCTC","DE","Reichenbach/O.L.","SN"),
("DEBB16MGO1","DE","Reinbek","SH"),
("DEIAD7IPDP","DE","Reinfeld/Holstein","SH"),
("DESB1QHC02","DE","Reinheim","HE"),
("DE4VCY76BJ","DE","Remagen","RP"),
("DEHDP4TE5B","DE","Remda-Teichel","TH"),
("DEOII78WX0","DE","Remscheid","NW"),
("DE7YQOAQRF","DE","Remseck am Neckar","BW"),
("DEM3DTAPCS","DE","Renchen","BW"),
("DE22WVG275","DE","Rendsburg","SH"),
("DELQCTM9TU","DE","Rennerod","RP"),
("DE8KJJAAYW","DE","Renningen","BW"),
("DEECQO13H3","DE","Rerik","MV"),
("DE5EZMG7R1","DE","Rethem/Aller","NI"),
("DEY4VLEOFM","DE","Reutlingen","BW"),
("DE9Y5J93GN","DE","Rheda-Wiedenbrück","NW"),
("DEF7CHAUKF","DE","Rhede","NW"),
("DE8K1ORTQQ","DE","Rheinau","BW"),
("DEXLBCAQYJ","DE","Rheinbach","NW"),
("DEP43Z7KNN","DE","Rheinberg","NW"),
("DERZ51TQH2","DE","Rheinböllen","RP"),
("DEAJQ2CHSA","DE","Rheine","NW"),
("DE33MEULYK","DE","Rheinfelden/Baden","BW"),
("DEP1KXM7LE","DE","Rheinsberg","BB"),
("DE6QF0GX2R","DE","Rheinstetten","BW"),
("DEGTTTBM4F","DE","Rhens","RP"),
("DEQQTLCR61","DE","Rhinow","BB"),
("DETQZGXKU4","DE","Ribnitz-Damgarten","MV"),
("DEBA5R78JO","DE","Richtenberg","MV"),
("DE2CHDZLSP","DE","Riedenburg","BY"),
("DECMAPEHQ8","DE","Riedlingen","BW"),
("DE7QO5AJAL","DE","Riedstadt","HE"),
("DETFD0NWPP","DE","Rieneck","BY"),
("DE9638SWY5","DE","Riesa","SN"),
("DEI9UWQL5Y","DE","Rietberg","NW"),
("DEBT3MCD75","DE","Rinteln","NI"),
("DESL6GIV6S","DE","Röbel/Müritz","MV"),
("DE290V5Z0O","DE","Rochlitz","SN"),
("DE8VLZGQXR","DE","Rockenhausen","RP"),
("DEJ0DWDL26","DE","Rodalben","RP"),
("DE79NP4UH7","DE","Rodenberg","NI"),
("DE3I29I3XQ","DE","Rödental","BY"),
("DEYIPF8M6S","DE","Rödermark","HE"),
("DENKP16R8E","DE","Rodewisch","SN"),
("DE0V35PLDT","DE","Rodgau","HE"),
("DE4F3MJ0DH","DE","Roding","BY"),
("DEJ3XSQ4LD","DE","Römhild","TH"),
("DEOAFV2N92","DE","Romrod","HE"),
("DEJD89ZL23","DE","Ronneburg","TH"),
("DE15QK642Q","DE","Ronnenberg","NI"),
("DE7ZJY34CS","DE","Rosbach vor der Höhe","HE"),
("DEFRNHEXJY","DE","Rosenfeld","BW"),
("DEAS79D9DE","DE","Rosenheim","BY"),
("DEF4YM80CG","DE","Rosenthal","HE"),
("DE0WE30RVF","DE","Rösrath","NW"),
("DEIJXXGHVQ","DE","Roßleben","TH"),
("DE930MCE1S","DE","Roßwein","SN"),
("DEIZER0R80","DE","Rostock, Hansestadt","MV"),
("DENN4OEZ4X","DE","Rotenburg an der Fulda","HE"),
("DEI1UYIQPR","DE","Rotenburg/Wümme","NI"),
("DETQE64FYN","DE","Roth","BY"),
("DEEDEF5NGT","DE","Rötha","SN"),
("DEAKHPKLM2","DE","Röthenbach an der Pegnitz","BY"),
("DENH157RW0","DE","Rothenburg ob der Tauber","BY"),
("DEHB7MQ695","DE","Rothenburg/O.L.","SN"),
("DEKOKPB1IM","DE","Rothenfels","BY"),
("DEL0B5LX89","DE","Rottenburg a.d.Laaber","BY"),
("DEF9EM1BNJ","DE","Rottenburg am Neckar","BW"),
("DEMU5C1EHL","DE","Röttingen","BY"),
("DE22AD3TZP","DE","Rottweil","BW"),
("DETBUF92OO","DE","Rötz","BY"),
("DEC2AEEYX0","DE","Rüdesheim am Rhein","HE"),
("DET2DUHVFJ","DE","Rudolstadt","TH"),
("DEXQX1JXQC","DE","Ruhla","TH"),
("DE8LSHOG60","DE","Ruhland","BB"),
("DEJGFXFCY8","DE","Runkel","HE"),
("DEFB2W6IG4","DE","Rüsselsheim","HE"),
("DE8D6RAW4J","DE","Rutesheim","BW"),
("DEIW16D77W","DE","Rüthen","NW"),
("DEOMT3ZRBE","DE","Saalburg-Ebersdorf","TH"),
("DE3EBAWRF5","DE","Saalfeld/Saale","TH"),
("DE5LWFI1Z0","DE","Saarbrücken","SL"),
("DEY06B7E7V","DE","Saarburg","RP"),
("DE01Y0TAFX","DE","Saarlouis","SL"),
("DEOQ7LIMQN","DE","Sachsenhagen","NI"),
("DE7N3PO2QN","DE","Sachsenheim","BW"),
("DE2XYAB66C","DE","Salzgitter","NI"),
("DE85C1FRY3","DE","Salzkotten","NW"),
("DEI6O0SFN0","DE","Salzwedel, Hansestadt","ST"),
("DE2QQQSGDV","DE","Sandau/Elbe","ST"),
("DEDC6OJC0R","DE","Sandersdorf-Brehna","ST"),
("DEHCTW4S0M","DE","Sangerhausen","ST"),
("DEYPMQ49R6","DE","Sankt Augustin","NW"),
("DE0HXTXBOB","DE","Sankt Goar","RP"),
("DEOUZ770YO","DE","Sankt Goarshausen","RP"),
("DEDRKHJL4I","DE","Sarstedt","NI"),
("DEAR9F00M1","DE","Sassenberg","NW"),
("DEHJUFVJRJ","DE","Sassnitz","MV"),
("DEDRRKRP95","DE","Sayda","SN"),
("DEHUN1FRJQ","DE","Schalkau","TH"),
("DEIS5JTRKB","DE","Schauenstein","BY"),
("DEBFQ7YIQC","DE","Scheer","BW"),
("DE9HX0765P","DE","Scheibenberg","SN"),
("DE0SQGKA63","DE","Scheinfeld","BY"),
("DE3CMW478G","DE","Schelklingen","BW"),
("DEMZNLHEXQ","DE","Schenefeld","SH"),
("DEVVQ31WS2","DE","Scheßlitz","BY"),
("DEPJJATPDX","DE","Schieder-Schwalenberg","NW"),
("DE20U772NU","DE","Schifferstadt","RP"),
("DE1AFJPD9K","DE","Schillingsfürst","BY"),
("DE80OAXGCN","DE","Schiltach","BW"),
("DEZVXTLARO","DE","Schirgiswalde-Kirschau","SN"),
("DEALVIOJCQ","DE","Schkeuditz","SN"),
("DEUS9J5I3D","DE","Schkölen","TH"),
("DEISNG8038","DE","Schleiden","NW"),
("DEW02IBT6M","DE","Schleiz","TH"),
("DEF243LHTF","DE","Schleswig","SH"),
("DEA2YFL2T4","DE","Schlettau","SN"),
("DEUHK3INBE","DE","Schleusingen","TH"),
("DEODXZ63LL","DE","Schlieben","BB"),
("DE5QPR8I6I","DE","Schlitz","HE"),
("DEL5Y77SB2","DE","Schloß Holte-Stukenbrock","NW"),
("DE9W5SKG78","DE","Schlotheim","TH"),
("DEU4708TME","DE","Schlüchtern","HE"),
("DEKB5SUCBG","DE","Schlüsselfeld","BY"),
("DEH9NP1ZRB","DE","Schmalkalden","TH"),
("DEVX4FEBO8","DE","Schmallenberg","NW"),
("DEFV9OPW29","DE","Schmölln","TH"),
("DE8722JDI1","DE","Schnackenburg","NI"),
("DEN6RO5J01","DE","Schnaittenbach","BY"),
("DEG4HVF53V","DE","Schneeberg","SN"),
("DE1DJQAL0I","DE","Schneverdingen","NI"),
("DET2LDF4F2","DE","Schömberg","BW"),
("DEA6RGPSH5","DE","Schönau","BW"),
("DEXY0C4485","DE","Schönau im Schwarzwald","BW"),
("DEISVTEWB7","DE","Schönberg","MV"),
("DEYXLE10HB","DE","Schönebeck/Elbe","ST"),
("DE69RW192Y","DE","Schöneck/Vogtl.","SN"),
("DE83BC8JHQ","DE","Schönewalde","BB"),
("DECDKQ9VY8","DE","Schongau","BY"),
("DESJMUK35R","DE","Schöningen","NI"),
("DECXNE6PCE","DE","Schönsee","BY"),
("DESOR079RK","DE","Schönwald","BY"),
("DENBAW7840","DE","Schopfheim","BW"),
("DERRUCUZ37","DE","Schöppenstedt","NI"),
("DEXQL4FYJ8","DE","Schorndorf","BW"),
("DEMA8UJ0E6","DE","Schortens","NI"),
("DEBO3IX8IP","DE","Schotten","HE"),
("DE0D1UD42A","DE","Schramberg","BW"),
("DEUNEAMYI8","DE","Schraplau","ST"),
("DE8R2SRGZ3","DE","Schriesheim","BW"),
("DE53L2C4RC","DE","Schrobenhausen","BY"),
("DEHT6VX95S","DE","Schrozberg","BW"),
("DEXK3JIMRR","DE","Schüttorf","NI"),
("DEDUJ5BJ8G","DE","Schwaan","MV"),
("DENUJZZBBH","DE","Schwabach","BY"),
("DE4IC2RHUO","DE","Schwäbisch Gmünd","BW"),
("DE2X7KJZCX","DE","Schwäbisch Hall","BW"),
("DETW34FCL2","DE","Schwabmünchen","BY"),
("DE6416GCNK","DE","Schwaigern","BW"),
("DEVZMMHHBJ","DE","Schwalbach am Taunus","HE"),
("DEEJ4YIGWC","DE","Schwalmstadt","HE"),
("DECZGSB2UI","DE","Schwandorf","BY"),
("DE6WOM9B74","DE","Schwanebeck","ST"),
("DEBURSB2CP","DE","Schwarzenbach am Wald","BY"),
("DELGO4XKG9","DE","Schwarzenbach an der Saale","BY"),
("DEKX2WZWE6","DE","Schwarzenbek","SH"),
("DET3T3F18Q","DE","Schwarzenberg/Erzgeb.","SN"),
("DEVZJ62WWO","DE","Schwarzenborn","HE"),
("DECKSA59JP","DE","Schwarzheide","BB"),
("DE7MM7J0DC","DE","Schwedt/Oder","BB"),
("DE47GJ8OA3","DE","Schweich","RP"),
("DEOTAQP6E2","DE","Schweinfurt","BY"),
("DER7CWGWMO","DE","Schwelm","NW"),
("DEI8V199ED","DE","Schwentinental","SH"),
("DEHUWPI7T6","DE","Schwerin","MV"),
("DE04XQACT1","DE","Schwerte","NW"),
("DEJ6Y03KOM","DE","Schwetzingen","BW"),
("DESKO1T2FA","DE","Sebnitz","SN"),
("DEXB0GJUNJ","DE","Seehausen/Altmark","ST"),
("DEYKA8W4AG","DE","Seeland","ST"),
("DEA8GES50L","DE","Seelow","BB"),
("DEPONIR2TO","DE","Seelze","NI"),
("DEET5XNSHL","DE","Seesen","NI"),
("DEDSU9W5Q7","DE","Sehnde","NI"),
("DED6L6CMS1","DE","Seifhennersdorf","SN"),
("DEAFK1HDQW","DE","Selb","BY"),
("DE7VTUOAG1","DE","Selbitz","BY"),
("DE2BAZG07U","DE","Seligenstadt","HE"),
("DE7S1JETLP","DE","Selm","NW"),
("DE86RQJIMR","DE","Selters/Westerwald","RP"),
("DEDFM1Q22T","DE","Senden","BY"),
("DEEDTVE0PM","DE","Sendenhorst","NW"),
("DESR67KSXS","DE","Senftenberg","BB"),
("DEYOIH658K","DE","Seßlach","BY"),
("DELUMBXP5C","DE","Siegburg","NW"),
("DE2Y7HYX4R","DE","Siegen","NW"),
("DEOAY92V10","DE","Sigmaringen","BW"),
("DEKKIQPRBA","DE","Simbach am Inn","BY"),
("DEMXMJMRWP","DE","Simmern/Hunsrück","RP"),
("DEQ47O1BFQ","DE","Sindelfingen","BW"),
("DELEZOA1PU","DE","Singen/Hohentwiel","BW"),
("DEL7LBZWML","DE","Sinsheim","BW"),
("DET95G115R","DE","Sinzig","RP"),
("DE5CG7OVY9","DE","Soest","NW"),
("DEAXYKZNEL","DE","Solingen","NW"),
("DEVZWUWJGP","DE","Solms","HE"),
("DETL6UNBLT","DE","Soltau","NI"),
("DEO20CYZM8","DE","Sömmerda","TH"),
("DEXLSW86H4","DE","Sondershausen","TH"),
("DE6EZ2YGSR","DE","Sonneberg","TH"),
("DE1YLPA7IZ","DE","Sonnewalde","BB"),
("DE9JC7JYFG","DE","Sonthofen","BY"),
("DEK8CTFUXL","DE","Sontra","HE"),
("DE8XO6DHXF","DE","Spaichingen","BW"),
("DEGJ4QRNQ0","DE","Spalt","BY"),
("DE728Q1O6L","DE","Spangenberg","HE"),
("DEWJEBDCXM","DE","Speicher/Eifel","RP"),
("DE9MTN3Q2J","DE","Spenge","NW"),
("DEA7A1U022","DE","Speyer","RP"),
("DE3AT5YZRV","DE","Spremberg","BB"),
("DEJ67WI5JS","DE","Springe","NI"),
("DESCFV3IFD","DE","Sprockhövel","NW"),
("DEPQFKRHMU","DE","St. Blasien","BW"),
("DERF0QFRMY","DE","St. Georgen im Schwarzwald","BW"),
("DEXTVGZF8R","DE","St. Ingbert","SL"),
("DERONU628V","DE","St. Wendel","SL"),
("DESNFJ42EW","DE","Stade","NI"),
("DEHFNX69W4","DE","Stadt Wehlen","SN"),
("DE3SK37TUZ","DE","Stadtallendorf","HE"),
("DEHHTOK2JD","DE","Stadtbergen","BY"),
("DEQZXU1BRJ","DE","Stadthagen","NI"),
("DEQFHXPD1S","DE","Stadtilm","TH"),
("DE6MVDFQDX","DE","Stadtlengsfeld","TH"),
("DE86LS955Z","DE","Stadtlohn","NW"),
("DE42U6EMQ5","DE","Stadtoldendorf","NI"),
("DE172QL4JR","DE","Stadtprozelten","BY"),
("DERF575I5D","DE","Stadtroda","TH"),
("DEPQ6YWBX1","DE","Stadtsteinach","BY"),
("DEDS7SEXXF","DE","Starnberg","BY"),
("DE505Q5PHW","DE","Staßfurt","ST"),
("DE4M4949NT","DE","Staufen im Breisgau","BW"),
("DE0TSW4PYI","DE","Staufenberg","HE"),
("DEI5AW38B8","DE","Stavenhagen","MV"),
("DE8HYD6GAA","DE","Stein","BY"),
("DE2EK7O81O","DE","Steinach","TH"),
("DE1TL6IJP1","DE","Steinau an der Straße","HE"),
("DEP0XT892H","DE","Steinbach-Hallenberg","TH"),
("DEQ0VXH57K","DE","Steinbach/Taunus","HE"),
("DEKSR90SY2","DE","Steinfurt","NW"),
("DELJ843Y5T","DE","Steinheim","NW"),
("DEY3M7COO2","DE","Steinheim an der Murr","BW"),
("DEPJZ7P7R9","DE","Stendal","ST"),
("DE0IJ1BH3W","DE","Sternberg","MV"),
("DE1C15A7Y9","DE","Stockach","BW"),
("DEALGMA4P0","DE","Stolberg/Rheinland","NW"),
("DENO7CWYMX","DE","Stollberg/Erzgeb.","SN"),
("DEH5YSN2PO","DE","Stolpen","SN"),
("DEEQTPYRY8","DE","Storkow/Mark","BB"),
("DEDFUNJJN7","DE","Stößen","ST"),
("DE8VK5T72A","DE","Straelen","NW"),
("DED1303SOI","DE","Stralsund, Hansestadt","MV"),
("DEJI8H97PN","DE","Strasburg/Uckermark","MV"),
("DEMKA63YEC","DE","Straubing","BY"),
("DETZHN6KYK","DE","Strausberg","BB"),
("DEL1KPT98D","DE","Strehla","SN"),
("DERGU1NKOA","DE","Stromberg","RP"),
("DE4ZG8XUKR","DE","Stühlingen","BW"),
("DET2E0NDK8","DE","Stutensee","BW"),
("DEE5Y8E6L5","DE","Stuttgart","BW"),
("DENG7A1VK6","DE","Südliches Anhalt","ST"),
("DEU1FSW0KQ","DE","Suhl","TH"),
("DE2YQPCBYQ","DE","Sulingen","NI"),
("DEGXZU4L0R","DE","Sulz am Neckar","BW"),
("DE27233N9Y","DE","Sulzbach-Rosenberg","BY"),
("DEOPQKPABR","DE","Sulzbach/Saar","SL"),
("DE91HLCGCT","DE","Sulzburg","BW"),
("DEDBOHWO9Y","DE","Sundern/Sauerland","NW"),
("DEWB1ZYBYN","DE","Süßen","BW"),
("DE0O8QYJH8","DE","Syke","NI"),
("DELZTXF6RS","DE","Tambach-Dietharz","TH"),
("DEHFAD3JC0","DE","Tangerhütte","ST"),
("DEUE0TQYGR","DE","Tangermünde","ST"),
("DENOHL7YUS","DE","Tann/Rhön","HE"),
("DEYOQDUI6B","DE","Tanna","TH"),
("DEXGP1Z11U","DE","Tauberbischofsheim","BW"),
("DEG2O604XN","DE","Taucha","SN"),
("DETE90D4TB","DE","Taunusstein","HE"),
("DESKPM2VYZ","DE","Tecklenburg","NW"),
("DEBN1BP265","DE","Tegernsee","BY"),
("DE4UC5Y9TS","DE","Telgte","NW"),
("DEO3S27MEZ","DE","Teltow","BB"),
("DE73MAYKAA","DE","Templin","BB"),
("DE8BLYDS4I","DE","Tengen","BW"),
("DENGOMQHEE","DE","Tessin","MV"),
("DEL7GSTUR1","DE","Teterow","MV"),
("DEYDBWYL66","DE","Tettnang","BW"),
("DEWS4AL8T8","DE","Teublitz","BY"),
("DEPIUF08UL","DE","Teuchern","ST"),
("DEFBD955A4","DE","Teupitz","BB"),
("DEJM0H77O4","DE","Teuschnitz","BY"),
("DEZTFL29TR","DE","Thale","ST"),
("DESN7SW1EC","DE","Thalheim/Erzgeb.","SN"),
("DECRLIXVMH","DE","Thannhausen","BY"),
("DEIMYQUNUU","DE","Tharandt","SN"),
("DEHAFJK8BC","DE","Themar","TH"),
("DEWI4TKJ5W","DE","Thum","SN"),
("DEAQE8M1P4","DE","Tirschenreuth","BY"),
("DEOOUIBPCT","DE","Titisee-Neustadt","BW"),
("DE0SDK0OWX","DE","Tittmoning","BY"),
("DE71RSKWOV","DE","Todtnau","BW"),
("DEN3495TET","DE","Töging am Inn","BY"),
("DEI9BUYONZ","DE","Tönisvorst","NW"),
("DEG0JHPGFX","DE","Tönning","SH"),
("DEI6P32EYP","DE","Torgau","SN"),
("DEH3ZMWDGE","DE","Torgelow","MV"),
("DEMR8LGWKW","DE","Tornesch","SH"),
("DEW4ELKTI3","DE","Traben-Trarbach","RP"),
("DEZ861M5R4","DE","Traunreut","BY"),
("DE8QQ546JR","DE","Traunstein","BY"),
("DEYSCFOXBL","DE","Trebbin","BB"),
("DE1Q6MJPPI","DE","Trebsen/Mulde","SN"),
("DEXWKK1BO9","DE","Treffurt","TH"),
("DE2FE6MYXK","DE","Trendelburg","HE"),
("DERA0F8B19","DE","Treuchtlingen","BY"),
("DE17WLXM3V","DE","Treuen","SN"),
("DEIOFJZ4T2","DE","Treuenbrietzen","BB"),
("DEJ89576PY","DE","Triberg im Schwarzwald","BW"),
("DEHPEP1FZ3","DE","Tribsees","MV"),
("DENVPLISG0","DE","Trier","RP"),
("DEGWKG0EIJ","DE","Triptis","TH"),
("DENROUYETG","DE","Trochtelfingen","BW"),
("DE4756N5AA","DE","Troisdorf","NW"),
("DE1ZVJRCK8","DE","Trossingen","BW"),
("DE94P9J8T6","DE","Trostberg","BY"),
("DE0H1YWUF1","DE","Tübingen","BW"),
("DE1K7PQHZR","DE","Tuttlingen","BW"),
("DEGVA87UHH","DE","Twistringen","NI"),
("DEZ6QJEKPE","DE","Übach-Palenberg","NW"),
("DE1QDYLSZM","DE","Überlingen","BW"),
("DED6B3OBU5","DE","Uebigau-Wahrenbrück","BB"),
("DE75EFZWWZ","DE","Ueckermünde","MV"),
("DE2MIH67W8","DE","Uelzen","NI"),
("DEYA7J366H","DE","Uetersen","SH"),
("DEDIL2UF71","DE","Uffenheim","BY"),
("DELMGKICJL","DE","Uhingen","BW"),
("DEZ2369ZF8","DE","Ulm","BW"),
("DEAMSDTZV7","DE","Ulmen","RP"),
("DEIG9CWHEH","DE","Ulrichstein","HE"),
("DE3U1L7L77","DE","Ummerstadt","TH"),
("DENADXAT6K","DE","Unkel","RP"),
("DEFYY9YTGG","DE","Unna","NW"),
("DE9PT677NA","DE","Unterschleißheim","BY"),
("DE2OWAA3HY","DE","Usedom","MV"),
("DEDVVOO284","DE","Usingen","HE"),
("DE17EZ0UGA","DE","Uslar","NI"),
("DEKAGRH41K","DE","Vacha","TH"),
("DETYV31D2F","DE","Vaihingen an der Enz","BW"),
("DE8Y3X0C21","DE","Vallendar","RP"),
("DEJG1KAHVV","DE","Varel","NI"),
("DERCM9GOU9","DE","Vechta","NI"),
("DENPDP2F4B","DE","Velbert","NW"),
("DED88DKAF4","DE","Velburg","BY"),
("DERGO1YJXP","DE","Velden","BY"),
("DEVKZC9ULW","DE","Velen","NW"),
("DEJYLMDPYQ","DE","Vellberg","BW"),
("DEY64IHJM8","DE","Vellmar","HE"),
("DE0BAYV7OR","DE","Velten","BB"),
("DESN31HOX1","DE","Verden/Aller","NI"),
("DENIO08MR6","DE","Veringenstadt","BW"),
("DETWPAFCJF","DE","Verl","NW"),
("DENTEI129T","DE","Versmold","NW"),
("DEQCU71S9P","DE","Vetschau/Spreewald","BB"),
("DEAXQJKHQD","DE","Viechtach","BY"),
("DEEFNTS79F","DE","Viernheim","HE"),
("DE1NY2Q8WG","DE","Viersen","NW"),
("DELROMJXBU","DE","Villingen-Schwenningen","BW"),
("DEV1EFJ4TX","DE","Vilsbiburg","BY"),
("DEJHRBO1RP","DE","Vilseck","BY"),
("DEPPSFYPVJ","DE","Vilshofen an der Donau","BY"),
("DEGJ60HIVD","DE","Visselhövede","NI"),
("DEJ9T3DM1X","DE","Vlotho","NW"),
("DE3T9RU0HJ","DE","Voerde/Niederrhein","NW"),
("DEQ9YOYU8F","DE","Vogtsburg im Kaiserstuhl","BW"),
("DEEEGVWC8G","DE","Vohburg an der Donau","BY"),
("DEL1KZNLWR","DE","Vohenstrauß","BY"),
("DEE6I97ZSX","DE","Vöhrenbach","BW"),
("DE9RM7MVN0","DE","Vöhringen","BY"),
("DE94V6G4M2","DE","Volkach","BY"),
("DE661USYL7","DE","Völklingen","SL"),
("DE54GC39AC","DE","Volkmarsen","HE"),
("DE0XKMS8N2","DE","Vreden","NW"),
("DECJ8TNUVU","DE","Wachenheim an der Weinstraße","RP"),
("DE1XPUWA11","DE","Wächtersbach","HE"),
("DEEHDIQNVR","DE","Wadern","SL"),
("DEKGEDO1F1","DE","Waghäusel","BW"),
("DEKNV8IR2K","DE","Wahlstedt","SH"),
("DEPREL2GNH","DE","Waiblingen","BW"),
("DEX1ZOOVF9","DE","Waibstadt","BW"),
("DEBUN0V22F","DE","Waischenfeld","BY"),
("DEQYN9PQTE","DE","Waldbröl","NW"),
("DEH80KON1M","DE","Waldeck","HE"),
("DEO1ADWQN8","DE","Waldenbuch","BW"),
("DEKA9GDCV3","DE","Waldenburg","SN"),
("DEAJDZ96ER","DE","Waldenburg","BW"),
("DEFEB42CQR","DE","Waldershof","BY"),
("DEE15BSSJC","DE","Waldheim","SN"),
("DE3TSG5OKG","DE","Waldkappel","HE"),
("DE7YFH5U8K","DE","Waldkirch","BW"),
("DE9JOCWE3A","DE","Waldkirchen","BY"),
("DEG8L815L4","DE","Waldkraiburg","BY"),
("DEZEL426KA","DE","Waldmünchen","BY"),
("DE40R9UZT4","DE","Waldsassen","BY"),
("DEJIGFXKQD","DE","Waldshut-Tiengen","BW"),
("DESBLTH7YG","DE","Walldorf","BW"),
("DELJLOQ5ZU","DE","Walldürn","BW"),
("DE6R31RX5A","DE","Wallenfels","BY"),
("DEFMQC6GQZ","DE","Walsrode","NI"),
("DESBSAJRQ4","DE","Waltershausen","TH"),
("DEBBT1HSVO","DE","Waltrop","NW"),
("DEJZPAWVLB","DE","Wanfried","HE"),
("DEIBOOSENL","DE","Wangen im Allgäu","BW"),
("DEQGV97MEJ","DE","Wanzleben-Börde","ST"),
("DEY7KG0F4K","DE","Warburg","NW"),
("DEEUVBPHM7","DE","Waren/Müritz","MV"),
("DETAWLPJ7F","DE","Warendorf","NW"),
("DE02O8P3RN","DE","Warin","MV"),
("DEBB3BR8W6","DE","Warstein","NW"),
("DE2SHS94Z2","DE","Wassenberg","NW"),
("DEFWO4FVJG","DE","Wasserburg am Inn","BY"),
("DEY8ONBFBM","DE","Wassertrüdingen","BY"),
("DERFYINVPP","DE","Wasungen","TH"),
("DEN7HWCHZR","DE","Wedel","SH"),
("DEENWUIGAG","DE","Weener","NI"),
("DEOY40EFN5","DE","Wegberg","NW"),
("DEVMOIHD75","DE","Wegeleben","ST"),
("DELP2X71PL","DE","Wehr","BW"),
("DEOLF71POQ","DE","Weida","TH"),
("DEOTR28F74","DE","Weiden in der Oberpfalz","BY"),
("DE1WMIAUOV","DE","Weikersheim","BW"),
("DEKQSRRIDG","DE","Weil am Rhein","BW"),
("DE3TO5JCV7","DE","Weil der Stadt","BW"),
("DE5N9E2HI3","DE","Weilburg","HE"),
("DED5MNZAJJ","DE","Weilheim an der Teck","BW"),
("DE1CBTUO9X","DE","Weilheim in Oberbayern","BY"),
("DEHY30AZ8G","DE","Weimar","TH"),
("DEMIVOZESD","DE","Weingarten","BW"),
("DEJF1JQK2R","DE","Weinheim","BW"),
("DEWEKQ2UOK","DE","Weinsberg","BW"),
("DESRL3QTKD","DE","Weinstadt","BW"),
("DEBG2BUUOE","DE","Weismain","BY"),
("DEAPX090S6","DE","Weißenberg","SN"),
("DEECWH7L10","DE","Weißenburg in Bayern","BY"),
("DEDN34GOHS","DE","Weißenfels","ST"),
("DE4J3ZESDO","DE","Weißenhorn","BY"),
("DEHBPRBHYQ","DE","Weißensee","TH"),
("DEUU71G91T","DE","Weißenstadt","BY"),
("DEW5XCUF5Y","DE","Weißenthurm","RP"),
("DEZ8XD0B2I","DE","Weißwasser/O.L.","SN"),
("DENSAY98P3","DE","Weiterstadt","HE"),
("DE3W5K57D1","DE","Welzheim","BW"),
("DEDBE7RJ5Q","DE","Welzow","BB"),
("DES34TF7C2","DE","Wemding","BY"),
("DEZM18VQCY","DE","Wendlingen am Neckar","BW"),
("DEMIISPWU3","DE","Werben/Elbe","ST"),
("DE88AZSGQK","DE","Werdau","SN"),
("DEJUDY1P10","DE","Werder/Havel","BB"),
("DEC297SM6E","DE","Werdohl","NW"),
("DE5P7VM1YU","DE","Werl","NW"),
("DEA8U2OKN8","DE","Wermelskirchen","NW"),
("DEF07GQ8H3","DE","Wernau/Neckar","BW"),
("DEARB2DHHJ","DE","Werne","NW"),
("DE7PETQCO0","DE","Werneuchen","BB"),
("DELI393QII","DE","Wernigerode","ST"),
("DERPZIXGL7","DE","Wertheim","BW"),
("DE7WALES4M","DE","Werther/Westf.","NW"),
("DEHIF7V48G","DE","Wertingen","BY"),
("DENBQQ289T","DE","Wesel","NW"),
("DEX8BUPX2X","DE","Wesenberg","MV"),
("DEUDJ95NVM","DE","Wesselburen","SH"),
("DE6BU2F2I2","DE","Wesseling","NW"),
("DEE8TGH2AE","DE","Westerburg","RP"),
("DEBL91JCZD","DE","Westerstede","NI"),
("DEPIMU6IHD","DE","Wetter","HE"),
("DETBF8EYAS","DE","Wetter/Ruhr","NW"),
("DE749O7J2J","DE","Wettin-Löbejün","ST"),
("DE5CKOOK2D","DE","Wetzlar","HE"),
("DE2P897PM0","DE","Widdern","BW"),
("DE119FZK76","DE","Wiehe","TH"),
("DEOHVV0YF5","DE","Wiehl","NW"),
("DEAZUZKXCM","DE","Wiesbaden","HE"),
("DEMLVUBIVC","DE","Wiesensteig","BW"),
("DEJ4RJOZQD","DE","Wiesloch","BW"),
("DEGL8GJOMU","DE","Wiesmoor","NI"),
("DENGT8D6U0","DE","Wildau","BB"),
("DESQU38PFS","DE","Wildberg","BW"),
("DET6CI62VM","DE","Wildenfels","SN"),
("DEO438SP2G","DE","Wildeshausen","NI"),
("DE6WOK3JKV","DE","Wilhelmshaven","NI"),
("DEAFYJ4DBY","DE","Wilkau-Haßlau","SN"),
("DEKNHQQDCF","DE","Willebadessen","NW"),
("DEIFNA5QRB","DE","Willich","NW"),
("DEMGVP0GLA","DE","Wilsdruff","SN"),
("DEWJT1X50H","DE","Wilster","SH"),
("DETH7JUKYD","DE","Wilthen","SN"),
("DE0MO5CFHZ","DE","Windischeschenbach","BY"),
("DEWDPWTA7Q","DE","Windsbach","BY"),
("DET1RQ6R8Z","DE","Winnenden","BW"),
("DE8GI30HG1","DE","Winsen/Luhe","NI"),
("DE346FKOFG","DE","Winterberg","NW"),
("DE14DVELL8","DE","Wipperfürth","NW"),
("DEMCZS37RC","DE","Wirges","RP"),
("DENAGOSXPV","DE","Wismar, Hansestadt","MV"),
("DE1WBMLQ3M","DE","Wissen","RP"),
("DEUHH923IO","DE","Witten","NW"),
("DEFHGJO8WC","DE","Wittenberg","ST"),
("DEIC1A9R6B","DE","Wittenberge","BB"),
("DEOHX981V2","DE","Wittenburg","MV"),
("DEIDCKGU8W","DE","Wittichenau","SN"),
("DECPG1XCDG","DE","Wittingen","NI"),
("DEOFRY6X9U","DE","Wittlich","RP"),
("DEF73N8ZQR","DE","Wittmund","NI"),
("DEC2BTXKQ9","DE","Wittstock/Dosse","BB"),
("DE96A7JON7","DE","Witzenhausen","HE"),
("DE3E6ACF4R","DE","Woldegk","MV"),
("DEN8EV75MK","DE","Wolfach","BW"),
("DE8YE5I4FS","DE","Wolfenbüttel","NI"),
("DEBPZUEM2H","DE","Wolfhagen","HE"),
("DE18RDOW5B","DE","Wolframs-Eschenbach","BY"),
("DE4K6CPTWX","DE","Wolfratshausen","BY"),
("DESB3AFI3R","DE","Wolfsburg","NI"),
("DE72LLPN3Q","DE","Wolfstein","RP"),
("DEWV4KR9VV","DE","Wolgast","MV"),
("DEU28JW5HO","DE","Wolkenstein","SN"),
("DEGKZW32NA","DE","Wolmirstedt","ST"),
("DE48WTW0JS","DE","Worms","RP"),
("DEVOCMX8IR","DE","Wörrstadt","RP"),
("DEAQB6VTUC","DE","Wörth am Main","BY"),
("DEET8HVVS0","DE","Wörth am Rhein","RP"),
("DE4OT0ODTK","DE","Wörth an der Donau","BY"),
("DE166ZEPRO","DE","Wriezen","BB"),
("DEG3UBWPOA","DE","Wülfrath","NW"),
("DEJWSERKFV","DE","Wunsiedel","BY"),
("DE88WXMPHO","DE","Wunstorf","NI"),
("DEVONADFYT","DE","Wuppertal","NW"),
("DEIT5FITQ1","DE","Würselen","NW"),
("DEPIGH2VDB","DE","Wurzbach","TH"),
("DE498QZQFV","DE","Würzburg","BY"),
("DEE25SI4M0","DE","Wurzen","SN"),
("DEXRGGL6HA","DE","Wustrow/Wendland","NI"),
("DEPYSRU52Y","DE","Wyk auf Föhr","SH"),
("DEFBPE24AG","DE","Xanten","NW"),
("DE7G9PKVQH","DE","Zahna-Elster","ST"),
("DEN7X8DFJ2","DE","Zarrentin am Schaalsee","MV"),
("DEEBU8GX7W","DE","Zehdenick","BB"),
("DE8WAA1LR8","DE","Zeil am Main","BY"),
("DE11YLWO3J","DE","Zeitz","ST"),
("DEW1R9HBCV","DE","Zell am Harmersbach","BW"),
("DEM7434BZD","DE","Zell im Wiesental","BW"),
("DE7AN9VFHX","DE","Zell/Mosel","RP"),
("DEGFID4MX0","DE","Zella-Mehlis","TH"),
("DEOOA50N1M","DE","Zerbst/Anhalt","ST"),
("DEU5PYHPBP","DE","Zeulenroda-Triebes","TH"),
("DEZZYUFFRW","DE","Zeven","NI"),
("DEVA90X61L","DE","Ziegenrück","TH"),
("DEVCQVZSHU","DE","Zierenberg","HE"),
("DEY7TFW54V","DE","Ziesar","BB"),
("DE52QKHIGD","DE","Zirndorf","BY"),
("DETPDQWFBR","DE","Zittau","SN"),
("DER2MRU4LS","DE","Zörbig","ST"),
("DECE88JC4O","DE","Zossen","BB"),
("DEEV9WDPA6","DE","Zschopau","SN"),
("DEFOWB382U","DE","Zülpich","NW"),
("DEAPL5T7Y5","DE","Zweibrücken","RP"),
("DEL6E5JJUX","DE","Zwenkau","SN"),
("DEE3URT4Y8","DE","Zwickau","SN"),
("DESVKW3MRE","DE","Zwiesel","BY"),
("DECDK5KIB6","DE","Zwingenberg","HE"),
("DEPQB8966O","DE","Zwönitz","SN");