INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("DKTDW9H79W","DK","Århus",NULL),
("DKMB8JHHCM","DK","Bornholm",NULL),
("DKZ4SJN2KW","DK","Capital Region",NULL),
("DK7BICGWYA","DK","Central Jutland",NULL),
("DK9VKQ2UNO","DK","Copenhagen city",NULL),
("DK5W8MEK9D","DK","Frederiksborg",NULL),
("DKP2WC4H8C","DK","Fredriksberg",NULL),
("DKTROANNKW","DK","Fyn",NULL),
("DKI5NKZA95","DK","København",NULL),
("DK7HSL21YR","DK","Nordjylland",NULL),
("DK3V48DDK6","DK","North Jutland",NULL),
("DK48GRW1OE","DK","Region South Denmark",NULL),
("DK6CZ6N9BU","DK","Region Zealand",NULL),
("DKQ4FT6ELA","DK","Ribe",NULL),
("DKAPIN22U7","DK","Ringkøbing",NULL),
("DKBAY8BNNI","DK","Roskilde",NULL),
("DK0MPOW1JN","DK","Sønderjylland",NULL),
("DK5YGBD1LN","DK","Storstrøm",NULL),
("DKR4BT750J","DK","Vejle",NULL),
("DKGZRSNEAO","DK","Vestsjælland",NULL),
("DK10CX2VK7","DK","Viborg",NULL);