INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("DZU4UI81A5","DZ","Adrar",NULL),
("DZ2R54MGGQ","DZ","Aïn Defla",NULL),
("DZ1VOV7PE5","DZ","Aïn Temouchent",NULL),
("DZ96EV5MEZ","DZ","Alger",NULL),
("DZR8HZAS5C","DZ","Annaba",NULL),
("DZJBH6RXWT","DZ","Batna",NULL),
("DZTLO0A35K","DZ","Béchar",NULL),
("DZAKGF7UFY","DZ","Bejaïa",NULL),
("DZ3WYDP3Q9","DZ","Biskra",NULL),
("DZF8F66C0Z","DZ","Blida",NULL),
("DZXP08S5T3","DZ","Bordj Bou Arréridj",NULL),
("DZQ9JY4YX8","DZ","Bouira",NULL),
("DZVVLLZCUE","DZ","Boumerdes",NULL),
("DZKALRMMQK","DZ","Chlef",NULL),
("DZBRT4XM7N","DZ","Constantine",NULL),
("DZWQM1PJ9L","DZ","Djelfa",NULL),
("DZFV6F70US","DZ","El Bayadh",NULL),
("DZAGJX2AHD","DZ","El Oued",NULL),
("DZ1AHYXPMU","DZ","El Tarf",NULL),
("DZG8V5R4Q7","DZ","Ghardaïa",NULL),
("DZ0WM7XG08","DZ","Guelma",NULL),
("DZXK5ZVMDW","DZ","Illizi",NULL),
("DZXUVVKIP0","DZ","Jijel",NULL),
("DZQK5IPWPP","DZ","Khenchela",NULL),
("DZTCXQTYYQ","DZ","Laghouat",NULL),
("DZI3QEQ3AO","DZ","Mascara",NULL),
("DZY6JIO9IF","DZ","Médéa",NULL),
("DZUOXJKN9D","DZ","Mila",NULL),
("DZ074U52KO","DZ","Mostaganem",NULL),
("DZ6B2XEDLD","DZ","Mʼsila",NULL),
("DZK5V9EDO8","DZ","Naama النعامة",NULL),
("DZ2MSMA10A","DZ","Oran",NULL),
("DZ944F7P3D","DZ","Ouargla",NULL),
("DZ06AFKWS4","DZ","Oum el Bouaghi",NULL),
("DZ1ODF22O4","DZ","Relizane",NULL),
("DZOGRYIR9R","DZ","Saïda",NULL),
("DZWD733AH4","DZ","Sétif",NULL),
("DZHSK1OC6P","DZ","Sidi Bel Abbès",NULL),
("DZ0J52LT7A","DZ","Skikda",NULL),
("DZAY8SQHKN","DZ","Souk Ahras",NULL),
("DZVRQZ283K","DZ","Tamanghasset",NULL),
("DZ0NMO0SE1","DZ","Tébessa",NULL),
("DZCJ4YDB8N","DZ","Tiaret",NULL),
("DZ9HG0Z1NV","DZ","Tindouf",NULL),
("DZTEUWMYGM","DZ","Tipaza",NULL),
("DZM2AMVOO7","DZ","Tissemsilt",NULL),
("DZ8S5L3E9D","DZ","Tizi Ouzou",NULL),
("DZVQDVR0QL","DZ","Tlemcen",NULL);