INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("ECEKH0JYN5","EC","Azuay",NULL),
("EC1YSWMG4V","EC","Bolívar",NULL),
("EC8AHCORPK","EC","Cañar",NULL),
("ECH2F935UH","EC","Carchi",NULL),
("ECQBI9A5FB","EC","Chimborazo",NULL),
("EC377QOCMW","EC","Cotopaxi",NULL),
("ECM38AUYUC","EC","El Oro",NULL),
("EC0AL3GFL7","EC","Esmeraldas",NULL),
("ECR4H19WDD","EC","Galápagos",NULL),
("EC4L4SXQOJ","EC","Guayas",NULL),
("ECUXTPVO1W","EC","Imbabura",NULL),
("ECZMZF2LMU","EC","Loja",NULL),
("ECP3WZZ9C4","EC","Los Ríos",NULL),
("ECUHWR7KA1","EC","Manabí",NULL),
("ECI4RDTS9S","EC","Morona-Santiago",NULL),
("ECF97IVUCK","EC","Napo",NULL),
("ECX8JXIW1C","EC","Orellana",NULL),
("ECDX4LIFN0","EC","Pastaza",NULL),
("ECKEED7O5M","EC","Pichincha",NULL),
("ECXC5S7HD4","EC","Provincia de Santa Elena",NULL),
("ECQX29T4M7","EC","Provincia de Santo Domingo de los Tsáchilas",NULL),
("EC1QTK6HLQ","EC","Sucumbios",NULL),
("ECVZ33N8QL","EC","Tungurahua",NULL),
("ECLVDSDQX3","EC","Zamora-Chinchipe",NULL);