INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("EGYTSUWZB1","EG","6th of October",NULL),
("EG8TU4CAWY","EG","Ad Daqahlīyah",NULL),
("EGH35DN9WC","EG","Al Baḩr al Aḩmar",NULL),
("EGJOKQZM1X","EG","Al Buḩayrah",NULL),
("EGGTRCS3E1","EG","Al Fayyūm",NULL),
("EGW869J271","EG","Al Gharbīyah",NULL),
("EG5CFTMB55","EG","Al Ismā‘īlīyah",NULL),
("EG0QWZCXWT","EG","Al Jīzah",NULL),
("EGQO6JRKKO","EG","Al Minūfīyah",NULL),
("EGTRXDT4EZ","EG","Al Minyā",NULL),
("EGHUS46XA6","EG","Al Qāhirah",NULL),
("EGN66043UV","EG","Al Qalyūbīyah",NULL),
("EGR0EJKZ7E","EG","Al Wādī al Jadīd",NULL),
("EGQ5RKA5JS","EG","Alexandria",NULL),
("EG0BW686CW","EG","As Suways",NULL),
("EGDJXHMRCE","EG","Aswān",NULL),
("EGRRXCR5QI","EG","Asyūţ",NULL),
("EGAH2KMLCM","EG","Banī Suwayf",NULL),
("EGW9T5F52T","EG","Būr Sa‘īd",NULL),
("EGOZABQNPI","EG","Dumyāţ",NULL),
("EGFMU6RKP2","EG","Eastern Province",NULL),
("EG1RNOC0B9","EG","Helwan",NULL),
("EG94EPAHIZ","EG","Janūb Sīnāʼ",NULL),
("EGGSA7G0PW","EG","Kafr ash Shaykh",NULL),
("EGMK3E4SH6","EG","Luxor",NULL),
("EGJ4UW456D","EG","Maţrūḩ",NULL),
("EGAL2K2LKI","EG","Qinā",NULL),
("EGEUQUUFQH","EG","Shamāl Sīnāʼ",NULL),
("EGZTW4MDA6","EG","Sūhāj",NULL);