INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("ESJSCQRNFU","ES","Andalusia",NULL),
("ES0Q8N274H","ES","Aragon",NULL),
("ESCHL6ARL8","ES","Asturias",NULL),
("ESUERL5VTO","ES","Autonomous Region of Madrid",NULL),
("ESN6FEUU8U","ES","Balearic Islands",NULL),
("ESKHINOM40","ES","Basque Country",NULL),
("ES4Q7EHSNB","ES","Canary Islands",NULL),
("ES6EWCAQ1X","ES","Cantabria",NULL),
("ESXGBRAKMV","ES","Castille and León",NULL),
("ES14IQQNQU","ES","Castille-La Mancha",NULL),
("ESDX9UQX6W","ES","Catalonia",NULL),
("ESC29MSAJP","ES","Ceuta",NULL),
("ESQVH1F3WG","ES","Extremadura",NULL),
("ES7F7Y2XTF","ES","Galicia",NULL),
("ESV2ALZGIC","ES","La Rioja",NULL),
("ESJSYC2H2T","ES","Murcia",NULL),
("ESCJUSMR9U","ES","Navarre",NULL),
("ES6GS9ELPA","ES","Valencia",NULL);