INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("ETOZWOGF0Z","ET","Addis Abeba",NULL),
("ET7YB9GD3T","ET","Adis Abeba",NULL),
("ETXXLJPUDV","ET","Āfar",NULL),
("ETB54PRTZF","ET","Āmara",NULL),
("ETTV39B39I","ET","Arsi",NULL),
("ET2LSIZVCW","ET","Asosa",NULL),
("ETTXGISTE3","ET","Bale",NULL),
("ETZITRCT66","ET","Bīnshangul Gumuz",NULL),
("ETPAG0EQIG","ET","Borena ",NULL),
("ETBAZB6B7Z","ET","Debub Gonder",NULL),
("ET9OI2IW6H","ET","Debub Shewa",NULL),
("ETFZ8RSFYI","ET","Debub Welo",NULL),
("ETPEI341KG","ET","Dire Dawa",NULL),
("ETBJRIVZH4","ET","Eritrea",NULL),
("ETN075WDNB","ET","Gambela",NULL),
("ETCW35B1N1","ET","Gambēla Hizboch",NULL),
("ETG65K7P0J","ET","Gamo Gofa",NULL),
("ET9S14RJ9F","ET","Gojam",NULL),
("ETJGLFT8R6","ET","Gonder",NULL),
("ET5UCHWZIC","ET","Harerge",NULL),
("ET5NXDDYWM","ET","Hārerī Hizb",NULL),
("ETQXRIG0Y0","ET","Ilubabor",NULL),
("ETHJFAR6HW","ET","Kefa",NULL),
("ET1TDYTWBZ","ET","Metekel",NULL),
("ETK8CX68KX","ET","Mirab Gojam",NULL),
("ET5BGMBEMS","ET","Mirab Harerge",NULL),
("ETX23P9KMB","ET","Mirab Shewa",NULL),
("ETDZ97WK6G","ET","Misrak Gojam",NULL),
("ETSIDZQYXW","ET","Misrak Harerge",NULL),
("ET9EIKS5DP","ET","Nazret",NULL),
("ET7HFH11SF","ET","Ogaden",NULL),
("ET11MXMSDF","ET","Omo",NULL),
("ETBRE1PCYZ","ET","Oromīya",NULL),
("ETQHJJMX9U","ET","Semen Gonder",NULL),
("ETEOBGP3VQ","ET","Semen Shewa",NULL),
("ET5INRB16M","ET","Semen Welo",NULL),
("ETTLOJXMIO","ET","Sidamo",NULL),
("ET327QZGKE","ET","Sumalē",NULL),
("ET4VUUZQK4","ET","Tigray",NULL),
("ET88VJA263","ET","Welega",NULL),
("ETNVNLH59L","ET","Welega Kifle Hager",NULL),
("ET7HB7XWL2","ET","Welo",NULL),
("ETRGWQ6GVF","ET","YeDebub Bihēroch Bihēreseboch na Hizboch",NULL);