INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("GR91TXD03M","GR","Attica",NULL),
("GRMU95PZLC","GR","Central Greece",NULL),
("GRGH37B4U9","GR","Central Macedonia",NULL),
("GRYFMGY8H8","GR","Crete",NULL),
("GRAA5NB8AY","GR","East Macedonia and Thrace",NULL),
("GR3K4SJP5Z","GR","Epirus",NULL),
("GR786ID1SB","GR","Ionian Islands",NULL),
("GRHFSGN9OX","GR","Mount Athos",NULL),
("GRKULW2VU6","GR","North Aegean",NULL),
("GRFYZZO4YV","GR","Peloponnese",NULL),
("GRD5EQ762O","GR","South Aegean",NULL),
("GRLV495T7P","GR","Thessaly",NULL),
("GRNSLQOGW4","GR","West Greece",NULL),
("GREW3202XD","GR","West Macedonia",NULL);