INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("GT29D82LXP","GT","Alta Verapaz",NULL),
("GTEJF2ZC7E","GT","Baja Verapaz",NULL),
("GT8BG8EEMN","GT","Chimaltenango",NULL),
("GTQR39Z7D2","GT","Chiquimula",NULL),
("GTHRAJC79R","GT","El Progreso",NULL),
("GTRPUQ1149","GT","Escuintla",NULL),
("GTDLIR05EQ","GT","Guatemala",NULL),
("GTXHZWPDY6","GT","Huehuetenango",NULL),
("GT58QHG097","GT","Izabal",NULL),
("GTP3YQ530I","GT","Jalapa",NULL),
("GTOJ9POOFL","GT","Jutiapa",NULL),
("GT5FIVTG1Y","GT","Petén",NULL),
("GTPSG6SPDH","GT","Quetzaltenango",NULL),
("GTTC8YF9G4","GT","Quiché",NULL),
("GTSQTHE92K","GT","Retalhuleu",NULL),
("GTPLFJ2HHR","GT","Sacatepéquez",NULL),
("GT9YY2OBKH","GT","San Marcos",NULL),
("GTOTF42W8U","GT","Santa Rosa",NULL),
("GTN2B2CEM1","GT","Sololá",NULL),
("GTZ2L2J2TT","GT","Suchitepéquez",NULL),
("GT1SVP4G6S","GT","Totonicapán",NULL),
("GT9MWBJ566","GT","Zacapa",NULL);