INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("HN59R2CG9E","HN","Atlántida",NULL),
("HN0BF4GSH2","HN","Choluteca",NULL),
("HNFEK1LIOR","HN","Colón",NULL),
("HNMJEXTOZZ","HN","Comayagua",NULL),
("HNYR1A7BO8","HN","Copán",NULL),
("HNM3C3VU6B","HN","Cortés",NULL),
("HN8QDU81LV","HN","El Paraíso",NULL),
("HNL0SEPREN","HN","Francisco Morazán",NULL),
("HNJFXQRLYE","HN","Gracias a Dios",NULL),
("HNPBHL5NXE","HN","Intibucá",NULL),
("HNDB8MCUHY","HN","Islas de la Bahía",NULL),
("HNV9DK1R7K","HN","La Paz",NULL),
("HN75BYRACG","HN","Lempira",NULL),
("HNLT2RG06U","HN","Ocotepeque",NULL),
("HNBEGO9YN4","HN","Olancho",NULL),
("HN80O9RWUZ","HN","Santa Bárbara",NULL),
("HN16XSGA92","HN","Valle",NULL),
("HN3CUKC0EO","HN","Yoro",NULL);