INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("HRFVDOT0T1","HR","Bjelovarsko-Bilogorska",NULL),
("HR1IBTE5SF","HR","Brodsko-Posavska",NULL),
("HRCQ7T0GV3","HR","Dubrovačko-Neretvanska",NULL),
("HRTPO5Q2U5","HR","Grad Zagreb",NULL),
("HRX8UQ9ORA","HR","Istarska",NULL),
("HR623K8W0L","HR","Karlovačka",NULL),
("HRM8EMOAQI","HR","Koprivničko-Križevačka",NULL),
("HRZENQHIVE","HR","Krapinsko-Zagorska",NULL),
("HRRQ50EXAK","HR","Ličko-Senjska",NULL),
("HR0E59A5UW","HR","Međimurska",NULL),
("HRD8J2I9KI","HR","Osječko-Baranjska",NULL),
("HRO885R4JI","HR","Požeško-Slavonska",NULL),
("HRUPI8MTTM","HR","Primorsko-Goranska",NULL),
("HR7YVH3PEH","HR","Šibensko-Kniniska",NULL),
("HRYYJH74ZV","HR","Sisačko-Moslavačka",NULL),
("HRC813DKL8","HR","Splitsko-Dalmatinska",NULL),
("HR94HWXAI4","HR","Varaždinska",NULL),
("HR9EMC41U3","HR","Virovitičk-Podravska",NULL),
("HRZDK7IK3U","HR","Vukovarsko-Srijemska",NULL),
("HRT4X6PJEZ","HR","Zadarska",NULL),
("HRNVVK6EPF","HR","Zagrebačka",NULL);