INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("IESLIWNAIO","IE","Carlow",NULL),
("IET9OFRUEQ","IE","Cavan",NULL),
("IEO240ZDK3","IE","Cork",NULL),
("IEV273EI46","IE","County Clare",NULL),
("IE3M2QXLER","IE","County Kerry",NULL),
("IEU26MXLDL","IE","County Kildare",NULL),
("IEOHMNV7QQ","IE","County Kilkenny",NULL),
("IE9YUNGYTJ","IE","County Longford",NULL),
("IELWAJHOAC","IE","County Louth",NULL),
("IERHYP2BBR","IE","County Mayo",NULL),
("IETXEO55EE","IE","County Meath",NULL),
("IE382K7V4T","IE","County Offaly",NULL),
("IESECA3MMV","IE","County Roscommon",NULL),
("IE4LK6WVYP","IE","County Sligo",NULL),
("IETCDYHSDL","IE","County Waterford",NULL),
("IE1F69BA23","IE","County Westmeath",NULL),
("IEPFDS20N6","IE","County Wexford",NULL),
("IEL8DI4B8Y","IE","County Wicklow",NULL),
("IEOMX5EARG","IE","Donegal",NULL),
("IEQXP18S5X","IE","Dún Laoghaire-Rathdown",NULL),
("IE7JQ9JDG5","IE","Fingal County",NULL),
("IEMTNQ4VOS","IE","Galway",NULL),
("IEHLYWWQCM","IE","Laois",NULL),
("IEN2NWUTT2","IE","Leitrim",NULL),
("IECJBWXR1J","IE","Limerick",NULL),
("IELPAPKYI2","IE","Monaghan",NULL),
("IEKHYG7B2V","IE","South Dublin",NULL),
("IEDQR8JLAV","IE","Tipperary North Riding",NULL),
("IE5MS3ETMZ","IE","Tipperary South Riding",NULL);