INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("INF2P733I1","IN","Abhayapuri","Assam"),
("IN5WVHG6H4","IN","Achabbal","Jammu & Kashmir"),
("INEF9N47NE","IN","Achhnera","Uttar Pradesh"),
("IN8XSLEHYU","IN","Adalaj","Gujrat"),
("INKO1ORKPX","IN","Adari","Uttar Pradesh"),
("INGKEXQW25","IN","Adilabad","Andhra Pradesh"),
("INBBSGJFUR","IN","Adityana","Gujrat"),
("INDNDS5BMP","IN","Adoni","Andhra Pradesh"),
("INZODQ83NP","IN","Adoor","Kerala"),
("INN2MEYOJ9","IN","Adra"," Purulia"),
("IN0CPJRKA5","IN","Agartala","Tripura"),
("IN7OXDZK3Z","IN","Agra","Uttar Pradesh"),
("IN8GQHKE77","IN","Ahiwara","Chhattisgarh"),
("INGUMEJ5OJ","IN","Ahmedabad","Gujarat"),
("INHE29YDF6","IN","Ahmedgarh","Punjab"),
("IN2CJ1XM15","IN","Ahmednagar","Maharashtra"),
("IN3RNN5UVM","IN","Aizawl","Mizoram"),
("INOH17NPR4","IN","Ajmer","Rajasthan"),
("IN3UE27T89","IN","Akaltara","Chhattisgarh"),
("IN6SB3FC9I","IN","Akathiyoor","Kerala"),
("IN4W6AQ2WF","IN","Akhnoor","Jammu & Kashmir"),
("INJYM6NEBR","IN","Akola","Maharashtra"),
("IN8PTGJ2QP","IN","Alang","Gujrat"),
("INV1SAE1SJ","IN","Alappuzha","Kerala"),
("INYZTO1Q4K","IN","Aldona","Goa"),
("INORRC533D","IN","Aligarh","Uttar Pradesh"),
("INTXTCZJ1V","IN","Alipurduar","West Bengal"),
("INLU5ZWYJU","IN","Allahabad","Uttar Pradesh"),
("INXCJY3NJS","IN","Almora","Uttarakhand"),
("INEB4KE7X7","IN","Along","Arunachal Pradesh"),
("IN5RK5AM0V","IN","Alwar","Rajasthan"),
("INH5VD3F81","IN","Amadalavalasa","Andhra Pradesh"),
("INRSZVFJNU","IN","Amalapuram","Andhra Pradesh"),
("INURF9ZCH4","IN","Amarpur","Bihar"),
("IN329EO9A5","IN","Ambagarh Chowki","Chhattisgarh"),
("INF6JJLRKD","IN","Ambaji","Gujrat"),
("INJJ8Z3WUY","IN","Ambala","Haryana"),
("INN97NMPRQ","IN","Ambaliyasan","Gujrat"),
("INR14FBFLQ","IN","Ambikapur","Chhattisgarh"),
("INL496WTKG","IN","Amguri","Assam"),
("INDTFGPAEC","IN","Amlabad","Jharkhand"),
("INKMZ6BRW2","IN","Amli","Dadra & Nagar Haveli"),
("INT1I4G3V2","IN","Amravati","Maharashtra"),
("IN8484YTKC","IN","Amreli","Gujarat"),
("INM0SBB7OV","IN","Amritsar","Punjab"),
("INUN25FZ88","IN","Amroha","Uttar Pradesh"),
("IN1RCHV7J3","IN","Anakapalle","Andhra Pradesh"),
("INCS8BLTN8","IN","Anand","Gujarat"),
("INTGJ4N70I","IN","Anandapur","Orissa"),
("INV3NA2WJ3","IN","Anandnagaar","Assam"),
("INNWLJ45NG","IN","Anantapur","Andhra Pradesh"),
("INXVRJOFRI","IN","Anantnag","Jammu & Kashmir"),
("INVBNJIN1D","IN","Ancharakandy","Kerala"),
("INRPOTL8X9","IN","Andada","Gujrat"),
("IN4JT8OGPM","IN","Anjar","Gujrat"),
("INBH6ZWYIR","IN","Anklav","Gujrat"),
("IN95BSTC5K","IN","Ankleshwar","Gujarat"),
("IN1UEN2CX6","IN","Antaliya","Gujrat"),
("INVQFK647H","IN","Anugul","Orissa"),
("INLEHICZAM","IN","Ara","Jharkhand"),
("IN5LEYYKIZ","IN","Arakkonam","Tamil Nadu"),
("INEXNH9KO5","IN","Arambagh","West Bengal"),
("INB3PH8XZU","IN","Arambhada","Gujrat"),
("INBHCNHN9M","IN","Arang","Chhattisgarh"),
("IN8NK7836N","IN","Araria","Bihar"),
("IN0U4AFTFQ","IN","Arasikere","Karnataka"),
("INX475270D","IN","Arcot","Tamil Nadu"),
("INOD050AS9","IN","Areraj","Bihar"),
("INYDG6GNTH","IN","Arki","Himachal Pradesh"),
("INHYRXR7NO","IN","Arnia","Jammu & Kashmir"),
("INCVUE2VRQ","IN","Aroor","Kerala"),
("IN8SW82OI0","IN","Arrah","Bihar"),
("IN1Y7IL1Z3","IN","Aruppukkottai","Tamil Nadu"),
("INZR0RYNGA","IN","Asankhurd","Haryana"),
("INIBOL6GBE","IN","Asansol","West Bengal"),
("IN88NAW5BY","IN","Asarganj","Bihar"),
("IN3JGPKGSK","IN","Ashok Nagar","Madhya Pradesh"),
("IN8TC6GSHZ","IN","Ashtamichira","Kerala"),
("IN46KAMWPU","IN","Asika","Orissa"),
("IN4C51IHZM","IN","Asola","Delhi"),
("IN0GBLW455","IN","Assandh","Haryana"),
("INXIBDATDF","IN","Ateli","Haryana"),
("INZYPMUEHZ","IN","Attingal","Kerala"),
("INRM1930V4","IN","Atul","Gujrat"),
("INH7PEBUJ8","IN","Aurangabad","Maharashtra"),
("INCVMNOZ2O","IN","Aurangabad","Bihar"),
("INYSAS7SSZ","IN","Avinissery","Kerala"),
("INET8IU4MB","IN","Awantipora","Jammu & Kashmir"),
("INBBPN69VJ","IN","Azamgarh","Uttar Pradesh"),
("IN4I7TIAHG","IN","Babiyal","Haryana"),
("IN2S9AK19Z","IN","Baddi","Himachal Pradesh"),
("INVIHPM41Y","IN","Bade Bacheli","Chhattisgarh"),
("INGRMN0I64","IN","Badepalle","Andhra Pradesh"),
("IN0EXIOFZR","IN","Badharghat","Tripura"),
("IN882SABS5","IN","Bagaha","Bihar"),
("INT9VGEWFU","IN","Bahadurganj","Bihar"),
("INN1HNJOSK","IN","Bahadurgarh","Haryana"),
("IN3Q2R62JE","IN","Baharampur","West Bengal"),
("INAL7LXZRR","IN","Bahraich","Uttar Pradesh"),
("IN9M7NINI6","IN","Bairgania","Bihar"),
("INP0U8OMSR","IN","Bakhtiarpur","Bihar"),
("INDVJJX3Y8","IN","Balaghat","Madhya Pradesh"),
("INP5UM4LED","IN","Balangir","Orissa"),
("IN7L1P9JWY","IN","Balasore","Orissa"),
("INJQ78D00Q","IN","Baleshwar","Orissa"),
("INVKATO82D","IN","Bali","Rajasthan"),
("INDW0IHEWO","IN","Ballabhgarh","Hariyana"),
("IN0XEAHA81","IN","Ballia","Uttar Pradesh"),
("IN1FAEFB4B","IN","Bally","West Bengal"),
("INVF5KN7X1","IN","Balod","Chhattisgarh"),
("IN3YKLDG9E","IN","Baloda Bazar","Chhattisgarh"),
("INEOOWZWY0","IN","Balrampur","Uttar Pradesh"),
("INC8ESJJ3F","IN","Balurghat","West Bengal"),
("INY8ZMGXOK","IN","Bamra","Orissa"),
("INW859PFO4","IN","Banda","Uttar Pradesh"),
("IN3C129Z3L","IN","Bandikui","Rajasthan"),
("IN7IDR1H60","IN","Bandipore","Jammu & Kashmir"),
("INQ6N64CR0","IN","Bangalore","Karnataka"),
("INLWAABYFF","IN","Banganapalle","Andhra Pradesh"),
("INAGIJFL5N","IN","Banka","Bihar"),
("IN3JE50L6R","IN","Bankura","West Bengal"),
("INRTYW5PWQ","IN","Banmankhi Bazar","Bihar"),
("INL71X5HCG","IN","Banswara","Rajastan"),
("INXU0DG60K","IN","Bapatla","Andhra Pradesh"),
("INPFPQ0VHS","IN","Barahiya","Bihar"),
("INPFOU5KLQ","IN","Barakar","West Bengal"),
("INSNOY41E2","IN","Baramati","Maharashtra"),
("INVFFCLGWA","IN","Baramula","Jammu & Kashmir"),
("INVM1VHIN6","IN","Baran","Rajasthan"),
("INYC13XMUP","IN","Barasat","West Bengal"),
("INAINEJ2HF","IN","Barauli","Bihar"),
("INHWS3DOE9","IN","Barbigha","Bihar"),
("INAF4SYSZW","IN","Barbil","Orissa"),
("IN5002NVRX","IN","Bardhaman","West Bengal"),
("INEFBYHTDZ","IN","Bareilly","Uttar Pradesh"),
("INQ623VGC6","IN","Bargarh","Orissa"),
("INWHYUAXRF","IN","Barh","Bihar"),
("INXRILM9I0","IN","Baripada","Orissa"),
("INPUZ6NC6D","IN","Barmer","Rajasthan"),
("INJ8GEPTKL","IN","Barnala","Punjab"),
("INBJGMG71E","IN","Barpeta","Assam"),
("INYJZLTIMI","IN","Barpeta Road","Assam"),
("INCLPZYVDH","IN","Barughutu","Jharkhand"),
("IN4UWTNGFZ","IN","Barwala","Haryana"),
("IN0WLG3MV2","IN","Basudebpur","Orissa"),
("IN6VO0DAJQ","IN","Batala","Punjab"),
("INW8PV32D7","IN","Bathinda","Punjab"),
("INX91KQHKQ","IN","Bazpur","Uttarakhand"),
("IND57HS3JZ","IN","Begusarai","Bihar"),
("INZ7ZCII2F","IN","Behea","Bihar"),
("INRSAUVO2S","IN","Belgaum","Karnataka"),
("INX4DOMXF0","IN","Bellampalle","Andhra Pradesh"),
("IN2NHVR1UQ","IN","Bellary","Karnataka"),
("IN9U3SC573","IN","Belpahar","Orissa"),
("INYIYU71M5","IN","Bemetra","Chhattisgarh"),
("IN60TSX9T0","IN","Bethamcherla","Andhra Pradesh"),
("INWAWOCQEL","IN","Bettiah","Bihar"),
("INKHDXNL1L","IN","Betul","Madhya Pradesh"),
("IN4ZFB12G7","IN","Bhabua","Bihar"),
("IN2A00JT1G","IN","Bhadrachalam","Andhra Pradesh"),
("IN3X4GNI18","IN","Bhadrak","Orissa"),
("IN0F5N1785","IN","Bhagalpur","Bihar"),
("IN7OG8QXFS","IN","Bhagha Purana","Punjab"),
("IN7GTR9U7D","IN","Bhainsa","Andhra Pradesh"),
("INRCTFUVOU","IN","Bharuch","Gujarat"),
("INAUIB1QH8","IN","Bhatapara","Chhattisgarh"),
("INEYG5VWY3","IN","Bhavani","Tamil Nadu"),
("INDRUML1ZD","IN","Bhavnagar","Gujarat"),
("INETT8OH3Z","IN","Bhawanipatna","Orissa"),
("INBLBDCSLR","IN","Bheemunipatnam","Andhra Pradesh"),
("INQ2WLZUOC","IN","Bhimavaram","Andhra Pradesh"),
("INLIY7KYKY","IN","Bhiwani","Haryana"),
("INSE7GVBG7","IN","Bhongir","Andhra Pradesh"),
("INXRK9J519","IN","Bhopal","Madhya Pradesh"),
("IN8YV7SJJE","IN","Bhuban","Orissa"),
("IN2IMNG6L8","IN","Bhubaneswar","Orissa"),
("INLTPG55N2","IN","Bhuj","Gujarat"),
("INW7CGDDPL","IN","Bidhan Nagar","West Bengal"),
("INBKT44CJ6","IN","Bihar Sharif","Bihar"),
("INU5UBCGKX","IN","Bikaner","Rajasthan"),
("IN9ADFG1HD","IN","Bikramganj","Bihar"),
("IN9UTM8J8K","IN","Bilasipara","Assam"),
("IN31O8D8F8","IN","Bilaspur","Himachal Pradesh"),
("IND9KPP4MZ","IN","Bilaspur","Chhattisgarh"),
("INF0EV2W8B","IN","Biramitrapur","Orissa"),
("INQ2YYL6IP","IN","Birgaon","Chhattisgarh"),
("IN77XLFCUS","IN","Bobbili","Andhra Pradesh"),
("INMEIBJ5BZ","IN","Bodh Gaya","Bihar"),
("IN6PU8L3JB","IN","Bodhan","Andhra Pradesh"),
("IN5HAQOSGW","IN","Bokaro Steel City","Jharkhand"),
("IN0DHFQC8C","IN","Bomdila","Arunachal Pradesh"),
("INRRNBXYA3","IN","Bongaigaon","Assam"),
("INO5C98VLE","IN","Brahmapur","Orissa"),
("INDV51OLXP","IN","Brajrajnagar","Orissa"),
("INZF4PSD1J","IN","Budhlada","Punjab"),
("IN5OU2N56B","IN","Burhanpur","Madhya Pradesh"),
("INAILJE6YS","IN","Buxar","Bihar"),
("IN24URQSGP","IN","Byasanagar","Orissa"),
("IN8LE0ZFJ4","IN","Calcutta","West Bengal"),
("IN4E7RKE3V","IN","Cambay","Gujarat"),
("INWOEBVD3Y","IN","Chaibasa","Jharkhand"),
("INHXP7P5WX","IN","Chakradharpur","Jharkhand"),
("INRBYQQIVV","IN","Chalakudy","Kerala"),
("INW2NGGQCD","IN","Chalisgaon","Maharashtra"),
("INFQOB4S9M","IN","Chamba","Himachal Pradesh"),
("INPZTF5QDW","IN","Chamba","Uttarakhand"),
("IN1BNSTINQ","IN","Champa","Chhattisgarh"),
("INKA711JFH","IN","Champhai","Mizoram"),
("INA3SEV20L","IN","Chamrajnagar","Karnataka"),
("IN1U17LE4N","IN","Chandan Bara","Bihar"),
("INQRGJ93AU","IN","Chandausi","Uttar Pradesh"),
("INEHWG1BXB","IN","Chandigarh","Punjab"),
("INEQQASRWU","IN","Chandrapura","Jharkhand"),
("INMX17B6V1","IN","Changanassery","Kerala"),
("INXBL6FV1T","IN","Chanpatia","Bihar"),
("INDXAE87QN","IN","Charkhi Dadri","Haryana"),
("INXGXQ8TKU","IN","Chatra","Jharkhand"),
("INQM22SX4P","IN","Cheeka","Haryana"),
("IN8QWNMXHZ","IN","Chendamangalam","Kerala"),
("INURE3Y4QW","IN","Chengalpattu","Tamil Nadu"),
("INLOMUI7O8","IN","Chengannur","Kerala"),
("INUQBNNGDW","IN","Chennai","Tamil Nadu"),
("IN69JS70S2","IN","Cherthala","Kerala"),
("INR65QBVNX","IN","Cheruthazham","Kerala"),
("INJAR1IGAC","IN","Chhapra","Bihar"),
("IN6M0U2DQ8","IN","Chhatarpur","Madhya Pradesh"),
("INNA1UATW2","IN","Chikkaballapur","Karnataka"),
("IN02TCXHAH","IN","Chikmagalur","Karnataka"),
("INS2JAIUNP","IN","Chilakaluripet","Andhra Pradesh"),
("INGNJJ1ASO","IN","Chinchani","Maharashtra"),
("INKTIVNFYO","IN","Chinna salem","Tamil nadu"),
("INHR0F9BX1","IN","Chinsura","West Bengal"),
("INDGCVBZKS","IN","Chintamani","Karnataka"),
("INN4BOF4D0","IN","Chirala","Andhra Pradesh"),
("INXWVLBT9T","IN","Chirkunda","Jharkhand"),
("INLA9UL6WZ","IN","Chirmiri","Chhattisgarh"),
("INN8UZ8FRV","IN","Chitradurga","Karnataka"),
("INK3K07X05","IN","Chittoor","Andhra Pradesh"),
("INTVQ5P0ZA","IN","Chittur-Thathamangalam","Kerala"),
("INB85WF2W3","IN","Chockli","Kerala"),
("INAR2J7UER","IN","Churi","Jharkhand"),
("INXZS4WS9Q","IN","Coimbatore","Tamil Nadu"),
("INN0VD0VNC","IN","Colgong","Bihar"),
("IN3T9JV5M6","IN","Contai","West Bengal"),
("INWPP3K4VH","IN","Cooch Behar","West Bengal"),
("IN3NM0FWQ3","IN","Coonoor","Tamil Nadu"),
("INWMGXH49L","IN","Cuddalore","Tamil Nadu"),
("INYI4TNR0K","IN","Cuddapah","Andhra Pradesh"),
("INHQN1VJJY","IN","Curchorem Cacora","Goa"),
("IN65ZM1QQY","IN","Cuttack","Orissa"),
("INC6VUB5F9","IN","Dabra","Madhya Pradesh"),
("INOK3CC3WU","IN","Dadri","Uttar Pradesh"),
("INUKWP4FOB","IN","Dahod","Gujarat"),
("INLNXMDNLQ","IN","Dalhousie","Himachal Pradesh"),
("INUHK5M0EB","IN","Dalli-Rajhara","Chhattisgarh"),
("INLHNYLKTF","IN","Dalsinghsarai","Bihar"),
("IN4P585TJQ","IN","Daltonganj","Jharkhand"),
("INHHDV5YLZ","IN","Daman and Diu","Daman & Diu"),
("INF6527KDT","IN","Darbhanga","Bihar"),
("IN10SNKL2P","IN","Darjeeling","West Bengal"),
("INB8YG1H6J","IN","Dasua","Punjab"),
("INZJE4IZ4X","IN","Datia","Madhya Pradesh"),
("IN6AZDUC7V","IN","Daudnagar","Bihar"),
("INDZJXKLNV","IN","Davanagere","Karnataka"),
("INULBV3IE2","IN","Debagarh","Orissa"),
("IN2T7KSCHZ","IN","Deesa","Gujarat"),
("INMHCGTJC7","IN","Dehradun","Uttarakhand"),
("INJV43HSZB","IN","Dehri-on-Sone","Bihar"),
("INDA7GTMJV","IN","Delhi","Delhi"),
("INFRF83X7Q","IN","Deoghar","Jharkhand"),
("INEK784JFN","IN","Deoria","Uttar Pradesh"),
("INFKQWCP8P","IN","Devarakonda","Andhra Pradesh"),
("IN0G6U3QPI","IN","Devgarh","Maharashtra"),
("INH5RL2YCH","IN","Dewas","Madhya Pradesh"),
("INJJPN24AI","IN","Dhaka","Bihar"),
("INO1F0QNQR","IN","Dhamtari","Chhattisgarh"),
("IN4XL7OBQ6","IN","Dhanbad","Jharkhand"),
("INGHSJG40Z","IN","Dhar","Madhya Pradesh"),
("INNPMQUW8J","IN","Dharampur"," India"),
("INXOKOBAGG","IN","Dharamsala","Himachal Pradesh"),
("IN82NXDE3U","IN","Dharmanagar","Tripura"),
("INVWDB0EBO","IN","Dharmapuri","Tamil Nadu"),
("IN3XEYUNHS","IN","Dharmavaram","Andhra Pradesh"),
("INB1HNCX3L","IN","Dharwad","Karnataka"),
("IN0RID5M71","IN","Dhekiajuli","Assam"),
("INILCIZN63","IN","Dhenkanal","Orissa"),
("INLL1F8J8K","IN","Dholka","Gujarat"),
("INKP7XNBIN","IN","Dhubri","Assam"),
("IN2017N985","IN","Dhule","Maharashtra"),
("INULOU9VYV","IN","Dhuri","Punjab"),
("INGZBPJJ94","IN","Dibrugarh","Assam"),
("IN9H1WSJKU","IN","Digboi","Assam"),
("INKL28VBDQ","IN","Dighwara","Bihar"),
("INX2K6YI2E","IN","Dimapur","Nagaland"),
("INID42WE65","IN","Dinanagar","Punjab"),
("INV72NQMIB","IN","Dindigul","Tamil Nadu"),
("IN8LJ4WXUT","IN","Diphu","Assam"),
("INZF0XX2CG","IN","Dipka","Chhattisgarh"),
("INFHICWOIR","IN","Dispur","Assam"),
("INWKFN7YYG","IN","Dombivli","Maharashtra"),
("INJIKGFE9F","IN","Dongargarh","Chhattisgarh"),
("INT9DRBQ7R","IN","Dumka","Jharkhand"),
("IN8Q34FLWB","IN","Dumraon","Bihar"),
("IN6CYDAWTU","IN","Durg-Bhilai Nagar","Chhattisgarh"),
("INFDAUSJAL","IN","Durgapur","Maharashtra"),
("INTOD5EKXN","IN","Durgapur","West Bengal"),
("INB0RQMN1T","IN","Ellenabad 2","Haryana"),
("IN0Z6BW05B","IN","Eluru","Andhra Pradesh"),
("INEF67ZHST","IN","Erattupetta","Kerala"),
("IN55ZKQW72","IN","Erode","Tamil Nadu"),
("INXYSJMUCM","IN","Etawah","Uttar Pradesh"),
("INUJXQK32Y","IN","Faridabad","Haryana"),
("INJ85JPYCV","IN","Faridkot","Punjab"),
("IN4BFV8MX5","IN","Farooqnagar","Andhra Pradesh"),
("INLQP7K1UE","IN","Fatehabad","Uttar Pradesh"),
("INLS55W74F","IN","Fatehabad","Haryana"),
("INGAY59B0E","IN","Fatehabad","Madhya Pradesh"),
("INNG9V270N","IN","Fatehpur","Uttar Pradesh"),
("INYPVJRQYC","IN","Fatehpur","Rajasthan"),
("INJ3IFANVQ","IN","Fatwah","Bihar"),
("INXTW74XLS","IN","Fazilka","Punjab"),
("INDVNG3N41","IN","Firozpur","Punjab"),
("INCZL4QJH9","IN","Firozpur Cantt.","Punjab"),
("INMZPXNKOL","IN","Forbesganj","Bihar"),
("INELSJIEBW","IN","Gadag","Karnataka"),
("INAYCDMGFZ","IN","Gadwal","Andhra Pradesh"),
("ING037JKH5","IN","Ganaur","Haryana"),
("INK637RRS5","IN","Gandhinagar","Gujarat"),
("INCLPVZ0R9","IN","Gangtok","Sikkim"),
("INZ4NLK2K1","IN","Garhwa","Jharkhand"),
("IN3N8M8PSS","IN","Gauripur","Assam"),
("INWW0NNTTZ","IN","Gaya","Bihar"),
("INEIUEJMNI","IN","Gharaunda","Haryana"),
("INQB3BEOCH","IN","Ghatshila","Jharkhand"),
("INCL4KBXD7","IN","Giddarbaha","Punjab"),
("INTDVH7OHL","IN","Giridih","Jharkhand"),
("IN7CZQYN8O","IN","Goalpara","Assam"),
("INYC0D0DUC","IN","Gobindgarh","Punjab"),
("INYZXAXAHQ","IN","Gobranawapara","Chhattisgarh"),
("INOC7V1OG8","IN","Godda","Jharkhand"),
("IN0GYZ47O2","IN","Godhra","Gujarat"),
("INKOGK1AX0","IN","Gogri Jamalpur","Bihar"),
("INAUA74SYT","IN","Gohana","Haryana"),
("IN55P6U5FV","IN","Golaghat","Assam"),
("INMEUQMIT6","IN","Gomoh","Jharkhand"),
("IN79Q9KN9U","IN","Gooty","Andhra Pradesh"),
("INIK2NC0GI","IN","Gopalganj","Bihar"),
("IN65O0B4VY","IN","Greater Noida","Uttar Pradesh"),
("INIQO59IBG","IN","Gudalur","Tamil Nadu"),
("INR2PCQZ68","IN","Gudivada","Andhra Pradesh"),
("INJ8VW9CEF","IN","Gudur","Andhra Pradesh"),
("INI3GU8CSR","IN","Gulbarga","Karnataka"),
("IN2HWBZ7SR","IN","Gumia","Jharkhand"),
("IN9H3ZH980","IN","Gumla","Jharkhand"),
("INI3XSGC7Y","IN","Gundlupet","Karnataka"),
("INGNSOZLF2","IN","Guntakal","Andhra Pradesh"),
("IN2BE1J6ST","IN","Guntur","Andhra Pradesh"),
("INOWT5516O","IN","Gunupur","Orissa"),
("IN53GLFOKW","IN","Gurdaspur","Punjab"),
("INCDKBY0E0","IN","Gurgaon","Haryana"),
("INCS2VYVPM","IN","Guruvayoor","Kerala"),
("INRIRXKXMP","IN","Guwahati","Assam"),
("IN13BHRWD4","IN","Gwalior","Madhya Pradesh"),
("IN9YF8YU9A","IN","Haflong","Assam"),
("INMB6L7V7Z","IN","Haibat(Yamuna Nagar)","Haryana"),
("INEZWYXJOY","IN","Hailakandi","Assam"),
("INM0GEWTI6","IN","Hajipur","Bihar"),
("INRYEQSN0E","IN","Haldia","West Bengal"),
("INZ707386H","IN","Haldwani","Uttarakhand"),
("IN73G5M548","IN","Hamirpur","Himachal Pradesh"),
("IN5KM2E596","IN","Hamirpur","Uttar Pradesh"),
("IN3NWVBXAB","IN","Hansi","Haryana"),
("IN4AJ8IPPQ","IN","Hanuman Junction","Andhra Pradesh"),
("INT6VFBZOH","IN","Hardoi","Uttar Pradesh"),
("INJBKYGT4J","IN","Haridwar","Uttarakhand"),
("INH0FSXP42","IN","Hassan","Karnataka"),
("IN0NAJD096","IN","Hazaribag","Jharkhand"),
("IN75MJ4A0O","IN","Hilsa","Bihar"),
("INLKM2EQLV","IN","Himatnagar","Gujarat"),
("INR0OPQSRQ","IN","Hindupur","Andhra Pradesh"),
("ING2AT2J09","IN","Hinjilicut","Orissa"),
("INOMSTXTIJ","IN","Hisar","Haryana"),
("INE5LSW6NN","IN","Hisua","Bihar"),
("IN7CDY44PL","IN","Hodal","Haryana"),
("IN6ZF9JFJ7","IN","Hojai","Assam"),
("IN2B105KJJ","IN","Hoshiarpur","Punjab"),
("INP4CMB0AJ","IN","Hospet","Karnataka"),
("INCNHHS62Z","IN","Howrah","West Bengal"),
("IN6I8PYRX0","IN","Hubli","Karnataka"),
("IN3Z19JKT9","IN","Hussainabad","Jharkhand"),
("INO5VZ66II","IN","Hyderabad","Andhra Pradesh"),
("INT00M62LD","IN","Ichalkaranji","Maharashtra"),
("INLT2JLZKP","IN","Ichchapuram","Andhra Pradesh"),
("INYLZI5SRT","IN","Idar","Gujarat"),
("INXNT3TCMN","IN","Imphal","Manipur"),
("INCM9JPUWA","IN","Indore","Madhya Pradesh"),
("INOYUAYE0W","IN","Indranagar","Tripura"),
("IN0ZF5S6ZQ","IN","Irinjalakuda","Kerala"),
("INUTTN5GBH","IN","Islampur","Bihar"),
("IN3L1SGX34","IN","Islampur","West Bengal"),
("INWXFUCGRC","IN","Itanagar","Arunachal Pradesh"),
("INF6H8DHY7","IN","Itarsi","Madhya Pradesh"),
("INASVF86XB","IN","Jabalpur","Madhya Pradesh"),
("INSY48V7DR","IN","Jagatsinghapur","Orissa"),
("IN5SMH8DTO","IN","Jagdalpur","Chhattisgarh"),
("INJBWXSU43","IN","Jagdispur","Bihar"),
("INMZIV6G7Y","IN","Jaggaiahpet","Andhra Pradesh"),
("INEB6AJJ2O","IN","Jagraon","Punjab"),
("INCO6L209M","IN","Jagtial","Andhra Pradesh"),
("INC6J51N8O","IN","Jaipur","Rajasthan"),
("INNRKT7RRM","IN","Jaisalmer","Rajasthan"),
("IN2YXMHZBT","IN","Jaitu","Punjab"),
("INOHEQHODU","IN","Jajapur","Orissa"),
("INVWZXK7L7","IN","Jajmau","Uttar Pradesh"),
("INZ506XST0","IN","Jalalabad","Punjab"),
("INQQM8PX2E","IN","Jalandhar","Punjab"),
("INFH4W5IR1","IN","Jalandhar Cantt.","Punjab"),
("INEQYZYK6X","IN","Jaleswar","Orissa"),
("INQ73N0WNQ","IN","Jalna","Maharashtra"),
("INNAZC71QM","IN","Jamalpur","Bihar"),
("INIVJNDAPS","IN","Jammalamadugu","Andhra Pradesh"),
("IN1NSZ7ZWY","IN","Jammu","Jammu & Kashmir"),
("IN70L7X9YK","IN","Jamnagar","Gujarat"),
("INKXXRYOEG","IN","Jamshedpur","Jharkhand"),
("INJY4X9UQA","IN","Jamtara","Jharkhand"),
("INHJAPI6OP","IN","Jamui","Bihar"),
("IN69X4JVO3","IN","Jandiala","Punjab"),
("INTLVR9A8T","IN","Jangaon","Andhra Pradesh"),
("IN8DRI7ITP","IN","Janjgir","Chhattisgarh"),
("IN13FJ939G","IN","Jashpurnagar","Chhattisgarh"),
("IND6KW290V","IN","Jaspur","Uttarakhand"),
("INVVN55WYE","IN","Jatani","Orissa"),
("IN9QWH8P79","IN","Jaunpur","Uttar Pradesh"),
("INTMS2Q2J3","IN","Jehanabad","Bihar"),
("IN840AE059","IN","Jeypur","Orissa"),
("INVTE1PDGZ","IN","Jhajha","Bihar"),
("IN3CHB2OLV","IN","Jhajjar","Haryana"),
("INBDY1FI4O","IN","Jhanjharpur","Bihar"),
("INM5Y05491","IN","Jhansi","Uttar Pradesh"),
("INYO3N1JM5","IN","Jhargram","West Bengal"),
("INV3HYS2U3","IN","Jharsuguda","Orissa"),
("INFS5VA9KX","IN","Jhumri Tilaiya","Jharkhand"),
("INFJXKN7LM","IN","Jind","Haryana"),
("INWP9Y8W34","IN","Joda","Orissa"),
("IN0K2TMXW2","IN","Jodhpur","Rajasthan"),
("INP1Y0BIXQ","IN","Jogabani","Bihar"),
("IN1VBP3XBZ","IN","Jogendranagar","Tripura"),
("INMLXUH1YI","IN","Jorhat","Assam"),
("INL1B8Y8AO","IN","Jowai","Meghalaya"),
("IN98OLQMCS","IN","Junagadh","Gujarat"),
("INHNHLKTK7","IN","Kadapa","Andhra Pradesh"),
("INEI1WJ0E5","IN","Kadi","Gujarat"),
("IN2QD1YNQ8","IN","Kadiri","Andhra Pradesh"),
("INWEUM16FJ","IN","Kadirur","Kerala"),
("INUW4EQPM4","IN","Kagaznagar","Andhra Pradesh"),
("IN7O0QOFVR","IN","Kailasahar","Tripura"),
("IN69T4WJDS","IN","Kaithal","Haryana"),
("INY7FZEUI8","IN","Kakching","Manipur"),
("INRNNHC9MJ","IN","Kakinada","Andhra Pradesh"),
("INXNAM36D9","IN","Kalan Wali","Haryana"),
("INF6ECPR5O","IN","Kalavad","Gujarat"),
("INZKNDF6M7","IN","Kalka","Haryana"),
("INT9P5JBPG","IN","Kalliasseri","Kerala"),
("INZ0327HCN","IN","Kalol","Gujarat"),
("INNQ0DI51I","IN","Kalpetta","Kerala"),
("INQPV5VIDP","IN","Kalpi","Uttar Pradesh"),
("INR2VAELRD","IN","Kalyan","Maharashtra"),
("INMUGTBTHZ","IN","Kalyandurg","Andhra Pradesh"),
("INJHD2NFKD","IN","Kamareddy","Andhra Pradesh"),
("IN4GJ0YWPQ","IN","Kanchipuram","Tamil Nadu"),
("INYK1D6SRS","IN","Kandukur","Andhra Pradesh"),
("INN8LZ13YK","IN","Kanhangad","Kerala"),
("INLCN8R7MW","IN","Kanjikkuzhi","Kerala"),
("INO5XM2ND0","IN","Kanker","Chhattisgarh"),
("IN8EEE756U","IN","Kannur","Kerala"),
("INDSTEVSZH","IN","Kanpur","Uttar Pradesh"),
("IN5MQXUCUI","IN","Kantabanji","Orissa"),
("INIR5KEILM","IN","Kanti","Bihar"),
("INXZ0457ZI","IN","Kapadvanj","Gujarat"),
("INZSXULWBQ","IN","Kapurthala","Punjab"),
("INJ2OEEIWX","IN","Karaikal","Pondicherry"),
("INA2HOL3BI","IN","Karaikudi","Tamil Nadu"),
("IN2CN7JMQI","IN","Karanjia","Orissa"),
("INFND1KPS3","IN","Karimganj","Assam"),
("INRGH6YE38","IN","Karimnagar","Andhra Pradesh"),
("INHKX3N9LQ","IN","Karjan","Gujarat"),
("INL9Y5VOOA","IN","Karkala","Karnataka"),
("INC1CWR40I","IN","Karnal","Haryana"),
("INKHOJWRRE","IN","Karoran","Punjab"),
("INCPH0Y3QK","IN","Kartarpur","Punjab"),
("INCPP8DEJP","IN","Karungal","Tamil Nadu"),
("INFVM6ZMPJ","IN","Karur","Tamil Nadu"),
("IN4E216UFJ","IN","Karwar","Karnataka"),
("INKWJJ0A3C","IN","Kasaragod","Kerala"),
("INZTKD733N","IN","Kashipur","Uttarakhand"),
("INZQUYCJIG","IN","Kathua","Jammu & Kashmir"),
("INYLI4GXN0","IN","Katihar","Bihar"),
("INU7JUIN6H","IN","Katni","Madhya Pradesh"),
("INHRVOVZBU","IN","Kavali","Andhra Pradesh"),
("INP6S1QAIO","IN","Kavaratti","Lakshadweep"),
("INV0SBYGCS","IN","Kawardha","Chhattisgarh"),
("INOWM6JTO0","IN","Kayamkulam","Kerala"),
("INLJPGJ1A8","IN","Kendrapara","Orissa"),
("IN73AXETLA","IN","Kendujhar","Orissa"),
("INUEMSVYKJ","IN","Keshod","Gujarat"),
("INV7QF1EGM","IN","Khagaria","Bihar"),
("INY52H6DPE","IN","Khambhalia","Gujarat"),
("INH0CVTY5N","IN","Khambhat","Gujarat"),
("INCRG8Q0SL","IN","Khammam","Andhra Pradesh"),
("IN8I0AWGWU","IN","Khanna","Punjab"),
("INMZCTD27U","IN","Kharagpur","Bihar"),
("IN2KQVIVJU","IN","Kharagpur","West Bengal"),
("INNZ3E0V09","IN","Kharar","Punjab"),
("INE1JBHG64","IN","Kheda","Gujarat"),
("INFIXSK5NN","IN","Khedbrahma","Gujarat"),
("INPDJ7922X","IN","Kheralu","Gujarat"),
("IN26C22CBG","IN","Khordha","Orissa"),
("INDVSVBY0Q","IN","Khowai","Tripura"),
("INHXJ137PT","IN","Khunti","Jharkhand"),
("INL80UA3SC","IN","kichha","Uttarakhand"),
("IN95FBHRSV","IN","Kishanganj","Bihar"),
("INMKRXIROZ","IN","Kochi","Kerala"),
("INP81TFQM0","IN","Kodinar","Gujarat"),
("INYNV9QOM0","IN","Kodungallur","Kerala"),
("INT1BBS36E","IN","Kohima","Nagaland"),
("INNYC6Q05G","IN","Kokrajhar","Assam"),
("IN879OYWPW","IN","Kolar","Karnataka"),
("INJK6A9SA2","IN","Kolhapur","Maharashtra"),
("INTLEMPK0D","IN","Kolkata","West Bengal"),
("INJDJ9DPQM","IN","Kollam","Kerala"),
("INWZBVV0RF","IN","Kollankodu","Tamil Nadu"),
("INLXPUQZXJ","IN","Kondagaon","Chhattisgarh"),
("INKB5AW6NF","IN","Koothuparamba","Kerala"),
("INJ6PXWFKS","IN","Koraput","Orissa"),
("INFVNBVFQG","IN","Koratla","Andhra Pradesh"),
("INDFB3E8NZ","IN","Korba","Chhattisgarh"),
("INKS9GZWWJ","IN","Kot Kapura","Punjab"),
("IN3MGZ20SH","IN","Kota","Uttar Pradesh"),
("INWGSRVJ89","IN","Kota","Rajasthan"),
("INYJDCS0BD","IN","Kota","Karnataka"),
("INTLUSHQCK","IN","Kotdwara","Uttarakhand"),
("INDSKFTCXQ","IN","Kothagudem","Andhra Pradesh"),
("INSQHO9QX8","IN","Kothamangalam","Kerala"),
("INABK3BWG4","IN","Kothapeta","Andhra Pradesh"),
("INHAXZ1AKE","IN","Kotma","Madhya Pradesh"),
("IN24UWGSN8","IN","Kottayam","Kerala"),
("INJ4XSVV15","IN","Kovvur","Andhra Pradesh"),
("IN6M8HIOM0","IN","Kozhikode","Kerala"),
("INYKZZUJEX","IN","Kunnamkulam","Kerala"),
("INN8U41HDK","IN","Kurali","Punjab"),
("INMADH5ENB","IN","Kurnool","Andhra Pradesh"),
("IN0VTIKFJJ","IN","Kyathampalle","Andhra Pradesh"),
("IN0IJU2YSQ","IN","Lachhmangarh","Rajasthan"),
("IN7MV848SQ","IN","Ladnu","Rajasthan"),
("INI58NJVZJ","IN","Ladwa","Haryana"),
("INRS2C8MV9","IN","Lahar","Madhya Pradesh"),
("IN5F37DWYK","IN","Laharpur","Uttar Pradesh"),
("INITSM1LDK","IN","Lakheri","Rajasthan"),
("INQL8AG7U8","IN","Lakhimpur","Uttar Pradesh"),
("IN0XK9JGIO","IN","Lakhisarai","Bihar"),
("INVMW9IVU1","IN","Lakshmeshwar","Karnataka"),
("INONOQ81AZ","IN","Lal Gopalganj Nindaura","Uttar Pradesh"),
("INMJ93Q4CR","IN","Lalganj","Bihar"),
("IN1W1LDJA9","IN","Lalganj","Uttar Pradesh"),
("IN66IO1CQQ","IN","Lalgudi","Tamil Nadu"),
("IN0EH8FS72","IN","Lalitpur","Uttar Pradesh"),
("INBH52LITN","IN","Lalsot","Rajasthan"),
("INEU8REI1K","IN","Lanka","Assam"),
("INPJ9RWZIW","IN","Lar","Uttar Pradesh"),
("INE05TSCW3","IN","Lathi","Gujarat"),
("INU25FKZ3Z","IN","Latur","Maharashtra"),
("INUCQ8VSTK","IN","Leh","Jammu & Kashmir"),
("INB2C82V4G","IN","Lilong","Manipur"),
("INV9ANM6RG","IN","Limbdi","Gujarat"),
("IN8XWTWZSQ","IN","Lingsugur","Karnataka"),
("INCJZ7BSSM","IN","Loha","Maharashtra"),
("INV4VXZ0EV","IN","Lohardaga","Jharkhand"),
("INAOIWV9D4","IN","Lonar","Maharashtra"),
("IN6AX3APUM","IN","Lonavla","Maharashtra"),
("IN8TTKML6H","IN","Longowal","Punjab"),
("INQ2FQ2TLC","IN","Loni","Uttar Pradesh"),
("INI49DDNIK","IN","Losal","Rajasthan"),
("INXFO75ITE","IN","Lucknow","Uttar Pradesh"),
("INCNYY95GZ","IN","Ludhiana","Punjab"),
("IN7WQAPBM8","IN","Lumding","Assam"),
("INGWMTJ4EG","IN","Lunawada","Gujarat"),
("INK2OQLI5Y","IN","Lundi","Madhya Pradesh"),
("IN63WF9DFH","IN","Lunglei","Mizoram"),
("IN96RZHE8X","IN","Macherla","Andhra Pradesh"),
("INBURUZ6BJ","IN","Machilipatnam","Andhra Pradesh"),
("IN90AUIFSO","IN","Madanapalle","Andhra Pradesh"),
("INIP4S3J9D","IN","Maddur","Karnataka"),
("INQ1D7GL5R","IN","Madgaon","Goa"),
("INFXME4XYD","IN","Madhepura","Bihar"),
("INX88GN156","IN","Madhubani","Bihar"),
("INR9ZVT98J","IN","Madhugiri","Karnataka"),
("INALRR6XIM","IN","Madhupur","Jharkhand"),
("INV41Z2ZD0","IN","Madikeri","Karnataka"),
("IN8MGWNL3F","IN","Madurai","Tamil Nadu"),
("INU2AOBJ7M","IN","Magadi","Karnataka"),
("IN5ZDCWWYR","IN","Mahad","Maharashtra"),
("IN00R3Z538","IN","Mahalingpur","Karnataka"),
("INRJ5F58U0","IN","Maharajganj","Bihar"),
("INB5OMOW9T","IN","Maharajpur","Madhya Pradesh"),
("INVM5SJ4KK","IN","Mahasamund","Chhattisgarh"),
("IN4CN4HQC8","IN","Mahbubnagar","Andhra Pradesh"),
("INAINGQIG1","IN","Mahe","Pondicherry"),
("INN5OC2Y5Y","IN","Mahendragarh","Haryana"),
("INLBQ4FAOK","IN","Mahendragarh","Chhattisgarh"),
("INNBO421CD","IN","Mahesana","Gujarat"),
("INJ0TAIAC6","IN","Mahidpur","Madhya Pradesh"),
("ING1IIZOGK","IN","Mahnar Bazar","Bihar"),
("INZ6PFHD04","IN","Mahuli","Maharashtra"),
("INPO9SQL59","IN","Mahuva","Gujarat"),
("INMZJ49VBP","IN","Maihar","Madhya Pradesh"),
("INXT8WHOHH","IN","Mainaguri","West Bengal"),
("INV6XDKXI9","IN","Makhdumpur","Bihar"),
("INMR1CC7MZ","IN","Makrana","Rajasthan"),
("IN653G1E6Y","IN","Mal","West Bengal"),
("IN8EVQ2C8X","IN","Malajkhand","Madhya Pradesh"),
("INJ6A34TCQ","IN","Malappuram","Kerala"),
("INKE3XLPWS","IN","Malavalli","Karnataka"),
("INVZ8XEEWN","IN","Malegaon","Maharashtra"),
("INSRDV4LTN","IN","Malerkotla","Punjab"),
("INR4QVX3MH","IN","Malkangiri","Orissa"),
("INHPE3FAVA","IN","Malkapur","Maharashtra"),
("INA37PI3CB","IN","Malout","Punjab"),
("INVQ6ZBZM3","IN","Malpura","Rajasthan"),
("IN4DZ1GMIX","IN","Malur","Karnataka"),
("INCX1R8W1J","IN","Manasa","Madhya Pradesh"),
("IN098JCLU8","IN","Manavadar","Gujarat"),
("INB17N1UQ5","IN","Manawar","Madhya Pradesh"),
("IN7Q6NCPLO","IN","Manchar","Maharashtra"),
("INNNFVJHFK","IN","Mancherial","Andhra Pradesh"),
("INQO339YBL","IN","Mandalgarh","Rajasthan"),
("INZJ81DZ6L","IN","Mandamarri","Andhra Pradesh"),
("INPD923VRQ","IN","Mandapeta","Andhra Pradesh"),
("INI6M2O1ME","IN","Mandawa","Rajasthan"),
("INPQIZPULP","IN","Mandi","Himachal Pradesh"),
("INDTQRTXCJ","IN","Mandi Dabwali","Haryana"),
("INALLDGC4Y","IN","Mandideep","Madhya Pradesh"),
("INJQ08SNNI","IN","Mandla","Madhya Pradesh"),
("IND5I3Z3SD","IN","Mandsaur","Madhya Pradesh"),
("INXI4QFG9P","IN","Mandvi","Gujarat"),
("IN2V3I88HS","IN","Mandya","Karnataka"),
("INYI0R5NAJ","IN","Maner","Bihar"),
("INTSMTVE6S","IN","Mangaldoi","Assam"),
("INXAICRS2T","IN","Mangalore","Karnataka"),
("INN6CWEUOD","IN","Mangalvedhe","Maharashtra"),
("INCO4ICE15","IN","Manglaur","Uttarakhand"),
("IN6OY225U0","IN","Mangrol","Rajasthan"),
("INGDC76E1T","IN","Mangrol","Gujarat"),
("INKEPZ8ECK","IN","Mangrulpir","Maharashtra"),
("IN2G2FV4K2","IN","Manihari","Bihar"),
("INTJ4WPZW5","IN","Manjlegaon","Maharashtra"),
("IND8DJNED8","IN","Mankachar","Assam"),
("INS371HJMK","IN","Manmad","Maharashtra"),
("IN0PZWTKYM","IN","Mansa","Punjab"),
("IN43JT3FYH","IN","Mansa","Gujarat"),
("INNB0BQEJJ","IN","Manuguru","Andhra Pradesh"),
("INHRLZA7JB","IN","Manvi","Karnataka"),
("INWI7Q36D7","IN","Manwath","Maharashtra"),
("INAW0EBZVZ","IN","Mapusa","Goa"),
("INBWA2ATMR","IN","Margao","Goa"),
("INK7QVEA6A","IN","Margherita","Assam"),
("INTE1WLE3V","IN","Marhaura","Bihar"),
("INA49M34LF","IN","Mariani","Assam"),
("IN1VHBP33A","IN","Marigaon","Assam"),
("INAU6P4C0X","IN","Markapur","Andhra Pradesh"),
("INR1UCFY8Q","IN","Marmagao","Goa"),
("IN2HC6MXLN","IN","Masaurhi","Bihar"),
("INT3ZI72SI","IN","Mathabhanga","West Bengal"),
("INWZ71B7Z3","IN","Mathura","Uttar Pradesh"),
("IN8TGOROET","IN","Mattannur","Kerala"),
("IN6Q0TOMHH","IN","Mauganj","Madhya Pradesh"),
("INPGZXJSFF","IN","Maur","Punjab"),
("INRMH3UG72","IN","Mavelikkara","Kerala"),
("IN9NQ0B4UH","IN","Mavoor","Kerala"),
("INVUBJHS07","IN","Mayang Imphal","Manipur"),
("IN804RTJ7K","IN","Medak","Andhra Pradesh"),
("IN6OO04V3D","IN","Medinipur","West Bengal"),
("INITEUY9CU","IN","Meerut","Uttar Pradesh"),
("IN3NDLGESO","IN","Mehkar","Maharashtra"),
("INEWG7GNSM","IN","Mehmedabad","Gujarat"),
("INCGMHCPUV","IN","Memari","West Bengal"),
("INJ9QII2CM","IN","Merta City","Rajasthan"),
("INQQ764ZVJ","IN","Mhaswad","Maharashtra"),
("INWBRCZJYC","IN","Mhow Cantonment","Madhya Pradesh"),
("IN0LTDBO8U","IN","Mhowgaon","Madhya Pradesh"),
("INXYDG1P2S","IN","Mihijam","Jharkhand"),
("INF9YK9T45","IN","Miraj","Maharashtra"),
("IN5VH5FGHF","IN","Mirganj","Bihar"),
("IN1ATCY27W","IN","Miryalaguda","Andhra Pradesh"),
("IN1KC2AEUP","IN","Modasa","Gujarat"),
("INOTAYNE3S","IN","Modinagar","Uttar Pradesh"),
("IN9LXO1F43","IN","Moga","Punjab"),
("INPYFN0NJ1","IN","Mogalthur","Andhra Pradesh"),
("IN7W3HAY7Z","IN","Mohali","Punjab"),
("INSIXFX077","IN","Mokameh","Bihar"),
("INM5VNK0RA","IN","Mokokchung","Nagaland"),
("INZ7YZUI02","IN","Monoharpur","West Bengal"),
("INE4KO3SOV","IN","Morena","Madhya Pradesh"),
("INALA7MIE8","IN","Morinda","Punjab"),
("INNAW8BNIA","IN","Morshi","Maharashtra"),
("INUGAPYARC","IN","Morvi","Gujarat"),
("INEB1I3PDE","IN","Motihari","Bihar"),
("INBNMX516T","IN","Motipur","Bihar"),
("INC22OQLZL","IN","Mount Abu","Rajasthan"),
("IN19A0J1DY","IN","Mudalgi","Karnataka"),
("INDFGH5TWG","IN","Mudbidri","Karnataka"),
("INHIEMKKGW","IN","Muddebihal","Karnataka"),
("INNIKD4JY5","IN","Mudhol","Karnataka"),
("INS96CAKAO","IN","Mukerian","Punjab"),
("INZR55K1L2","IN","Mukhed","Maharashtra"),
("INJ0P4K507","IN","Muktsar","Punjab"),
("INOLLS5KYY","IN","Mul","Maharashtra"),
("INT5B4QLSQ","IN","Mulbagal","Karnataka"),
("INDYVYZH0J","IN","Multai","Madhya Pradesh"),
("INHPN1VO9K","IN","Mumbai","Maharashtra"),
("INAVCFGBEA","IN","Mundargi","Karnataka"),
("INHPE7B7XO","IN","Mungeli","Chhattisgarh"),
("IN5SM59NOR","IN","Munger","Bihar"),
("INCCS702RA","IN","Muradnagar","Uttar Pradesh"),
("INY4QEG5OX","IN","Murliganj","Bihar"),
("INU356B2UH","IN","Murshidabad","West Bengal"),
("INVHM54AWH","IN","Murtijapur","Maharashtra"),
("INMPPNRHYQ","IN","Murwara","Madhya Pradesh"),
("INMO42TT0O","IN","Musabani","Jharkhand"),
("INW5U88PP3","IN","Mussoorie","Uttarakhand"),
("IN6B8BM5S9","IN","Muvattupuzha","Kerala"),
("INUIXMZVCL","IN","Muzaffarnagar","Uttar Pradesh"),
("INKGNEAO27","IN","Muzaffarpur","Bihar"),
("INUXF2M45T","IN","Mysore","Karnataka"),
("INGE43JXDE","IN","Nabadwip","West Bengal"),
("INFA0F5C0P","IN","Nabarangapur","Orissa"),
("INTO33D6A7","IN","Nabha","Punjab"),
("IN3Q9QVFJB","IN","Nadbai","Rajasthan"),
("INUOFELSS1","IN","Nadiad","Gujarat"),
("IN2TH85HXZ","IN","Nagaon","Assam"),
("IN613J7EQB","IN","Nagapattinam","Tamil Nadu"),
("IN4Z1ZFKB9","IN","Nagar","Rajasthan"),
("IN8QNUJGWM","IN","Nagari","Andhra Pradesh"),
("IN9DUFVRE1","IN","Nagarkurnool","Andhra Pradesh"),
("INTIK0WBB1","IN","Nagaur","Rajasthan"),
("INBD0QXC06","IN","Nagda","Madhya Pradesh"),
("IN3O1M4X8E","IN","Nagercoil","Tamil Nadu"),
("INB2T6U88N","IN","Nagina","Uttar Pradesh"),
("INQTON40OG","IN","Nagla","Uttarakhand"),
("INDP7B17H4","IN","Nagpur","Maharashtra"),
("INWJR1G0FS","IN","Nahan","Himachal Pradesh"),
("IN39ZYH7L8","IN","Naharlagun","Arunachal Pradesh"),
("IN0AV5BJMP","IN","Naihati","West Bengal"),
("IN8T0A0IFW","IN","Naila Janjgir","Chhattisgarh"),
("IN16YI7DAA","IN","Nainital","Uttarakhand"),
("INM984HUCI","IN","Nainpur","Madhya Pradesh"),
("IN57NGR950","IN","Najibabad","Uttar Pradesh"),
("IN26A3PP0R","IN","Nakodar","Punjab"),
("INWY93CKDY","IN","Nakur","Uttar Pradesh"),
("INTM3BGFTL","IN","Nalasopara","Maharashtra"),
("INNG2FQ8FT","IN","Nalbari","Assam"),
("INFQX4GYVC","IN","Namagiripettai","Tamil Nadu"),
("INX5G9PU8J","IN","Namakkal","Tamil Nadu"),
("INGBUXQNJE","IN","Nanded-Waghala","Maharashtra"),
("IN4MTVU9O9","IN","Nandgaon","Maharashtra"),
("INZMEFKASH","IN","Nandivaram-Guduvancheri","Tamil Nadu"),
("INF9R43ZNK","IN","Nandura","Maharashtra"),
("INAIH161FA","IN","Nandurbar","Maharashtra"),
("INN85IHUSH","IN","Nandyal","Andhra Pradesh"),
("ING7X1HPJW","IN","Nangal","Punjab"),
("INYA129PMJ","IN","Nanjangud","Karnataka"),
("IN74LD60OT","IN","Nanjikottai","Tamil Nadu"),
("IN9TCQO485","IN","Nanpara","Uttar Pradesh"),
("INB56SVQPU","IN","Narasapur","Andhra Pradesh"),
("IN0QW9FJTN","IN","Narasaraopet","Andhra Pradesh"),
("INOF0UFONO","IN","Naraura","Uttar Pradesh"),
("INI0F64OCG","IN","Narayanpet","Andhra Pradesh"),
("INTJ9O9YJ9","IN","Nargund","Rajasthan"),
("INPGJ4ZDRN","IN","Narkatiaganj","Bihar"),
("INSSH8G5XZ","IN","Narkhed","Maharashtra"),
("IN6D5A1IRU","IN","Narnaul","Haryana"),
("IN10JAZ2KO","IN","Narsinghgarh","Madhya Pradesh"),
("INJ3SIHK6A","IN","Narsipatnam","Andhra Pradesh"),
("INCOITUFS0","IN","Narwana","Haryana"),
("INSYBUG2OH","IN","Nashik","Maharashtra"),
("IN38S2BCRU","IN","Nasirabad","Rajasthan"),
("INGKDX4J8H","IN","Natham","Tamil Nadu"),
("IN7QA1632Z","IN","Nathdwara","Rajasthan"),
("IN1DTIFI0I","IN","Naugachhia","Bihar"),
("INQSL24CWL","IN","Naugawan Sadat","Uttar Pradesh"),
("INX9J1SRJ0","IN","Nautanwa","Uttar Pradesh"),
("INHU2OX4NZ","IN","Navalgund","Rajasthan"),
("INHHHXZHGP","IN","Navi Mumbai","Maharashtra"),
("INA2REEO0C","IN","Navsari","Gujarat"),
("INXJEQAXRS","IN","Nawabganj","Uttar Pradesh"),
("INRTGPY4OF","IN","Nawada","Bihar"),
("INL6CKOTAY","IN","Nawalgarh","Rajasthan"),
("INV2DAQDMN","IN","Nawanshahr","Punjab"),
("INW0E6X5YP","IN","Nawapur","Maharashtra"),
("INZFEXJ3D5","IN","Nedumangad","Kerala"),
("IN9PPYJZWE","IN","Neem-Ka-Thana","Rajasthan"),
("IN19OSNAGJ","IN","Neemuch","Madhya Pradesh"),
("INBUQ90PYZ","IN","Nehtaur","Uttar Pradesh"),
("IN5DXOHATR","IN","Nelamangala","Rajasthan"),
("IN0JPJJMXL","IN","Nellikuppam","Tamil Nadu"),
("INVMDJXT28","IN","Nellore","Andhra Pradesh"),
("INOTIPIHPN","IN","Nepanagar","Madhya Pradesh"),
("INUMCCW63X","IN","Neyveli","Tamil Nadu"),
("INQTG9FEUB","IN","Neyyattinkara","Kerala"),
("IN18UY1X7Q","IN","Nidadavole","Andhra Pradesh"),
("INQPF964X1","IN","Nilanga","Maharashtra"),
("INR9DNGHL6","IN","Nimbahera","Rajasthan"),
("INA2FPHA1I","IN","Nipani","Rajasthan"),
("INIVHKSOAJ","IN","Nirmal","Andhra Pradesh"),
("INEQSKUPML","IN","Niwai","Rajasthan"),
("INZ09FHVLS","IN","Niwari","Madhya Pradesh"),
("INX1HEBIWT","IN","Nizamabad","Andhra Pradesh"),
("INEDE62OPG","IN","Nohar","Rajasthan"),
("INFI197NV7","IN","NOIDA","Uttar Pradesh"),
("INO5M508XX","IN","Nokha","Bihar"),
("IN9FCKY8EC","IN","Nokha","Rajasthan"),
("INMSJOH95W","IN","Nongstoin","Meghalaya"),
("INS760V17J","IN","Noorpur","Uttar Pradesh"),
("IN7TO81M6A","IN","North Lakhimpur","Assam"),
("IN2IV1R9ED","IN","Nowgong","Madhya Pradesh"),
("IN1Y2I77F0","IN","Nowrozabad","Madhya Pradesh"),
("INFL0AN7TU","IN","Nuzvid","Andhra Pradesh"),
("IN1I3259D7","IN","O' Valley","Tamil Nadu"),
("INR98IINWK","IN","Obra","Uttar Pradesh"),
("INLY3T6ITL","IN","Oddanchatram","Tamil Nadu"),
("IN3TVQ1PL2","IN","Ongole","Andhra Pradesh"),
("IN7O5CXJKP","IN","Orai","Uttar Pradesh"),
("INST8BG4V1","IN","Osmanabad","Maharashtra"),
("IN2ZV9HOUL","IN","Ottappalam","Kerala"),
("INIQCJFYMN","IN","Ozar","Maharashtra"),
("INMRZKBKA3","IN","P.N.Patti","Tamil Nadu"),
("INDIFTMAVP","IN","Pachora","Maharashtra"),
("INAQZRFUDY","IN","Pachore","Madhya Pradesh"),
("INKPH0O4NB","IN","Pacode","Tamil Nadu"),
("INWNW776BL","IN","Padmanabhapuram","Tamil Nadu"),
("INPQFC1A2B","IN","Padra","Gujarat"),
("IN113HVGFG","IN","Padrauna","Uttar Pradesh"),
("IN6XGU145X","IN","Paithan","Maharashtra"),
("INS2408FLY","IN","Pakaur","Jharkhand"),
("IN60A7BCID","IN","Palacole","Andhra Pradesh"),
("INDLU82AO8","IN","Palai","Kerala"),
("IN7539A962","IN","Palakkad","Kerala"),
("INBB3KRPIX","IN","Palani","Tamil Nadu"),
("INPS415NFI","IN","Palanpur","Gujarat"),
("IN99RBKGKS","IN","Palasa Kasibugga","Andhra Pradesh"),
("INLO1WY8Z9","IN","Palghar","Maharashtra"),
("INJ2UBRC8H","IN","Pali","Madhya Pradesh"),
("IN5DJA1YTA","IN","Pali","Rajasthan"),
("IN8KMS06KM","IN","Palia Kalan","Uttar Pradesh"),
("INVLITUI2D","IN","Palitana","Gujarat"),
("INKXPC9XUF","IN","Palladam","Tamil Nadu"),
("INBDPDBINK","IN","Pallapatti","Tamil Nadu"),
("IN39C3GXQB","IN","Pallikonda","Tamil Nadu"),
("INJ94DR7RC","IN","Palwal","Haryana"),
("IN4GOEEJTP","IN","Palwancha","Andhra Pradesh"),
("INWJ282QS5","IN","Panagar","Madhya Pradesh"),
("IN059G20SL","IN","Panagudi","Tamil Nadu"),
("IN9WZ04QD8","IN","Panaji","Goa"),
("IN62MKLGAI","IN","Panchkula","Haryana"),
("INZDR23K74","IN","Panchla","West Bengal"),
("INPHLSHDEQ","IN","Pandharkaoda","Maharashtra"),
("INADRE45NA","IN","Pandharpur","Maharashtra"),
("IN7AUSQ5BQ","IN","Pandhurna","Madhya Pradesh"),
("INI2SMN0QC","IN","Pandua","West Bengal"),
("INHB5YPKPZ","IN","Panipat","Haryana"),
("INXHE1M1CT","IN","Panna","Madhya Pradesh"),
("INB7M2CYSU","IN","Panniyannur","Kerala"),
("IN0LGNL703","IN","Panruti","Tamil Nadu"),
("INI627QS7O","IN","Panvel","Maharashtra"),
("IN9LPWN2QY","IN","Pappinisseri","Kerala"),
("IN9D1LBUFC","IN","Paradip","Orissa"),
("INFW01304L","IN","Paramakudi","Tamil Nadu"),
("IN76TXY0L8","IN","Parangipettai","Tamil Nadu"),
("INMB49DV8M","IN","Parasi","Uttar Pradesh"),
("IN897J4MVJ","IN","Paravoor","Kerala"),
("INIVLMWP73","IN","Parbhani","Maharashtra"),
("INW10U2M3O","IN","Pardi","Gujarat"),
("INX7YA26WB","IN","Parlakhemundi","Orissa"),
("ING3UKQQ49","IN","Parli","Maharashtra"),
("INLPVIF3LB","IN","Parola","Maharashtra"),
("IN5M678AW6","IN","Partur","Maharashtra"),
("INIUGK1DWI","IN","Parvathipuram","Andhra Pradesh"),
("INHQ37G8H2","IN","Pasan","Madhya Pradesh"),
("INYDLEH6QM","IN","Paschim Punropara","West Bengal"),
("INTWT26Q8O","IN","Pasighat","Arunachal Pradesh"),
("INLP9N255J","IN","Patan","Gujarat"),
("INW9RDI8GG","IN","Pathanamthitta","Kerala"),
("INM1U38KP1","IN","Pathankot","Punjab"),
("INHJ4OACDV","IN","Pathardi","Maharashtra"),
("IN1NI4TONP","IN","Pathri","Maharashtra"),
("INYE3GMJX9","IN","Patiala","Punjab"),
("INKSCSD2UV","IN","Patna","Bihar"),
("INMYJWBXSD","IN","Patran","Punjab"),
("INKBHEZ44Y","IN","Patratu","Jharkhand"),
("INJ7F5QCFB","IN","Pattamundai","Orissa"),
("IN5R4IUYDG","IN","Patti","Punjab"),
("INXXD9U5NF","IN","Pattukkottai","Tamil Nadu"),
("ING4TG9XFS","IN","Patur","Maharashtra"),
("IN5UYW6D7C","IN","Pauni","Maharashtra"),
("IN5CUZA8G8","IN","Pauri","Uttarakhand"),
("IN6TH1Z4GG","IN","Pavagada","Karnataka"),
("IN9AWJ8BCD","IN","Payyannur","Kerala"),
("IN6B9CPHPU","IN","Pedana","Andhra Pradesh"),
("INTJU4SBCY","IN","Peddapuram","Andhra Pradesh"),
("IN5UZ4ZGK9","IN","Pehowa","Haryana"),
("INRHSZT4DZ","IN","Pen","Maharashtra"),
("INFMC441ZX","IN","Perambalur","Tamil Nadu"),
("INLU1D5ECA","IN","Peravurani","Tamil Nadu"),
("IN9CE8TZHK","IN","Peringathur","Kerala"),
("INHAKAEXAU","IN","Perinthalmanna","Kerala"),
("INKMZONZM9","IN","Periyakulam","Tamil Nadu"),
("INTNNY209B","IN","Periyasemur","Tamil Nadu"),
("INCNK6N1R4","IN","Pernampattu","Tamil Nadu"),
("INBBFQ9PLT","IN","Perumbavoor","Kerala"),
("INBLHZK39E","IN","Petlad","Gujarat"),
("INRWDUWM59","IN","Phagwara","Punjab"),
("INAPFYR722","IN","Phalodi","Rajasthan"),
("INIITR7EKJ","IN","Phaltan","Maharashtra"),
("IN02JL6SZX","IN","Phillaur","Punjab"),
("INPCRMZXW9","IN","Phulabani","Orissa"),
("INNC7EJAH1","IN","Phulera","Rajasthan"),
("INSAT0PDJQ","IN","Phulpur","Uttar Pradesh"),
("ING3BMVAKL","IN","Phusro","Jharkhand"),
("INNC7MA3WX","IN","Pihani","Uttar Pradesh"),
("INF4BYET07","IN","Pilani","Rajasthan"),
("IN4T8T7RJN","IN","Pilibanga","Rajasthan"),
("INVUAR5VCS","IN","Pilibhit","Uttar Pradesh"),
("IN7KFHNBE3","IN","Pilkhuwa","Uttar Pradesh"),
("INFQ2UJ22N","IN","Pindwara","Rajasthan"),
("INVAH321RX","IN","Pinjore","Haryana"),
("INW1O1W1U4","IN","Pipar City","Rajasthan"),
("INL9L9L0C1","IN","Pipariya","Madhya Pradesh"),
("INREVAHYYD","IN","Piro","Bihar"),
("IN8GGAH78D","IN","Pithampur","Madhya Pradesh"),
("IN9WF5X9AJ","IN","Pithapuram","Andhra Pradesh"),
("INJVS4W46N","IN","Pithoragarh","Uttarakhand"),
("INJ1Y1ZXE8","IN","Pollachi","Tamil Nadu"),
("INDVIV2Q8C","IN","Polur","Tamil Nadu"),
("INNOHLYR4H","IN","Pondicherry","Pondicherry"),
("INNWMK1S7L","IN","Pondur","Andhra pradesh"),
("INU6MU312H","IN","Ponnani","Kerala"),
("INWLCZCLBZ","IN","Ponneri","Tamil Nadu"),
("IN9TK7LOP8","IN","Ponnur","Andhra Pradesh"),
("INLBTM308Y","IN","Porbandar","Gujarat"),
("IN7USBVVSS","IN","Porsa","Madhya Pradesh"),
("ING4RSQ3RZ","IN","Port Blair","Andaman & Nicobar Islands"),
("INWC7H1WQM","IN","Powayan","Uttar Pradesh"),
("IN7J9BKH9S","IN","Prantij","Rajasthan"),
("INC238XV0D","IN","Pratapgarh","Tripura"),
("IN0S6QVXQS","IN","Pratapgarh","Rajasthan"),
("INAXABT1Y0","IN","Prithvipur","Madhya Pradesh"),
("INL8C5QMY2","IN","Proddatur","Andhra Pradesh"),
("INO1ALXBZY","IN","Pudukkottai","Tamil Nadu"),
("IN35PZ3FRD","IN","Pudupattinam","Tamil Nadu"),
("IND2P63N7O","IN","Pukhrayan","Uttar Pradesh"),
("INWKUM6SOU","IN","Pulgaon","Maharashtra"),
("INUZGSAFQE","IN","Puliyankudi","Tamil Nadu"),
("INKFDNV519","IN","Punalur","Kerala"),
("IN7QGBEO0A","IN","Punch","Jammu & Kashmir"),
("IN8VWFNL9I","IN","Pune","Maharashtra"),
("INKQAU508Q","IN","Punganur","Andhra Pradesh"),
("INGMECSFM0","IN","Punjaipugalur","Tamil Nadu"),
("IN62BKQCUZ","IN","Puranpur","Uttar Pradesh"),
("IN7REVCODW","IN","Puri","Orissa"),
("INENRJO0A5","IN","Purna","Maharashtra"),
("INMOIF34F9","IN","Purnia","Bihar"),
("IN6QUX2PWA","IN","Purquazi","Uttar Pradesh"),
("INGA5TYIQD","IN","Purulia","West Bengal"),
("IN6HWVI615","IN","Purwa","Uttar Pradesh"),
("INVJKZOZ9U","IN","Pusad","Maharashtra"),
("INQ3STSO39","IN","Puttur","Karnataka"),
("INZ82YRTBY","IN","Puttur","Andhra Pradesh"),
("INB8TTFVZA","IN","Qadian","Punjab"),
("INEJ93JIY9","IN","Quilandy","Kerala"),
("INMQ3FF6OF","IN","Rabkavi Banhatti","Karnataka"),
("INFRD6KP4V","IN","Radhanpur","Gujarat"),
("INYYPDTOO8","IN","Rae Bareli","Uttar Pradesh"),
("IN8YBRH913","IN","Rafiganj","Bihar"),
("IN04IFA7UP","IN","Raghogarh-Vijaypur","Madhya Pradesh"),
("INY8WJY1FW","IN","Raghunathpur","West Bengal"),
("IN04AUTZ21","IN","Rahatgarh","Madhya Pradesh"),
("INXETEOUIP","IN","Rahuri","Maharashtra"),
("INZ0497ZZ6","IN","Raichur","Karnataka"),
("IN7WP6X43X","IN","Raiganj","West Bengal"),
("IN9DR2CU4A","IN","Raigarh","Chhattisgarh"),
("IN9YPYT7NS","IN","Raikot","Punjab"),
("IN7S1FR1LZ","IN","Raipur","Chhattisgarh"),
("INXB5VF8TP","IN","Rairangpur","Orissa"),
("INMLSZGX9P","IN","Raisen","Madhya Pradesh"),
("INVYOO5CGD","IN","Raisinghnagar","Rajasthan"),
("IN4ITVKEVI","IN","Rajagangapur","Orissa"),
("INQ0D596VV","IN","Rajahmundry","Andhra Pradesh"),
("INSNU8K4YG","IN","Rajakhera","Rajasthan"),
("IN3M58YMM2","IN","Rajaldesar","Rajasthan"),
("IN4FYPUT7K","IN","Rajam","Andhra Pradesh"),
("INULQ3SLZK","IN","Rajampet","Andhra Pradesh"),
("IN9USUZQA2","IN","Rajapalayam","Tamil Nadu"),
("INDFBC1XF6","IN","Rajauri","Jammu & Kashmir"),
("INDDV773S2","IN","Rajgarh","Madhya Pradesh"),
("INPI5H451D","IN","Rajgarh (Alwar)","Rajasthan"),
("IN0U7ZLI1Z","IN","Rajgarh (Churu","Rajasthan"),
("INXCBZAQ5N","IN","Rajgir","Bihar"),
("IN41UC5NEU","IN","Rajkot","Gujarat"),
("IN5KBAPDOP","IN","Rajnandgaon","Chhattisgarh"),
("IN8WPTEQSC","IN","Rajpipla","Gujarat"),
("IN34BDUH0Z","IN","Rajpura","Punjab"),
("INIVBNIPIO","IN","Rajsamand","Rajasthan"),
("INATZZ7NPF","IN","Rajula","Gujarat"),
("INJF8Y51A9","IN","Rajura","Maharashtra"),
("IN5MM03NZL","IN","Ramachandrapuram","Andhra Pradesh"),
("INJA920RQA","IN","Ramagundam","Andhra Pradesh"),
("INLPASD08X","IN","Ramanagaram","Karnataka"),
("INFGVLI6UO","IN","Ramanathapuram","Tamil Nadu"),
("INSHOV4NHN","IN","Ramdurg","Karnataka"),
("INYRPZIGA4","IN","Rameshwaram","Tamil Nadu"),
("IN6LWJL4H1","IN","Ramganj Mandi","Rajasthan"),
("INLCM4IHSA","IN","Ramnagar","Bihar"),
("INYH625NQ4","IN","Ramnagar","Uttarakhand"),
("INEG3XXE14","IN","Ramngarh","Jharkhand"),
("INZYOL35MP","IN","Ramngarh","Rajasthan"),
("INH8U0QNBO","IN","Rampur","Uttar Pradesh"),
("IN4HR94HDJ","IN","Rampur Maniharan","Uttar Pradesh"),
("INYHGWVI0V","IN","Rampura Phul","Punjab"),
("INHOGKT2AB","IN","Rampurhat","West Bengal"),
("INB4B1RMQV","IN","Ramtek","Maharashtra"),
("IN3H58ZJRX","IN","Ranaghat","West Bengal"),
("IN18UXRUS8","IN","Ranavav","Gujarat"),
("INI8TCB3NN","IN","Ranchi","Jharkhand"),
("IN8YPZLFVO","IN","Rangia","Assam"),
("INW0XVKPTL","IN","Rania","Haryana"),
("INYOIPIAY1","IN","Ranibennur","Karnataka"),
("INJRDVU0I2","IN","Rapar","Gujarat"),
("INZ72KNX9J","IN","Rasipuram","Tamil Nadu"),
("INY6FIW93U","IN","Rasra","Uttar Pradesh"),
("INXMKFXIGG","IN","Ratangarh","Rajasthan"),
("IN9UB4VU7U","IN","Rath","Uttar Pradesh"),
("IN2AFP7P96","IN","Ratia","Haryana"),
("INVOOSXSMV","IN","Ratlam","Madhya Pradesh"),
("INF6BCPRSY","IN","Ratnagiri","Maharashtra"),
("INM43HZAC1","IN","Rau","Madhya Pradesh"),
("INKRRSG0ZC","IN","Raurkela","Orissa"),
("INON4MGRHW","IN","Raver","Maharashtra"),
("INYS8NK1M7","IN","Rawatbhata","Rajasthan"),
("IN6PO5007L","IN","Rawatsar","Rajasthan"),
("INSYD8ZCLN","IN","Raxaul Bazar","Bihar"),
("IN0QAHHSDG","IN","Rayachoti","Andhra Pradesh"),
("INLM36NPDT","IN","Rayadurg","Andhra Pradesh"),
("INE2ZE26ZV","IN","Rayagada","Orissa"),
("IN5D34QPSR","IN","Reengus","Rajasthan"),
("INF38WWMCH","IN","Rehli","Madhya Pradesh"),
("IN8GOV51PK","IN","Renigunta","Andhra Pradesh"),
("IN4OZ6VZ21","IN","Renukoot","Uttar Pradesh"),
("INC562VZTA","IN","Reoti","Uttar Pradesh"),
("IN227YPKGX","IN","Repalle","Andhra Pradesh"),
("IN04T66IQA","IN","Revelganj","Bihar"),
("IN7PH2PJ31","IN","Rewa","Madhya Pradesh"),
("INP94K9YVB","IN","Rewari","Haryana"),
("IN12AQMRNN","IN","Rishikesh","Uttarakhand"),
("INVHT2ZKD6","IN","Risod","Maharashtra"),
("INAU9ZED13","IN","Robertsganj","Uttar Pradesh"),
("INN5OW4J85","IN","Robertson Pet","Karnataka"),
("INMIW99JW5","IN","Rohtak","Haryana"),
("IN1P80AL7K","IN","Ron","Karnataka"),
("INGHJUUKYI","IN","Roorkee","Uttarakhand"),
("INQNFV7N0T","IN","Rosera","Bihar"),
("IN6W2GGYLH","IN","Rudauli","Uttar Pradesh"),
("INOUIYFQJW","IN","Rudrapur","Uttar Pradesh"),
("IN72Q2NPLE","IN","Rudrapur","Uttarakhand"),
("INC09JNADT","IN","Rupnagar","Punjab"),
("IN7FAOEW63","IN","Sabalgarh","Madhya Pradesh"),
("INQO16FK2N","IN","Sadabad","Uttar Pradesh"),
("INNTQBIBPV","IN","Sadalgi","Karnataka"),
("INCZEZ9RTG","IN","Sadasivpet","Andhra Pradesh"),
("IN734MZAPQ","IN","Sadri","Rajasthan"),
("INZQWEBZ2Z","IN","Sadulshahar","Rajasthan"),
("INSSAA305G","IN","Safidon","Haryana"),
("INZKG8C9PK","IN","Safipur","Uttar Pradesh"),
("INDU6D4V44","IN","Sagar","Madhya Pradesh"),
("INM0JXZLXS","IN","Sagar","Karnataka"),
("IND82H88X8","IN","Sagwara","Rajasthan"),
("INTDH5N6P1","IN","Saharanpur","Uttar Pradesh"),
("IN0VF5RJ9D","IN","Saharsa","Bihar"),
("INJSBJE8CR","IN","Sahaspur","Uttar Pradesh"),
("INGE8PN6XG","IN","Sahaswan","Uttar Pradesh"),
("INJEM7LC8M","IN","Sahawar","Uttar Pradesh"),
("IN8NRZ71CR","IN","Sahibganj","Jharkhand"),
("INUNA8VM0C","IN","Sahjanwa","Uttar Pradesh"),
("IN181PFZ6Z","IN","Saidpur"," Ghazipur"),
("INES605FMD","IN","Saiha","Mizoram"),
("IN2DCAFO19","IN","Sailu","Maharashtra"),
("INBCI7ZIK1","IN","Sainthia","West Bengal"),
("INRMQ6LW50","IN","Sakleshpur","Karnataka"),
("INPB0UQM8T","IN","Sakti","Chhattisgarh"),
("IN0K3F85PK","IN","Salaya","Gujarat"),
("INH8SGQCHH","IN","Salem","Tamil Nadu"),
("INY7NK4TLU","IN","Salur","Andhra Pradesh"),
("IN4LPV8XP9","IN","Samalkha","Haryana"),
("INHTPQYEBF","IN","Samalkot","Andhra Pradesh"),
("INM3VDGDUE","IN","Samana","Punjab"),
("INLIZPBKKG","IN","Samastipur","Bihar"),
("IN6ACF71OP","IN","Sambalpur","Orissa"),
("INVDFTSR8F","IN","Sambhal","Uttar Pradesh"),
("INU4SAHNP2","IN","Sambhar","Rajasthan"),
("IN5PSH9DYG","IN","Samdhan","Uttar Pradesh"),
("INNAVUCKK8","IN","Samthar","Uttar Pradesh"),
("INX01PRA4L","IN","Sanand","Gujarat"),
("INFXWXKLZP","IN","Sanawad","Madhya Pradesh"),
("INAS7K651T","IN","Sanchore","Rajasthan"),
("INGWOTG82E","IN","Sandi","Uttar Pradesh"),
("IN834ZE8LT","IN","Sandila","Uttar Pradesh"),
("IN5HQQ3QGE","IN","Sandur","Karnataka"),
("INJNYPT0IA","IN","Sangamner","Maharashtra"),
("INW74DF6SO","IN","Sangareddy","Andhra Pradesh"),
("INAWNO58IB","IN","Sangaria","Rajasthan"),
("INQ81TZH7I","IN","Sangli","Maharashtra"),
("IN468Y6R83","IN","Sangole","Maharashtra"),
("INYCHEJ92T","IN","Sangrur","Punjab"),
("IN5PHBYZMO","IN","Sankarankoil","Tamil Nadu"),
("IN8NI75PQA","IN","Sankari","Tamil Nadu"),
("INWZ82QG5P","IN","Sankeshwar","Karnataka"),
("INTM3DW562","IN","Santipur","West Bengal"),
("INVODTNZIW","IN","Sarangpur","Madhya Pradesh"),
("INN04SQV2M","IN","Sardarshahar","Rajasthan"),
("INUBOLSUAM","IN","Sardhana","Uttar Pradesh"),
("INHDZDJ5GE","IN","Sarni","Madhya Pradesh"),
("INTT8HTQDH","IN","Sasaram","Bihar"),
("INQHAHDD37","IN","Sasvad","Maharashtra"),
("INOSSGM334","IN","Satana","Maharashtra"),
("ING2H08XE1","IN","Satara","Maharashtra"),
("INRMJLCW23","IN","Sathyamangalam","Tamil Nadu"),
("INEDKRQOZF","IN","Satna","Madhya Pradesh"),
("INGSW3VZ7C","IN","Sattenapalle","Andhra Pradesh"),
("IN1OC9MQBE","IN","Sattur","Tamil Nadu"),
("INDUZQR2U6","IN","Saunda","Jharkhand"),
("INFEY63XLJ","IN","Saundatti-Yellamma","Karnataka"),
("INQHMLHTXI","IN","Sausar","Madhya Pradesh"),
("INIAS514KE","IN","Savanur","Karnataka"),
("INZK4RMZX2","IN","Savarkundla","Gujarat"),
("INDW9HUU0K","IN","Savner","Maharashtra"),
("INCN5UH3D0","IN","Sawai Madhopur","Rajasthan"),
("IND56EAQT9","IN","Sawantwadi","Maharashtra"),
("INAY0XXYZB","IN","Sedam","Karnataka"),
("INU9SO4T8G","IN","Sehore","Madhya Pradesh"),
("INHEAYHNYV","IN","Sendhwa","Madhya Pradesh"),
("INT4A3V3D5","IN","Seohara","Uttar Pradesh"),
("IN1E2ZC2A6","IN","Seoni","Madhya Pradesh"),
("INC3VGW4WD","IN","Seoni-Malwa","Madhya Pradesh"),
("INI7C0VBVP","IN","Shahabad"," Hardoi"),
("ING5TB86HA","IN","Shahabad"," Rampur"),
("INLK9XNK4Z","IN","Shahabad","Karnataka"),
("INN0FK4CXM","IN","Shahade","Maharashtra"),
("INKAMFLI51","IN","Shahbad","Haryana"),
("INNYCW5U6Q","IN","Shahdol","Madhya Pradesh"),
("INEGO10S0O","IN","Shahganj","Uttar Pradesh"),
("INSF8XS6JC","IN","Shahjahanpur","Uttar Pradesh"),
("ING6R2OW3C","IN","Shahpur","Karnataka"),
("INVG80AFQP","IN","Shahpura","Rajasthan"),
("INVEQW7QL0","IN","Shajapur","Madhya Pradesh"),
("IN6TXY0HAH","IN","Shamgarh","Madhya Pradesh"),
("INO2JDZNPU","IN","Shamli","Uttar Pradesh"),
("IN4XVFDL49","IN","Shamsabad"," Agra"),
("IN0V58MQ8S","IN","Shamsabad"," Farrukhabad"),
("INK6RLO22C","IN","Shegaon","Maharashtra"),
("IN4MP49EZE","IN","Sheikhpura","Bihar"),
("INCUTPGYYG","IN","Shendurjana","Maharashtra"),
("INT4PFVY8G","IN","Shenkottai","Tamil Nadu"),
("IN4Z1S2447","IN","Sheoganj","Rajasthan"),
("INQUB08AFL","IN","Sheohar","Bihar"),
("IN49BK7A11","IN","Sheopur","Madhya Pradesh"),
("INEQHAOPQT","IN","Sherghati","Bihar"),
("INPSLRXQYN","IN","Sherkot","Uttar Pradesh"),
("INKAOTK4FP","IN","Shiggaon","Karnataka"),
("INDQ9L1BMF","IN","Shikapur","Karnataka"),
("IN13QQTHJI","IN","Shikarpur"," Bulandshahr"),
("IN95A6V8UG","IN","Shikohabad","Uttar Pradesh"),
("INIJA3NQS0","IN","Shillong","Meghalaya"),
("INH2LID8YF","IN","Shimla","Himachal Pradesh"),
("INBO545ONF","IN","Shimoga","Karnataka"),
("INTXMP6H6P","IN","Shirdi","Maharashtra"),
("IN0HSO7LPO","IN","Shirpur-Warwade","Maharashtra"),
("INOA61J4GV","IN","Shirur","Maharashtra"),
("INTL0ZANE4","IN","Shishgarh","Uttar Pradesh"),
("INL1URI0HJ","IN","Shivpuri","Madhya Pradesh"),
("INHA7OVWDJ","IN","Sholavandan","Tamil Nadu"),
("IN7JLRO1MI","IN","Sholingur","Tamil Nadu"),
("INNMHYAW2V","IN","Shoranur","Kerala"),
("INXWNGX40E","IN","Shorapur","Karnataka"),
("INE7394GTC","IN","Shrigonda","Maharashtra"),
("IN0E3OGP74","IN","Shrirampur","Maharashtra"),
("INBO2LL5HJ","IN","Shrirangapattana","Karnataka"),
("IN14ZZ8ZDM","IN","Shujalpur","Madhya Pradesh"),
("IN7HWBXQNX","IN","Siana","Uttar Pradesh"),
("IN5RMLGUPS","IN","Sibsagar","Assam"),
("INISE4XVNZ","IN","Siddipet","Andhra Pradesh"),
("INZNY7MCUU","IN","Sidhi","Madhya Pradesh"),
("INTQ6RGUPL","IN","Sidhpur","Gujarat"),
("INLC716XTP","IN","Sidlaghatta","Karnataka"),
("INP8TN3GN2","IN","Sihor","Gujarat"),
("IN3LAQY4KR","IN","Sihora","Madhya Pradesh"),
("INVQJCL8Y6","IN","Sikanderpur","Uttar Pradesh"),
("INK58Q32FT","IN","Sikandra Rao","Uttar Pradesh"),
("INA8GDO3FS","IN","Sikandrabad","Uttar Pradesh"),
("INPQINU2FQ","IN","Sikar","Rajasthan"),
("INTY2E60LR","IN","Silao","Bihar"),
("IN6TH9VX25","IN","Silapathar","Assam"),
("IN5JJUMZMC","IN","Silchar","Assam"),
("INP5ZK8FA1","IN","Siliguri","West Bengal"),
("INECGKD1BJ","IN","Sillod","Maharashtra"),
("INVTTQQWWW","IN","Silvassa","Dadra & Nagar Haveli"),
("INFFR2EDE4","IN","Simdega","Jharkhand"),
("INJEORTYT7","IN","Sindgi","Karnataka"),
("INB9SOB487","IN","Sindhnur","Karnataka"),
("INY2XOYULD","IN","Singapur","Andhra Pradesh"),
("INACGPQUT9","IN","Singrauli","Madhya Pradesh"),
("IN9H02FTAQ","IN","Sinnar","Maharashtra"),
("IN33FE7OM5","IN","Sira","Karnataka"),
("INQKUOEF2O","IN","Sircilla","Andhra Pradesh"),
("INSIEID7RM","IN","Sirhind Fatehgarh Sahib","Punjab"),
("INOSP3MZUP","IN","Sirkali","Tamil Nadu"),
("IN2A4AYQFO","IN","Sirohi","Rajasthan"),
("INAACPQFDI","IN","Sironj","Madhya Pradesh"),
("INXR1BZTXN","IN","Sirsa","Haryana"),
("INLMR8MMXO","IN","Sirsaganj","Uttar Pradesh"),
("INW1ZUSFI2","IN","Sirsi","Karnataka"),
("INPVRGB5Y8","IN","Sirsi","Uttar Pradesh"),
("INX0KWTHJF","IN","Siruguppa","Karnataka"),
("IN4BNQXLFT","IN","Sitamarhi","Bihar"),
("INMENET6HI","IN","Sitapur","Uttar Pradesh"),
("IN28ZDEYMB","IN","Sitarganj","Uttarakhand"),
("INY68SOR8S","IN","Sivaganga","Tamil Nadu"),
("IN2WI0HXT4","IN","Sivagiri","Tamil Nadu"),
("INCHJ5O1OQ","IN","Sivakasi","Tamil Nadu"),
("IN9N3OLQZJ","IN","Siwan","Bihar"),
("INW7CKZKC2","IN","Sohagpur","Madhya Pradesh"),
("INHV2YTW35","IN","Sohna","Haryana"),
("INDNA1OYSX","IN","Sojat","Rajasthan"),
("INLVM7LLQI","IN","Solan","Himachal Pradesh"),
("INT32TNFV4","IN","Solapur","Maharashtra"),
("INBY34U698","IN","Sonamukhi","West Bengal"),
("INTK9HJ1F5","IN","Sonepur","Bihar"),
("INX1CJN31H","IN","Songadh","Gujarat"),
("IN64AUJ5YU","IN","Sonipat","Haryana"),
("IN42ZY9873","IN","Sopore","Jammu & Kashmir"),
("INSGLCI1HG","IN","Soro","Orissa"),
("IN3TZQW172","IN","Soron","Uttar Pradesh"),
("IN5HWONVJS","IN","Soyagaon","Maharashtra"),
("INYIQ7RXAK","IN","Sri Madhopur","Rajasthan"),
("INEVWXWDDZ","IN","Srikakulam","Andhra Pradesh"),
("IN6DQ3EY6J","IN","Srikalahasti","Andhra Pradesh"),
("ING284YRWW","IN","Srinagar","Jammu & Kashmir"),
("INAN31LELZ","IN","Srinivaspur","Karnataka"),
("INAIX7VB72","IN","Srirampore","West Bengal"),
("INOX52WBMC","IN","Srivilliputhur","Tamil Nadu"),
("INEVGCMC9X","IN","Suar","Uttar Pradesh"),
("INZDZKRKK1","IN","Sugauli","Bihar"),
("IN3I9YTG0I","IN","Sujangarh","Rajasthan"),
("IND6L9H7MW","IN","Sujanpur","Punjab"),
("IN229PFINF","IN","Sultanganj","Bihar"),
("INVM0N7LPA","IN","Sultanpur","Uttar Pradesh"),
("IN3Y8WE9FS","IN","Sumerpur","Rajasthan"),
("ING02Y7OUA","IN","Sumerpur","Uttar Pradesh"),
("INR307MNMI","IN","Sunabeda","Orissa"),
("IN9M5G8VQB","IN","Sunam","Punjab"),
("INTZ889N1P","IN","Sundargarh","Orissa"),
("INN3OVSI6J","IN","Sundarnagar","Himachal Pradesh"),
("INM6R8TDQ2","IN","Supaul","Bihar"),
("IN0WJ8RAKL","IN","Surandai","Tamil Nadu"),
("IN9SUJGV94","IN","Surat","Gujarat"),
("INZXZRG5B2","IN","Suratgarh","Rajasthan"),
("INC2A5F18G","IN","Suri","West Bengal"),
("INXROP19BB","IN","Suriyampalayam","Tamil Nadu"),
("IN15VI14M0","IN","Suryapet","Andhra Pradesh"),
("IN2MRIS3K4","IN","Tadepalligudem","Andhra Pradesh"),
("IN5V9LWI2U","IN","Tadpatri","Andhra Pradesh"),
("IN9QKB0VM1","IN","Taki","West Bengal"),
("IN1HK2M62P","IN","Talaja","Gujarat"),
("INTU7LXSP3","IN","Talcher","Orissa"),
("INNZOKIQFR","IN","Talegaon Dabhade","Maharashtra"),
("INHZ2HVPJW","IN","Talikota","Karnataka"),
("IN74YUA0J3","IN","Taliparamba","Kerala"),
("INVQPSJFV6","IN","Talode","Maharashtra"),
("INFKRXB6OT","IN","Talwara","Punjab"),
("IN6RB1HVXP","IN","Tamluk","West Bengal"),
("INZWJAX2DS","IN","Tanda","Uttar Pradesh"),
("INT3LCIGJX","IN","Tandur","Andhra Pradesh"),
("IN1BUDIJ6O","IN","Tanuku","Andhra Pradesh"),
("INBHQSDOIC","IN","Tarakeswar","West Bengal"),
("INK1MI40AX","IN","Tarana","Madhya Pradesh"),
("IN3VAMCUJE","IN","Taranagar","Rajasthan"),
("IN5ERNYYC9","IN","Taraori","Haryana"),
("ING32TRK5C","IN","Tarikere","Karnataka"),
("INMSUQS5NW","IN","Tarn Taran","Punjab"),
("IN0YIDS2RY","IN","Tasgaon","Maharashtra"),
("INGJMEHZOX","IN","Tehri","Uttarakhand"),
("IN2RQUBW7X","IN","Tekkalakota","Karnataka"),
("INO1OH7CD8","IN","Tenali","Andhra Pradesh"),
("INAVL3YD1E","IN","Tenkasi","Tamil Nadu"),
("INWOTENIBP","IN","Tenu Dam-cum- Kathhara","Jharkhand"),
("IN91KLYRJM","IN","Terdal","Karnataka"),
("INT730JH8U","IN","Tetri Bazar","Uttar Pradesh"),
("INDTXB7ZQ3","IN","Tezpur","Assam"),
("INNJHA2T0C","IN","Thakurdwara","Uttar Pradesh"),
("INVKXTBHG4","IN","Thammampatti","Tamil Nadu"),
("INOK481C2E","IN","Thana Bhawan","Uttar Pradesh"),
("IN60PDZFHM","IN","Thanesar","Haryana"),
("INZZX2TXEO","IN","Thangadh","Gujarat"),
("INIBITSYYH","IN","Thanjavur","Tamil Nadu"),
("INI3PJGSYM","IN","Tharad","Gujarat"),
("INSN0S3IF3","IN","Tharamangalam","Tamil Nadu"),
("INHC5BAKZS","IN","Tharangambadi","Tamil Nadu"),
("INWHMOFK6Y","IN","Theni Allinagaram","Tamil Nadu"),
("INNWH3PFQH","IN","Thirumangalam","Tamil Nadu"),
("IN3QA79PBQ","IN","Thirunindravur","Tamil Nadu"),
("IN1H2C114X","IN","Thiruparappu","Tamil Nadu"),
("INJQMYBSXY","IN","Thirupuvanam","Tamil Nadu"),
("INPE2EUSWY","IN","Thiruthuraipoondi","Tamil Nadu"),
("INJ65SVGJX","IN","Thiruvalla","Kerala"),
("INYLAZNEW6","IN","Thiruvallur","Tamil Nadu"),
("IN5J5GC2F1","IN","Thiruvananthapuram","Kerala"),
("INHIGCBCAV","IN","Thiruvarur","Tamil Nadu"),
("INIGOEX7CV","IN","Thodupuzha","Kerala"),
("INTMUH1RN7","IN","Thoothukudi","Tamil Nadu"),
("INATOMV3OD","IN","Thoubal","Manipur"),
("INM4PYG0TZ","IN","Thrissur","Kerala"),
("INGHEDPR8J","IN","Thuraiyur","Tamil Nadu"),
("IND30FUOM5","IN","Tikamgarh","Madhya Pradesh"),
("INHASDEGR1","IN","Tilda Newra","Chhattisgarh"),
("INLGZ1GS1X","IN","Tilhar","Uttar Pradesh"),
("IN9GAZ7JIL","IN","Tindivanam","Tamil Nadu"),
("INMJ0G7NLP","IN","Tinsukia","Assam"),
("INYD2CUTEF","IN","Tiptur","Karnataka"),
("INADHR5IOF","IN","Tirora","Maharashtra"),
("INZZF6IXS4","IN","Tiruchendur","Tamil Nadu"),
("INHTLOG6DF","IN","Tiruchengode","Tamil Nadu"),
("INKGREA6TK","IN","Tiruchirappalli","Tamil Nadu"),
("INJBCPT04T","IN","Tirukalukundram","Tamil Nadu"),
("IN0JZIHRNZ","IN","Tirukkoyilur","Tamil Nadu"),
("INL8N1F1G0","IN","Tirunelveli","Tamil Nadu"),
("INH8ESE8CY","IN","Tirupathur","Tamil Nadu"),
("INJPNDPS6Q","IN","Tirupati","Andhra Pradesh"),
("INB69TYWSJ","IN","Tiruppur","Tamil Nadu"),
("IN5GLKH1KZ","IN","Tirur","Kerala"),
("INAZSP84NS","IN","Tiruttani","Tamil Nadu"),
("INTB6J3DAF","IN","Tiruvannamalai","Tamil Nadu"),
("INJJ8IF11K","IN","Tiruvethipuram","Tamil Nadu"),
("INIM50OQ0Z","IN","Tirwaganj","Uttar Pradesh"),
("INQSPZXCRR","IN","Titlagarh","Orissa"),
("INOYARBL6V","IN","Tittakudi","Tamil Nadu"),
("IN4FDJGF4Z","IN","Todabhim","Rajasthan"),
("IN1AZQ0ZPR","IN","Todaraisingh","Rajasthan"),
("INRFQORIFG","IN","Tohana","Haryana"),
("INHQ7SBDOF","IN","Tonk","Rajasthan"),
("INS1Z9H48J","IN","Tuensang","Nagaland"),
("INF89G7Z7Z","IN","Tuljapur","Maharashtra"),
("INEYO6G3MX","IN","Tulsipur","Uttar Pradesh"),
("INUUQ67FM0","IN","Tumkur","Karnataka"),
("INHMAYQJH5","IN","Tumsar","Maharashtra"),
("INRRLZQTY5","IN","Tundla","Uttar Pradesh"),
("INRNC8QY6L","IN","Tuni","Andhra Pradesh"),
("INSXR0CE1T","IN","Tura","Meghalaya"),
("IN0BRRV9XN","IN","Uchgaon","Maharashtra"),
("IN0JMQCLW4","IN","Udaipur","Tripura"),
("IN88CZ7JLZ","IN","Udaipur","Rajasthan"),
("INGD0TR1MR","IN","Udaipurwati","Rajasthan"),
("INDEI9NFWN","IN","Udgir","Maharashtra"),
("INZJEB5AFE","IN","Udhagamandalam","Tamil Nadu"),
("INJSDQBZQS","IN","Udhampur","Jammu & Kashmir"),
("INCQL3S8V6","IN","Udumalaipettai","Tamil Nadu"),
("INNEFAUBYT","IN","Udupi","Karnataka"),
("INVD40OKE7","IN","Ujhani","Madhya Pradesh"),
("INCSXORNH3","IN","Ujjain","Madhya Pradesh"),
("INE376B2DY","IN","Umarga","Maharastra"),
("INGS9A473Z","IN","Umaria","Madhya Pradesh"),
("INK709SEG5","IN","Umarkhed","Maharastra"),
("IN6DTY1B1G","IN","Umarkote","Orissa"),
("INE8NQB0PR","IN","Umbergaon","Gujarat"),
("INTY1X65XR","IN","Umred","Maharastra"),
("INDX05CHAJ","IN","Umreth","Gujarat"),
("INV4HWFJDT","IN","Una","Gujarat"),
("INS0K309UT","IN","Unjha","Gujarat"),
("IN8WRF1O7E","IN","Unnamalaikadai","Tamil Nadu"),
("INM8KZPUIK","IN","Unnao","Uttar Pradesh"),
("INY0HEJU7B","IN","Upleta","Gujarat"),
("INUSEV18PA","IN","Uran","Maharashtra"),
("IN5GQ65XLS","IN","Uran Islampur","Maharashtra"),
("IN55RV0AGY","IN","Uravakonda","Andhra Pradesh"),
("INAXCTSK4N","IN","Urmar Tanda","Punjab"),
("INCJIES8PX","IN","Usilampatti","Tamil Nadu"),
("INOF3UCPMI","IN","Uthamapalayam","Tamil Nadu"),
("INUDEUOUTY","IN","Uthiramerur","Tamil Nadu"),
("INS6RLRW84","IN","Utraula","Uttar Pradesh"),
("INFRI7Z74O","IN","Vadakara","Kerala"),
("INN8IZX5IS","IN","Vadakkuvalliyur","Tamil Nadu"),
("INIWN6RH5J","IN","Vadalur","Tamil Nadu"),
("INOW5FSDJ7","IN","Vadgaon Kasba","Maharastra"),
("IN52F4AJSX","IN","Vadipatti","Tamil Nadu"),
("INSBXQGFIZ","IN","Vadnagar","Gujarat"),
("INC663OBNC","IN","Vadodara","Gujarat"),
("IN8SR06B8B","IN","Vaijapur","Maharastra"),
("INENGO79LZ","IN","Vaikom","Kerala"),
("INKIP1Y80A","IN","Valparai","Tamil Nadu"),
("INF7E3I2GQ","IN","Valsad","Gujarat"),
("INV8R1J0DX","IN","Vandavasi","Tamil Nadu"),
("INNTMV27VN","IN","Vaniyambadi","Tamil Nadu"),
("INPLOOTPY9","IN","Vapi","Gujarat"),
("INWCDFFT5A","IN","Varanasi","Uttar Pradesh"),
("IN1XCLXPJL","IN","Varkala","Kerala"),
("INI5GLCC92","IN","Vasai","Maharastra"),
("INXXQRNP0J","IN","Vedaranyam","Tamil Nadu"),
("IN2DYH64R8","IN","Vellakoil","Tamil Nadu"),
("IN13TZTCKC","IN","Vellore","Tamil Nadu"),
("INI1XUD6XA","IN","Venkatagiri","Andhra Pradesh"),
("IN4N1RD2AF","IN","Veraval","Gujarat"),
("INF9WMEOVF","IN","Vicarabad","Andhra Pradesh"),
("INSPFL2ZXK","IN","Vidisha","Madhya Pradesh"),
("IN1VEE2CP6","IN","Vijainagar","Rajasthan"),
("IN0QXDT8S9","IN","Vijapur","Gujarat"),
("INIPVWDRC6","IN","Vijayapura","Karnataka"),
("INGRRIRP2S","IN","Vijayawada","Andhra Pradesh"),
("INKH7MTWTU","IN","Vikramasingapuram","Tamil Nadu"),
("INNR7G00PI","IN","Viluppuram","Tamil Nadu"),
("INPLF3CR9T","IN","Vinukonda","Andhra Pradesh"),
("INJ1BBQE3B","IN","Viramgam","Gujarat"),
("INVBXP7RJU","IN","Virar","Maharastra"),
("INIRBIR01H","IN","Virudhachalam","Tamil Nadu"),
("INMGKZ8USS","IN","Virudhunagar","Tamil Nadu"),
("INV33LH7WD","IN","Visakhapatnam","Andhra Pradesh"),
("INIU3PMMK4","IN","Visnagar","Gujarat"),
("INEVN6WPNI","IN","Viswanatham","Tamil Nadu"),
("IN68HE3A7Y","IN","Vita","Maharastra"),
("INDAKVIH90","IN","Vizianagaram","Andhra Pradesh"),
("INCCQYZB3D","IN","Vrindavan","Uttar Pradesh"),
("IN7QJ3G7MM","IN","Vyara","Gujarat"),
("INF41JE8HS","IN","Wadgaon Road","Maharashtra"),
("INI1O1JX1V","IN","Wadhwan","Gujarat"),
("INAST94WMB","IN","Wadi","Karnataka"),
("INN6F3D2QT","IN","Wai","Maharashtra"),
("IN6RCLZUDI","IN","Wanaparthy","Andhra Pradesh"),
("INV1JEZLA9","IN","Wani","Maharashtra"),
("INE3II05UO","IN","Wankaner","Gujarat"),
("INB9SPBIII","IN","Wara Seoni","Madhya Pradesh"),
("IN9V39PHRL","IN","Warangal","Andhra Pradesh"),
("INIA0HWARA","IN","Wardha","Maharashtra"),
("INE9TEEO2Q","IN","Warhapur","Uttar Pradesh"),
("INXUF9DYSM","IN","Warisaliganj","Bihar"),
("INUWVKDN5V","IN","Warora","Maharashtra"),
("INY6DUH55V","IN","Warud","Maharashtra"),
("INEZ9TNCKL","IN","Washim","Maharashtra"),
("IN7ZUKYN7T","IN","Wokha","Nagaland"),
("INJ2DWPJSN","IN","Yadgir","Karnataka"),
("INP6I6BO2Q","IN","Yamunanagar","Haryana"),
("INNBJAO3VW","IN","Yanam","Pondicherry"),
("IN3QG2DNVX","IN","Yavatmal","Maharastra"),
("INQ8UGRM3H","IN","Yawal","Maharastra"),
("INSMN4APUX","IN","Yellandu","Andhra Pradesh"),
("IN1D8QH3MK","IN","Yemmiganur","Andhra Pradesh"),
("INU2N8QI5G","IN","Yerraguntla","Andhra Pradesh"),
("INQZWIM0ZF","IN","Yevla","Maharashtra"),
("INNNJXDDVF","IN","Zahirabad","Andhra Pradesh"),
("INR3597RU1","IN","Zaidpur","Uttar Pradesh"),
("INUHALZG1Q","IN","Zamania","Uttar Pradesh"),
("INGY92Z8HM","IN","Zira","Punjab"),
("INW1J9FEO7","IN","Zirakpur","Punjab"),
("INIUGPLARG","IN","Zunheboto","Nagaland");