INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("IS34GVD2IM","IS","Borgarfjardarsysla",NULL),
("ISBEVO2427","IS","Capital Region",NULL),
("ISIL9URV0G","IS","Dalasysla",NULL),
("ISV5OZD4BG","IS","East",NULL),
("IS8RBLTU74","IS","Eyjafjardarsysla",NULL),
("IS83TB7VIP","IS","Gullbringusysla",NULL),
("ISGRJ8NJOJ","IS","Hafnarfjördur",NULL),
("ISODI2HTIQ","IS","Husavik",NULL),
("ISKUCEOKJX","IS","Isafjördur",NULL),
("ISNC8U7RKO","IS","Keflavik",NULL),
("ISI3W6NLPC","IS","Kjosarsysla",NULL),
("ISZ8EG1W7M","IS","Kopavogur",NULL),
("ISRJ1F3KCQ","IS","Myrasysla",NULL),
("ISXLL5C5TV","IS","Neskaupstadur",NULL),
("IS8P1WBR8A","IS","Nordur-Isafjardarsysla",NULL),
("ISZMR1JYOA","IS","Nordur-Mulasysla",NULL),
("ISHPQK92A6","IS","Nordur-Tingeyjarsysla",NULL),
("ISNWB015V9","IS","Northeast",NULL),
("ISVW66OEHO","IS","Northwest",NULL),
("IS18PL6DWO","IS","Olafsfjördur",NULL),
("IS3M8CPJJD","IS","Rangarvallasysla",NULL),
("ISFVDG18QW","IS","Reykjavík",NULL),
("IS5W3UBKIC","IS","Saudarkrokur",NULL),
("ISS8XZLTNO","IS","Seydisfjordur",NULL),
("ISFV15FLIV","IS","Siglufjordur",NULL),
("ISHVBI42FA","IS","Skagafjardarsysla",NULL),
("ISYI493NMV","IS","Snafellsnes- og Hnappadalssysla",NULL),
("ISVJVGDI5T","IS","South",NULL),
("ISE7YTTGOB","IS","Southern Peninsula",NULL),
("ISC0UH29S1","IS","Strandasysla",NULL),
("ISSWBVKXRF","IS","Sudur-Mulasysla",NULL),
("ISHMVU51NJ","IS","Sudur-Tingeyjarsysla",NULL),
("IS9MD332EG","IS","Vestmannaeyjar",NULL),
("IS39Y6JQ7B","IS","Vestur-Bardastrandarsysla",NULL),
("ISNJ77GZMY","IS","Vestur-Hunavatnssysla",NULL),
("ISLISRKGBT","IS","Vestur-Isafjardarsysla",NULL),
("IS2OX6RCMU","IS","Vestur-Skaftafellssysla",NULL),
("ISLK14A8GY","IS","West",NULL),
("ISSN58MR68","IS","Westfjords",NULL);