INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("JORELQG59C","JO","Ajlun",NULL),
("JOYT0TTZME","JO","Al Mafraq",NULL),
("JOMUJZFR01","JO","Amman",NULL),
("JO7DLB9TB0","JO","Aqaba",NULL),
("JO8XRO2011","JO","Az Zarqa",NULL),
("JOT2UN1H2N","JO","Balqa",NULL),
("JOCLNRDOTK","JO","Irbid",NULL),
("JO2EVB87CG","JO","Jerash",NULL),
("JO4357479Y","JO","Karak",NULL),
("JO94LAMNYY","JO","Ma’an",NULL),
("JO8LQLAJ6C","JO","Madaba",NULL),
("JOX2O591ME","JO","Mafraq",NULL),
("JO4SM9ZW78","JO","Tafielah",NULL),
("JO0SIMGGLP","JO","Zarqa",NULL);