INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("KHI1EGF7GM","KH","Bantéay Méan Cheăy",NULL),
("KH3ZN8QIP6","KH","Bătdâmbâng",NULL),
("KHBN2LO25C","KH","Kâmpóng Cham",NULL),
("KHQMC65Z5N","KH","Kâmpóng Chhnăng",NULL),
("KH1J3GRJ3V","KH","Kâmpóng Thum",NULL),
("KHJQ3A9THK","KH","Kâmpôt",NULL),
("KHGJ65MBID","KH","Kândal",NULL),
("KHYUK3UPQV","KH","Kaôh Kŏng",NULL),
("KH9UC1EGWX","KH","Kêb",NULL),
("KH608GTP0A","KH","Khétt Kâmpóng Spœ",NULL),
("KH96GVIY9G","KH","Krâchéh",NULL),
("KHTTJOJAJT","KH","Krŏng Preăh Seihânŭ",NULL),
("KH4WUJCRHJ","KH","Môndól Kiri",NULL),
("KHRPZLEZWN","KH","Ŏtdâr Méan Cheăy",NULL),
("KH6CJPBT54","KH","Palĭn",NULL),
("KHNPS6ZC04","KH","Phnum Penh",NULL),
("KH8VNKM43E","KH","Poŭthĭsăt",NULL),
("KHU2Z82WW9","KH","Preăh Seihânŭ",NULL),
("KH8GYJA4OX","KH","Preăh Vihéar",NULL),
("KHTG4TS4X0","KH","Prey Vêng",NULL),
("KH0LLNQP1K","KH","Rôtânăh Kiri",NULL),
("KHS1TVXQ56","KH","Siĕm Réab",NULL),
("KH63PH8DE2","KH","Stœ̆ng Trêng",NULL),
("KHUIVMNSNO","KH","Svay Riĕng",NULL),
("KHE9B4YCOR","KH","Takêv",NULL);