INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("KRHFQZHGUL","KR","Busan",NULL),
("KRUHEQ7DB1","KR","Daegu",NULL),
("KR3739F9WN","KR","Daejeon",NULL),
("KREZXCEJXV","KR","Gangwon",NULL),
("KRYOUF4P1Z","KR","Gwangju",NULL),
("KR6GPET1FX","KR","Gyeonggi",NULL),
("KR8I6OS2B6","KR","Incheon",NULL),
("KR28JGSGBQ","KR","Jeju",NULL),
("KR4669V892","KR","North Chungcheong",NULL),
("KRPZGI1VF9","KR","North Gyeongsang",NULL),
("KREMY7PADR","KR","North Jeolla",NULL),
("KRJX8BDJ1I","KR","Seoul",NULL),
("KRP8SLH2N6","KR","South Chungcheong",NULL),
("KR13P3Z4DD","KR","South Gyeongsang",NULL),
("KRRBKHLY94","KR","South Jeolla",NULL),
("KRVHF90HSQ","KR","Ulsan",NULL);