INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("LASVGSPNV9","LA","Attapu",NULL),
("LAJFR5RQFC","LA","Bokèo",NULL),
("LAYG6Y4UAV","LA","Bolikhamxai",NULL),
("LAMJPK394W","LA","Champasak",NULL),
("LA5KOU7J4Q","LA","Houaphan",NULL),
("LAYVWQMB2K","LA","Khammouan",NULL),
("LAS9JW3USQ","LA","Louang Namtha",NULL),
("LAEHAHREDX","LA","Louangphabang",NULL),
("LAY2S6MWWL","LA","Louangphrabang",NULL),
("LARTBD4EYW","LA","Loungnamtha",NULL),
("LANHTRBLHP","LA","Oudômxai",NULL),
("LA3R7U5KS4","LA","Phongsali",NULL),
("LAMKA9G7U7","LA","Salavan",NULL),
("LA05L4KJ18","LA","Saravan",NULL),
("LA1UZDGG2J","LA","Savannahkhét",NULL),
("LA79EDU6HH","LA","Savannakhet",NULL),
("LAQRQ7ZKFZ","LA","Viangchan",NULL),
("LAQ04BK5JM","LA","Vientiane",NULL),
("LA0IZGZ207","LA","Xékong",NULL),
("LABEK6L2NB","LA","Xiagnabouli",NULL),
("LAUEJTZYSP","LA","Xiangkhoang",NULL);