INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("LRV1LQJEQ6","LR","Bomi",NULL),
("LRXO14EX5H","LR","Bong",NULL),
("LRWEU7XXVQ","LR","Gbarpolu",NULL),
("LRED6JYBTT","LR","Grand Bassa County",NULL),
("LRCFJVU92R","LR","Grand Cape Mount",NULL),
("LRY4WC21UY","LR","Grand Gedeh",NULL),
("LRGP6DN141","LR","Grand Jide",NULL),
("LRFBKDME7Z","LR","Grand Kru",NULL),
("LRUQVO0XGZ","LR","Lofa",NULL),
("LR2CC4E73U","LR","Margibi",NULL),
("LRW98JBDKQ","LR","Maryland",NULL),
("LRO54BKBAE","LR","Montserrado",NULL),
("LR25323J25","LR","Nimba",NULL),
("LRWEABLD5H","LR","River Cess",NULL),
("LRME0XRLOF","LR","River Gee",NULL),
("LRQSQB31Q5","LR","Sinoe",NULL);