INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("LYL1PYHPIU","LY","Ajdābiyā",NULL),
("LYS06AXBQQ","LY","Al ‘Azīzīyah",NULL),
("LY0VA9V7KM","LY","Al Abyār",NULL),
("LYQDUB0C5L","LY","Al Ajaylāt",NULL),
("LYEVKVL2QE","LY","Al Bayḑā’",NULL),
("LY2WP08GR9","LY","Al Fātiḩ",NULL),
("LYC1I792TZ","LY","Al Jabal al Akhḑar",NULL),
("LYGNBG0H1F","LY","Al Jufrah",NULL),
("LYDMAZO1DR","LY","Al Jumayl",NULL),
("LYX3R6JJFV","LY","Al Khums",NULL),
("LYKY2T1WTH","LY","Al Kufrah",NULL),
("LYK5XKNZ01","LY","Al Marj",NULL),
("LYLA09CE0A","LY","Al Qarābūll",NULL),
("LYHSG0BWWW","LY","Al Qubbah",NULL),
("LYUZQVVKDF","LY","An Nuqāţ al Khams",NULL),
("LYPA0D90EU","LY","Ash Shāţiʼ",NULL),
("LYBE4NS5XA","LY","Awbārī",NULL),
("LYYEB9A765","LY","Az Zahra’",NULL),
("LY6W12GEI6","LY","Az Zāwiyah",NULL),
("LYOIJYJXTV","LY","Banghāzī",NULL),
("LYBXI42GE0","LY","Banī Walīd",NULL),
("LYVPA5XGB4","LY","Bin Jawwād",NULL),
("LYDC6TROZG","LY","Darnah",NULL),
("LY7JEQG8LS","LY","Ghadāmis",NULL),
("LY54W8LB9G","LY","Gharyān",NULL),
("LY1KMZ1X3E","LY","Ghāt",NULL),
("LYA982Y8I5","LY","Jādū",NULL),
("LYRXW75H0B","LY","Jālū",NULL),
("LYMXJ78TNA","LY","Janzūr",NULL),
("LYDA9F8CUJ","LY","Masallatah",NULL),
("LYM2LKA4Q2","LY","Mişrātah",NULL),
("LY1MA63AIP","LY","Mizdah",NULL),
("LY71XGVLR9","LY","Murzuq",NULL),
("LYV0O3DIM0","LY","Nālūt",NULL),
("LYL8KWCBYD","LY","Qamīnis",NULL),
("LYX8K1J2QR","LY","Qaşr Bin Ghashīr",NULL),
("LY4O809Z94","LY","Sabhā",NULL),
("LY0X7EGUE1","LY","Şabrātah",NULL),
("LY2YXE9WS7","LY","Sawfajjīn",NULL),
("LY4D8OGZGK","LY","Shaḩḩāt",NULL),
("LYNOKWNU0O","LY","Şurmān",NULL),
("LYS8283G96","LY","Surt",NULL),
("LYF7LP3DW8","LY","Tajura’ ",NULL),
("LYR4X73DRR","LY","Ţarābulus",NULL),
("LY1CNP6NDZ","LY","Tarhūnah",NULL),
("LYWG70XH6C","LY","Ţubruq",NULL),
("LYOR2S5Y1W","LY","Tūkrah",NULL),
("LY3Y37BVYC","LY","Yafran",NULL),
("LY7L1E9FD6","LY","Zlīţan",NULL),
("LYWL6T2C5R","LY","Zuwārah",NULL);