INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("MDHFHBXGHY","MD","Balti",NULL),
("MDYDMSH88N","MD","Bender",NULL),
("MDUCN1HARC","MD","Cahul",NULL),
("MD99RHT9HA","MD","Călăraşi",NULL),
("MDPYMMF3KD","MD","Căuşeni",NULL),
("MDH76ZGEMA","MD","Chişinău",NULL),
("MDR9C9J4LT","MD","Dubăsari",NULL),
("MDDCA7MSIB","MD","Edinet",NULL),
("MDQ4Y67JKO","MD","Găgăuzia",NULL),
("MDQQN659HW","MD","Lapusna",NULL),
("MDIT52XRVB","MD","Orhei",NULL),
("MD36IPY00P","MD","Raionul Anenii Noi",NULL),
("MD4ZVCIF18","MD","Raionul Basarabeasca",NULL),
("MD6PEBZW8I","MD","Raionul Briceni",NULL),
("MDPEKN5FY8","MD","Raionul Cahul",NULL),
("MDLHYKHZ9M","MD","Raionul Cantemir",NULL),
("MDY4ZGK1OQ","MD","Raionul Cimişlia",NULL),
("MDQ31PZA8P","MD","Raionul Criuleni",NULL),
("MDOSCT8B2U","MD","Raionul Donduşeni",NULL),
("MDS0EAZNXY","MD","Raionul Drochia",NULL),
("MDSWECX32O","MD","Raionul Edineţ",NULL),
("MD64E6EMV3","MD","Raionul Făleşti",NULL),
("MDF7WNJYHB","MD","Raionul Floreşti",NULL),
("MDZVLZJIXB","MD","Raionul Glodeni",NULL),
("MDFBODER2L","MD","Raionul Hînceşti",NULL),
("MDVGRA3NDI","MD","Raionul Ialoveni",NULL),
("MDUA6D9NP8","MD","Raionul Leova",NULL),
("MDJB83T5E9","MD","Raionul Nisporeni",NULL),
("MDG3NVUPHQ","MD","Raionul Ocniţa",NULL),
("MD5819VFRQ","MD","Raionul Orhei",NULL),
("MDPY4ZLT85","MD","Raionul Rezina",NULL),
("MD4G8YLN82","MD","Raionul Rîşcani",NULL),
("MDRVXLKECQ","MD","Raionul Sîngerei",NULL),
("MDND0JSRAI","MD","Raionul Şoldăneşti",NULL),
("MDQEHC8PHD","MD","Raionul Soroca",NULL),
("MD5QBREKT5","MD","Raionul Străşeni",NULL),
("MDGQR153RT","MD","Raionul Taraclia",NULL),
("MDGSC9KMRA","MD","Raionul Teleneşti",NULL),
("MD19M9Y3M4","MD","Raionul Ungheni",NULL),
("MDUYV9JOEZ","MD","Soroca",NULL),
("MDF50L9SEP","MD","Ştefan-Vodă",NULL),
("MDKRY4EQEF","MD","Stinga Nistrului",NULL),
("MDZ0PY4C2Z","MD","Tighina",NULL),
("MDAX8UMNT1","MD","Ungheni",NULL),
("MDSUM1M1R7","MD","Ungheni Judetul",NULL);