INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("MESQB6HQMG","ME","Opština Andrijevica",NULL),
("MERBFWNHVY","ME","Opština Bar",NULL),
("MEF4S2RM3K","ME","Opština Berane",NULL),
("MEGQM2SE9K","ME","Opština Bijelo Polje",NULL),
("ME4LRMCD23","ME","Opština Budva",NULL),
("MEPIZCZVBF","ME","Opština Cetinje",NULL),
("MEZ4HRQLB6","ME","Opština Danilovgrad",NULL),
("MECY94CJOH","ME","Opština Herceg Novi",NULL),
("ME5G3HU6KJ","ME","Opština Kolašin",NULL),
("MEOKWOG83G","ME","Opština Kotor",NULL),
("MECL726J9I","ME","Opština Mojkovac",NULL),
("MEHJMU3BB8","ME","Opština Nikšić",NULL),
("MESFQMLB6A","ME","Opština Plav",NULL),
("MEV3YCB2SO","ME","Opština Pljevlja",NULL),
("MENZRUJ0C1","ME","Opština Plužine",NULL),
("MEKZVNA7W3","ME","Opština Podgorica",NULL),
("MENMP9YWJT","ME","Opština Rožaje",NULL),
("ME0I6BKY08","ME","Opština Šavnik",NULL),
("MEYR2HSEIC","ME","Opština Tivat",NULL),
("MEDE0OMXSA","ME","Opština Ulcinj",NULL),
("MEKHJIE3CE","ME","Opština Žabljak",NULL);