INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("MK1TJESJE9","MK","Aračinovo",NULL),
("MKAJ8R2KQ2","MK","Bač",NULL),
("MKUZWIUZ0C","MK","Belčišta",NULL),
("MKZ0EPQKMR","MK","Berovo",NULL),
("MKD566PLGZ","MK","Bistrica",NULL),
("MK4OR79I93","MK","Bitola",NULL),
("MKH5LC4MO4","MK","Blatec",NULL),
("MKN2TDMF50","MK","Bogdanci",NULL),
("MKLC7AXNA2","MK","Bogovinje",NULL),
("MKB29KLJO3","MK","Bosilovo",NULL),
("MKOAFTW3XK","MK","Brvenica",NULL),
("MK5QYS63TR","MK","Čair",NULL),
("MKG02ENDHZ","MK","Capari",NULL),
("MKFQK0A83Z","MK","Čaška",NULL),
("MKIISFMQZR","MK","Čegrana",NULL),
("MKHXKN1EFI","MK","Centar",NULL),
("MKEHW2UD2A","MK","Centar Župa",NULL),
("MK4MAEUEDC","MK","Češinovo",NULL),
("MKX6SJWRBE","MK","Čučer-Sandevo",NULL),
("MKPW1QAH9P","MK","Debar",NULL),
("MKZ5RTJT4O","MK","Delčevo",NULL),
("MKFF3ATHNR","MK","Delogoždi",NULL),
("MKNFAK7MYW","MK","Demir Hisar",NULL),
("MKI0NSHWHG","MK","Demir Kapija",NULL),
("MK29AM3FAJ","MK","Dobruševo",NULL),
("MKUDTOVGFI","MK","Dolna Banjica",NULL),
("MKWQ34C20V","MK","Dolneni",NULL),
("MK3OOKL61N","MK","Drugovo",NULL),
("MKFC9ISK2M","MK","Džepčište",NULL),
("MKYVBTCQB9","MK","Gazi Baba",NULL),
("MKHFDTIEPL","MK","Gevgelija",NULL),
("MK2D6OJ8BY","MK","Gostivar",NULL),
("MKKLHD6KZ4","MK","Gradsko",NULL),
("MKFBXS191J","MK","Ilinden",NULL),
("MKOFD6T2RW","MK","Izvor",NULL),
("MKFYKY6WXR","MK","Jegunovce",NULL),
("MKIF4OZ3SF","MK","Kamenjane",NULL),
("MKEQ7GZ9ZO","MK","Karbinci",NULL),
("MKPDVIFNFU","MK","Karpoš",NULL),
("MKLZTRWRIF","MK","Kavadarci",NULL),
("MK6M36QWL5","MK","Kičevo",NULL),
("MKMTMM3MAS","MK","Kisela Voda",NULL),
("MKZ5BESQ9E","MK","Klečevce",NULL),
("MKQ25MTN10","MK","Kočani",NULL),
("MKA5602S6O","MK","Konče",NULL),
("MKLSBPFLHE","MK","Kondovo",NULL),
("MKRTTKJ2Y9","MK","Konopište",NULL),
("MK53WZRXZ1","MK","Kosel",NULL),
("MK3625Y9UK","MK","Kratovo",NULL),
("MK25AHRSVI","MK","Kriva Palanka",NULL),
("MKLO24R1EW","MK","Krivogaštani",NULL),
("MK5AVW8VYB","MK","Kruševo",NULL),
("MK21H1ABLD","MK","Kukliš",NULL),
("MKHWU8OQQ9","MK","Kukurečani",NULL),
("MKFTE6VS20","MK","Kumanovo",NULL),
("MK2YWBUVMW","MK","Labuništa",NULL),
("MKX4X8FJLW","MK","Lozovo",NULL),
("MKFF536WDL","MK","Lukovo",NULL),
("MKPRRLKULM","MK","Macedonia, The Former Yugoslav Republic of",NULL),
("MKTIXNDKJB","MK","Makedonska Kamenica",NULL),
("MKOGJ4Z41F","MK","Makedonski Brod",NULL),
("MKK6IQ2WBS","MK","Mavrovi Anovi",NULL),
("MKO3D8XYVR","MK","Mešeišta",NULL),
("MKGTEUDY52","MK","Miravci",NULL),
("MKFO6ET7UD","MK","Mogila",NULL),
("MKDD3F9F7X","MK","Murtino",NULL),
("MKIL6GJ170","MK","Negotino",NULL),
("MKUMV8L1A0","MK","Negotino-Pološko",NULL),
("MKPHFJP9W3","MK","Novaci",NULL),
("MKM0JVFRTY","MK","Novo Selo",NULL),
("MKCZFW0MWV","MK","Obleševo",NULL),
("MK9R3USEUI","MK","Ohrid",NULL),
("MKVA2LJZO5","MK","Opstina Bogomila",NULL),
("MKZ80FZUEC","MK","Opstina Gjorce Petrov",NULL),
("MKTT8UF4PP","MK","Opstina Lipkovo",NULL),
("MKWSKP6F82","MK","Opstina Rankovce",NULL),
("MKPAO89DD9","MK","Opština Rostuša",NULL),
("MKLEPL83X2","MK","Orašac",NULL),
("MKW5WBAL17","MK","Orizari",NULL),
("MKELXL05NP","MK","Oslomej",NULL),
("MKGCYQPB0A","MK","Pehčevo",NULL),
("MKQPVZST1O","MK","Petrovec",NULL),
("MKYX09J1HY","MK","Plasnica",NULL),
("MKNEJOK7D1","MK","Podareš",NULL),
("MKJCR8NSJE","MK","Prilep",NULL),
("MKHFD98EX7","MK","Probištip",NULL),
("MKCXHWZYUM","MK","Radoviš",NULL),
("MKCDAXLOY4","MK","Resen",NULL),
("MK0QDOIX2Z","MK","Rosoman",NULL),
("MKCF9LU7S6","MK","Samokov",NULL),
("MK49248XRK","MK","Saraj",NULL),
("MKB2IWQH1R","MK","Šipkovica",NULL),
("MK7FGQCIQP","MK","Sopište",NULL),
("MKYZAS63ZB","MK","Sopotnica",NULL),
("MKC2GKZ75B","MK","Srbinovo",NULL),
("MK9O7059SC","MK","Star Dojran",NULL),
("MKO831RTQP","MK","Staravina",NULL),
("MKT1I04HCH","MK","Staro Nagoričane",NULL),
("MKJS1J07UA","MK","Štip",NULL),
("MKV2A0C3D1","MK","Struga",NULL),
("MKBH23ATT4","MK","Strumica",NULL),
("MKVB5ZTIGD","MK","Studeničani",NULL),
("MKAIWBPRLL","MK","Šuto Orizari",NULL),
("MKUWM6Z08B","MK","Sveti Nikole",NULL),
("MKHAES47XZ","MK","Tearce",NULL),
("MKJ2ZCKFPV","MK","Tetovo",NULL),
("MKYM6OES98","MK","Topolčani",NULL),
("MKPWFPWN0D","MK","Valandovo",NULL),
("MKYF63N337","MK","Vasilevo",NULL),
("MK52KQI9LG","MK","Veles",NULL),
("MKWS5BLEKA","MK","Velešta",NULL),
("MKBZZ7N0LM","MK","Vevčani",NULL),
("MKGSP4VSB1","MK","Vinica",NULL),
("MKVVRE5DU2","MK","Vitolište",NULL),
("MK5ZDREX1Q","MK","Vraneštica",NULL),
("MKX1YL1K7I","MK","Vrapčište",NULL),
("MKCXM8QY9L","MK","Vratnica",NULL),
("MKU1Z0EU2K","MK","Vrutok",NULL),
("MKUGB9ED0C","MK","Zajas",NULL),
("MKEYYGI5ZU","MK","Zelenikovo",NULL),
("MK2L3TKCEF","MK","Želino",NULL),
("MKEEFS9ID4","MK","Žitoše",NULL),
("MKZPED2EQH","MK","Zletovo",NULL),
("MKCOYVUXQX","MK","Zrnovci",NULL);