INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("MN9YSSSUQG","MN","Arhangay",NULL),
("MNMUC3KS63","MN","Bayan-Ölgiy",NULL),
("MNUHSRNWLL","MN","Bayanhongor",NULL),
("MN0ZKUWOR5","MN","Bulgan",NULL),
("MNMJYFEOV1","MN","Central Aimak",NULL),
("MNJ7530B6U","MN","Darhan Uul",NULL),
("MNSZMGV81W","MN","Dzavhan",NULL),
("MN7MQ3AI9X","MN","East Aimak",NULL),
("MN27CHV7IE","MN","East Gobi Aymag",NULL),
("MNFNIFYOAQ","MN","Govĭ-Altay",NULL),
("MNOW6J48GB","MN","Govĭ-Sumber",NULL),
("MNU6F5PO2R","MN","Hentiy",NULL),
("MNVE8RMR51","MN","Hovd",NULL),
("MNEOHCDS31","MN","Hövsgöl",NULL),
("MNOALTJ15D","MN","Middle Govĭ",NULL),
("MN8KIY9LQ4","MN","Orhon",NULL),
("MNZZVLQ1N5","MN","Selenge",NULL),
("MNP4H3XL4L","MN","South Gobi Aimak",NULL),
("MNWQFFSLT1","MN","South Hangay",NULL),
("MN5CZEXQJW","MN","Sühbaatar",NULL),
("MNPEIGG6L6","MN","Ulaanbaatar",NULL),
("MNA397OETL","MN","Uvs",NULL);