INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("MWIKCRE477","MW","Balaka",NULL),
("MWF7JM4U4Q","MW","Blantyre",NULL),
("MWI3GE21G6","MW","Chikwawa",NULL),
("MWRTXAR889","MW","Chiradzulu",NULL),
("MWSK17O8E4","MW","Chitipa",NULL),
("MWGYRKSVAB","MW","Dedza",NULL),
("MWZQP2S58K","MW","Dowa",NULL),
("MWZ6VQE307","MW","Karonga",NULL),
("MWN1ECASHQ","MW","Kasungu",NULL),
("MWQ8BJ4LV3","MW","Likoma",NULL),
("MWCK54QEPQ","MW","Lilongwe",NULL),
("MWKKHYNH5A","MW","Machinga",NULL),
("MWJJNTC4J3","MW","Mangochi",NULL),
("MWCUNHGIKT","MW","Mchinji",NULL),
("MW3QYU4NKO","MW","Mulanje",NULL),
("MW71MUJS52","MW","Mwanza",NULL),
("MWBTVOXFSA","MW","Mzimba",NULL),
("MW9FRQXCJ1","MW","Nkhata Bay",NULL),
("MW2HV64FUB","MW","Nkhotakota",NULL),
("MWHH609B2L","MW","Nsanje",NULL),
("MW4Y92D1CN","MW","Ntcheu",NULL),
("MWH4DFGWGJ","MW","Ntchisi",NULL),
("MWDBPHRKT8","MW","Phalombe",NULL),
("MW1Z9ABCVF","MW","Rumphi",NULL),
("MWA5IO7VBO","MW","Salima",NULL),
("MWZO3GKKZY","MW","Thyolo",NULL),
("MWVPFN99VA","MW","Zomba",NULL);