INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("MX85LJHHZS","MX","Acapulco","Guerrero"),
("MXMHGUDRIC","MX","Aguascalientes","Aguascalientes"),
("MXFMT06SY2","MX","Buenavista","México"),
("MXIEQRNM2W","MX","Campeche","Campeche"),
("MXRNG85G0R","MX","Cancún","Quintana Roo"),
("MXYGMB84NO","MX","Celaya","Guanajuato"),
("MXRGOY9N0R","MX","Chalco de Díaz Covarrubias","México"),
("MX2RJQDMM4","MX","Chetumal","Quintana Roo"),
("MXA2DFJD7H","MX","Chicoloapan de Juárez","México"),
("MXUTS2YFRP","MX","Chihuahua","Chihuahua"),
("MXWFN63OY5","MX","Chilpancingo","Guerrero"),
("MXFHVS3HWD","MX","Chimalhuacán","México"),
("MXK9T3N0LI","MX","Ciudad Acuña","Coahuila"),
("MXTDLRTCHP","MX","Ciudad Apodaca","Nuevo León"),
("MXR4WUTU08","MX","Ciudad Benito Juárez","Nuevo León"),
("MXCV1FDYTX","MX","Ciudad Cuauhtémoc","Chihuahua"),
("MX8M1VNMEG","MX","Ciudad de Villa de Álvarez","Colima"),
("MX0Z8TBPI3","MX","Ciudad del Carmen","Campeche"),
("MXUFYN9YWL","MX","Ciudad López Mateos","México"),
("MXTX17VV54","MX","Ciudad Madero","Tamaulipas"),
("MXI605TEMT","MX","Ciudad Nicolás Romero","México"),
("MXDUNPK6SE","MX","Ciudad Obregón","Sonora"),
("MXLR2UPYGJ","MX","Ciudad Valles","San Luis Potosí"),
("MXWHQSCVWV","MX","Ciudad Victoria","Tamaulipas"),
("MX2W0WANQO","MX","Coacalco de Berriozábal","México"),
("MXHDD2J6H4","MX","Coatzacoalcos","Veracruz"),
("MXXJZMIF6E","MX","Colima","Colima"),
("MXXW6AS25V","MX","Córdoba","Veracruz"),
("MXZ6R9THYB","MX","Cuautitlán","México"),
("MXVCEEIVJF","MX","Cuautitlán Izcalli","México"),
("MXEJ2XZ9BX","MX","Cuautla","Morelos"),
("MX6H7YKDTJ","MX","Cuernavaca","Morelos"),
("MXJLTD2SPY","MX","Culiacán","Sinaloa"),
("MX43DMYW2D","MX","Delicias","Chihuahua"),
("MXG5AFELDK","MX","Durango","Durango"),
("MX3KIOYC8I","MX","Ecatepec","State of Mexico"),
("MXX2V0UKYY","MX","Ensenada","Baja California"),
("MXNBKM8NZO","MX","Fresnillo","Zacatecas"),
("MXS946VHQZ","MX","General Escobedo","Nuevo León"),
("MX29N0LVJJ","MX","Gómez Palacio","Durango"),
("MXXEJRZHQN","MX","Guadalajara","Jalisco"),
("MXSB91Y9PQ","MX","Guadalupe","Nuevo León"),
("MXJUXECNDE","MX","Guadalupe","Zacatecas"),
("MXX1FIXZ2U","MX","Guaymas","Sonora"),
("MXELMD3D1V","MX","Hermosillo","Sonora"),
("MXOBWNKMD3","MX","Hidalgo del Parral","Chihuahua"),
("MXHBITYV8W","MX","Iguala","Guerrero"),
("MXXOFUNHP1","MX","Irapuato","Guanajuato"),
("MX2CF5PG1D","MX","Ixtapaluca","México"),
("MXRY0CLEF2","MX","Jiutepec","Morelos"),
("MXPXVOT4KQ","MX","Juárez","Chihuahua"),
("MXSZLFGAHJ","MX","La Paz","Baja California Sur"),
("MXMWPBDQP4","MX","León","Guanajuato"),
("MXPQGA5WDV","MX","Los Mochis","Sinaloa"),
("MXU9JND4E6","MX","Manzanillo","Colima"),
("MX4ZMLA34W","MX","Matamoros","Tamaulipas"),
("MXZU8CLYHA","MX","Mazatlán","Sinaloa"),
("MXPYLUVZQP","MX","Mérida","Yucatán"),
("MX8ADMERSI","MX","Mexicali","Baja California"),
("MXRF42I8YI","MX","Mexico City","Distrito Federal"),
("MX37VO6DYV","MX","Minatitlán","Veracruz"),
("MXBKQ7JGWR","MX","Miramar","Tamaulipas"),
("MXR9E517OT","MX","Monclova","Coahuila"),
("MXMSV41UN4","MX","Monterrey","Nuevo León"),
("MX2JS8WR48","MX","Morelia","Michoacán"),
("MXBVFVCBN3","MX","Naucalpan","México"),
("MXL18N8XHV","MX","Navojoa","Sonora"),
("MXQD0R7NWA","MX","Nezahualcóyotl","México"),
("MX6PI2GNBS","MX","Nogales","Sonora"),
("MXIQNU2AXO","MX","Nuevo Laredo","Tamaulipas"),
("MXC6CK3TGT","MX","Oaxaca","Oaxaca"),
("MX6GKE3HOA","MX","Ojo de Agua","México"),
("MX67DMUOFD","MX","Orizaba","Veracruz"),
("MXE27HD45P","MX","Pachuca","Hidalgo"),
("MXAIAEBQ7I","MX","Piedras Negras","Coahuila"),
("MX6SXA9MKF","MX","Playa del Carmen","Quintana Roo"),
("MXTX2OMH11","MX","Poza Rica","Veracruz"),
("MXK9IYEONO","MX","Puebla","Puebla"),
("MX6Y2IPA0W","MX","Puerto Vallarta","Jalisco"),
("MX2X6BJRRD","MX","Querétaro","Querétaro"),
("MXOU2AC4BX","MX","Reynosa","Tamaulipas"),
("MXDUVRJJGP","MX","Salamanca","Guanajuato"),
("MXHJ77T83V","MX","Saltillo","Coahuila"),
("MX597P0Z3P","MX","San Cristóbal de las Casas","Chiapas"),
("MXT5069C3M","MX","San Juan Bautista Tuxtepec","Oaxaca"),
("MX7YEQHUGZ","MX","San Juan del Río","Querétaro"),
("MXDN66WA22","MX","San Luis Potosí","San Luis Potosí"),
("MXKARL9VA3","MX","San Luis Río Colorado","Sonora"),
("MX0B9AODWV","MX","San Nicolás de los Garza","Nuevo León"),
("MXBBLT51TJ","MX","San Pablo de las Salinas","México"),
("MXP0QLASNU","MX","San Pedro Garza García","Nuevo León"),
("MX2FGCAQGB","MX","Santa Catarina","Nuevo León"),
("MX2PLQ3IMF","MX","Soledad de Graciano Sánchez","San Luis Potosí"),
("MXT78Z92IZ","MX","Tampico","Tamaulipas"),
("MX29LD1984","MX","Tapachula","Chiapas"),
("MXOOHZFXBH","MX","Tehuacán","Puebla"),
("MXNW8QFU58","MX","Tepexpan","México"),
("MX2E8BHRAJ","MX","Tepic","Nayarit"),
("MX0WX2557U","MX","Texcoco","México"),
("MXTOU8M5Q9","MX","Tijuana","Baja California"),
("MX2Y0HS6QU","MX","Tlalnepantla","México"),
("MXLY62PHMP","MX","Tlaquepaque","Jalisco"),
("MXDJSIOZCI","MX","Toluca","México"),
("MXN6RACHJE","MX","Tonalá","Jalisco"),
("MXFKW8QM2C","MX","Torreón","Coahuila"),
("MXK8EAQ103","MX","Tulancingo","Hidalgo"),
("MXKSL9RYSF","MX","Tuxtla Gutiérrez","Chiapas"),
("MX5JPH09WF","MX","Uruapan","Michoacán"),
("MXTSOKEQWZ","MX","Veracruz","Veracruz"),
("MXZB9PC9TX","MX","Veracruz, Boca del Río Municipality","Veracruz"),
("MX2F7UDZ9J","MX","Villahermosa","Tabasco"),
("MXJZ0J8XZ2","MX","Xalapa","Veracruz"),
("MXPNN3EK2E","MX","Xico","México"),
("MXVC48MX6O","MX","Zacatecas","Zacatecas"),
("MXCEIQDSAX","MX","Zamora","Michoacán"),
("MXRBG08G3X","MX","Zapopan","Jalisco");