INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("MY4Q0IA3W6","MY","Federal Territory of Labuan",NULL),
("MYF0E1XLQA","MY","Johor",NULL),
("MYZ91D1BAT","MY","Kedah",NULL),
("MYMRTU7WSB","MY","Kelantan",NULL),
("MYNSTXWQ3B","MY","Kuala Lumpur",NULL),
("MYQIDO34Z2","MY","Melaka",NULL),
("MYD1FFCP8Z","MY","Negeri Sembilan",NULL),
("MYH2UOYMZM","MY","Pahang",NULL),
("MYFTJBJNNA","MY","Perak",NULL),
("MY51Z96YBK","MY","Perlis",NULL),
("MYZRZCH8CY","MY","Pulau Pinang",NULL),
("MYA7N9TMV9","MY","Putrajaya",NULL),
("MYGEL028B7","MY","Sabah",NULL),
("MYAAHH9T19","MY","Sarawak",NULL),
("MYK0L28Y1J","MY","Selangor",NULL),
("MY5OSZBN8R","MY","Terengganu",NULL);