INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("NA0ZFWAQFF","NA","Bethanien",NULL),
("NADOIN1XGC","NA","Caprivi",NULL),
("NABDHMNDAK","NA","Caprivi Oos",NULL),
("NA5SFGS7RT","NA","Erongo",NULL),
("NA77PHY4WB","NA","Hardap",NULL),
("NATEZUBF7N","NA","Kaokoland",NULL),
("NATP9H2K27","NA","Karas",NULL),
("NADHO5PFYW","NA","Kavango",NULL),
("NANNDLSAXL","NA","Khomas",NULL),
("NAOWF0CNO5","NA","Kunene",NULL),
("NACYNEIPMW","NA","Ohangwena",NULL),
("NA7A1WQZTD","NA","Okavango",NULL),
("NAN7ZFHX16","NA","Omaheke",NULL),
("NATH764WCG","NA","Omusati",NULL),
("NAUZVDPI9X","NA","Oshana",NULL),
("NATBUJBNXY","NA","Oshikoto",NULL),
("NAVXECUGJO","NA","Otjiwarongo",NULL),
("NAXQU1N6IH","NA","Otjozondjupa",NULL),
("NA6EVWW5TP","NA","Outjo",NULL),
("NAGO9RB6P7","NA","Owambo",NULL);