INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("NGP62GXCOK","NG","Abia",NULL),
("NGE971X9XW","NG","Abuja Federal Capital Territory",NULL),
("NGKFFSQJ2D","NG","Adamawa",NULL),
("NGAYG80TWQ","NG","Akwa Ibom",NULL),
("NGZZ7XCVIQ","NG","Anambra",NULL),
("NG5PR2ZPZJ","NG","Bauchi",NULL),
("NG5ECVYE98","NG","Bayelsa",NULL),
("NGCPHDIE3I","NG","Benue",NULL),
("NGDAGP6ZGB","NG","Borno",NULL),
("NGO8DOXD83","NG","Cross River",NULL),
("NGSKZQY8ZB","NG","Delta",NULL),
("NGXGOGURZ8","NG","Ebonyi",NULL),
("NG2GY8FEJ4","NG","Edo",NULL),
("NGMXSKA0O2","NG","Ekiti",NULL),
("NGLNTJWSVU","NG","Enugu",NULL),
("NG9KB3BACE","NG","Gombe",NULL),
("NGQAM6O5AB","NG","Imo",NULL),
("NG32WE3KGO","NG","Jigawa",NULL),
("NG8A8434ZC","NG","Kaduna",NULL),
("NGOAG0KSEB","NG","Kano",NULL),
("NG20IQ5S29","NG","Katsina",NULL),
("NGVYNZI4OQ","NG","Kebbi",NULL),
("NGEWVH1UTP","NG","Kogi",NULL),
("NG5APQ2314","NG","Kwara",NULL),
("NG4JVACXJ7","NG","Lagos",NULL),
("NGV66EAU5O","NG","Nassarawa",NULL),
("NGR06SV0I0","NG","Niger",NULL),
("NGA7QCBSGG","NG","Ogun",NULL),
("NGCCQP99W5","NG","Ondo",NULL),
("NGG3JQYPFP","NG","Osun",NULL),
("NGQMILM0MW","NG","Oyo",NULL),
("NG8D9K6Q0J","NG","Plateau",NULL),
("NG2Q8C05IH","NG","Rivers",NULL),
("NG8277RNWH","NG","Sokoto",NULL),
("NG9F3WFPTO","NG","Taraba",NULL),
("NG328AT8TV","NG","Yobe",NULL),
("NGZ28Z7QHG","NG","Zamfara",NULL);