INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("NO46D04XHN","NO","Akershus",NULL),
("NOI4D2T7V4","NO","Aust-Agder",NULL),
("NO6JTZH79C","NO","Buskerud",NULL),
("NOX9PDJ2VN","NO","Finnmark",NULL),
("NO98OE651O","NO","Hedmark",NULL),
("NOAFR4NN9U","NO","Hordaland",NULL),
("NO63TNA208","NO","Møre og Romsdal",NULL),
("NOCQMWTHJ2","NO","Nord-Trøndelag",NULL),
("NOQ8HXEIMP","NO","Nordland",NULL),
("NOYDTL03G6","NO","Oppland",NULL),
("NO79UHCVQP","NO","Oslo county",NULL),
("NOMCLFU4IK","NO","Østfold",NULL),
("NODZHRI4GH","NO","Rogaland",NULL),
("NOHA3IDJOL","NO","Sogn og Fjordane",NULL),
("NOSJ25FTU1","NO","Sør-Trøndelag",NULL),
("NO5FHZKZKX","NO","Svalbard",NULL),
("NOZ2PI66ZO","NO","Telemark",NULL),
("NOG26ULVFE","NO","Troms",NULL),
("NOEIKTBEVH","NO","Vest-Agder",NULL),
("NOUCGEC0CC","NO","Vestfold",NULL);