INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("PEDNE1SWFS","PE","Amazonas",NULL),
("PEBTKQLO13","PE","Ancash",NULL),
("PEUZZ2OGU3","PE","Apurímac",NULL),
("PEWNR6L3FY","PE","Arequipa",NULL),
("PERU0JRFB2","PE","Ayacucho",NULL),
("PE9WTULUYF","PE","Cajamarca",NULL),
("PEUYIJECMB","PE","Callao",NULL),
("PE0EHLIXK9","PE","Cusco",NULL),
("PESKTJ05M9","PE","Huancavelica",NULL),
("PE1F4NA324","PE","Huanuco",NULL),
("PE1KOGXARX","PE","Ica",NULL),
("PEO9J674GZ","PE","Junín",NULL),
("PEO9IPE4ZG","PE","La Libertad",NULL),
("PEJ43U76Z9","PE","Lambayeque",NULL),
("PERNPOYGMM","PE","Lima",NULL),
("PEP6TWAAVZ","PE","Loreto",NULL),
("PEKEPYJPF3","PE","Madre de Dios",NULL),
("PETJX1PWAG","PE","Moquegua",NULL),
("PEJZ5HFS45","PE","Pasco",NULL),
("PEYY299Y8T","PE","Piura",NULL),
("PECXRVM7YG","PE","Provincia de Lima",NULL),
("PEQVHGSRWC","PE","Puno",NULL),
("PEQ2U6UZCT","PE","San Martín",NULL),
("PEXE26CBZP","PE","Tacna",NULL),
("PE9RLWZJCP","PE","Tumbes",NULL),
("PEFU58M2KD","PE","Ucayali",NULL);