INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("PHQWU20ZBF","PH","Abra",NULL),
("PHRLPHCOTN","PH","Agusan del Norte",NULL),
("PH1QF2QDQX","PH","Agusan del Sur",NULL),
("PHPGFF0ONR","PH","Aklan",NULL),
("PHKHTKH508","PH","Albay",NULL),
("PHRPP3EJRG","PH","Angeles",NULL),
("PH97I0K9YA","PH","Antique",NULL),
("PHPEQP2DHM","PH","Apayao",NULL),
("PHVB7CG7K7","PH","Aurora",NULL),
("PHXAACT1S3","PH","Bacolod City",NULL),
("PH9B4TK249","PH","Baguio",NULL),
("PHHUZJ7H53","PH","Basilan",NULL),
("PHSCF8KZGH","PH","Bataan",NULL),
("PHART3SM71","PH","Batanes",NULL),
("PHXBVHEZRV","PH","Batangas",NULL),
("PHURE28K51","PH","Benguet",NULL),
("PHXKAHKQZU","PH","Biliran",NULL),
("PHHTYAF6CC","PH","Bohol",NULL),
("PHI7UW7MS1","PH","Bukidnon",NULL),
("PHD74MS9OP","PH","Bulacan",NULL),
("PHTY7DO685","PH","Butuan",NULL),
("PHZ7GFDSSV","PH","Cagayan",NULL),
("PH0MS79L9N","PH","Cagayan de Oro",NULL),
("PHTD9LMYBG","PH","Caloocan",NULL),
("PHWIUKP2QP","PH","Camarines Norte",NULL),
("PHA64OZWKZ","PH","Camarines Sur",NULL),
("PHJD6SYGGS","PH","Camiguin",NULL),
("PHUQDGOPWK","PH","Capiz",NULL),
("PH7R5WUVM4","PH","Catanduanes",NULL),
("PH2QT1ND07","PH","Cavite",NULL),
("PHQ70POGII","PH","Cebu",NULL),
("PH6WYULVFS","PH","Cebu City",NULL),
("PHMKPHGCLI","PH","Compostela Valley",NULL),
("PH2FKQSKXJ","PH","Cotabato",NULL),
("PHSY9GERYL","PH","Cotabato City",NULL),
("PHNXG8SV1F","PH","Dagupan",NULL),
("PHFRWV3IE6","PH","Davao",NULL),
("PHXYWQJU9B","PH","Davao del Norte",NULL),
("PHSIR79QSX","PH","Davao del Sur",NULL),
("PHN85G47VK","PH","Davao Oriental",NULL),
("PHYSG1BU89","PH","Eastern Samar",NULL),
("PHS5ZCZ9NS","PH","General Santos",NULL),
("PHSF025TZT","PH","Guimaras",NULL),
("PH2596C5QA","PH","Ifugao",NULL),
("PHY6CA1LJU","PH","Iligan",NULL),
("PHQJ6QTTIL","PH","Ilocos Norte",NULL),
("PH9JNFCN8E","PH","Ilocos Sur",NULL),
("PHSIK5OBGM","PH","Iloilo",NULL),
("PHHSWIDGC4","PH","Iloilo City",NULL),
("PHZJUSDDEM","PH","Isabela",NULL),
("PHW228PBMI","PH","Kalinga",NULL),
("PHT7NHI340","PH","La Union",NULL),
("PHW0JAHWEG","PH","Laguna",NULL),
("PHF89SMOFI","PH","Lanao del Norte",NULL),
("PHQHQGTDYN","PH","Lanao del Sur",NULL),
("PHLM53Q94M","PH","Lapu-Lapu",NULL),
("PHANXRKB8Z","PH","Las Piñas",NULL),
("PHKIS667PX","PH","Leyte",NULL),
("PHPGDITC5E","PH","Lucena",NULL),
("PHYAIPKNBU","PH","Maguindanao",NULL),
("PHA9MULVU5","PH","Makati City",NULL),
("PHDMCKT1HJ","PH","Malabon",NULL),
("PHHU1B77Q6","PH","Mandaluyong City",NULL),
("PHH9V1W7W6","PH","Mandaue",NULL),
("PHGI11EV7R","PH","Manila",NULL),
("PHIJBCLTV3","PH","Marikina",NULL),
("PHOWEV351L","PH","Marinduque",NULL),
("PHEWNA4JHK","PH","Masbate",NULL),
("PH2IMGET8W","PH","Misamis Occidental",NULL),
("PHDJ9ZD421","PH","Misamis Oriental",NULL),
("PH0HW4MYP0","PH","Mountain Province",NULL),
("PHUCBZWSJY","PH","Muntinlupa",NULL),
("PHB6FQZNND","PH","Naga",NULL),
("PH7WCK0EL0","PH","Navotas",NULL),
("PHWI5IGUJB","PH","Negros Occidental",NULL),
("PH6UA3NU1Y","PH","Negros Oriental",NULL),
("PH0HO04BEC","PH","Northern Samar",NULL),
("PH7QW85I81","PH","Nueva Ecija",NULL),
("PH1EKH83TF","PH","Nueva Vizcaya",NULL),
("PHY4IMYKLZ","PH","Occidental Mindoro",NULL),
("PH1906LEIT","PH","Olongapo",NULL),
("PH5E1AXACY","PH","Oriental Mindoro",NULL),
("PHOWGX09CZ","PH","Ormoc",NULL),
("PHDVLCF6CH","PH","Palawan",NULL),
("PHGCN2R5WW","PH","Pampanga",NULL),
("PHKX7H8JGX","PH","Pangasinan",NULL),
("PHGWVG67GK","PH","Parañaque",NULL),
("PH31WJ880P","PH","Pasay",NULL),
("PHLORDTOAD","PH","Pasig",NULL),
("PHMHVU1CSH","PH","Pateros",NULL),
("PH8NYFVEZZ","PH","Puerto Princesa",NULL),
("PHGWIO5JER","PH","Quezon",NULL),
("PH7640UEEG","PH","Quezon City",NULL),
("PHWAAYM3GV","PH","Quirino",NULL),
("PHQEAMTAL9","PH","Rizal",NULL),
("PH63YBMC2U","PH","Romblon",NULL),
("PHI7UDL9TI","PH","Samar",NULL),
("PHJ4G57W1Y","PH","San Juan",NULL),
("PHBBL4L6DS","PH","Santiago",NULL),
("PHAC4XP7R8","PH","Sarangani",NULL),
("PHEML0VEIF","PH","Siquijor",NULL),
("PHJZLQWMP7","PH","Sorsogon",NULL),
("PHYABKHPCR","PH","South Cotabato",NULL),
("PH1HOROFZ2","PH","Southern Leyte",NULL),
("PH2K3YZMDI","PH","Sultan Kudarat",NULL),
("PHLZ9HLZPJ","PH","Sulu",NULL),
("PHA03RQGIS","PH","Surigao del Norte",NULL),
("PHX7JMNIPP","PH","Surigao del Sur",NULL),
("PH3SN2E1L0","PH","Tacloban",NULL),
("PH0VILU754","PH","Taguig",NULL),
("PH89VYQERO","PH","Tarlac",NULL),
("PHLAA8TZYX","PH","Tawi-Tawi",NULL),
("PHSL06NL7N","PH","Valenzuela",NULL),
("PHGP9BWEF5","PH","Zambales",NULL),
("PHOB3EPV2B","PH","Zamboanga City",NULL),
("PH5CJZCIW4","PH","Zamboanga del Norte",NULL),
("PH3WBRHIEY","PH","Zamboanga del Sur",NULL),
("PH7N942P9Q","PH","Zamboanga Sibugay",NULL);