INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("PY8OY8PWC3","PY","Alto Paraná",NULL),
("PYOLXIAWPF","PY","Amambay",NULL),
("PYMCJ0DTKP","PY","Asunción",NULL),
("PYGN2NRLSZ","PY","Boquerón",NULL),
("PY9R8ZNK2C","PY","Caaguazú",NULL),
("PY5ZUGWKVJ","PY","Caazapá",NULL),
("PYWFKA84ZP","PY","Canindeyú",NULL),
("PYS2DKN5KX","PY","Central",NULL),
("PYXSWKCYWI","PY","Concepción",NULL),
("PYYRZUBUE7","PY","Cordillera",NULL),
("PY9YHI3H7W","PY","Departamento de Alto Paraguay",NULL),
("PYJKG7Q04N","PY","Guairá",NULL),
("PYT085Z5OX","PY","Itapúa",NULL),
("PYWNS7I6FR","PY","Misiones",NULL),
("PY5WA8EI4X","PY","Ñeembucú",NULL),
("PY3K5TL9HE","PY","Paraguarí",NULL),
("PY9PK8U96R","PY","Presidente Hayes",NULL),
("PYWYYE5E6A","PY","San Pedro",NULL);