INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("RUPWHIH6QJ","RU","Adygeya",NULL),
("RU1JRQ9Q7B","RU","Altay",NULL),
("RUH78HCSPK","RU","Altayskiy Kray",NULL),
("RU1QVNIN87","RU","Amur",NULL),
("RUKPP2WGLX","RU","Arkhangelskaya oblast",NULL),
("RU0DN94VLL","RU","Astrakhan",NULL),
("RU3T3FMT0N","RU","Bashkortostan",NULL),
("RUJWB1KJ84","RU","Belgorod",NULL),
("RU9Y75ES2E","RU","Brjansk",NULL),
("RU6QNAM8WP","RU","Buryatiya",NULL),
("RU205OU6CD","RU","Chechnya",NULL),
("RU2NEM7NQH","RU","Chukotskiy Avtonomnyy Okrug",NULL),
("RULXM0QPFX","RU","Chuvashia",NULL),
("RUF372B4SE","RU","Dagestan",NULL),
("RU5Y2Z4FD6","RU","Ingushetiya",NULL),
("RU3SSBFJS1","RU","Irkutsk",NULL),
("RUHE273H4J","RU","Ivanovo",NULL),
("RUKCMWHEAN","RU","Jaroslavl",NULL),
("RUCDNGS0MV","RU","Jewish Autonomous Oblast",NULL),
("RUSE68XYAE","RU","Kabardino-Balkariya",NULL),
("RUDCMHTR0E","RU","Kaliningrad",NULL),
("RU4MAL1L9D","RU","Kalmykiya",NULL),
("RUYWTRWGNP","RU","Kaluga",NULL),
("RUUUYSS876","RU","Kamtsjatka",NULL),
("RULUNELOTQ","RU","Karachayevo-Cherkesiya",NULL),
("RUB3CCOLQN","RU","Kareliya",NULL),
("RUHJEE014U","RU","Kemerovo",NULL),
("RUV2NOAUVV","RU","Khabarovsk Krai",NULL),
("RUOJAA730J","RU","Khakasiya",NULL),
("RU7CWWXMJF","RU","Khanty-Mansiyskiy Avtonomnyy Okrug",NULL),
("RU6YU60Y1W","RU","Kirov",NULL),
("RU0OKBIG67","RU","Komi",NULL),
("RUZHH6LIQS","RU","Kostroma",NULL),
("RUVMOS888F","RU","Krasnodarskiy Kray",NULL),
("RU62L60M21","RU","Krasnoyarskiy Kray",NULL),
("RUANCT3J12","RU","Kurgan",NULL),
("RU0J9L10EW","RU","Kursk",NULL),
("RUM2PVAYAG","RU","Leningradskaya Oblastʼ",NULL),
("RU0VN1IP2T","RU","Lipetsk",NULL),
("RUCFMGYNJY","RU","Magadan",NULL),
("RU6TK8TY4F","RU","Mariy-El",NULL),
("RU1UBCSLTT","RU","Mordoviya",NULL),
("RUHGVZ5YSI","RU","Moscow",NULL),
("RUDFYB3HAA","RU","Moskovskaya Oblastʼ",NULL),
("RUAVI4UNJV","RU","Murmansk Oblast",NULL),
("RUHU7AG04X","RU","Nenetskiy Avtonomnyy Okrug",NULL),
("RUHZXMXQ5A","RU","Nizjnij Novgorod",NULL),
("RU53M8LXIW","RU","Novgorod",NULL),
("RUT10NOKI6","RU","Novosibirsk",NULL),
("RUFQHVRLT8","RU","Omsk",NULL),
("RULQVIG0TM","RU","Orenburg",NULL),
("RU4GUQDDM6","RU","Orjol",NULL),
("RUFNU37DAM","RU","Penza",NULL),
("RU4RIVCB4X","RU","Perm",NULL),
("RU10GI1946","RU","Primorskiy Kray",NULL),
("RUQZW4DJBS","RU","Pskov",NULL),
("RU75VEI51M","RU","Rjazan",NULL),
("RUXKI9VN7X","RU","Rostov",NULL),
("RUNNFOXKUO","RU","RSJA",NULL),
("RUJRSWB3OI","RU","Sakha",NULL),
("RU9KXSQYEN","RU","Sakhalin",NULL),
("RUJXWEK4C7","RU","Samara",NULL),
("RUSRWQBREV","RU","Sankt-Peterburg",NULL),
("RUI7RUBGCK","RU","Saratov",NULL),
("RU19CR8RER","RU","Severnaya Osetiya-Alaniya",NULL),
("RUOB58GHG8","RU","Smolensk",NULL),
("RU9CYL4DGN","RU","Stavropolʼskiy Kray",NULL),
("RUL8HWOTHQ","RU","Sverdlovsk",NULL),
("RU2THALV19","RU","Tambov",NULL),
("RU77INPYVY","RU","Tatarstan",NULL),
("RUBUKF802T","RU","Tjumen",NULL),
("RU9JQYC7OF","RU","Tomsk",NULL),
("RU05QL1RV8","RU","Tsjeljabinsk",NULL),
("RUZDVOBRNM","RU","Tula",NULL),
("RUM81U94OI","RU","Tverskaya Oblast’",NULL),
("RUNEG0L4GM","RU","Tyva",NULL),
("RUA68BY4KY","RU","Udmurtiya",NULL),
("RUHFNT7BFT","RU","Uljanovsk",NULL),
("RUJHOSMDAA","RU","Vladimir",NULL),
("RUSQBEVR05","RU","Volgograd",NULL),
("RUY9HWD1UV","RU","Vologda",NULL),
("RUHHOOS4IC","RU","Voronezj",NULL),
("RUL748LEID","RU","Yamalo-Nenetskiy Avtonomnyy Okrug",NULL),
("RU5TR1KS7J","RU","Zabaïkalski Kray",NULL);