INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("SD929R2Z90","SD","Al Jazirah",NULL),
("SDFGXFPVBB","SD","Al Qadarif",NULL),
("SDH595XYKC","SD","Al Wilāyah al Istiwāʼīyah",NULL),
("SDRLGDMAKV","SD","Al Wilāyah al Wusţá",NULL),
("SDDUNGTXG8","SD","Al Wilāyah ash Sharqīyah",NULL),
("SDDDO290DQ","SD","Ash Shamaliyah",NULL),
("SD5NW3MGFE","SD","Ba?r al Ghazal Wilayat",NULL),
("SD2VRP6CKJ","SD","Blue Nile",NULL),
("SD68ZZ5G7J","SD","Central Equatoria",NULL),
("SDUWM3WZU1","SD","Darfur Wilayat",NULL),
("SDNQ497KNA","SD","Eastern Equatoria",NULL),
("SDFFZMRJ5X","SD","Gharb al Istiwāʼīyah",NULL),
("SDS5XYL4HF","SD","Gharb Dārfūr",NULL),
("SD03JX3DYQ","SD","Gharb Kurdufān",NULL),
("SD430CONM3","SD","Janūb Dārfūr",NULL),
("SD3LPU5VRX","SD","Janūb Kurdufān",NULL),
("SD0OWLTD1U","SD","Junqalī",NULL),
("SDHKRLYQC2","SD","Kassalā",NULL),
("SDUCFI01M3","SD","Khartoum",NULL),
("SDMCXS7PQ8","SD","Kurdufan Wilayat",NULL),
("SDEMT80V3H","SD","Lakes",NULL),
("SDFV2DLEGG","SD","Nahr an Nīl",NULL),
("SDRVZRXLVK","SD","Northern",NULL),
("SDXSC5I3DW","SD","Red Sea",NULL),
("SDP75P287H","SD","Shamāl Baḩr al Ghazāl",NULL),
("SD3AVPPC5G","SD","Shamāl Dārfūr",NULL),
("SD8485Q3PO","SD","Shamāl Kurdufān",NULL),
("SDW2TE57BU","SD","Sinnār",NULL),
("SDEGKHPSYS","SD","Unity",NULL),
("SD2UIS7N9F","SD","Upper Nile",NULL),
("SDSHKIKA6G","SD","Warab",NULL),
("SDC0VI87DM","SD","Western Bahr al Ghazal",NULL),
("SDNX3DQ26T","SD","White Nile",NULL);