INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("SEXOL4CUJ4","SE","Blekinge",NULL),
("SEC4NWFUDS","SE","Dalarna",NULL),
("SEV9A3GNP4","SE","Gävleborg",NULL),
("SELTHBWO4T","SE","Gotland",NULL),
("SECQYOLITX","SE","Halland",NULL),
("SENHU2B7U6","SE","Jämtland",NULL),
("SEH49XSZ1D","SE","Jönköping",NULL),
("SETJPP7UJK","SE","Kalmar",NULL),
("SEKH96Z23M","SE","Kronoberg",NULL),
("SEJXPV5J1M","SE","Norrbotten",NULL),
("SEOBKGAMU3","SE","Örebro",NULL),
("SE6JTDDCYY","SE","Östergötland",NULL),
("SET74TA8GU","SE","Skåne",NULL),
("SE55PBPRYE","SE","Södermanland",NULL),
("SE2IUD4PHA","SE","Stockholm",NULL),
("SE8AOMMMKG","SE","Uppsala",NULL),
("SEUPA4XQY3","SE","Värmland",NULL),
("SEWOEMFC0H","SE","Västerbotten",NULL),
("SEVVV0KCAT","SE","Västernorrland",NULL),
("SENZFAM0RG","SE","Västmanland",NULL),
("SEQ1LNSKQO","SE","Västra Götaland",NULL);