INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("SOTJVAW3I6","SO","Awdal",NULL),
("SOCLSA8V66","SO","Bakool",NULL),
("SOBU4MNA1U","SO","Banaadir",NULL),
("SOLYWN3P2W","SO","Bari",NULL),
("SO8Y741QBE","SO","Bay",NULL),
("SOB4OJZVQB","SO","Galguduud",NULL),
("SOPUXC5Z7Q","SO","Gedo",NULL),
("SOX4E1THY1","SO","Hiiraan",NULL),
("SOF56HWHV7","SO","Lower Juba",NULL),
("SOLKRLFHW4","SO","Middle Juba",NULL),
("SOCUHITP9R","SO","Middle Shabele",NULL),
("SOTNSN5ROK","SO","Mudug",NULL),
("SOXV1TCX0Y","SO","Nugaal",NULL),
("SOHRKW9G1M","SO","Sanaag",NULL),
("SOBJ448DW2","SO","Shabeellaha Hoose",NULL),
("SO0PP6GDQD","SO","Sool",NULL),
("SO8S7LQ7K7","SO","Togdheer",NULL),
("SOZ449L6VW","SO","Woqooyi Galbeed",NULL);