INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("SV8W6ABO12","SV","Ahuachapán",NULL),
("SV2JGU3LPO","SV","Cabañas",NULL),
("SV9LPHEVHC","SV","Chalatenango",NULL),
("SVBIF7OPOW","SV","Cuscatlán",NULL),
("SVMU7YJ90L","SV","La Libertad",NULL),
("SVSHGW35KC","SV","La Paz",NULL),
("SVRAU66BIH","SV","La Unión",NULL),
("SVUXOINCFA","SV","Morazán",NULL),
("SV7M8RW9DP","SV","San Miguel",NULL),
("SVRTLUZ66Q","SV","San Salvador",NULL),
("SVH1XNCF56","SV","San Vicente",NULL),
("SVDTO163CE","SV","Santa Ana",NULL),
("SVQL5NUICM","SV","Sonsonate",NULL),
("SVBYGB4N2M","SV","Usulután",NULL);