INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("TNO9V0AWOO","TN","Al Mahdīyah",NULL),
("TN5MYJ6WCH","TN","Al Munastīr",NULL),
("TNQI9SVIB5","TN","Al Qaşrayn",NULL),
("TNTS2GQYXE","TN","Al Qayrawān",NULL),
("TN8TFIQ37W","TN","Ariana",NULL),
("TNQ6FX2SFT","TN","Bājah",NULL),
("TNAPL67XC1","TN","Banzart",NULL),
("TNPFHFDFUM","TN","Bin ‘Arūs",NULL),
("TN9940DCW4","TN","Jundūbah",NULL),
("TNIC1L4GEE","TN","Kef",NULL),
("TN5ZLDWXFM","TN","Madanīn",NULL),
("TNCW1QCWCM","TN","Manouba",NULL),
("TN5HMITIMC","TN","Nābul",NULL),
("TNUOXZ4CEA","TN","Qābis",NULL),
("TNBZO8X3VA","TN","Qafşah",NULL),
("TN0X0DTDZY","TN","Qibilī",NULL),
("TNVLHP441Z","TN","Şafāqis",NULL),
("TNSZYXBC8N","TN","Sīdī Bū Zayd",NULL),
("TNCXW90RJ1","TN","Silyānah",NULL),
("TNOKEHYEGT","TN","Sūsah",NULL),
("TN0XJ42L4V","TN","Taţāwīn",NULL),
("TNK2TVF2JR","TN","Tawzar",NULL),
("TNZF107L1V","TN","Tūnis",NULL),
("TN6GD4UTYU","TN","Tunis al Janubiyah Wilayat",NULL),
("TNRHYU23PN","TN","Zaghwān",NULL);