INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("TZSVYNS4PT","TZ","Arusha",NULL),
("TZYISQWWF3","TZ","Dar es Salaam",NULL),
("TZH5WRUT07","TZ","Dodoma",NULL),
("TZN8JCC095","TZ","Iringa",NULL),
("TZV7SOBIHA","TZ","Kagera",NULL),
("TZ0A0W6GZO","TZ","Kigoma",NULL),
("TZMWFGPFND","TZ","Kilimanjaro",NULL),
("TZO6P17Y63","TZ","Lindi",NULL),
("TZ6YRHG9SG","TZ","Manyara",NULL),
("TZJTCPACEW","TZ","Mara",NULL),
("TZ8TCY90BX","TZ","Mbeya",NULL),
("TZ70YEZ4H5","TZ","Morogoro",NULL),
("TZ39NKIF01","TZ","Mtwara",NULL),
("TZ9DRJQ5FY","TZ","Mwanza",NULL),
("TZZSW8S860","TZ","Pemba North",NULL),
("TZ94E89WDD","TZ","Pemba South",NULL),
("TZ60XOGYQP","TZ","Pwani",NULL),
("TZCI82OO1N","TZ","Rukwa",NULL),
("TZGYV9629F","TZ","Ruvuma",NULL),
("TZ7ONGL1UR","TZ","Shinyanga",NULL),
("TZ1RGIQ672","TZ","Singida",NULL),
("TZPG5D460L","TZ","Tabora",NULL),
("TZ4WUAY4Q5","TZ","Tanga",NULL),
("TZSDMDFG5G","TZ","Zanzibar Central/South",NULL),
("TZ8LZYS60H","TZ","Zanzibar North",NULL),
("TZN5URBUDG","TZ","Zanzibar Urban/West",NULL);