INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("UAR7QPCGV4","UA","Avtonomna Respublika Krym",NULL),
("UAUHI9XNQ5","UA","Cherkasʼka Oblastʼ",NULL),
("UA9P41W4IK","UA","Chernihivsʼka Oblastʼ",NULL),
("UAACCM7P2Y","UA","Chernivetsʼka Oblastʼ",NULL),
("UAXSO99JE4","UA","Dnipropetrovsʼka Oblastʼ",NULL),
("UA0XEYL44U","UA","Donetsʼka Oblastʼ",NULL),
("UAU8VRDDBN","UA","Ivano-Frankivsʼka Oblastʼ",NULL),
("UAQNAXCCWA","UA","Kharkivsʼka Oblastʼ",NULL),
("UA5KJF3XJ4","UA","Kherson Oblast",NULL),
("UAVX3G28AX","UA","Khmelʼnytsʼka Oblastʼ",NULL),
("UAH5OUJ0IA","UA","Kiev Oblast",NULL),
("UANS8054AA","UA","Kirovohradsʼka Oblastʼ",NULL),
("UAOTPSR9XM","UA","Luhansʼka Oblastʼ",NULL),
("UA70299D6Q","UA","Lʼvivsʼka Oblastʼ",NULL),
("UAJVL3V3DI","UA","Misto Kyyiv",NULL),
("UAWLJ1QTCE","UA","Misto Sevastopol",NULL),
("UAN27FB52I","UA","Mykolayivsʼka Oblastʼ",NULL),
("UA55SEIY52","UA","Odessa Oblast",NULL),
("UATQ5PUI7Q","UA","Poltava Oblast",NULL),
("UA4RSUL599","UA","Rivnensʼka Oblastʼ",NULL),
("UA7GOJLR1R","UA","Sumy Oblast",NULL),
("UAWU6FSBHM","UA","Ternopilʼsʼka Oblastʼ",NULL),
("UA2NBW5JMA","UA","Vinnytsʼka Oblastʼ",NULL),
("UABF4WKD5S","UA","Volynsʼka Oblastʼ",NULL),
("UAUUBGLD8I","UA","Zakarpatsʼka Oblastʼ",NULL),
("UA7FYZRGMT","UA","Zaporizʼka Oblastʼ",NULL),
("UA3YP9ICJT","UA","Zhytomyrsʼka Oblastʼ",NULL);