INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("UYKLAWR9YM","UY","Artigas Department",NULL),
("UYW0MCD5BR","UY","Canelones Department",NULL),
("UY94YX12X6","UY","Cerro Largo Department",NULL),
("UYLP0I8UCT","UY","Colonia Department",NULL),
("UYFMP7VOTR","UY","Durazno",NULL),
("UYOG42MFUV","UY","Flores",NULL),
("UYKSSMUQSG","UY","Florida Department",NULL),
("UYFTZONBH3","UY","Lavalleja Department",NULL),
("UYY7ATW4LK","UY","Maldonado Department",NULL),
("UYLQN76H3Q","UY","Montevideo",NULL),
("UYAWC5M5L2","UY","Paysandú",NULL),
("UYZLQMW8QU","UY","Río Negro",NULL),
("UYF1OB69WR","UY","Rivera",NULL),
("UY0JZ613WB","UY","Rocha",NULL),
("UYZ9GLF2NE","UY","Salto",NULL),
("UYNE1KMRF2","UY","San José",NULL),
("UYS3EYDBQD","UY","Soriano Department",NULL),
("UYVQJWTG7S","UY","Tacuarembó",NULL),
("UYQOE5R2JE","UY","Treinta y Tres",NULL);