INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("XKDB3UYN6W","XK","Komuna e Deçanit",NULL),
("XKGHT6L0B8","XK","Komuna e Dragashit",NULL),
("XKI2H10I9F","XK","Komuna e Drenasit",NULL),
("XKF1QAK2PY","XK","Komuna e Ferizajt",NULL),
("XKESSCFZ9W","XK","Komuna e Fushë Kosovës",NULL),
("XKH3223EAM","XK","Komuna e Gjakovës",NULL),
("XKGSNHAWWP","XK","Komuna e Gjilanit",NULL),
("XKYN0IPQH4","XK","Komuna e Istogut",NULL),
("XKI9GY9QUQ","XK","Komuna e Kaçanikut",NULL),
("XKTXSWB3IS","XK","Komuna e Kamenicës",NULL),
("XKV59626W1","XK","Komuna e Klinës",NULL),
("XKTXKJN1N5","XK","Komuna e Leposaviqit",NULL),
("XKB33KTYAN","XK","Komuna e Lipjanit",NULL),
("XKV2J761Z1","XK","Komuna e Malisheves",NULL),
("XK798AF4B9","XK","Komuna e Mitrovicës",NULL),
("XK1VSOWFT8","XK","Komuna e Novobërdës",NULL),
("XKJXSDW20R","XK","Komuna e Obiliqit",NULL),
("XK5JZBLZDT","XK","Komuna e Pejës",NULL),
("XK8L3OPFXQ","XK","Komuna e Podujevës",NULL),
("XKBQF769GP","XK","Komuna e Prishtinës",NULL),
("XK6833B3VG","XK","Komuna e Prizrenit",NULL),
("XKNUS9T621","XK","Komuna e Rahovecit",NULL),
("XKR6QHMO8X","XK","Komuna e Shtërpcës",NULL),
("XKEN5KWLA3","XK","Komuna e Shtimes",NULL),
("XKTD64H1L4","XK","Komuna e Skenderajt",NULL),
("XKWDDPJGRB","XK","Komuna e Thërandës",NULL),
("XKNHS9606K","XK","Komuna e Vitisë",NULL),
("XKOB5LXFPQ","XK","Komuna e Vushtrrisë",NULL),
("XKTVUAXGFU","XK","Komuna e Zubin Potokut",NULL),
("XKTTJD9BOX","XK","Komuna e Zveçanit",NULL);