INSERT INTO `city` (`uid`,`country_code`,`name`,`state`) VALUES
("YETH6ZIDK6","YE","‘Adan",NULL),
("YEPPSM5HDY","YE","Abyan",NULL),
("YEC88AOO4I","YE","Aḑ Ḑāli‘",NULL),
("YEHOVQZKOT","YE","Al Bayḑāʼ",NULL),
("YE1VSJ8CQY","YE","Al Ḩudaydah",NULL),
("YE2IL7ZY6C","YE","Al Jawf",NULL),
("YE6ENU2SCK","YE","Al Mahrah",NULL),
("YEG8AGSZ9T","YE","Al Maḩwīt",NULL),
("YEU2D3F41H","YE","Amanat Al Asimah",NULL),
("YEMNOMLVZR","YE","Dhamar",NULL),
("YE9MMCEYXV","YE","Ḩaḑramawt",NULL),
("YE67BY7LS1","YE","Ḩajjah",NULL),
("YEN652A6KX","YE","Ibb",NULL),
("YET9KF4J6E","YE","Laḩij",NULL),
("YE5SRKROFX","YE","Maʼrib",NULL),
("YEWRW3CP50","YE","Muḩāfaz̧at Raymah",NULL),
("YEWA37GN4A","YE","Omran",NULL),
("YEWPQ18WFE","YE","Şa‘dah",NULL),
("YEP6ZHUFEQ","YE","Şan‘āʼ",NULL),
("YE6BTJ1YJX","YE","San’a’",NULL),
("YE8N4PB807","YE","Shabwah",NULL),
("YEYR86OOLD","YE","Ta‘izz",NULL),
("YEUKUOZ9F6","YE","Ta’izz",NULL);